src/objects/acfBank_Detail__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Bank Detail</label>
    <nameField>
        <displayFormat>BNK{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/acfSuggested_Product__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfLead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Suggested_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Suggested_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Suggested Product</label>
    <nameField>
        <displayFormat>Prod-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Loans_Bank__c.object
<CustomObject>
    <label>CommunityBankAssociation</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunityBankAssociation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLoan_Amount__c</fullName>
        <description>Click Loans</description>
        <label>Outstanding Loan Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfIs_Bank_Statement_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Bank Statement Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Post_Login_Ques_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Post Login Ques Attempted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfLoan_Amount__c</fullName>
        <description>Click Loans</description>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOneTimePassword__c</fullName>
        <description>Click Loans</description>
        <label>One Time Password</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_partner_account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LVR_Rate__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>LVR_Rate</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans LVR &amp; Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LVR &amp; Rate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question_Type__c</fullName>
        <description>Click Loans</description>
        <label>Question Type</label>
        <picklist>
            <controllingField>acf_Type__c</controllingField>
            <picklistValues>
                <fullName>Property Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicant Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets and Liabilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_no__c</fullName>
        <description>Click Loans</description>
        <label>Sequence no</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WLQuoteDetailTracker.cls
@isTest
private class WLQuoteDetailTracker
{
    private static Lead objLead ;
    private static User objUser;
    private static Click_Community_Setup__c objcommunity;
    private static account accperson;
    private static account objAccount;
    private static Contact objContact;
    private static Opportunity objOpportunity;
    private static acfSuggested_Product__c objSuggestedProduct;
    private static acfBank_Detail__c objBankDatail;
    private static product2 objProduct;
    private static product2 objProducts;
    private static LVR_Rate__c objLvrRate;
    private static Script__c scobj;
    private static Click_Loans_Bank__c objClickLoanBankDetail;
    private static Question__c  objQuestion;
    

    static testMethod void validate1()
    {
        LoadData();            
        PageReference pageRef =Page.ClickPostloginQuestionnaires;
        Test.setCurrentPage(pageRef);
        system.runas(objUser)
        {
            WLQuoteDetail wlobj=new WLQuoteDetail ();
            wlobj.pge_name='ClickPostloginQuestionnaires';
            WLQuoteDetail.setProgressBarWidth(11,22,'ClickPostloginQuestionnaires','test');
        }      
    }
    static testMethod void validate2()
    {
        LoadData();
        PageReference pageRef = Page.ClickBankInfoDetails;
        Test.setCurrentPage(pageRef);
        system.runas(objUser)
        {
            WLQuoteDetail wlobj=new WLQuoteDetail ();
            wlobj.pge_name='ClickBankInfoDetails';
            WLQuoteDetail.setProgressBarWidth(11,22,'ClickBankInfoDetails','test');
        }
    }
    
    static testMethod void validate3()
    {
        LoadData();
        PageReference pageRef = Page.ClickPreLoginQuestions;
        Test.setCurrentPage(pageRef);
        system.runas(objUser)
        {
            WLQuoteDetail wlobj=new WLQuoteDetail ();
            wlobj.pge_name='ClickPreLoginQuestions';
            WLQuoteDetail.setProgressBarWidth(11,22,'ClickPreLoginQuestions','test');
        }
    }
    
    static testMethod void validate4()
    {
        LoadData1();            
        PageReference pageRef =Page.ClickPostloginQuestionnaires;
        Test.setCurrentPage(pageRef);
        system.runas(objUser)
        {
            WLQuoteDetail wlobj=new WLQuoteDetail ();
            wlobj.pge_name='ClickPostloginQuestionnaires';
        }      
    }
    
    private static void LoadData()
    {
        createclickCommunitySetup();
        createLead(); 
        CreatePersonAccount();      
        createContact();
        createUser();
        createProducts();
        createProduct();
        createsuggestedProducts();
        createbankDetails();
        createLvrRate();
        createScript();
        createQuestion();
        createClickLoanBankDetails();
        createOpportunity1();
        
    }
    
    private static void LoadData1()
    {
        createLead1(); 
        CreatePersonAccount1(); 
        createclickCommunitySetup();
        createContact();
        createUser();
        createProducts();
        createProduct();
        createsuggestedProducts(); 
        createOpportunity1();   
    }
   
    static void createLead()
    {
        objLead = new Lead();
        Id recorsTypeId  = ClickCommon.GetRecordTypeId('Lead','Click Refi');
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.Status = 'Open';
        objLead.RecordTypeId = recorsTypeId;
        objLead.acfOneTimePassword__c = '724715';
        objLead.acfApproximately_how_much_is_your_house__c = 100.01;
        objLead.acfLoan_Amount__c = 100.20;
        objLead.acfIs_Bank_Statement_Submitted__c = true;
        objLead.acfIs_Post_Login_Ques_Attempted__c =true;
        insert objLead;
    }

    static void createLead1()
    {
        objLead = new Lead();
        Id recorsTypeId  = ClickCommon.GetRecordTypeId('Lead','Click New Loans');
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.Status = 'Open';
        objLead.RecordTypeId = recorsTypeId;
        objLead.acfOneTimePassword__c = '724715';
        objLead.acfApproximately_how_much_is_your_house__c = 100.01;
        objLead.acfLoan_Amount__c = 100.20;
        objLead.acfIs_Bank_Statement_Submitted__c = true;
        objLead.acfIs_Post_Login_Ques_Attempted__c =true;
        insert objLead;
    }

    
    static void createContact()
    {
        objContact = new Contact();
        objContact.acf_lead__c = objLead.id;
        objContact = WLCommontrackerClass.createContact(objContact,objAccount);
    }
    
    static void createuser()
    {
         objUser = new User();
         objUser = WLCommonTrackerClass.CreatePortalUser(accperson.id);
    }
    
    static void createOpportunity1()
    {
        objOpportunity = new Opportunity();
        objOpportunity.acfBankdetailStatus__c = 'Skipped';
        objOpportunity = WLCommontrackerClass.createOpportunity(objOpportunity,objUser);
    }
    
   static void CreatePersonAccount()
   {
        accperson=new account();
        accperson=WLCommontrackerClass.CreatePersonAccount('test','test','test','test@gmail.com',objLead.id);
        accperson.acfAsset_House_Worth__c=44;
        update accperson;
        objLead.acf_partner_account__c=accperson.id;
        update objLead;
   }
    
    static void CreatePersonAccount1()
    {
       accperson=new account();
       accperson=WLCommontrackerClass.CreatePersonAccount('test','test','test','test@gmail.com',objLead.id);
       update accperson;
       objLead.acf_partner_account__c=accperson.id;
       update objLead;
    }
    
     static void createclickCommunitySetup() 
    {
        objcommunity = new Click_Community_Setup__c();
        objcommunity = WLCommontrackerClass.createcommunitysetup();
    }
    
    static void createsuggestedProducts() 
    {
         objSuggestedProduct               = new acfSuggested_Product__c();
         objSuggestedProduct.acfLead__c    = objLead.Id;
         objSuggestedProduct.acfProduct__c = objProduct.id;
         objSuggestedProduct = WLCommontrackerClass.createSuggestedProduct();
    }
    
    static void createbankDetails() 
    {
         objBankDatail =new acfBank_Detail__c();
         objBankDatail = WLCommontrackerClass.createBankDetail();
    }
    
    static void createProducts() 
    {
         objProduct = new product2();
         objProduct = WLCommontrackerClass.createProduct(objProduct);
    }
    
    static void createProduct() 
    {
         objProducts = new product2();
         objProducts = WLCommontrackerClass.createProduct(objProducts);
    }
    
    static void createLvrRate() 
    {
         objLvrRate = new LVR_Rate__c();
         objLvrRate= WLCommontrackerClass.createLvrRate(objProduct);
    }
    
    static void createScript() 
    {
        scobj = new Script__c();
        scobj.recordtypeid = Schema.SObjectType.Script__c.getRecordTypeInfosByName().get('Post-Login').getRecordTypeId();
        scobj.acf_Type__c          = 'Post-Login';
        scobj.acf_Sequence_no__c   = 1;
        scobj.acf_Question_Type__c = 'Applicant Details';
        scobj.Click_Community_Setup__c = ClickCommon.getCommunitySetup('testNetworkId').Id;
        insert scobj;
    }
    
    static void createClickLoanBankDetails() 
    {
         objClickLoanBankDetail = new Click_Loans_Bank__c();
         objClickLoanBankDetail = WLCommontrackerClass.createClickloan(objBankDatail,objcommunity);
    }
    
    static void createQuestion() 
    {
         objQuestion = new Question__c();
         objQuestion = WLCommontrackerClass.CreatePostLoginQuestions('Who is your current Lender',2,'Post-Login',true,true,scobj.id,'acfApproximately_how_much_is_your_house__c','Question__c',false,'acfAsset_House_Worth__c',true,true);
    }
}