src/objects/acfBank_Detail__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfBank_Name__c</fullName>
        <description>Click Loans</description>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Click Loans Bank Detail</label>
    <nameField>
        <displayFormat>BNK{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Click_Community_Setup__c</fullName>
        <formula>acf_Question__r.Click_Community_Setup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Community Setup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Click Loans Answer</label>
    <nameField>
        <displayFormat>Ans-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Click_Page_Prefix__c</fullName>
        <label>Page Prefix</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Support_Team_Name__c</fullName>
        <label>Support Team Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acf_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfBubble_Text__c</fullName>
        <description>Click Loans</description>
        <label>Bubble Text</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfIs_New_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is New Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_refinance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is refinance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfRefinance_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Refinance Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Master_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Master Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question_Type__c</fullName>
        <description>Click Loans</description>
        <label>Question Type</label>
        <picklist>
            <controllingField>acf_Type__c</controllingField>
            <picklistValues>
                <fullName>Property Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicant Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets and Liabilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Script</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_no__c</fullName>
        <description>Click Loans</description>
        <label>Sequence no</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/WLpreloginQuestionControllerTracker.cls
@isTest
public class WLpreloginQuestionControllerTracker
{
    private static Lead objLead;
    private static User objUser;
    private static Contact objContact;
    private static Account objAccount;
    private static Opportunity objOpportunity;
    private static product2 objPro;
    private static PriceBookEntry pbEntry;
    private static OpportunityLineItem oppLine;
    private static Click_Community_Setup__c  cmmset;
    private static Script__c objScript;
    private static Question__c  objQuestion;
    private static Question__c  MasobjQuestion;
    private static Document_Master__c objDocumentMaster;
    private static Answer__c ansobj;
    
    static testMethod void validate()
  {
    LoadData();
  
    ApexPages.currentPage().getParameters().put('utm_source','test');
    ApexPages.currentPage().getParameters().put('utm_medium','test1');
    ApexPages.currentPage().getParameters().put('utm_term','test2');
    ApexPages.currentPage().getParameters().put('utm_content','test3');
    ApexPages.currentPage().getParameters().put('utm_campaign','test4');
    ApexPages.currentPage().getParameters().put('type','refi');
    
    Cookie IsNewHomeLoan = new Cookie('IsNewHomeLoan','true','true',72000, true); 
    ApexPages.currentPage().setCookies( new Cookie[]{IsNewHomeLoan});
    
           
    Cookie Bname= new Cookie('Bname','true','true',72000, true); 
    ApexPages.currentPage().setCookies( new Cookie[]{Bname});
    
    Cookie WLACFQuestions= new Cookie('WLACFQuestions','true','true',72000, true); 
    ApexPages.currentPage().setCookies( new Cookie[]{WLACFQuestions});

    cmmset.Click_Support_Team_Name__c='test';
    cmmset.Click_Page_Prefix__c=null;
    update cmmset;
      
    WLpreloginQuestionController wlobj=new WLpreloginQuestionController();
   
   
  }
   static testMethod void validate1()
  {
    LoadData();
  
     ApexPages.currentPage().getParameters().put('utm_source','test');
     ApexPages.currentPage().getParameters().put('utm_medium','test1');
     ApexPages.currentPage().getParameters().put('utm_term','test2');
     ApexPages.currentPage().getParameters().put('utm_content','test3');
     ApexPages.currentPage().getParameters().put('utm_campaign','test4');
     ApexPages.currentPage().getParameters().put('type','test4');
    
     Cookie clickACFQues= new Cookie('clickACFQues','true','true',72000, true); 
     ApexPages.currentPage().setCookies( new Cookie[]{clickACFQues});
     
         
     Cookie Bname= new Cookie('Bname','true','true',72000, true); 
     ApexPages.currentPage().setCookies( new Cookie[]{Bname});
      
     cmmset.Click_Support_Team_Name__c='test';
     update cmmset;
    
     acfBank_Detail__c bnkobj=new acfBank_Detail__c();
     bnkobj.click_Show_on_Current_Lender_question__c=true;
    bnkobj.acfBank_Name__c='testing';
    insert bnkobj;
      
    WLpreloginQuestionController wlobj=new WLpreloginQuestionController();
    wlobj.RelatedQuestions();    
    wlobj.previousQuestion();
    WLpreloginQuestionController.AutoCompleteBanklList('test');
    wlobj.IsValidId('test');
    wlobj.resumePreviousSession();
    wlobj.clearCookies();
   
  }
  
  static testMethod void validate3()
  {
    LoadData1();
    Cookie IsNewHomeLoan = new Cookie('IsNewHomeLoan','true','true',72000, true); 
    ApexPages.currentPage().setCookies( new Cookie[]{IsNewHomeLoan});
     
    Cookie Bname= new Cookie('Bname','true','true',72000, true); 
    ApexPages.currentPage().setCookies( new Cookie[]{Bname});
    try
    {
    Cookie ClickACFQues= new Cookie(null,'true','true',72000, true); 
    ApexPages.currentPage().setCookies( new Cookie[]{ClickACFQues});
    }
    catch(exception ex)
    {} 
    WLpreloginQuestionController wlobj=new WLpreloginQuestionController();
  }
  
    private static void LoadData()
    {
        createLead();
        createAccount();
        createContact();
        createUser();
        createOpportunity();
        createProduct();
        createPriceBookEntry();
        createOpportunityLineItem();
        createcommunitysetup();
        createScript();
        createMasquestion();
        createquestion();
        CreateDocumentMaster();
        createAnswer();
       
   } 
   
   private static void LoadData1()
   {
        createcommunitysetup();
        createScript();
        createMasquestion();
        createquestion();
        CreateDocumentMaster();
        createAnswer();
    }      
   
        static void createLead()
      {
    
        objLead=new Lead();
        objLead=WLCommonTrackerClass.createLead(objLead);
   }
    
    static void createAccount()
    {
        objAccount = new Account();
        objAccount = WLCommonTrackerClass.CreatePersonAccount('test','test','88','test@gmail.com',objLead.id);
        objAccount.acfAsset_House_Worth__c=55;
        update objAccount; 
    }
    
    static void createContact()
     {
        objContact = new Contact();
        //objContact.AccountId = objAccount.id;
        //objContact.acf_lead__c = objLead.id;
        objContact = WLCommonTrackerClass.createContact(objContact,objAccount );
   }
    
    static void createuser()
    {
        objUser = new User();
        objuser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);
    }
    
    static void createOpportunity()
    {
      objOpportunity = new Opportunity();

      
      objOpportunity = WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);
      objOpportunity.AccountId = objAccount.id;
      objOpportunity.acfLoan_Amount_c__c=3000;
      objOpportunity.acfBankdetailStatus__c = 'Skipped';
      objOpportunity.acfApproximately_how_much_is_your_house__c=90;
      objOpportunity.create_from_custom_clone_button__c=true;
      objOpportunity.acfAsset_House_Worth__c=20;
      update objOpportunity;
    }
    static void createProduct()
    {
       objPro=new product2();
       objPro=WLCommonTrackerClass.createProduct(objPro);
  }
     static void createPriceBookEntry()
    {
        pbEntry = new PriceBookEntry();
        pbEntry.UnitPrice = 300;
        pbEntry.PriceBook2Id = Test.getStandardPricebookId();
        pbEntry.Product2Id = objPro.Id;
        pbEntry.IsActive = true;
        insert pbEntry ; 
    }
    
     static void createOpportunityLineItem()
    {
        oppLine = new OpportunityLineItem();
        oppLine.pricebookentryid=pbEntry.Id;
        oppLine.TotalPrice=2000;
        oppLine.Quantity = 2;
        oppLine.lender__c='test';
        oppLine.OpportunityID = objOpportunity.Id;
        insert oppLine;
   }
    static void createcommunitysetup()
    {
       cmmset= new Click_Community_Setup__c ();
       cmmset=WLCommonTrackerClass.createcommunitysetup();
       
  }
   static void createScript()
   {
        objScript = new Script__c();
        objScript.recordtypeid =Schema.SObjectType.Script__c.getRecordTypeInfosByName().get('Pre-Login').getRecordTypeId();
        objScript.acf_Type__c ='Pre-Login';
        objScript.acf_Sequence_no__c   = 1;
        objScript.acf_Question_Type__c = 'Applicant Details';
        objScript.Click_Community_Setup__c =cmmset.id;
        insert objScript;
   }
   static void createquestion()
   {
        objQuestion=new Question__c();
        objQuestion.acf_Question__c = 'Who is your current lender?';
        objQuestion.acf_Active__c = true;
        objQuestion.acf_Sequence_No__c = 2.0;
        objQuestion.acf_Type__c = 'Button';
        objQuestion.acfRefinance_Sequence_No__c = 1;
        objQuestion.acfIs_refinance__c = true;
        objQuestion.acfIs_New_Loan__c=true;
        objQuestion.Click_Is_Broker_Question__c=false;
        objQuestion.acf_Master_Question__c=MasobjQuestion.id;
        objQuestion.acfBubble_Text__c='test';        
        insert objQuestion;
        
   }
    static void createMasquestion()
   {
        MasobjQuestion=new Question__c();
        MasobjQuestion.acf_Question__c = 'Who is your current lender?';
        MasobjQuestion.acf_Active__c = true;
        MasobjQuestion.acf_Sequence_No__c = 2.0;
        MasobjQuestion.acf_Type__c = 'Text';
        MasobjQuestion.acfRefinance_Sequence_No__c = 1;
        MasobjQuestion.acfIs_refinance__c = true;
        MasobjQuestion.acfIs_New_Loan__c=true;
        MasobjQuestion.Click_Is_Broker_Question__c=false;
        MasobjQuestion.acf_Script__c=objScript.id;
        //objQuestion.acf_Script__c = objScript1.id;
        insert MasobjQuestion;
   }
   static void CreateDocumentMaster()
  {
   objDocumentMaster=new Document_Master__c();
   objDocumentMaster=WLCommonTrackerClass.createDocumentMaster(objDocumentMaster);
   }
   
   static void createAnswer()
   {
   ansobj=new Answer__c();
   ansobj=WLCommonTrackerClass.createAnswer(objQuestion.id,objQuestion.id,'test');
   }
   
}