src/objects/acfBank_Detail__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfBank_Name__c</fullName>
        <description>Click Loans</description>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Click Loans Bank Detail</label>
    <nameField>
        <displayFormat>BNK{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/acfDependent_Product__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipName>Dependent_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Dependent_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Dependent Product</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dependent Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Click_Community_Setup__c</fullName>
        <formula>acf_Question__r.Click_Community_Setup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Community Setup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Click Loans Answer</label>
    <nameField>
        <displayFormat>Ans-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Asset_And_Liability__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Community_Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Setup</label>
        <referenceTo>Click_Community_Setup__c</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>clickOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>click_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Click_Page_Prefix__c</fullName>
        <label>Page Prefix</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Loans_Bank__c.object
<CustomObject>
    <fields>
        <fullName>Click_Loans_Bank_Detail__c</fullName>
        <label>Click Loans Bank Detail</label>
        <referenceTo>acfBank_Detail__c</referenceTo>
        <relationshipName>Banks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Community_Setup__c</fullName>
        <label>Community Setup</label>
        <referenceTo>Click_Community_Setup__c</referenceTo>
        <relationshipName>Banks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CommunityBankAssociation</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunityBankAssociation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Dependent_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfAnswer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Answer</label>
        <referenceTo>Answer__c</referenceTo>
        <relationshipName>Dependent_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfDocument_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipName>Dependent_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Dependent Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dependent Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>IncomeAndExpenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Refinance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Refinance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfIs_New_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is New Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_refinance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is refinance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfRefinance_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Refinance Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Master_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Master Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Script</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_no__c</fullName>
        <description>Click Loans</description>
        <label>Sequence no</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/acfCreateNewOpportunityTracker.cls
@isTest
public class acfCreateNewOpportunityTracker 
{
    private static User objUser;
    private static Contact objContact;
    private static Account objAccount;
    private static Account objpersonAccount;
    private static Question__c objQue;
    private static Question__c objQue1;
    private static List<Question__c> lstQue;
    private static Answer__c objAns;
    private static List<Answer__c > lstAns;
    private static Lead objLead;
    private static Income_And_Expense__c objIAE;
    private static Opportunity objOpportunity;
    private static click_Applicant__c objCappl;
    private static Asset_And_Liability__c objAsali;
    private static Script__c objScript;
    private static Click_Community_Setup__c cmmset;
    private static product2 objPro;
    private static PriceBookEntry pbEntry;
    private static OpportunityLineItem oppLine;
    
    static TestMethod void Validate01()
     { 
        LoadData();
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(objLead.id);      
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        
        objScript.acf_Type__c='test1' ; 
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        PageReference pageRef = Page.cloneOpportunities;
        Test.setCurrentPageReference(pageRef);
        ApexPages.currentPage().getParameters().put('accid',lcr.getAccountId());
        
        List<string> lststr= new List<string>();
        Lststr.add('test');
        
        ApexPages.StandardController sc = new ApexPages.standardController(objOpportunity);
        acfCreateNewOpportunity obj=new acfCreateNewOpportunity(sc);
        obj.selectedLoanType = 'New Purchase';
        
        List <acfCreateNewOpportunity.WrapperIncomeAndExpense> lstWIAE=new List<acfCreateNewOpportunity.WrapperIncomeAndExpense>();
        acfCreateNewOpportunity.WrapperIncomeAndExpense objWIAE=new acfCreateNewOpportunity.WrapperIncomeAndExpense();
        objWIAE.objWrapIncomeExpense = objIAE;
        objWIAE.SelectedIE=true;
        lstWIAE.add(objWIAE);
        
        List<acfCreateNewOpportunity.WrapperApplicant> lstWrapl=new List<acfCreateNewOpportunity.WrapperApplicant>();
        acfCreateNewOpportunity.WrapperApplicant objWrapl=new acfCreateNewOpportunity.WrapperApplicant();
        objWrapl.objWrapApplicant = objCappl;
        objWrapl.SelectedApplicant=true;
        objWrapl.lstIe=lstWIAE;
        lstWrapl.add(objWrapl);
        
        List<acfCreateNewOpportunity.WrapperAssetAndLiability> lstWraali=new List<acfCreateNewOpportunity.WrapperAssetAndLiability>();
        acfCreateNewOpportunity.WrapperAssetAndLiability objWraali=new acfCreateNewOpportunity.WrapperAssetAndLiability();
        objWraali.objWrapAl=objAsali;
        objWraali.SelectedAl=true;
        objWraali.lstIe=lstWIAE;
        lstWraali.add(objWraali);
        
        
        List<acfCreateNewOpportunity.Questions> lstwraps = new List<acfCreateNewOpportunity.Questions>();
        acfCreateNewOpportunity.Questions objwraps = new acfCreateNewOpportunity.Questions();
        objwraps.objWrapQuestion = objQue;
        objwraps.strWrapAnswer='test';
        objwraps.lstSelectOpt = obj.getLoanType();
        objwraps.lstSelectOptions=lstAns;
        objwraps.lstCheckBoxAnswer=lststr;
        lstwraps.add(objwraps);
        
        acfCreateNewOpportunity.WrapperQuestions objwrap = new acfCreateNewOpportunity.WrapperQuestions();
        objwrap.lstRelatedQuestion = lstwraps ;
        objwrap.objWrapQuestion =objQue;
        objwrap.strWrapAnswer='test';
        objwrap.lstSelectOpt=obj.getLoanType();
        objwrap.lstSelectOptions= lstAns;
        objwrap.lstCheckBoxAnswer=Lststr;
        objwrap.lstWrapperApplicant=lstWrapl;
        objwrap.lstWrapperAssetAndLiability=lstWraali;
        
        obj.getNewAccountDetails();
        obj.getOPPDetails();
        obj.PreLoginQuestion();
        obj.getWrapperApplicant();
        obj.getWrapperAssetAndLiability();
        obj.getLoanType();
        obj.getBankNames();
        obj.CreateNewOpportunnit();
     }
 
      static TestMethod void Validate02()
     { 
        LoadData(); 
        ApexPages.StandardController sc = new ApexPages.standardController(objOpportunity);
        acfCreateNewOpportunity obj=new acfCreateNewOpportunity(sc);
        obj.getNewAccountDetails();
     }
     
     static testMethod void validate03()
     {
        LoadData();
        test.starttest();
        objQue1 = new Question__c ();
        objQue1=WLCommonTrackerClass.createQuestion(objQue1);
        objQue1.acf_Script__c = objScript.id;
        update objQue1;
        
        objQue.acf_Master_Question__c=objQue1.id;
        update objQue;
        
        objIAE.Asset_And_Liability__c = objAsali.id;
        update objIAE;
        
        ApexPages.currentPage().getParameters().put('accid',objpersonAccount.id);
        objpersonAccount.Click_Community_Setup__c  =cmmset.id;
        update objpersonAccount;
        
        objOpportunity.AccountId =objpersonAccount.id;
        objOpportunity.Transaction_Type__c='New Purchase';
        objOpportunity.StageName='Application Taken';
        objOpportunity.name='New';
        objOpportunity.RecordTypeid = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Click Refi').getRecordTypeId();
        update objOpportunity;
        
        objCappl.click_Account__c=objpersonAccount.id;
        objCappl.clickOpportunity__c=objOpportunity.id;
        update objCappl;
        
        objAsali.Opportunity__c  = objOpportunity.id;
        update objAsali;
        
        acfBank_Detail__c obj=new acfBank_Detail__c();
        obj.click_Show_on_Current_Lender_question__c=true;
        
        obj.acfBank_Name__c='test';
        insert obj;

        set<string> objset=new set<string>();
        objset.add('tesr');
        
        Click_Loans_Bank__c loanobj=new Click_Loans_Bank__c();
        loanobj.name='test';
        loanobj.Click_Loans_Bank_Detail__c=obj.id;
        obj.click_Show_on_Current_Lender_question__c=true;
        loanobj.Community_Setup__c=cmmset.id;
        insert loanobj;
        
        Document_Master__c docobj=new Document_Master__c();
        docobj.name='test';
        docobj.Click_Community_Setup__c=cmmset.id;
        insert docobj;
        
        Dependent_Document__c depobj=new Dependent_Document__c();
        depobj.name='test';
        depobj.acfDocument_Master__c=docobj.id;
        depobj.acfActive__c=true;
        insert depobj;
        
        acfDependent_Product__c productobj=new acfDependent_Product__c ();
        productobj.acfAnswer__c=objAns.id;
        productobj.acfProduct__c=objPro.id;
        insert productobj;
        
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(objLead.id);      
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        test.stoptest();
        
        acfCreateNewOpportunity oppobj=new acfCreateNewOpportunity (new ApexPages.StandardController(objOpportunity));
        oppobj.selectedLoanType='New Purchase';
        oppobj.getBankNames();
        oppobj.getLoanType();
        oppobj.getOPPDetails();
        oppobj.getNewAccountDetails();
        oppobj.getWrapperAssetAndLiability();
        //oppobj.CreateNewOpportunnit();
        acfCreateNewOpportunity.getRequiredDocumentsFromAnswersFromCRM(objLead.id,objset,cmmset.id);
        acfCreateNewOpportunity.getSuggestedProductsFromAnswers(objLead.id,objset,cmmset.id);
     }
     
     static testMethod void validate04()
     {
        LoadData();
        test.starttest();
        objAsali.Opportunity__c =objOpportunity.id;
        update objAsali;
        
        objQue1 = new Question__c ();
        objQue1=WLCommonTrackerClass.createQuestion(objQue1);
        objQue1.acf_Script__c = objScript.id;
        update objQue1;
       
        objQue.acf_Master_Question__c=objQue1.id;
        update objQue;
        ApexPages.currentPage().getParameters().put('accid',objpersonAccount.id);
        objpersonAccount.Click_Community_Setup__c  =cmmset.id;
        update objpersonAccount;
        
        objOpportunity.AccountId =objpersonAccount.id;
        objOpportunity.Transaction_Type__c='New Purchase';
        objOpportunity.StageName='Application Taken';
        objOpportunity.name='New';
        update objOpportunity;
        
        objCappl.click_Account__c=objpersonAccount.id;
        objCappl.clickOpportunity__c=objOpportunity.id;
        update objCappl;
        
        objAsali.Opportunity__c  = objOpportunity.id;
        update objAsali;
        acfBank_Detail__c obj=new acfBank_Detail__c();
        obj.click_Show_on_Current_Lender_question__c=true;
        
        obj.acfBank_Name__c='test';
        insert obj;
        
        
        set<string> objset=new set<string>();
        objset.add(string.valueof(objAns.id));
        
        Click_Loans_Bank__c loanobj=new Click_Loans_Bank__c();
        loanobj.name='test';
        loanobj.Click_Loans_Bank_Detail__c=obj.id;
        obj.click_Show_on_Current_Lender_question__c=true;
        loanobj.Community_Setup__c=cmmset.id;
        insert loanobj;
        
        Document_Master__c docobj=new Document_Master__c();
        docobj.name='test';
        docobj.Click_Community_Setup__c=cmmset.id;
        insert docobj;
        
        Dependent_Document__c depobj=new Dependent_Document__c();
        depobj.name='test';
        depobj.acfDocument_Master__c=docobj.id;
        depobj.acfAnswer__c = objAns.id;
        depobj.acfActive__c=true;
        insert depobj;
        
        objPro.Click_Loans_Bank_Detail__c = loanobj.Click_Loans_Bank_Detail__c;
        update objPro;
        
        acfDependent_Product__c productobj = new acfDependent_Product__c ();
        productobj.acfAnswer__c=objAns.id;
        productobj.acfProduct__c=objPro.id;
        insert productobj;
        
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(objLead.id);      
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        
        test.stoptest();
        
        acfCreateNewOpportunity oppobj=new acfCreateNewOpportunity (new ApexPages.StandardController(objOpportunity));
        oppobj.selectedLoanType='Refinance';
        oppobj.getBankNames();
        oppobj.getLoanType();
        oppobj.getOPPDetails();
        oppobj.getNewAccountDetails();
        oppobj.PreLoginQuestion();
        acfCreateNewOpportunity.getRequiredDocumentsFromAnswersFromCRM(objOpportunity.id,objset,cmmset.id);
        acfCreateNewOpportunity.getSuggestedProductsFromAnswers(objOpportunity.id,objset,cmmset.id);
     }
     
     static testMethod void validate05()
     {
        LoadDatas();
        test.starttest();
        objAsali.Opportunity__c =objOpportunity.id;
        update objAsali;
        
        objQue1 = new Question__c ();
        objQue1=WLCommonTrackerClass.createQuestion(objQue1);
        objQue1.acf_Script__c = objScript.id;
        update objQue1;
       
        objQue.acf_Master_Question__c=objQue1.id;
        update objQue;
        
        objpersonAccount.Click_Community_Setup__c  =cmmset.id;
        update objpersonAccount;
        ApexPages.currentPage().getParameters().put('accid',objpersonAccount.id);

        objOpportunity.AccountId =objpersonAccount.id;
        objOpportunity.Transaction_Type__c='Refinance';
        objOpportunity.StageName='Application Taken';
        objOpportunity.name='New';
        update objOpportunity;
        
        objCappl.click_Account__c=objpersonAccount.id;
        objCappl.clickOpportunity__c=objOpportunity.id;
        update objCappl;
        
        objAsali.Opportunity__c  = objOpportunity.id;
        update objAsali;
        
        acfBank_Detail__c obj=new acfBank_Detail__c();
        obj.click_Show_on_Current_Lender_question__c=true;
        
        obj.acfBank_Name__c='test';
        insert obj;

        //set<string> objset=new set<string>();
        //objset.add(string.valueof(objAns.id));
        
        Click_Loans_Bank__c loanobj=new Click_Loans_Bank__c();
        loanobj.name='test';
        loanobj.Click_Loans_Bank_Detail__c=obj.id;
        obj.click_Show_on_Current_Lender_question__c=true;
        loanobj.Community_Setup__c=cmmset.id;
        insert loanobj;
        
        Document_Master__c docobj=new Document_Master__c();
        docobj.name='test';
        docobj.Click_Community_Setup__c=cmmset.id;
        insert docobj;
        
        /*Dependent_Document__c depobj=new Dependent_Document__c();
        depobj.name='test';
        depobj.acfDocument_Master__c=docobj.id;
        depobj.acfAnswer__c = objAns.id;
        depobj.acfActive__c=true;
        insert depobj;
        
        objPro.Click_Loans_Bank_Detail__c = loanobj.Click_Loans_Bank_Detail__c;
        update objPro;
        
        acfDependent_Product__c productobj = new acfDependent_Product__c ();
        productobj.acfAnswer__c=objAns.id;
        productobj.acfProduct__c=objPro.id;
        insert productobj; */
        
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(objLead.id);      
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);
        Database.LeadConvertResult lcr = Database.convertLead(lc);
        test.stoptest();
        acfCreateNewOpportunity oppobj=new acfCreateNewOpportunity (new ApexPages.StandardController(objOpportunity));
        oppobj.selectedLoanType= 'Refinance';
        oppobj.getBankNames();
        oppobj.getLoanType();
        oppobj.getOPPDetails();
        oppobj.getNewAccountDetails();
        oppobj.PreLoginQuestion();
        oppobj.getPreLoginQuestion(cmmset.id);
        oppobj.CreateNewOpportunnit();
        //acfCreateNewOpportunity.getRequiredDocumentsFromAnswersFromCRM(objOpportunity.id,objset,cmmset.id);
        //acfCreateNewOpportunity.getSuggestedProductsFromAnswers(objOpportunity.id,objset,cmmset.id);
     }

     private static void LoadData()
     {
        createLead();
        createPersonAccount();
        createcommunitysetup();
        createContact();
        createUser();
        createOpportunity();
        createProduct();
        createPriceBookEntry();
        createOpportunityLineItem();
        createScript();
        createQuestion();
        createanswer();
        createclickApplicant();
        createAssetAndLiability();
        createIncomeAndExpense();
    }
    
    private static void LoadDatas()
    {
        createcommunitysetup();     
        createLead();
        createPersonAccount();
        createContact();
        createUser();
        createOpportunitys();
        createProduct();
        createPriceBookEntry();
        createOpportunityLineItem();
        createScript();
        createQuestion();
        createanswer();
        createclickApplicant();
        createAssetAndLiability();
        createIncomeAndExpense();
    }
    
    static void createLead()
    {
        objLead=new Lead();
        objLead=WLCommonTrackerClass.createLead(objLead);
    }
    
     static void createScript()
    {
        objScript = new Script__c();
        objScript = WLCommonTrackerClass.createScript('Pre-Login');
        update objScript;
    }
    
    static void createPersonAccount()
    {
        objpersonAccount= new Account();
        objpersonAccount=WLCommonTrackerClass.CreatePersonAccount('Fname','LName','strPhone','strLead12Email@gmail.com',objLead.Id);
    }
    
    static void createcommunitysetup()
    {
        cmmset= new Click_Community_Setup__c ();
        cmmset=WLCommonTrackerClass.createcommunitysetup();
        cmmset.Click_Page_Prefix__c = 'Click';
        update cmmset;
    }
    
    static void createContact()
    {
        objContact = new Contact();
        objContact = WLCommonTrackerClass.createContact(objContact,objpersonAccount);
    }
    
    static void createuser()
    {
        objUser = new User();
        objUser = WLCommonTrackerClass.CreatePortalUser(objpersonAccount.id);
    }
    
     static void createQuestion()
    {
        objQue = new Question__c ();
        objQue.acfIs_New_Loan__c=true;
        objQue.Click_Is_Broker_Question__c=false;
        objQue.acf_Question__c = 'Who is your current lender?';
        objQue.acf_Active__c = true;
        objQue.acf_Sequence_No__c = 2.0;
        objQue.acf_Type__c = 'Button';
        objQue.acfRefinance_Sequence_No__c = 1;
        objQue.acfIs_refinance__c = true;
        insert objQue;
        lstQue=new List<Question__c>();
        lstQue.add(objQue);
    }
    
    static void createanswer()
    {
       objAns = new Answer__c ();
       objAns.acf_Question__c = objQue.id;
       objAns=WLCommonTrackerClass.createAnswer(objAns);
       lstAns=new List<Answer__c >();
       lstAns.add(objAns);
    }
    
    static void createIncomeAndExpense()
    {
         objIAE=new Income_And_Expense__c ();
         objIAE=WLCommonTrackerClass.createIncomeExpense(objIAE,objCappl);
    }
    
    static void createclickApplicant()
    {
         objCappl=new click_Applicant__c();
         objCappl = WLCommonTrackerClass.createApplicant(objCappl,objpersonAccount,objOpportunity );
    }
    
     static void createAssetAndLiability()
    {
        objAsali=new Asset_And_Liability__c ();
        objAsali=WLCommonTrackerClass.createAssetandLiablility(objAsali,objpersonAccount);
    }
    
    static void createOpportunity()
    {
      objOpportunity = new Opportunity();
      objOpportunity.AccountId =objpersonAccount.id;
      objOpportunity.acfBankdetailStatus__c = 'Skipped';
      objOpportunity =  WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);
     }
     
     static void createOpportunitys()
    {
        objOpportunity = new Opportunity();
        objOpportunity.AccountId =objUser.AccountId ;
        objOpportunity.Community_Setup__c=ClickCommon.getCommunitySetup('null').Id;
        objOpportunity.recordtypeid= Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Click Refi').getRecordTypeId();
        objOpportunity.name = 'test';
        objOpportunity.Stagename = 'Application Taken';
        objOpportunity.CloseDate = System.today();
        objOpportunity.acfAsset_House_Worth__c = 200000;
        insert objOpportunity;
     } 
     
      static void createProduct()
    {
        objPro=new product2();
        objPro=WLCommonTrackerClass.createProduct(objPro);
     }
     
     static void createPriceBookEntry()
    {
        pbEntry = new PriceBookEntry();
        pbEntry.UnitPrice = 300;
        pbEntry.PriceBook2Id = Test.getStandardPricebookId();
        pbEntry.Product2Id = objPro.Id;
        pbEntry.IsActive = true;
        insert pbEntry ; 
    }
    
    static void createOpportunityLineItem()
    {
        oppLine = new OpportunityLineItem();
        oppLine.pricebookentryid=pbEntry.Id;
        oppLine.TotalPrice=2000;
        oppLine.Quantity = 2;
        oppLine.lender__c='test';
        oppLine.OpportunityID = objOpportunity.Id;
        insert oppLine;
    }
    
 }