src/objects/acfBank_Detail__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfBankSlugName__c</fullName>
        <description>Click Loans</description>
        <label>Bank Slug Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfBank_Name__c</fullName>
        <description>Click Loans</description>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Click Loans Bank Detail</label>
    <nameField>
        <displayFormat>BNK{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Click Loans Answer</label>
    <nameField>
        <displayFormat>Ans-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <label>Current Lender</label>
        <picklist>
            <picklistValues>
                <fullName>Current Lender - TBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advantedge Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anchorage Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia First Mortgage Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian First Mortgage Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Defence Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Unity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Melbourne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banksia Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bendigo Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluebay Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Mortgage Corporation Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circle Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citibank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastline Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collins Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commonwealth Bank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <label>Current Lender</label>
        <picklist>
            <controllingField>Transaction_Type__c</controllingField>
            <picklistValues>
                <fullName>Adelaide Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advantedge Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anchorage Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assured Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aussie Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia First Mortgage Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Defence Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian First Mortgage Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Unity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank MECU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Melbourne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banksia Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankstown City Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bendigo Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluebay Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Mortgage Corporation Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circle Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfIs_New_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is New Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_refinance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is refinance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfNew_Loan_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>New Loan Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acfRefinance_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Refinance Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_ApiName__c</fullName>
        <description>Click Loans</description>
        <label>ApiName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Script</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/acfpreloginQuesBrokerControllerTracker.cls
@isTest(SeeAllData=true)
public class acfpreloginQuesBrokerControllerTracker {
    
    public static Question__c objQuestion;
    public static Question__c objRelatedQuestion;
    public static Question__c objRelatedQuestion1;
    public static Script__c objScript;
    public static User objUser;
    public static acfBank_Detail__c objBankDetail;
    public static Answer__c objAnswer;
    public static Answer__c objRelatedQuestionAnswer;
    public static Answer__c objRelatedQuestionAnswer1;
    public static list<Answer__c> lstAnswer;
    public static Account objaccount;
    //private static acfBank_Detail__c objBankDetail;
    public static Lead objlead;
    
    public static testMethod void ValidateNewLoan()
    {
        
        objAccount = new Account();
        objAccount.firstname='testuser12345';
        objAccount.LastName= 'test2312';
        objaccount.PersonEmail='test1234566@gmail.com';
        objAccount.acfApproximately_how_much_is_your_house__pc = 12.00;
        objAccount.acfCurrent_Rate__pc = 10.20;
        objAccount.acfCurrent_Loan_Amount__pc = 10.00;
        objAccount.acfWhat_is_your_current_payment_type__pc ='Cash'; 
        
        insert objAccount;
        
        objBankDetail = new acfBank_Detail__c();
        objBankDetail.acfBank_Name__c = 'Bank of Statements';
        objBankDetail.acfBankSlugName__c = 'bank_of_statements';
        objBankDetail.click_Show_on_Current_Lender_question__c = true;
        insert objBankDetail;
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objAccount.id;
        objOpportunity.recordtypeid = acfCommon.GetRecordTypeId('Opportunity','Click Refi');
        objOpportunity.name = 'test';
        objOpportunity.Stagename = 'Application Taken';
        objOpportunity.CloseDate = System.today();
        objOpportunity.Current_Lender__c=objBankDetail.id;
        insert objOpportunity;
        
         
        
        
        
        objScript= acfCommonTrackerClass.createScriptnew('Pre-Login');
        system.debug('!@#$%'+objScript.id);
        objLead = new Lead();
        objLead = acfCommonTrackerClass.createLeadForPortal();
        
        Question__c objQuest                 = new Question__c ();
        objQuest.acf_Question__c             = 'Who is your current lender?';
        objQuest.acf_Active__c               = true;
        objQuest.acfRefinance_Sequence_No__c = 1;
        objQuest.acf_Type__c                 = 'Button';
        objQuest.acfNew_Loan_Sequence_No__c  = 1;
        objQuest.acfIs_refinance__c          = true;
        objQuest.acf_Script__c               = objScript.id;
        objQuest.acfIs_New_Loan__c           = false;
        objQuest.acf_ApiName__c              = 'Current_Lender__c';
        objQuest.Click_Is_Broker_Question__c = false;
        //objQuest.Click_Is_Broker_Question__c = true;
        insert objQuest;
        
        
        //objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Button',true,false,objScript.id,'Current_Lender__c');
        //objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Button',true,false,objScript.id,'Current_Lender__c');
        //objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Text',true,false,objScript.id,'Current_Lender__c');
        objAnswer     = acfCommonTrackerClass.createAnswer(objQuest.id, null,'Westpac Bank');
        objBankDetail = acfCommonTrackerClass.createBankDetail();
        acf_PreLoginQuestionController objacfpreloginQuestionController = new acf_PreLoginQuestionController();
        objacfpreloginQuestionController.IsInsertedId=null;
        objacfpreloginQuestionController.pageId='';
        
        objacfpreloginQuestionController.AccountId=objAccount.id;
        objacfpreloginQuestionController.ScriptId=objScript.id;
        objacfpreloginQuestionController.strmsg='hello';
        objacfpreloginQuestionController.PreviousVal=false;
        objacfpreloginQuestionController.IsNewpurchase=true;
        objacfpreloginQuestionController.lstAcc=null;
        //objacfpreloginQuestionController.mapQuestionIdToQuestion=null;
        objacfpreloginQuestionController.lstSelectedAnswers=null;
        objacfpreloginQuestionController.BankNamesAutosugest=null;
        objacfpreloginQuestionController.setMyAccountId(objAccount.id);
        objacfpreloginQuestionController.strBubbleText='text';
        //objacfpreloginQuestionController.lstMasterWrapperQuestion=null; 
        acf_PreLoginQuestionController.WrapperQuestions obnew= new acf_PreLoginQuestionController.WrapperQuestions();
        obnew.objWrapQuestion=objQuestion;
        obnew.strWrapAnswer='true';
        obnew.strWrapAnswer='true';
        obnew.lstSelectOpt=new List<SelectOption>();
        obnew.lstRelatedQuestion= new List<acf_PreLoginQuestionController.WrapperQuestions>();
        obnew.lstSelectOptions=null;
        obnew.lstCheckBoxAnswer=null;
        objacfpreloginQuestionController.QuesNo=1;
        objacfpreloginQuestionController.iserror='false';
        objacfpreloginQuestionController.indexNo=2;
        objacfpreloginQuestionController.ScriptId=objScript.id;
        objacfpreloginQuestionController.MyAccountId=objaccount.id;
        objacfpreloginQuestionController.LoanType='Refinance';
        objacfpreloginQuestionController.MyAccountId=objaccount.id;
        objacfpreloginQuestionController.getBankNames();
        objacfpreloginQuestionController.PreLoginQuestion();
        objacfpreloginQuestionController.getMyAccountId();
        objacfpreloginQuestionController.getMyAccount();
        objacfpreloginQuestionController.setLoanType('Refinance');
        objacfpreloginQuestionController.getLoanType();
        objacfpreloginQuestionController.updateAccount();
        objacfpreloginQuestionController.saveLead();
        objacfpreloginQuestionController.getBankNamesAutosugest();
    }
    
    private static testMethod void ValidateNewLoan2()
    {
        
        objAccount = new Account();
        objAccount.firstname='testuser23423423';
        objAccount.LastName= 'test234234';
        objaccount.PersonEmail='test234234@gmail.com';
        objAccount.acfApproximately_how_much_is_your_house__pc = 12.00;
        objAccount.acfCurrent_Rate__pc = 10.20;
        objAccount.acfCurrent_Loan_Amount__pc = 10.00;
        objAccount.acfWhat_is_your_current_payment_type__pc ='Cash';         
        insert objAccount;
        
        objScript= acfCommonTrackerClass.createScriptnew('Pre-Login');
        system.debug('!@#$%'+objScript.id);
        objLead = new Lead();
        
        objLead = acfCommonTrackerClass.createLeadForPortal();
        objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Button',true,false,objScript.id,'Current_Lender__c');
        objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Button',true,false,objScript.id,'Current_Lender__c');
        objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Text',true,false,objScript.id,'Current_Lender__c');
        objAnswer     = acfCommonTrackerClass.createAnswer(objQuestion.id, null,'Westpac Bank');
        objBankDetail = acfCommonTrackerClass.createBankDetail();
        acf_PreLoginQuestionController objacfpreloginQuestionController = new acf_PreLoginQuestionController();
        objacfpreloginQuestionController.QuesNo=1;
        objacfpreloginQuestionController.iserror='false';
        objacfpreloginQuestionController.indexNo=2;
        objacfpreloginQuestionController.ScriptId=objScript.id;
        objacfpreloginQuestionController.MyAccountId=objaccount.id;
        objacfpreloginQuestionController.LoanType='New Purchase';
        objacfpreloginQuestionController.MyAccountId=objaccount.id;
        objacfpreloginQuestionController.getBankNames();
        objacfpreloginQuestionController.PreLoginQuestion();
        objacfpreloginQuestionController.getMyAccountId();
        objacfpreloginQuestionController.getMyAccount();
        objacfpreloginQuestionController.setLoanType('Refinance');
        objacfpreloginQuestionController.getLoanType();
        objacfpreloginQuestionController.updateAccount();
        objacfpreloginQuestionController.saveLead();
    }
    
    
    
}