src/objects/acfBank_Detail__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Bank Detail</label>
    <nameField>
        <displayFormat>BNK{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Click_Community_Setup__c</fullName>
        <formula>acf_Question__r.Click_Community_Setup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Community Setup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Click Loans Answer</label>
    <nameField>
        <displayFormat>Ans-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Email__c</fullName>
        <label>Applicant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Applicant_Phone__c</fullName>
        <label>Applicant Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>acfEconsent_App2__c</fullName>
        <label>acfEconsent_App2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfEconsent__c</fullName>
        <label>Econsent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfEmployment_Type__c</fullName>
        <label>Employment Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Name__c</fullName>
        <label>Applicant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acfApplicant2_Marital_Status__c</fullName>
        <description>Click Loans</description>
        <label>Applicant2 Marital Status</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfApplicant2_Monthly_Salary__c</fullName>
        <description>Click Loans</description>
        <label>Applicant2 Annual Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfApplicant2_Name__c</fullName>
        <description>Click Loans</description>
        <label>Applicant2 Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfEconsent_App2__c</fullName>
        <label>acfEconsent_App2</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfEconsent__c</fullName>
        <description>Click Loans</description>
        <label>acfEconsent</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Name__c</fullName>
        <description>Click Loans</description>
        <label>Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>affiliate_source__c</fullName>
        <label>affiliate_source</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfEmployment_Type__c</fullName>
        <description>Click Loans</description>
        <label>Employment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Time - PAYG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfIs_Post_Login_Ques_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Post Login Ques Attempted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>affiliate_source__c</fullName>
        <description>Tracking code from affiliate on source of lead</description>
        <label>affiliate_source</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfApplicant_2_Api_Name__c</fullName>
        <description>Click Loans</description>
        <inlineHelpText>This field is used to store field API name for second applicant questions</inlineHelpText>
        <label>Applicant 2 Api Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfDependent_Field_Name__c</fullName>
        <description>Click Loans</description>
        <label>Dependent on (Field Name)</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfDependent_Object_Name__c</fullName>
        <description>Click Loans</description>
        <label>Dependent on (Object Name)</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfDependent_Value__c</fullName>
        <description>Click Loans</description>
        <label>Dependent  on (Field Value)</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfEmployment_Type__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Employment Type</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Applicant_Question__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Applicant Question</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_New_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is New Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_refinance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is refinance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfNew_Loan_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>New Loan Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acfRefinance_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Refinance Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acfReplace_Mobile_No__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Replace Mobile No</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_ApiName__c</fullName>
        <description>Click Loans</description>
        <label>ApiName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Dependents__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Applicant Dependents</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question_Type__c</fullName>
        <description>Click Loans</description>
        <label>Question Type</label>
        <picklist>
            <controllingField>acf_Type__c</controllingField>
            <picklistValues>
                <fullName>Property Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicant Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets and Liabilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Script</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_no__c</fullName>
        <description>Click Loans</description>
        <label>Sequence no</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/acfpostloginQuesBrokerControllerTracker.cls
@isTest(SeeAllData = true)
private class acfpostloginQuesBrokerControllerTracker
{

    private static Opportunity objOpportunity;
    private static Account objAccount;
    private static Contact objContact;
    private static Script__c objScript;
    private static  Answer__c objAnswer;
    private static  Answer__c objRelatedQuestionAnswer;
    private static  Answer__c objRelatedQuestionAnswer1;
    private static  Question__c objRelatedQuestion;
    private static  Question__c objRelatedQuestion1;
    private static Lead objLead;
    private static User thisuser;
    public static Question__c objQuestion;
    public static User objUser;
    public static acfBank_Detail__c objBankDetail;
    public static click_Applicant__c objApplicant;
    public static string strapplicantName;
    public static string strAppSeqNo;
    public static string strapplicantEmail;
    public static string strPhone;
    public static integer QuesNo;
    static testMethod void M1(){

        loadData();

        QuesNo = 1;
        Integer intTempQues;
        intTempQues = QuesNo +1;
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('cid',objAccount.id);
        acfpostloginQuestionsController_partner obj = new acfpostloginQuestionsController_partner();

        obj.MasterQuesNo = 0;
        obj.RelatedQuestions();
     //   obj.AddingRelatedQuestion();
        obj.checkQuestionStaus();
        obj.redirect();
        obj.MasterQuesNo = 0;
        obj.NextQuestion();
  //      obj.PreviousQuestion();
        obj.AssetLiablity();
        obj.IsValidDate('2015-10-12');
        obj.CreateDateFromString('2015-10-12');
        obj.checkUserResponse();
        obj.app2Email = 'test@gmail.com';
        obj.accountname = 'ttt';
        obj.issApplicant2Check = true;
     
        
      
        obj.sendApplicantConsentMailandSms();
        obj.applicant2consent();

    }

    /*static testMethod void validateClickpostloginQuestionsController()
    {
        CreateData();

        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('cid',objAccount.id);

        objScript=new Script__c();
        objScript     = acfCommonTrackerClass.createScript('Post-Login');
        objQuestion   = acfCommonTrackerClass.CreatePostLoginQuestions('Who is your current lender?',1,'Button',false,true,objScript.id,'acf_Applicant_Name__c','Lead',false,'',false);
        objQuestion   = acfCommonTrackerClass.CreatePostLoginQuestions('Who is your current lender?',1,'Text',true,false,objScript.id,'acfApplicant2_Name__c','Contact',false,'',false);
        objAnswer     = acfCommonTrackerClass.createAnswer(objQuestion.id, null,'Westpac Bank');
        //      System.runAs(objuser)
        //      {
        acfpostloginQuestionsController_partner objacfpostloginQuestionsController = new acfpostloginQuestionsController_partner();
        objacfpostloginQuestionsController.UserAccountId=objaccount.id;
        objacfpostloginQuestionsController.QuesNo = 0;
        objacfpostloginQuestionsController.MasterQuesNo = 0;
        acfpostloginQuestionsController_partner.WrapperQuestions lstwrap=new acfpostloginQuestionsController_partner.WrapperQuestions();
        lstwrap.objWrapQuestion=objQuestion;
        lstwrap.strWrapAnswer=objAnswer.id;
        objacfpostloginQuestionsController.lstMasterWrapperQuestion.add(lstwrap);
        objacfpostloginQuestionsController.redirect();
        objacfpostloginQuestionsController.lstMasterWrapperQuestion.add(lstwrap);
        objacfpostloginQuestionsController.RelatedQuestions();
        objacfpostloginQuestionsController.AddingRelatedQuestion();
        objacfpostloginQuestionsController.NextQuestion();
  //      objacfpostloginQuestionsController.PreviousQuestion();
        objacfpostloginQuestionsController.AssetLiablity();
        objacfpostloginQuestionsController.assetaddMethodNRAC();
        objacfpostloginQuestionsController.IsValidDate(string.valueof(system.today()));
        objacfpostloginQuestionsController.CreateDateFromString(string.valueof(system.today()));

        acfpostloginQuestionsController_partner obj = new acfpostloginQuestionsController_partner();



        obj.NextQuestion();
        obj.checkUserResponse();
        obj.app2Email = 'test@gmail.com';
        obj.accountname = 'ttt';
        obj.issApplicant2Check = true;
        obj.sendApplicantConsentMailandSms();

        obj.applicant2consent();
        //        }
    }

    static testMethod void validateClickpostloginQuestionsController0()
    {
        CreateData();
         PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('cid',objAccount.id);

        objAccount.acf_Applicant_Name__pc = '2';
        update objAccount;
         Account objAccount2 = new Account();
        //objAccount.recordtype.name='Business Account';
        objAccount2.name='testname';
        insert objAccount2;
        objContact = new Contact();
        objContact.AccountId = objAccount2.id;
        objContact.LastName = 'test';
        objContact.email = 'swati.sharma@saasfocus.com';
        insert objContact;
        Set<String> customerUserTypes = new Set<String> {'CSPLiteUser', 'PowerPartner', 'PowerCustomerSuccess',   'CustomerSuccess'};
        Profile prfile = [select Id,name from Profile where UserType in :customerUserTypes limit 1];
        user objUser2 = new User(
        profileId = prfile.id,
        username = 'newUsertestnew09876545@yahoo.com',
        email = 'pb@f.com',
        emailencodingkey = 'UTF-8',
        localesidkey = 'en_US',
        languagelocalekey = 'en_US',
        timezonesidkey = 'America/Los_Angeles',
        alias='nuser',
        lastname='lastname',
        contactId = objContact.id
        );
        insert objUser2;
        objScript     = acfCommonTrackerClass.createScript('Post-Login');
        objQuestion   = acfCommonTrackerClass.CreatePostLoginQuestions('Who is your current lender?',1,'Button',false,true,objScript.id,'acf_Applicant_Name__c','Contact',true,'acfApplicant2_Name__c',true);
        objRelatedQuestion   = acfCommonTrackerClass.CreatePostLoginQuestions('Who is your current lender?',1,'Button',false,true,null,'acfApplicant2_Marital_Status__c','lead',true,'acfApplicant2_Monthly_Salary__c',true);
        objAnswer     = acfCommonTrackerClass.createAnswer(objQuestion.id, null,'2');

        System.runAs(objUser2)
        {
            acfpostloginQuestionsController_partner objacfpostloginQuestionsController = new acfpostloginQuestionsController_partner();
            objacfpostloginQuestionsController.UserAccountId=objaccount.id;
            objacfpostloginQuestionsController.QuesNo = 0;
            objacfpostloginQuestionsController.MasterQuesNo = 0;
            acfpostloginQuestionsController_partner.WrapperQuestions lstwrap=new acfpostloginQuestionsController_partner.WrapperQuestions();
            lstwrap.objWrapQuestion=objQuestion;
            lstwrap.strWrapAnswer=objAnswer.id;
            objacfpostloginQuestionsController.lstMasterWrapperQuestion.add(lstwrap);
            objacfpostloginQuestionsController.redirect();
            objacfpostloginQuestionsController.lstMasterWrapperQuestion.add(lstwrap);
            objacfpostloginQuestionsController.RelatedQuestions();
            objacfpostloginQuestionsController.AddingRelatedQuestion();
            //objacfpostloginQuestionsController.NextQuestion();
     //       objacfpostloginQuestionsController.PreviousQuestion();
            objacfpostloginQuestionsController.AssetLiablity();
            objacfpostloginQuestionsController.assetaddMethodNRAC();
            objacfpostloginQuestionsController.InsertRequiredDocuments(objLead.id,objacfpostloginQuestionsController.lstMasterWrapperQuestion);
        }
    }
    public static void CreateData()
    {



        acfpreloginQuesBrokerControllerTracker.ValidateNewLoan();
        objAccount=acfpreloginQuesBrokerControllerTracker.objAccount;
        objLead=acfpreloginQuesBrokerControllerTracker.objLead;
        objUser=acfpreloginQuesBrokerControllerTracker.objUser;
        //system.AssertNotEquals(objUser.id,null);
    }*/
    public static void loadData(){

        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        system.debug('portalRole is ' + portalRole);

        Profile profile1 = [Select Id from Profile where name = 'System Administrator'];
        User portalAccountOwner1 = new User(
        UserRoleId = portalRole.Id,
        ProfileId = profile1.Id,
        Username = System.now().millisecond() + 'test2222@test.com',
        Alias = 'batman',
        Email='test@test.com',
        EmailEncodingKey='UTF-8',
        Firstname='Bruce',
        Lastname='Wayne',
        LanguageLocaleKey='en_US',
        LocaleSidKey='en_US',
        TimeZoneSidKey='America/Chicago'
        );
        insert portalAccountOwner1;

        //User u1 = [Select ID From User Where Id =: portalAccountOwner1.Id];

        System.runAs ( portalAccountOwner1 ) {
        //Create account
        objAccount = new Account(
        Name = 'TestAccount',
        OwnerId = portalAccountOwner1.Id
        );
        Database.insert(objAccount);
        Lead ld = new Lead();
        ld.LastName = 'test';
        ld.acfIs_Post_Login_Ques_Attempted__c = true;
        insert ld;
        //Create contact
        Contact contact1 = new Contact(
        FirstName = 'Test',
        Lastname = 'McTesty',
        AccountId = objAccount.Id,
        acf_lead__c = ld.id,
        Email = System.now().millisecond() + 'test@test.com'
        );
        Database.insert(contact1);

        //Create user
        Profile portalProfile = [SELECT Id FROM Profile WHERE UserType = 'CspLitePortal' LIMIT 1];
        objUser = new User(
        Username = System.now().millisecond() + 'test12345@test.com',
        ContactId = contact1.Id,
        ProfileId = portalProfile.Id,
        Alias = 'test123',
        Email = 'test12345@test.com',
        EmailEncodingKey = 'UTF-8',
        LastName = 'McTesty',
        CommunityNickname = 'test12345',
        TimeZoneSidKey = 'America/Los_Angeles',
        LocaleSidKey = 'en_US',
        LanguageLocaleKey = 'en_US'
        );
        Database.insert(objUser);

        objScript = new Script__c();
        Id recorsTypeId  = acfCommon.GetRecordTypeId('Script__c','Post-Login');
        objScript.RecordTypeId = recorsTypeId;
        objScript.acf_Type__c = 'Post-Login';
        objScript.acf_Sequence_no__c = 1;
        objScript.acf_Question_Type__c = 'Applicant Details';
        //objScript.Click_Community_Setup__c = 'a2SO0000001PtV9';
        insert objScript;
        //objQuestion   = acfCommonTrackerClass.CreatePostLoginQuestions('Who is your current lender?',1,'Button',false,true,objScript.id,'acf_Applicant_Name__c','Contact',true,'acfApplicant2_Name__c',true);
        //objRelatedQuestion   = acfCommonTrackerClass.CreatePostLoginQuestions('Who is your current lender?',1,'Button',false,true,null,'acfApplicant2_Marital_Status__c','lead',true,'acfApplicant2_Monthly_Salary__c',true);

              strapplicantName = '';
        strAppSeqNo = '';
        strapplicantEmail  ='';
        strPhone ='';
        strapplicantName ='MB test';
        strAppSeqNo = '2';
        strapplicantEmail = 'abc@gmail.com';
         strPhone ='9855421202';
        objApplicant = new click_Applicant__c();
        objApplicant.acf_Applicant_Name__c = strapplicantName;
        objApplicant.Applicant_Email__c = strapplicantEmail;     
        objApplicant.Applicant_Phone__c = strPhone;
        insert objApplicant;

        objQuestion = new Question__c ();
        objQuestion.acf_Question__c = 'Who is your current lender?04xxxxxxx';
        objQuestion.acf_Active__c  = true;
        objQuestion.acfRefinance_Sequence_No__c = 1;
        objQuestion.acf_Type__c                 = 'Button';
        objQuestion.acfNew_Loan_Sequence_No__c  = 1.0;
        objQuestion.acfIs_refinance__c          = true;
        objQuestion.acf_Script__c               = objScript.id;
        objQuestion.acfIs_New_Loan__c           = true;
        objQuestion.acf_ApiName__c              = 'acfApplicant2_Name__c';
        objQuestion.acfDependent_Object_Name__c = 'Lead';
        objQuestion.acfDependent_Field_Name__c  = 'acfApproximately_how_much_is_your_house__c';
        objQuestion.acf_Dependents__c = true;
        objQuestion.acfApplicant_2_Api_Name__c = 'acfApplicant2_email__c';
        objQuestion.acfIs_Applicant_Question__c = false;
        objQuestion.acfReplace_Mobile_No__c = true;
        objQuestion.acfDependent_Value__c = 'test';
        objQuestion.acfEmployment_Type__c = true;
        insert objQuestion;

        objRelatedQuestion = new Question__c ();
        objRelatedQuestion.acf_Question__c = 'Who is your current lender?04xxxxxxx';
        objRelatedQuestion.acf_Active__c  = true;
        objRelatedQuestion.acfReplace_Mobile_No__c = true;
        objRelatedQuestion.acfRefinance_Sequence_No__c = 1;
        objRelatedQuestion.acf_Type__c                 = 'Text';
        objRelatedQuestion.acfNew_Loan_Sequence_No__c  = 1.0;
        objRelatedQuestion.acfIs_refinance__c          = true;
        objRelatedQuestion.acf_Script__c               = objScript.id;
        objRelatedQuestion.acfIs_New_Loan__c           = true;
        objRelatedQuestion.acf_ApiName__c              = 'acfEconsent_App2__c';
        objRelatedQuestion.acfDependent_Object_Name__c = 'Contact';
        objRelatedQuestion.acfDependent_Field_Name__c  = 'acfApproximately_how_much_is_your_house__c';
        objRelatedQuestion.acf_Dependents__c = true;
        objRelatedQuestion.acfApplicant_2_Api_Name__c = 'acfApplicant2_phone__c';
        objRelatedQuestion.acfIs_Applicant_Question__c = false;
        objRelatedQuestion.acfDependent_Value__c = 'test';
        objRelatedQuestion.acfEmployment_Type__c = true;
        insert objRelatedQuestion;

        Question__c objQuestion1 = new Question__c ();
        objQuestion1.acf_Question__c = '04xxxxxxxWho is your current lender?';
        objQuestion1.acf_Active__c  = true;
        objQuestion1.acfRefinance_Sequence_No__c = 1;
        objQuestion1.acf_Type__c                 = 'Button';
        objQuestion1.acfNew_Loan_Sequence_No__c  = 1.0;
        objQuestion1.acfIs_refinance__c          = true;
        //objQuestion1.acf_Script__c               = objScript.id;
        objQuestion1.acfEmployment_Type__c = true;
        objQuestion1.acfIs_New_Loan__c           = true;
        objQuestion1.acf_ApiName__c              = 'acfEconsent__c';
        objQuestion1.acfDependent_Object_Name__c = 'Lead';
        objQuestion1.acfDependent_Field_Name__c  = 'acfApproximately_how_much_is_your_house__c';
        objQuestion1.acf_Dependents__c = true;
        objQuestion1.acfApplicant_2_Api_Name__c = 'affiliate_source__c';
        objQuestion1.acfIs_Applicant_Question__c = false;
        objQuestion1.acfReplace_Mobile_No__c = true;
        objQuestion1.acfDependent_Value__c = 'test';
        insert objQuestion1;

        objAnswer     = WLCommonTrackerClass.createAnswer(objQuestion.id, null,'2');
        }
    }
}