src/objects/acfBank_Detail__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfBank_Name__c</fullName>
        <description>Click Loans</description>
        <label>Bank Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Click Loans Bank Detail</label>
    <nameField>
        <displayFormat>BNK{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Bank Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Answer__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Click_Community_Setup__c</fullName>
        <formula>acf_Question__r.Click_Community_Setup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Community Setup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Click Loans Answer</label>
    <nameField>
        <displayFormat>Ans-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLoan_Amount__c</fullName>
        <description>Click Loans</description>
        <label>Outstanding Loan Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfIs_Bank_Statement_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Bank Statement Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Post_Login_Ques_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Post Login Ques Attempted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfLoan_Amount__c</fullName>
        <description>Click Loans</description>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOneTimePassword__c</fullName>
        <description>Click Loans</description>
        <label>One Time Password</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDependent_Field_Name__c</fullName>
        <description>Click Loans</description>
        <label>Dependent on (Field Name)</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfDependent_Object_Name__c</fullName>
        <description>Click Loans</description>
        <label>Dependent on (Object Name)</label>
        <picklist>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfIs_refinance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is refinance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Script</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClickPreLoginQuestionControllerTracker.cls
@isTest
public class   ClickPreLoginQuestionControllerTracker
{
    private static Lead objLead ;
    private static User objUser;
    private static Click_Community_Setup__c objcommunity;
    private static List<Click_Community_Setup__c> lstcommunity;
    private static account objpersonAccount;
    private static account objAccount;
    private static account objAccount1;
    public static Question__c objQuestion;
    private static click_Applicant__c objclickappl;
    private static Contact objContact;
    private static Lead objLead12;
    private static Opportunity objOpportunity;
    public static Script__c  objScript;
    
    static testMethod void validate()
    {
        LoadData();
        
        objAccount1 =new account();
        objAccount1.recordtypeid=Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        objAccount1.lastname='test';
        objAccount1.SelfLookup__c=objAccount.id;
        objAccount1.PersonEmail='test@gmail.com';
        objAccount1.Phone='6768868';
        objAccount1.Click_Community_Setup__c=objcommunity.id; 
        objAccount1.IsMaster__c=false;
        insert objAccount1;
        objScript = WLCommonTrackerClass.createScript('Pre-Login');
        
        objScript.Click_Community_Setup__c = objcommunity.id;
        update objScript;
        
        Question__c queobj1=new Question__c();
        queobj1.acf_Active__c=true;
        queobj1.Click_Is_Broker_Question__c=false;
        queobj1.acf_Script__c=objScript.id;
        queobj1.acfDependent_Field_Name__c='test';
        queobj1.click_is_EConsent__c=true;
        queobj1.acfDependent_Object_Name__c='Contact';
        insert queobj1;  
        
        Answer__c ansobj=new Answer__c();
        ansobj.acf_Question__c=objQuestion.id;
        insert ansobj;
        
        ClickPreLoginQuestionController obj=new ClickPreLoginQuestionController(new ApexPages.StandardController(objpersonAccount));
        obj.strBubbleText='ashna';
        string abc=obj.strBubbleText;
        obj.selectedCommunity=objcommunity.id;
        ClickPreLoginQuestionController.WrapperQuestions oo=new ClickPreLoginQuestionController.WrapperQuestions();
        oo.strWrapAnswer='test';
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--Select--'));
        options.add(new SelectOption('Refinance','Refinance'));
        options.add(new SelectOption('New Purchase','New Purchase')); 
        
        oo.lstSelectOpt=options;
        
        List<Answer__c> lstans=new List<Answer__c>();
        lstans.add(ansobj);
        oo.lstSelectOptions=lstans;
        
        List<string> lst=new  List<string>();
        lst.add('test');
        oo.lstCheckBoxAnswer=lst;
        
        account objAccount2 =new account();
        objAccount2.recordtypeid=Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        objAccount2.lastname='test';
        objAccount2.SelfLookup__c=objAccount.id;
        objAccount2.PersonEmail='test@gmail.com';
        objAccount2.Phone='6768868';
        objAccount2.Click_Community_Setup__c=objcommunity.id; 
        objAccount2.IsMaster__c=false;
        insert objAccount2;
        list<Account> lstAcc = new list<Account>();
        lstAcc.add(objAccount2);
        obj.lstAcc =  lstAcc;   
        obj.saveLead();
        
        acfBank_Detail__c acobj=new acfBank_Detail__c();
        acobj.acfBank_Name__c='test';
        acobj.click_Show_on_Current_Lender_question__c=true;
        insert acobj;
        
        List<SelectOption> bnkobj=obj.getBankNames();
        List<SelectOption> loanobj=obj.getLoanType();
        List<SelectOption> comobj=obj.getCommunity();
        
        obj.selectedLoanType = 'New Purchase';
        obj.saveLead();
}

 static testMethod void validate3()
    {
        LoadData();
        
        objAccount1 =new account();
        objAccount1.recordtypeid=Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        objAccount1.lastname='test';
        objAccount1.SelfLookup__c=objAccount.id;
        objAccount1.PersonEmail='test@gmail.com';
        objAccount1.Phone='6768868';
        objAccount1.Click_Community_Setup__c=objcommunity.id; 
        objAccount1.IsMaster__c=false;
        insert objAccount1;
        objScript = WLCommonTrackerClass.createScript('Pre-Login');
        
        objScript.Click_Community_Setup__c = objcommunity.id;
        update objScript;
        
        Question__c queobj1=new Question__c();
        queobj1.acf_Active__c=true;
        queobj1.Click_Is_Broker_Question__c=false;
        queobj1.acf_Script__c=objScript.id;
        queobj1.acfDependent_Field_Name__c='test';
        queobj1.click_is_EConsent__c=true;
        queobj1.acfDependent_Object_Name__c='Contact';
        insert queobj1;  
        
        Answer__c ansobj=new Answer__c();
        ansobj.acf_Question__c=objQuestion.id;
        insert ansobj;
        
        ClickPreLoginQuestionController obj=new ClickPreLoginQuestionController(new ApexPages.StandardController(objpersonAccount));
        ClickPreLoginQuestionController.WrapperQuestions oo=new ClickPreLoginQuestionController.WrapperQuestions();
        oo.strWrapAnswer = 'test'; 
        List<ClickPreLoginQuestionController.WrapperQuestions> lstoo=new List<ClickPreLoginQuestionController.WrapperQuestions>();
        lstoo.add(oo);
        obj.lstWrapperQuestion = lstoo;
        obj.strBubbleText='ashna';
        string abc=obj.strBubbleText;
        obj.saveLead();
        obj.selectedCommunity=objcommunity.id;
        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--Select--'));
        options.add(new SelectOption('Refinance','Refinance'));
        options.add(new SelectOption('New Purchase','New Purchase')); 
        oo.lstSelectOpt=options;
        
        List<Answer__c> lstans=new List<Answer__c>();
        lstans.add(ansobj);
        oo.lstSelectOptions=lstans;
        
        List<string> lst=new  List<string>();
        lst.add('test');
        oo.lstCheckBoxAnswer=lst;
        
        account objAccount2 =new account();
        objAccount2.recordtypeid=Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        objAccount2.lastname='test';
        objAccount2.SelfLookup__c=objAccount.id;
        objAccount2.PersonEmail='test@gmail.com';
        objAccount2.Phone='6768868';
        objAccount2.Click_Community_Setup__c=objcommunity.id; 
        objAccount2.IsMaster__c=false;
        insert objAccount2;
        list<Account> lstAcc = new list<Account>();
        lstAcc.add(objAccount2);
        obj.lstAcc =  lstAcc;   
        
        acfBank_Detail__c acobj=new acfBank_Detail__c();
        acobj.acfBank_Name__c='test';
        acobj.click_Show_on_Current_Lender_question__c=true;
        insert acobj;
        
        List<SelectOption> bnkobj=obj.getBankNames();
        List<SelectOption> loanobj=obj.getLoanType();
        List<SelectOption> comobj=obj.getCommunity();
        obj.selectedLoanType = 'New Purchase';
}

       static testMethod void validate4()
    {
        LoadData();
        
        objAccount1 =new account();
        objAccount1.recordtypeid=Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        objAccount1.lastname='test';
        objAccount1.SelfLookup__c=objAccount.id;
        objAccount1.PersonEmail='test@gmail.com';
        objAccount1.Phone='6768868';
        objAccount1.Click_Community_Setup__c=objcommunity.id; 
        objAccount1.IsMaster__c=false;
        insert objAccount1;
        objScript = WLCommonTrackerClass.createScript('Pre-Login');
        
        objScript.Click_Community_Setup__c = objcommunity.id;
        update objScript;
        
        Question__c queobj1=new Question__c();
        queobj1.acf_Active__c=true;
        queobj1.Click_Is_Broker_Question__c=false;
        queobj1.acf_Script__c=objScript.id;
        queobj1.acfDependent_Field_Name__c='test';
        queobj1.click_is_EConsent__c=true;
        queobj1.acfDependent_Object_Name__c='Contact';
        insert queobj1;  
        
        Answer__c ansobj=new Answer__c();
        ansobj.acf_Question__c=objQuestion.id;
        insert ansobj;
        
        ClickPreLoginQuestionController obj=new ClickPreLoginQuestionController(new ApexPages.StandardController(objpersonAccount));
        obj.selectedLoanType = 'New Purchase';
        ClickPreLoginQuestionController.WrapperQuestions oo=new ClickPreLoginQuestionController.WrapperQuestions();
        List<ClickPreLoginQuestionController.WrapperQuestions> lstoo=new List<ClickPreLoginQuestionController.WrapperQuestions>();
        lstoo.add(oo);
        obj.lstWrapperQuestion = lstoo;
        obj.strBubbleText='ashna';
        string abc=obj.strBubbleText;
        obj.selectedCommunity=objcommunity.id;
        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--Select--'));
        options.add(new SelectOption('Refinance','Refinance'));
        options.add(new SelectOption('New Purchase','New Purchase')); 
        oo.lstSelectOpt=options;
        
        List<Answer__c> lstans=new List<Answer__c>();
        lstans.add(ansobj);
        oo.lstSelectOptions=lstans;
        
        List<string> lst=new  List<string>();
        lst.add('test');
        oo.lstCheckBoxAnswer=lst;
        
        account objAccount2 =new account();
        objAccount2.recordtypeid=Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        objAccount2.lastname='test';
        objAccount2.SelfLookup__c=objAccount.id;
        objAccount2.PersonEmail='test@gmail.com';
        objAccount2.Phone='6768868';
        objAccount2.Click_Community_Setup__c=objcommunity.id; 
        objAccount2.IsMaster__c=false;
        insert objAccount2;
        list<Account> lstAcc = new list<Account>();
        lstAcc.add(objAccount2);
        obj.lstAcc =  lstAcc;   
        
        acfBank_Detail__c acobj=new acfBank_Detail__c();
        acobj.acfBank_Name__c='test';
        acobj.click_Show_on_Current_Lender_question__c=true;
        insert acobj;
        
        List<SelectOption> bnkobj=obj.getBankNames();
        List<SelectOption> loanobj=obj.getLoanType();
        List<SelectOption> comobj=obj.getCommunity();
        obj.selectedLoanType = 'New Purchase';
        obj.saveLead();
}


      static testMethod void validate1()
    {
        LoadData();
        ApexPages.currentPage().getParameters().put('Id',objpersonAccount.id);
        ClickPreLoginQuestionController obj=new ClickPreLoginQuestionController(new ApexPages.StandardController(objpersonAccount));
        obj.PreLoginQuestion();
        obj.saveLead();
        obj.getCommunity();
        obj.getBankNames();
    }
    
      static testMethod void validate2()
    {
        LoadData();
        objAccount1 =new account();
        objAccount1.recordtypeid=Schema.SObjectType.account.getRecordTypeInfosByName().get('Person Account').getRecordTypeId();
        objAccount1.lastname='test';
        objAccount1.SelfLookup__c=objAccount.id;
        objAccount1.PersonEmail='test@gmail.com';
        objAccount1.Phone='6768868';
        objAccount1.Click_Community_Setup__c=objcommunity.id; 
        objAccount1.IsMaster__c=false;
        insert objAccount1;
                      
        Question__c queobj1=new Question__c();
        queobj1.acf_Active__c=true;
        queobj1.Click_Is_Broker_Question__c=false;
        queobj1.acf_Script__c=objScript.id;
        queobj1.acfDependent_Field_Name__c='test';
        queobj1.click_is_EConsent__c=true;
        queobj1.acfDependent_Object_Name__c='Contact';
        objQuestion.acfIs_refinance__c = true;
        insert queobj1;  
        
        Answer__c ansobj=new Answer__c();
        ansobj.acf_Question__c=objQuestion.id;
        insert ansobj;
  
        ClickPreLoginQuestionController obj=new ClickPreLoginQuestionController(new ApexPages.StandardController(objpersonAccount));
        obj.selectedCommunity=objcommunity.id;
        obj.selectedLoanType='Refinance';
        obj.PreLoginQuestion();
        obj.saveLead();
}
    private static void LoadData()
    {    
        createLead12();
        createPersonAccount();
        createAccount();
        createUser();
        createclickCommunitySetup();
        createLead(); 
        createScript();
        createQuestion();
        createContact();
        createOpportunity1();
    }
   
       static void createLead12()
    {
        objLead12 = new Lead();
        objLead12 = WLCommonTrackerClass.createLead(objLead12 );
    }
    
    static void createLead()
    {
       objLead = new Lead();
       
        Id recorsTypeId  = acfCommon.GetRecordTypeId('Lead','Click Refi');
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.Status = 'Open';
        objLead.RecordTypeId = recorsTypeId;
        objLead.acfOneTimePassword__c = '724715';
        objLead.acfApproximately_how_much_is_your_house__c = 100.01;
        objLead.acfLoan_Amount__c = 100.20;
        objLead.acfIs_Bank_Statement_Submitted__c = true;
        objLead.acfIs_Post_Login_Ques_Attempted__c =true;
        insert objLead;
    }

    static void createLead1()
    {
        objLead = new Lead();
        Id recorsTypeId  = acfCommon.GetRecordTypeId('Lead','Click Refi');
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.Status = 'Open';
        objLead.RecordTypeId = recorsTypeId;
        objLead.acfOneTimePassword__c = '724715';
        objLead.acfApproximately_how_much_is_your_house__c = 100.01;
        objLead.acfLoan_Amount__c = 100.20;
        objLead.acfIs_Bank_Statement_Submitted__c = true;
        objLead.acfIs_Post_Login_Ques_Attempted__c =true;
        insert objLead;
    }

    static void createContact()
    {
        objContact = new Contact();
        objContact.acf_lead__c = objLead.id;
        objContact = WLCommontrackerClass.createContact(objContact,objAccount);
    }
    
    static void createuser()
    {
         objUser = new User();
         objUser = WLCommonTrackerClass.CreatePortalUser(objpersonAccount.id);
    }
    
    static void createOpportunity1()
    {
      objOpportunity = new Opportunity();
      objOpportunity.acfBankdetailStatus__c = 'Skipped';
      objOpportunity = WLCommontrackerClass.createOpportunity(objOpportunity,objUser);
    }
    
     static void createPersonAccount()
    {
        objpersonAccount= new Account();
        objpersonAccount=WLCommonTrackerClass.CreatePersonAccount('Fname','LName','strPhone','strLead12Email@gmail.com',objLead12.Id);
    }
   
    static void  createAccount()
     {
         objAccount =new account();
         objAccount=WLCommontrackerClass.createAccount(objAccount);
     }
    
    
     static void createclickCommunitySetup() 
    {
        objcommunity = new Click_Community_Setup__c();
        objcommunity = WLCommontrackerClass.createcommunitysetup();
        lstcommunity = new List<Click_Community_Setup__c>();
        lstcommunity.add(objcommunity );
    }
    
    public static void createScript()
    {
        objScript = WLCommonTrackerClass.createScript('Pre-Login');
        objScript.Click_Community_Setup__c = objcommunity.id;
        update objScript;
    }
    
    public static void createQuestion()
    {
        objQuestion=new Question__c();
        Id ScriptID = objScript.id;
        objQuestion = WLCommontrackerClass.CreatePrePostLoginQuestions('test',1,'Pre-Login',true,true,ScriptID,'test');
    }
}