src/objects/acfCMS_Page__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDescription__c</fullName>
        <description>Click Loans</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acfHeading__c</fullName>
        <description>Click Loans</description>
        <label>Heading</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Click Loans CMS Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/acfFAQ__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfAnswer__c</fullName>
        <description>Click Loans</description>
        <label>Answer</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acfCMSPage__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>CMS Page</label>
        <referenceTo>acfCMS_Page__c</referenceTo>
        <relationshipName>acfFAQs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfFAQType__c</fullName>
        <description>Click Loans</description>
        <label>FAQ Type</label>
        <picklist>
            <picklistValues>
                <fullName>Borrower Eligibility</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applying for a Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Verification</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Making Loan Payments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>About Click Loans</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfQuestion__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <type>TextArea</type>
    </fields>
    <label>Click Loans FAQ</label>
    <nameField>
        <displayFormat>FAQ-{0000}</displayFormat>
        <label>acfFAQ Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ACF FAQs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/WLPostquestionControllerTracker.cls
@isTest(seeAllData=true)
private class WLPostquestionControllerTracker{
    private static User objUser;
    private static Contact objContact;
    private static Account objAccount;
    private static Opportunity objOpportunity;
    
    static testMethod void validateController(){
            LoadData();
            WLPostquestionController objpost = new WLPostquestionController();
            objpost.isError = true;
            objpost.ResetPopup();
            objpost.postQuery();
         }     
         
    static testMethod void validateController2(){
            LoadData();
            WLPostquestionController objpost = new WLPostquestionController();
            objpost.isError = true;       
            objpost.ResetPopup();
            objpost.strPost = null;
            objpost.postQuery();
        }
    
    private static void LoadData(){
            createAccount();
  //          createContact();
            createUser();
            createOpportunity();
    }
    
    static void createAccount(){
            objAccount = new Account();
            objAccount = acfCommonTrackerClass.CreatePersonAccount('test','test','+619540505050','test@fakeemail.com',null);
    }
    
    static void createContact(){
            objContact = new Contact();
            objContact = WLCommontrackerClass.createContact(objContact,objAccount);
    }
    
    static void createUser(){
            objUser = new User();
  //          objUser.Contactid = objContact.id;
            objUser = WLCommontrackerClass.CreatePortalUser(objAccount.id);
    }
    
    static void createOpportunity(){
            objOpportunity = new Opportunity();
            objOpportunity.acfBankdetailStatus__c = 'Skipped';
            objOpportunity = WLCommontrackerClass.createOpportunity(objOpportunity,objUser);
    }
/*        acfCMS_Page__c obj = new acfCMS_Page__c ();
        obj .Name ='ClickFAQ';
        obj .acfDescription__c = 'Ankit Singh';
        obj .acfHeading__c = 'abcd';
        insert obj ;
        
        list<acfFAQ__c>  lstacf = new list<acfFAQ__c>(); 
        acfFAQ__c objf = new acfFAQ__c();
        objf.acfAnswer__c  = 'test';
        objf.acfCMSPage__c = obj.id;
        objf.acfFAQType__c = 'Applying for a Loan';
        objf.acfQuestion__c = 'test';
        lstacf.add(objf);
        
        acfFAQ.wrapperFAQType wrap = new acfFAQ.wrapperFAQType();
        acfFAQ.WrapperFAQ wrp = new acfFAQ.WrapperFAQ();
        wrp.id = '1234';
        
        acfFAQ  objFAQ = new acfFAQ();
        objFAQ.strUserName = 'test';
        objFAQ.strUserPhone = 'test';
        objFAQ.strUserEmail = 'test@test.com';
        objFAQ.strQuestion = 'test';
        objFAQ.strErrorMsg = 'test';
        objFAQ.lstacfFAQ = lstacf; 
        objFAQ.submitCase();
        
    
    }*/


}