src/objects/acfCMS_Page__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDescription__c</fullName>
        <description>Click Loans</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acfHeading__c</fullName>
        <description>Click Loans</description>
        <label>Heading</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <label>Click Loans CMS Page</label>
    <nameField>
        <label>Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CMS Page</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/acfContentManagementSystem__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfCMS_Page__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>CMS Page</label>
        <referenceTo>acfCMS_Page__c</referenceTo>
        <relationshipName>Content_Management_System</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfDescriptionImageURL__c</fullName>
        <description>Click Loans</description>
        <formula>IF(  acfDescriptionAttachmentID__c &lt;&gt; null, &quot;/servlet/servlet.FileDownload?file=&quot;&amp; acfDescriptionAttachmentID__c , &quot;&quot;)</formula>
        <label>Description Image URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfDescription__c</fullName>
        <description>Click Loans</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acfHeadingRemoveSpace__c</fullName>
        <description>Click Loans</description>
        <formula>SUBSTITUTE( acfHeading__c , &apos; &apos;, &apos;&apos;)</formula>
        <label>Heading Remove Space</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfHeading_Caption__c</fullName>
        <description>Click Loans</description>
        <label>Heading Caption</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfHeading__c</fullName>
        <description>Click Loans</description>
        <label>Heading</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfImageURL__c</fullName>
        <description>Click Loans</description>
        <formula>IF( acfAttachmentId__c  &lt;&gt; null, &quot;/servlet/servlet.FileDownload?file=&quot;&amp;acfAttachmentId__c, &quot;&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Heading Image URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfIs_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfMoreDetailURL__c</fullName>
        <description>Click Loans</description>
        <label>More Detail URL</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfSectionName__c</fullName>
        <description>Click Loans</description>
        <label>Section Name</label>
        <picklist>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer Links</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer Link Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTP Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend OTP Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>About Us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfSequence__c</fullName>
        <description>Click Loans</description>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acfShort_Description__c</fullName>
        <description>Click Loans</description>
        <label>Short Description</label>
        <type>TextArea</type>
    </fields>
    <label>Click Loans Content Management System</label>
    <nameField>
        <displayFormat>cms-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Management System</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/clickFooterLinkController.cls
/*=================================================
				Click Loans
=====================================================*/
public without sharing class clickFooterLinkController
{
    public list<acfContentManagementSystem__c> lstFooterLink {get;set;}
    public string strPagetitle {get;set;}
    public string strDescription {get;set;}
    public clickFooterLinkController()
    {    
        strPagetitle = '';
        strDescription = '';
        string strCMSPageId = apexpages.currentpage().getparameters().get('pid');
        try{
            lstFooterLink = [select acfDescription__c,acfShort_Description__c ,acfIs_Checked__c ,acfHeadingRemoveSpace__c, acfHeading__c, acfImageURL__c, acfMoreDetailURL__c, acfSectionName__c, acfSequence__c,acfDescriptionImageURL__c, Id, Name,acfHeading_Caption__c,acfCMS_Page__c FROM acfContentManagementSystem__c WHERE acfCMS_Page__c =: strCMSPageId AND acfIs_Checked__c = true AND acfSectionName__c != 'Footer Links' AND acfSectionName__c = 'Footer Link Content' ORDER BY acfSequence__c ASC NULLS FIRST]; 
            list<acfCMS_Page__c> lstCSMPage = [select id,name,acfDescription__c,acfHeading__c from acfCMS_Page__c where id =:strCMSPageId limit 1];
            if(lstCSMPage != null && lstCSMPage.size()>0)
            {
                strPagetitle = lstCSMPage[0].acfHeading__c;
                strDescription = lstCSMPage[0].acfDescription__c;
            }
        }catch(Exception Ex){
            system.debug('@@@@@@@@@'+ex);
        }
    }
}