src/objects/acfContentManagementSystem__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDescription__c</fullName>
        <description>Click Loans</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acfHeader_Sequance__c</fullName>
        <description>Click Loans</description>
        <label>Header Sequance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acfHeading__c</fullName>
        <description>Click Loans</description>
        <label>Heading</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfIs_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfPageName__c</fullName>
        <description>Click Loans</description>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>acfLogin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfSectionName__c</fullName>
        <description>Click Loans</description>
        <label>Section Name</label>
        <picklist>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer Links</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer Link Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTP Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend OTP Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>About Us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfSequence__c</fullName>
        <description>Click Loans</description>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Click Loans Content Management System</label>
    <nameField>
        <displayFormat>cms-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Management System</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Click_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Click_Network_ID__c</fullName>
        <label>Community Network ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Page_Prefix__c</fullName>
        <label>Page Prefix</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>click_Home_Page_URL__c</fullName>
        <label>Home Page URL</label>
        <type>Url</type>
    </fields>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acf_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfIs_Identity_Document_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfOneTimePassword__c</fullName>
        <description>Click Loans</description>
        <label>One Time Password</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfApproval_Conditions__c</fullName>
        <description>Click Loans</description>
        <label>Approval Conditions</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>acfDate_Conditionally_Approved__c</fullName>
        <description>Click Loans</description>
        <label>Date Conditionally Approved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acfDate_Docs_Generated__c</fullName>
        <description>Click Loans</description>
        <label>Date Docs Generated</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acfDate_Formally_Approved__c</fullName>
        <description>Click Loans</description>
        <label>Date Formally Approved</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acfExpected_Settlement_Date__c</fullName>
        <description>Click Loans</description>
        <label>Expected Settlement Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>acfIs_Identity_Document_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfTenure__c</fullName>
        <description>Click Loans</description>
        <label>Tenure</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Status__c</fullName>
        <description>Click Loans</description>
        <label>Status</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Application</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Settled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditionally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Formally Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved with pending documents</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Docs Generated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved and pending settlement</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClickWelcomeDashboardBrokerTracker.cls
@isTest(SeeAllData = false)
private class ClickWelcomeDashboardBrokerTracker 
{
    private static User objUser;
    private static Contact objContact;
    private static Account objAccount;
    private static Opportunity objOpportunity1;

    
    static testMethod void validate() 
    {
        LoadData();
        Click_Community_Setup__c obj1 = new Click_Community_Setup__c();
        obj1.Click_Network_ID__c = Network.getNetworkId();
        obj1.Click_IsActive__c = true;
        obj1.Click_Page_Prefix__c = 'Click';
  //      obj1.click_Home_Page_URL__c = 'https://uat-creditandfinance.cs5.force.com/ClickLoans';
        insert obj1;      
        
        
      Opportunity objOpportunity = new Opportunity();
      objOpportunity.AccountId =objAccount.id;
      Recordtype rt=[select id from Recordtype where name='Click Refi' and sobjecttype='opportunity' limit 1];
      objOpportunity.recordtypeid = rt.id;
      
      objOpportunity.acfDate_Conditionally_Approved__c = system.today();
      objOpportunity.Description = 'test';
      objOpportunity.acfApproval_Conditions__c = 'testing';
      objOpportunity.acfDate_Formally_Approved__c = system.today();
      objOpportunity.acfDate_Docs_Generated__c = system.today();
      objOpportunity.acfExpected_Settlement_Date__c = system.today().adddays(+3);
      objOpportunity.acf_Status__c = 'Conditionally Approved';
      objOpportunity.acfTenure__c = 2.5;
      objOpportunity.name = 'test';
      objOpportunity.Stagename = 'Application Taken';
      objOpportunity.CloseDate = System.today();
      //objOpportunity.      
      insert objOpportunity;
        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('cid',objAccount.id);
        ClickWelcomeDashboardclone obj = new ClickWelcomeDashboardclone();
        obj.pge_name = 'ClickEditProfile';
        
        

    }
    
      static testMethod void validate1() 
    {
        LoadData1();
        Click_Community_Setup__c obj1 = new Click_Community_Setup__c();
        obj1.Click_Network_ID__c = Network.getNetworkId();
        obj1.Click_IsActive__c = true;
        obj1.Click_Page_Prefix__c = 'Click';
//        obj1.click_Home_Page_URL__c = 'https://uat-creditandfinance.cs5.force.com/ClickLoans';
        insert obj1;    
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objuser.AccountId;
        objOpportunity.name = 'test';
        objOpportunity.recordtypeid = ClickCommon.GetRecordTypeId('Opportunity','Click Refi');
        objOpportunity.Stagename = 'Approval';
        objOpportunity.CloseDate = System.today();
        insert objOpportunity;
        
        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboardclone obj = new ClickWelcomeDashboardclone();
        obj.pge_name = 'ClickEditProfile';
        

    }
    
       static testMethod void validate2() 
    {
        LoadData1();
        Click_Community_Setup__c obj1 = new Click_Community_Setup__c();
        obj1.Click_Network_ID__c = Network.getNetworkId();
        obj1.Click_IsActive__c = true;
        obj1.Click_Page_Prefix__c = 'Click';
 //       obj1.click_Home_Page_URL__c = 'https://uat-creditandfinance.cs5.force.com/ClickLoans';
        insert obj1;     
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objuser.AccountId;
        objOpportunity.name = 'test';
        objOpportunity.recordtypeid = ClickCommon.GetRecordTypeId('Opportunity','Click Refi');
        objOpportunity.Stagename = 'Loan Document';
        objOpportunity.CloseDate = System.today();
        insert objOpportunity;
        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboard obj = new ClickWelcomeDashboard();
        

    }
    
         static testMethod void validate3() 
    {
        LoadData1();
        Click_Community_Setup__c obj1 = new Click_Community_Setup__c();
        obj1.Click_Network_ID__c = Network.getNetworkId();
        obj1.Click_IsActive__c = true;
        obj1.Click_Page_Prefix__c = 'Click';
 //       obj1.click_Home_Page_URL__c = 'https://uat-creditandfinance.cs5.force.com/ClickLoans';
        insert obj1;   
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objuser.AccountId;
        objOpportunity.name = 'test';
        objOpportunity.recordtypeid = ClickCommon.GetRecordTypeId('Opportunity','Click Refi');
        objOpportunity.Stagename = 'Settlement';
        objOpportunity.CloseDate = System.today();
        insert objOpportunity; 
        
         acfContentManagementSystem__c   objContentManagementSystem = new acfContentManagementSystem__c();
        objContentManagementSystem.acfHeading__c = 'POPULAR SEARCHES';
        objContentManagementSystem.acfPageName__c = 'acfLogin';
        objContentManagementSystem.acfSectionName__c = 'Dashboard';
        objContentManagementSystem.acfSequence__c = 5;
        objContentManagementSystem.acfDescription__c = 'Online loans';
        objContentManagementSystem.acfIs_Checked__c = true;
        objContentManagementSystem.acfHeader_Sequance__c = 4;
        objContentManagementSystem.Click_Community_Setup__c = obj1.Id;
        insert objContentManagementSystem;
        
        Task t = new Task();
        t.OwnerId = UserInfo.getUserId();
        t.Subject='test';
        t.Status='open';
        t.Priority='Normal';
        t.WhatId = objOpportunity.id;
        insert t;

        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboardclone obj = new ClickWelcomeDashboardclone();
        

    }
    
     /*static testMethod void validate4() 
    {
        LoadData1();
        
        system.runas(objUser)
        {
        Lead objLead = new Lead();
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.acfIs_Identity_Document_Rejected__c = false;
        objLead.RecordTypeId = ClickCommon.GetRecordTypeId('Lead','Click Refi');
        objLead.Status = 'Open';
        objLead.acfOneTimePassword__c = '724715';
        insert objLead;
        
 //       objUser.contact.acf_lead__c = objLead.id;
 //       update objUser;
        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboardclone obj = new ClickWelcomeDashboardclone();
        obj.pge_name = 'WLEditProfile';
        }
        

    }*/
    
    
    private static void LoadData()
    {
        createAccount();
  //    createContact();
        createUser();
        createOpportunity();

    }
    
     private static void LoadData1()
    {
        createAccount();
  //    createContact();
        createUser();
  //      createOpportunity();

    }
    
    static void createAccount()
    {
        objAccount = new Account();
        objAccount = WLCommonTrackerClass.createAccount(objAccount);
    }
    
    static void createContact()
    {
        objContact = new Contact();
        //objContact.AccountId = objAccount.id;
        //objContact.acf_lead__c = objLead.id;
        objContact = WLCommonTrackerClass.createContact(objContact,objAccount);
    }
    
    static void createuser()
    {
        objUser = new User();
  //      objuser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);
    }
    
     static void createOpportunity()
    {
      objOpportunity1 = new Opportunity();
      objOpportunity1 = WLCommonTrackerClass.createOpportunity(objOpportunity1,objUser);
    }
    
}