src/objects/acfContentManagementSystem__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDescription__c</fullName>
        <description>Click Loans</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acfHeader_Sequance__c</fullName>
        <description>Click Loans</description>
        <label>Header Sequance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acfHeading__c</fullName>
        <description>Click Loans</description>
        <label>Heading</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfIs_Checked__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfPageName__c</fullName>
        <description>Click Loans</description>
        <label>Page Name</label>
        <picklist>
            <picklistValues>
                <fullName>acfLogin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Common</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfSectionName__c</fullName>
        <description>Click Loans</description>
        <label>Section Name</label>
        <picklist>
            <picklistValues>
                <fullName>Footer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer Links</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Footer Link Content</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dashboard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTP Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resend OTP Popup</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>About Us</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Preliminary Quote</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfSequence__c</fullName>
        <description>Click Loans</description>
        <label>Sequence</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Click Loans Content Management System</label>
    <nameField>
        <displayFormat>cms-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Management System</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acf_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfIs_Identity_Document_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Rejected</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfOneTimePassword__c</fullName>
        <description>Click Loans</description>
        <label>One Time Password</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfIs_Identity_Document_Rejected__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Rejected</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ClickWelcomeDashboardTracker.cls
@isTest(SeeAllData = false)
private class ClickWelcomeDashboardTracker 
{
    private static User objUser;
    private static Contact objContact;
    private static Account objAccount;

    
    static testMethod void validate() 
    {
        LoadData();
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objuser.AccountId;
        objOpportunity.name = 'test';
        objOpportunity.Stagename = 'Application Taken';
        objOpportunity.CloseDate = System.today();
        insert objOpportunity;
        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboard obj = new ClickWelcomeDashboard();
        obj.pge_name = 'ClickEditProfile';
        

    }
    
      static testMethod void validate1() 
    {
        LoadData();
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objuser.AccountId;
        objOpportunity.name = 'test';
        objOpportunity.Stagename = 'Approval';
        objOpportunity.CloseDate = System.today();
        insert objOpportunity;
        
        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboard obj = new ClickWelcomeDashboard();
        obj.pge_name = 'ClickEditProfile';
        

    }
    
       static testMethod void validate2() 
    {
        LoadData();
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objuser.AccountId;
        objOpportunity.name = 'test';
        objOpportunity.Stagename = 'Loan Document';
        objOpportunity.CloseDate = System.today();
        insert objOpportunity;
        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboard obj = new ClickWelcomeDashboard();
        

    }
    
         static testMethod void validate3() 
    {
        LoadData();
        
        Opportunity objOpportunity = new Opportunity();
        objOpportunity.AccountId = objuser.AccountId;
        objOpportunity.name = 'test';
        objOpportunity.Stagename = 'Settlement';
        objOpportunity.CloseDate = System.today();
        insert objOpportunity; 
        
         acfContentManagementSystem__c   objContentManagementSystem = new acfContentManagementSystem__c();
        objContentManagementSystem.acfHeading__c = 'POPULAR SEARCHES';
        objContentManagementSystem.acfPageName__c = 'acfLogin';
        objContentManagementSystem.acfSectionName__c = 'Dashboard';
        objContentManagementSystem.acfSequence__c = 5;
        objContentManagementSystem.acfDescription__c = 'Online loans';
        objContentManagementSystem.acfIs_Checked__c = true;
        objContentManagementSystem.acfHeader_Sequance__c = 4;
        insert objContentManagementSystem;
        
        Task t = new Task();
        t.OwnerId = UserInfo.getUserId();
        t.Subject='test';
        t.Status='open';
        t.Priority='Normal';
        t.WhatId = objOpportunity.id;
        insert t;

        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboard obj = new ClickWelcomeDashboard();
        

    }
    
     static testMethod void validate4() 
    {
        LoadData();
        
        Lead objLead = new Lead();
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.acfIs_Identity_Document_Rejected__c = false;
        objLead.Status = 'Open';
        objLead.acfOneTimePassword__c = '724715';
        insert objLead;
        
        PageReference pageRef = new PageReference('http://www.google.com');
        Test.setCurrentPage(pageRef);
        ClickWelcomeDashboard obj = new ClickWelcomeDashboard();
        obj.pge_name = 'ClickEditProfile';
        

    }
    
    
    private static void LoadData()
    {
        createAccount();
        createContact();
        createUser();

    }
    
    static void createAccount()
    {
        objAccount = new Account();
        objAccount = acfCommontrackerClass.createAccount(objAccount);
    }
    
    static void createContact()
    {
        objContact = new Contact();
        //objContact.AccountId = objAccount.id;
        //objContact.acf_lead__c = objLead.id;
        objContact = acfCommontrackerClass.createContact(objContact,objAccount);
    }
    
    static void createuser()
    {
        objUser = new User();
        objuser.ContactId = objContact.id;
        objUser = acfCommontrackerClass.createuser(objUser);
    }
    


    
}