src/objects/acfDealIQ_Condition__c.object
<CustomObject>
    <fields>
        <fullName>acfGlobal_DealIQ_Rule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global DealIQ Rule</label>
        <referenceTo>Global_DealIQ_Condition__c</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>DealIQ_Conditions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>acf_DealIQ_Conditions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>DealIQ Condition</label>
    <nameField>
        <label>DealIQ Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DealIQ Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_DealIQ_Condition__c.object
<CustomObject>
    <fields>
        <fullName>Document_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipLabel>Global DealIQ Rule</relationshipLabel>
        <relationshipName>Global_DealIQ_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Global DealIQ Rule</label>
    <nameField>
        <label>Global DealIQ Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global DealIQ Rule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DealIQTriggerHandlerTracker.cls
@isTest
public with sharing class DealIQTriggerHandlerTracker {
    private static Lead objLead;
        private static User objUser;
        private static Contact objContact;
        private static Account objAccount;
        private static Opportunity objOpp;
        private static click_Applicant__c objClickApp;
        private static Click_Community_Setup__c  cmmset;
        private static Required_Document__c objre;
        private static Document_Master__c objmas;

        static testMethod void validate(){
            loadData();
            ACFSwitch__c acfswitch = new ACFSwitch__c();
            acfswitch.Trigger_Switch_DealIQCondition__c = true;
            insert acfswitch;
            
            Document_Master__c masobj=new Document_Master__c();
            masobj.name='test';
            masobj.Click_Community_Setup__c=cmmset.id;
            insert masobj;
            
            Global_DealIQ_Condition__c dealRule = new Global_DealIQ_Condition__c();
            dealRule.Name =  'Test';
            dealRule.Document_Master__c = masobj.id;
            insert dealRule;
            
            acfDealIQ_Condition__c dealCond = new acfDealIQ_Condition__c();
            dealCond.acfOpportunity__c = objOpp.id;
            dealCond.acfGlobal_DealIQ_Rule__c = dealRule.id;
            dealCond.Name = 'Test Demo';
            system.debug('hiii');
            insert dealCond;
            
            
        }
        
        static void LoadData(){
            createLead();
            createAccount();
            createContact();
            createmasterdoc();
            createUser();
            createOpportunity();
            createcommunitysetup();
        }

      static void createLead(){
            objLead=new Lead();
            objLead=WLCommonTrackerClass.createLead(objLead);
       }
    
    static void createAccount(){
        objAccount = new Account();
        objAccount = WLCommonTrackerClass.CreatePersonAccount('test','test','88','test@gmail.com',objLead.id);
        objAccount.acfAsset_House_Worth__c=55;
        update objAccount; 
    }
    
    static void createContact(){
        objContact = new Contact();
        objContact = WLCommonTrackerClass.createContact(objContact,objAccount );
    }
    
    static void createuser()
    {
        objUser = new User();
        objuser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);
    }
    
    static void createOpportunity()
    {
        objOpp = new Opportunity();
        objOpp = WLCommonTrackerClass.createOpportunity(objOpp,objUser);
     
    }
     static void createcommunitysetup()
    {
       cmmset= new Click_Community_Setup__c ();
       cmmset=WLCommonTrackerClass.createcommunitysetup();
    }
    
   static void createmasterdoc()
    {
        objmas= new Document_Master__c(); 
        objmas= WLCommonTrackerClass.createDocumentMaster(objmas);
    }
    
}