src/objects/acfDealIQ_Condition__c.object
<CustomObject>
    <fields>
        <fullName>acfCategory__c</fullName>
        <formula>TEXT(acfGlobal_DealIQ_Rule__r.Category__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Category</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfClick_Loans_Bank_Detail__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Bank Detail</label>
        <referenceTo>acfBank_Detail__c</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>DealIQ_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfClick_Loans_Suggested_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Suggested Product</label>
        <referenceTo>acfSuggested_Product__c</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>DealIQ_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfComments__c</fullName>
        <label>Comments</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>acfCondition_Closed_DateTime__c</fullName>
        <label>Condition Closed DateTime</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>acfGlobal_DealIQ_Rule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global DealIQ Rule</label>
        <referenceTo>Global_DealIQ_Condition__c</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>DealIQ_Conditions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>acf_DealIQ_Conditions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>DealIQ_Conditions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfStatus__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Mitigated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Mitigated</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfSystem_Mitigated_Notes__c</fullName>
        <label>System Mitigated Notes</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>acfTrigger_String__c</fullName>
        <label>Trigger String</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>acfUser__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>DealIQ_ConditionsUser1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DealIQ Condition</label>
    <nameField>
        <label>DealIQ Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DealIQ Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/EmailHistory__c.object
<CustomObject>
    <fields>
        <fullName>AcfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Email History</relationshipLabel>
        <relationshipName>Email_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>subject__c</fullName>
        <label>subject</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Email History</label>
    <nameField>
        <displayFormat>Email-{0}</displayFormat>
        <label>Email History Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_DealIQ_Condition__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Character</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collateral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capital</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Capacity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Global DealIQ Rule</label>
    <nameField>
        <label>Global DealIQ Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global DealIQ Rule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Jumio Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/S3Document__c.object
<CustomObject>
    <fields>
        <fullName>emailHistory__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Email History</label>
        <referenceTo>EmailHistory__c</referenceTo>
        <relationshipLabel>S3Documents</relationshipLabel>
        <relationshipName>S3Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>S3Document</label>
    <nameField>
        <label>S3Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>S3Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Servicing__c.object
<CustomObject>
    <fields>
        <fullName>Max_Borrowing_Power__c</fullName>
        <label>Max Borrowing Power</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Net_Monthly_Surplus__c</fullName>
        <label>Net Monthly Surplus</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Servicing Calculators</relationshipLabel>
        <relationshipName>Servicing_Calculators</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Services_Funds_Requested__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Services Funds Requested</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Services_Funds_Required__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Services Funds Required</label>
        <type>Checkbox</type>
    </fields>
    <label>Servicing Calculator</label>
    <nameField>
        <label>Servicing Calculator Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Servicing Calculators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WLDealIQcontroller.cls
public class WLDealIQcontroller {
public String opportunityId;
public List<Opportunity> lstopportunity{get;set;}
public List<acfDealIQ_Condition__c> lstDealIqCondition{get;set;}
public Boolean creditGuide{get;set;}
public Boolean creditProposalDisclosure{get;set;}
public Boolean preliminaryAssesment{get;set;}
public String creditGuideId{get;set;}
public String creditProposalDisclosureId{get;set;}
public String preliminaryAssesmentId{get;set;}
public acfDealIQ_Condition__c objDealIqCondition{get;set;}
    public WLDealIQcontroller () {
       opportunityId = '';
       creditGuide = false;
       creditProposalDisclosure =false;
       preliminaryAssesment = false;
       creditGuideId = '';
       creditProposalDisclosureId = '';
       preliminaryAssesmentId = '';
       lstopportunity = new List<Opportunity>();
       lstDealIqCondition = new List<acfDealIQ_Condition__c>();
       opportunityId = ApexPages.currentPage().getParameters().get('id');
       List<EmailHistory__c> lstEmailHistory = new List<EmailHistory__c>();
       Set<Id> setOfEmailHistoryId= new Set<Id>();
       List<S3Document__c> lstS3Doc = new List<S3Document__c>();
       if(opportunityId != null && opportunityId != '')
       {
           lstopportunity = [SELECT Id, Name ,amount ,(SELECT Id,Name,acfClick_Loans_Bank_Detail__c,acfClick_Loans_Suggested_Product__c,acfComments__c,
                             acfCondition_Closed_DateTime__c,acfOpportunity__c,acfGlobal_DealIQ_Rule__c,acfGlobal_DealIQ_Rule__r.Category__c,acfCategory__c,
                             acfProduct__c,acfStatus__c,acfSystem_Mitigated_Notes__c,acfTrigger_String__c,acfUser__c FROM acf_DealIQ_Conditions__r),(SELECT Id,
                             Description,IsDeleted,ListPrice,Name,OpportunityId,ProductCode,Quantity,ServiceDate,SortOrder,TotalPrice,UnitPrice
                             FROM OpportunityLineItems),(select id,Max_Borrowing_Power__c,Net_Monthly_Surplus__c,Opportunity__c,Services_Funds_Requested__c,
                             Services_Funds_Required__c from Servicing_Calculators__r),(select id,Name,AcfOpportunity__c,subject__c from Email_History__r Order By createddate DESC)
                             FROM Opportunity WHERE Id =:Id.valueof(opportunityId)];
                            
           if(lstopportunity != null && !lstopportunity.Isempty())  
           {
               for(Opportunity objOpp : lstopportunity)
               {
                   if(objOpp.Email_History__r != null && !objOpp.Email_History__r.isEmpty())
                   {
                       for(EmailHistory__c objEmailHistory : objOpp.Email_History__r)
                       {
                           lstEmailHistory.add(objEmailHistory); 
                           setOfEmailHistoryId.add(objEmailHistory.id);    
                       }
                   }
               }
           }   
           
           if(lstEmailHistory != null && !lstEmailHistory.isEmpty()) 
           {
               lstS3Doc = [select id,Name,emailHistory__c from S3Document__c where emailHistory__c =:setOfEmailHistoryId Order By createddate ASC];
               if(lstS3Doc != null && !lstS3Doc.IsEmpty())
               {
                   for(S3Document__c objS3Doc : lstS3Doc)
                   {
                       if(objS3Doc.Name.containsIgnoreCase('CreditGuide'))
                       {
                           creditGuide = true;
                           creditGuideId = '/'+objS3Doc.emailHistory__c;
                       }
                       else if(objS3Doc.Name.containsIgnoreCase('CreditProposal'))
                       {     
                           creditProposalDisclosure = true;
                           creditProposalDisclosureId = '/'+objS3Doc.emailHistory__c;
                       }
                       else if(objS3Doc.Name.containsIgnoreCase('Preliminary'))     
                       {
                           preliminaryAssesment = true;
                           preliminaryAssesmentId = '/'+objS3Doc.emailHistory__c;
                       }       
                   }
               }
           }                                                      
       }
    }
    //========================================================================================================
    // This Method is used to get Deal IQ Record when we click on Mitigate or View Button.
    //========================================================================================================
    public void DealIqRecord()
    {
        string DealIqConditionIds = Apexpages.currentPage().getParameters().get('DealIqIds');
        system.debug('DealIqConditionIds*****************'+DealIqConditionIds);
        if(DealIqConditionIds != null && DealIqConditionIds != '')
        {
           lstDealIqCondition = [SELECT Id,Name,acfClick_Loans_Bank_Detail__c,acfClick_Loans_Suggested_Product__c,acfComments__c,acfCondition_Closed_DateTime__c,
                                 acfOpportunity__c,acfGlobal_DealIQ_Rule__c,acfGlobal_DealIQ_Rule__r.Name,acfGlobal_DealIQ_Rule__r.Category__c,acfCategory__c,
                                 acfProduct__c,acfStatus__c,acfSystem_Mitigated_Notes__c,acfTrigger_String__c,acfUser__c From acfDealIQ_Condition__c
                                 where id=:DealIqConditionIds limit 1];
           system.debug('lstDealIqCondition *****************'+lstDealIqCondition);
        }
    }
    
    //========================================================================================================
    // This Method is used to update Deal IQ Record when we click on Mitigate or View Button.
    //========================================================================================================
    public pagereference updateDealIqRecord()
    {
        if(lstDealIqCondition != null && lstDealIqCondition.size() > 0)
        {
            acfDealIQ_Condition__c objDealIqCondition = new acfDealIQ_Condition__c(id=lstDealIqCondition[0].id);
            objDealIqCondition.acfStatus__c = 'Mitigated';
            objDealIqCondition.acfComments__c = lstDealIqCondition[0].acfComments__c;
            update objDealIqCondition;
            system.debug('objDealIqCondition************'+objDealIqCondition);
            pagereference pg = new pagereference('/apex/AcfDealIQ?id='+opportunityId);  
            pg.setredirect(true); 
            return pg;
        }
        return null;
    }
}