src/objects/acfDealIQ_Condition__c.object
<CustomObject>
    <fields>
        <fullName>acfGlobal_DealIQ_Rule__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Global DealIQ Rule</label>
        <referenceTo>Global_DealIQ_Condition__c</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>DealIQ_Conditions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>DealIQ Conditions</relationshipLabel>
        <relationshipName>acf_DealIQ_Conditions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfStatus__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Mitigated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>System Mitigated</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>DealIQ Condition</label>
    <nameField>
        <label>DealIQ Condition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DealIQ Conditions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Source__c</fullName>
        <description>Click Loans</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Jumio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Global_DealIQ_Condition__c.object
<CustomObject>
    <fields>
        <fullName>Document_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipLabel>Global DealIQ Rule</relationshipLabel>
        <relationshipName>Global_DealIQ_Rule</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Global DealIQ Rule</label>
    <nameField>
        <label>Global DealIQ Rule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Global DealIQ Rule</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDocument_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Bank_Statement_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Bank Statement Doc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Is_Identity_Verification_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Identity Verification Doc</label>
        <type>Checkbox</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/DealIQConditionTriggerHandler.cls
public class DealIQConditionTriggerHandler extends TriggerHandler{
    public override void afterInsert() {
      
       insertRequiredDocuments();
       
    }
    
    public override void afterUpdate() {
      
       deleteRequiredDocuments();
       
    }
    
    private void insertRequiredDocuments(){
        List<Required_Document__c> reqDocList = new List<Required_Document__c>();
        Set<id> dealGlobalSet = new Set<id>();
        Map<id,Global_DealIQ_Condition__c> dealGlobalMap = new Map<id,Global_DealIQ_Condition__c>();
        
        for(acfDealIQ_Condition__c dealCond:(List<acfDealIQ_Condition__c>)trigger.new){
            dealGlobalSet.add(dealCond.acfGlobal_DealIQ_Rule__c);
        }
        
        List<Global_DealIQ_Condition__c> acfGlobalList = [Select id,Name,Document_Master__c FROM Global_DealIQ_Condition__c where id=:dealGlobalSet];
        Map<id,Document_Master__c> docMasterMap = new Map<id,Document_Master__c>([Select id,Name,acf_Source__c FROM Document_Master__c LIMIT 50000]);
        
        for(Global_DealIQ_Condition__c deal:acfGlobalList){
            dealGlobalMap.put(deal.id,deal);
        }
        
        for(acfDealIQ_Condition__c dealCond:(List<acfDealIQ_Condition__c>)trigger.new){
            system.debug('hiiii');
            Required_Document__c reqDoc = new Required_Document__c();
            if(dealGlobalMap != null && dealGlobalMap.containsKey(dealCond.acfGlobal_DealIQ_Rule__c) && dealCond.acfOpportunity__c != null){
                system.debug('@@@'+dealGlobalMap);
                string docMasterId = dealGlobalMap.get(dealCond.acfGlobal_DealIQ_Rule__c).Document_Master__c;
                reqDoc.acfDocument_Master__c = docMasterId;
                reqDoc.acfOpportunity__c = dealCond.acfOpportunity__c;
                reqDoc.DealIQCondition__c = dealCond.id;
                if(docMasterMap != null && docMasterId != null)
                    reqDoc.Name = docMasterMap.get(docMasterId).Name + '- Condition';
                if(docMasterMap.get(docMasterId).acf_Source__c == 'Jumio'){
                    reqDoc.acf_Is_Identity_Verification_Doc__c = true;
                }
                else if(docMasterMap.get(docMasterId).acf_Source__c == 'Bank Statement'){
                    reqDoc.acf_Bank_Statement_Doc__c = true;
                }
                else if(docMasterMap.get(docMasterId).acf_Source__c == 'Downloadable'){
                    reqDoc.Is_Download_Doc__c = true;
                }
                else if(docMasterMap.get(docMasterId).acf_Source__c == 'E-Consent'){
                    reqDoc.Click_Is_E_consent__c = true;
                }
                else if(docMasterMap.get(docMasterId).acf_Source__c == 'Note'){
                    reqDoc.Click_Is_Note_Type__c = true;
                }
            }
            reqDocList.add(reqDoc);
        }
        if(reqDocList!=null && reqDocList.size() > 0){
            insert reqDocList;
        }
       
    }
    
    private void deleteRequiredDocuments(){
        List<Required_Document__c> reqDocList = new List<Required_Document__c>();
        Set<id> dealGlobalSet = new Set<id>();
        Map<id,Required_Document__c> reqDealMap = new Map<id,Required_Document__c>();
        List<Required_Document__c> deleteReqList = new List<Required_Document__c>();
        
        String STATUS = 'acfStatus__c';
        for(acfDealIQ_Condition__c dealCond:(List<acfDealIQ_Condition__c>)trigger.new){
            dealGlobalSet.add(dealCond.id);
        }
        
        reqDocList = [Select id,DealIQCondition__c FROM Required_Document__c where DealIQCondition__c=:dealGlobalSet];
        for(Required_Document__c req:reqDocList){
            reqDealMap.put(req.DealIQCondition__c,req);
        }
        
        for(acfDealIQ_Condition__c dealCond:(List<acfDealIQ_Condition__c>)trigger.new){
            
            if(dealCond.acfStatus__c != null && dealCond.acfStatus__c != trigger.oldMap.get(dealCond.id).get(STATUS) && dealCond.acfStatus__c == 'System Mitigated'){
                if(reqDealMap!= null && reqDealMap.containsKey(dealCond.id)){
                    deleteReqList.add(reqDealMap.get(dealCond.id));
                }  
            }
        } 
        if(deleteReqList != null && deleteReqList.size()  > 0){
            delete deleteReqList;
        } 
    }
}