src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E_Consent__c.object
<CustomObject>
    <label>E-Consent</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>E-Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E-Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>ClickEstablishment_Fee__c</fullName>
        <label>Establishment Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClickMonthly_Fees__c</fullName>
        <label>Monthly Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClickMortgage_Risk_Fee__c</fullName>
        <label>Mortgage Risk Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClickTitle_Protection_Fee__c</fullName>
        <label>Title Protection Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>ClickTotal_Upfront_Fee__c</fullName>
        <label>Total Upfront Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfComparison_Rate__c</fullName>
        <description>Click Loans</description>
        <label>Comparison Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLegal_Fees__c</fullName>
        <description>Click Loans</description>
        <label>Legal Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOngoing_Fees__c</fullName>
        <description>Click Loans</description>
        <label>Ongoing Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfValuation_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Valuation Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>acfApplication_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Application Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfComparison_Rate__c</fullName>
        <description>Click Loans</description>
        <label>Comparison Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfLegal_Fees__c</fullName>
        <description>Click Loans</description>
        <label>Legal Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOngoing_Fees__c</fullName>
        <description>Click Loans</description>
        <label>Ongoing Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfRate__c</fullName>
        <description>Click Loans</description>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfValuation_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Valuation Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>clickEstablishment_Fee__c</fullName>
        <label>Establishment Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>clickMonthly_Fees__c</fullName>
        <label>Monthly Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>clickMortgage_Risk_Fee__c</fullName>
        <label>Mortgage Risk Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>clickTitle_Protection_Fee__c</fullName>
        <label>Title Protection Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>clickTotal_Upfront_Fee__c</fullName>
        <label>Total Upfront Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>acfApplication_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Application Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLegal_Fees__c</fullName>
        <description>Click Loans</description>
        <label>Legal Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOngoing_Fees__c</fullName>
        <description>Click Loans</description>
        <label>Ongoing Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfValuation_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Valuation Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfvarTenure_In_Years__c</fullName>
        <description>Click Loans</description>
        <label>Tenure (In Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Product_Document__c.object
<CustomObject>
    <fields>
        <fullName>Click_Loans_Document_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipLabel>DepedentDocumentOnProduct</relationshipLabel>
        <relationshipName>DepedentDocumentOnProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>DepedentDocumentOnProduct</relationshipLabel>
        <relationshipName>DepedentDocumentOnProduct</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DepedentDocumentOnProducts</label>
    <nameField>
        <label>Product-Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DepedentDocumentOnProduct</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/acfTriggerOnOpportunityLineItemTracker.cls
@isTest
public class acfTriggerOnOpportunityLineItemTracker
{
        
        
    private static User objUser;
    private static Contact objContact;
    private static Account objAccount;
    private static Opportunity objOpportunity1;
    private static Product2 objPro;
    private static PriceBookEntry pbEntry;
    private static OpportunityLineItem oppLine;
    private static Document_Master__c objDocMas;
    private static Required_Document__c objReqDoc;
    private static OpportunityLineItem oli2;
    private static Click_Applicant__c oppClick;
    private static E_Consent__c eobj;
    
static testMethod void validate()
{

        LoadData();
        Product_Document__c objProDocument = new Product_Document__c ();
        objProDocument.Product__c= objPro.id;
        objProDocument.Click_Loans_Document_Master__c = objDocMas.id;
        insert objProDocument;
        
        oppLine.acfApplication_Fee__c = 1;
        oppLine.acfValuation_Fee__c= 1;
        oppLine.acfLegal_Fees__c= 1;
        oppLine.acfOngoing_Fees__c= 1;
        oppLine.acfRate__c= 1;
        oppLine.clickMonthly_Fees__c= 1;
        oppLine.clickEstablishment_Fee__c= 1;
        oppLine.clickMortgage_Risk_Fee__c= 1;
        oppLine.clickTitle_Protection_Fee__c= 1;
        oppLine.acfComparison_Rate__c = 1;
        oppLine.clickTotal_Upfront_Fee__c = 12;
        update oppLine;
        test.starttest();
        Delete oppline;
        test.stoptest();
} 
 
    private static void LoadData()
    {
            ACFSwitch__c acfswitch = new ACFSwitch__c();
        acfswitch.Opportunity_Line_Item_Switch__c = true;    
        insert acfswitch;
        createAccount();
        createContact();
        createUser();
        createOpportunity();
        createProduct();
        createPriceBookEntry();
        createOpportunityLineItem();
        createDocumentMaster();
        createRequiredDocument();
        createClickApplicant();
    }
    
    static void createAccount()
    {
        objAccount = new Account();
        objAccount.acfApproximately_how_much_is_your_house__pc = 10000000;
        objAccount.acfAsset_House_Worth__c = 765;
        objAccount = WLCommonTrackerClass.createAccount(objAccount);
        system.debug('###'+objAccount);
    }
    
    static void createContact()
    {
        objContact = new Contact();
        objContact = WLCommonTrackerClass.createContact(objContact,objAccount);
    }
    
    static void createuser()
    {
        objUser = new User();
        objuser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);
    }
    
     static void createProduct()
    {
        objPro = new Product2();
        objPro.acfvarTenure_In_Years__c = 1;
        objPro = WLCommonTrackerClass.createProduct(objPro);
    }
    
     static void createPriceBookEntry()
    {
        pbEntry = new PriceBookEntry();
        pbEntry.UnitPrice = 300;
        pbEntry.PriceBook2Id = Test.getStandardPricebookId();
        pbEntry.Product2Id = objPro.Id;
        pbEntry.IsActive = true;
        insert pbEntry ; 
    }

     static void createOpportunity()
    {
      objOpportunity1 = new Opportunity();
      objOpportunity1.accountid=  objAccount.Id;
      objOpportunity1 = WLCommonTrackerClass.createOpportunity(objOpportunity1,objUser);
      objOpportunity1.name = 'test23';
      update objOpportunity1;
   
    }
    
     static void createOpportunityLineItem()
    {
        oppLine = new OpportunityLineItem();
        oppLine.pricebookentryid=pbEntry.Id;
        oppLine.TotalPrice=2000;
        oppLine.Quantity = 2;
        oppLine.OpportunityID = objOpportunity1.Id;
        oppLine.lender__c = 'ANZ';
        insert oppLine;
    }
    static void createClickApplicant(){
        oppClick = new Click_Applicant__c();
        oppClick = WLCommonTrackerClass.createApplicant(oppClick,objAccount,objOpportunity1);
    }
    static void createEConsent(){
        eObj = new E_Consent__c();
        eObj = WLCommonTrackerClass.createEconsent(oppClick);
    }
    
      static void createDocumentMaster()
    {
        objDocMas = new Document_Master__c();
        objDocMas = WLCommonTrackerClass.createDocumentMaster(objDocMas);
    }
    
      static void createRequiredDocument()
    {
        objReqDoc = new Required_Document__c();
        objReqDoc= WLCommonTrackerClass.createRequiredDocument(objReqDoc,objDocMas,objOpportunity1);
    }
    
}