src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>QueuedAsyncRequestSwitch__c</fullName>
        <defaultValue>true</defaultValue>
        <description>for turn on or off the TriggerOnAsyncRequest in case of infinity loop</description>
        <label>[Trigger Switch] Async Request</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/AsyncRequest__c.object
<CustomObject>
    <description>This object is for recording Asynchronous calls, which can use with batch to serialise process.</description>
    <fields>
        <fullName>ErrorMessage__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Error Recovery</description>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNREQ{YYYY}-{MM}-{DD}--{0}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MercurySettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecoverSyncFailure__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this switch will enable MercurySyncRecoveryScheduler to run hourly, every time restart MercurySyncRecoveryScheduler should run: System.schedule(&apos;Mercury Recovery&apos;, &apos;0 0 * * * ?&apos;, new MercurySyncRecoveryScheduler() );</description>
        <inlineHelpText>enable MercurySyncRecoveryScheduler to run hourly</inlineHelpText>
        <label>Recover Sync Failure</label>
        <type>Checkbox</type>
    </fields>
    <label>Mercury Settings</label>
</CustomObject>

Lendi/src/classes/MercurySyncRecoveryScheduler.cls
public with sharing class MercurySyncRecoveryScheduler implements Schedulable {

	//only recover 401, 5+, 503
	public void execute(SchedulableContext ctx) {
		if(!MercurySettings__c.getOrgDefaults().RecoverSyncFailure__c) return;
		AsyncRequestSelector ars = new AsyncRequestSelector();
		List<AsyncRequest__c> reqs = ars.getFailedRequests('' + AsyncRequestType.SF_TO_MERCURY);
		reqs.addAll(ars.getFailedRequests('' + AsyncRequestType.MERCURY_TO_SF));

		List<AsyncRequest__c> recoverList = new List<AsyncRequest__c>();
		for(AsyncRequest__c r : reqs){
			if(r.ErrorMessage__c.contains('StatusCode=401') || r.ErrorMessage__c.contains('StatusCode=503') || r.ErrorMessage__c.contains('Invalid integer: 5+')) {
				r.Failed__c = false;
				recoverList.add(r);
			}
		}
		System.debug(LoggingLevel.INFO, '[MercurySyncRecoveryScheduler] Recover List ' + recoverList);
		update recoverList;

		if(!ACFSwitch__c.getOrgDefaults().QueuedAsyncRequestSwitch__c) return;
		AsyncApexJobSelector aajs = new AsyncApexJobSelector();
		if(recoverList.size() != 0 && aajs.getInCompleteJobs().size() == 0) {
			System.debug(LoggingLevel.INFO, '[MercurySyncRecoveryScheduler] Execute Async Request...');
			Database.executeBatch(new MercuryRequestBatch(0), 1);
		}
	}

}