src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Asset_And_Liability_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Asset_And_Liability_Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/Asset_And_Liability__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset And Liabilities</relationshipLabel>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Account__r.PersonContact.acfWhat_is_your_postcode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postcode__c</fullName>
        <label>Postcode</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Type__c</fullName>
        <label>Street Type</label>
        <picklist>
            <picklistValues>
                <fullName>Street</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Road</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Court</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alley</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Arcade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Avenue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Boulevard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bypass</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circuit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Close</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Corner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crescent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cul-de-sac</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Drive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Esplanade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Green</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Grove</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Highway</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Junction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Link</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mews</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parade</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Place</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Square</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Terrace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Avm_Property__c.object
<CustomObject>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Property Avm</relationshipLabel>
        <relationshipName>Property_Avm</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Expiry_date__c</fullName>
        <formula>VALUE($Label.Expiry_Time) + LastModifiedDate</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expiry date:</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>propertyId__c</fullName>
        <externalId>true</externalId>
        <label>propertyId</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Avm Property</label>
    <nameField>
        <displayFormat>PN--{0000}</displayFormat>
        <label>Property Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Avm Property</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/CoreLogic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AvmEndpoint__c</fullName>
        <label>AvmEndpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientID__c</fullName>
        <label>ClientID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>ClientSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SearchApiEndPoint__c</fullName>
        <label>SearchApiEndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenEndPoint__c</fullName>
        <label>TokenEndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CoreLogic</label>
</CustomObject>

src/objects/Financials_Source__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM User Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner User Input</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financials Source</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/clsCoreLogicServicesHelperTracker.cls
@istest
public class clsCoreLogicServicesHelperTracker
{
    private static Account objAccount;
    private static Asset_And_Liability__c objasset;
    private  static Lead objLead;

        static testMethod void validate()
        {   
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorsVeda()); 
            LoadData();
            test.starttest();
            Avm_Property__c objavm=new Avm_Property__c();
            objavm.propertyId__c=99999;
            //insert objavm;

            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;
            
            clsCoreLogicServicesHelper.avmFaresDetail ob=new clsCoreLogicServicesHelper.avmFaresDetail();
            ob.faresReferenceID='test';
            

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Account__c=objAccount.id;
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            //objasset.Address__c='test';
            update objasset;
            test.stoptest();
        }

        static testMethod void validate1()
        {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorsVeda());
            LoadData();

            test.starttest();
            Avm_Property__c objavm=new Avm_Property__c();
            objavm.propertyId__c=99999;
            //objavm.Expiry_date__c=System.today()-1;
            // insert objavm;

            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            //objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            update objasset;

            Financials_Source__c objfin=new Financials_Source__c();
            objfin.Asset_And_Liability__c=objasset.id;
            objfin.Source__c='RPData';
            //objfin.Amount__c=1000;
            insert objfin;
            test.stoptest();
        }
         
        
        static testMethod void validate1a()
        {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorsVeda());
            LoadData();

            
            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            update objasset;

            Financials_Source__c objfin=new Financials_Source__c();
            objfin.Asset_And_Liability__c=objasset.id;
            objfin.Source__c='RPData';
            //objfin.Amount__c=1000;
            insert objfin;
            List<Asset_And_Liability__c> lstAssetandLiability = new List<Asset_And_Liability__c>();
            lstAssetandLiability.add(objasset);
            test.starttest();
            clsCoreLogicServicesHelper.CreateRpdata(lstAssetandLiability);
            test.stoptest();
        }

        static testMethod void validate3()
        {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorsVeda());
            LoadData();
            test.starttest();
            Avm_Property__c objavm=new Avm_Property__c();
            objavm.propertyId__c=99999;
            insert objavm;
            
            Avm_Property__c objavms=new Avm_Property__c();
            objavms.propertyId__c=99999;
            insert objavms;

            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            //objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            update objasset;

            Financials_Source__c objfin=new Financials_Source__c();
            objfin.Asset_And_Liability__c=objasset.id;
            objfin.Source__c='RPData';
            objfin.Amount__c=1000;
            // insert objfin;
            test.stoptest();
        }
        
        static testMethod void validate3a()
        {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorsVedas());
            LoadData();
            
            Avm_Property__c objavm=new Avm_Property__c();
            objavm.propertyId__c=99999;
            insert objavm;

            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            //objasset.Street_Number__c='test';
            //.Street_Name__c='test';
            //objasset.Street_Type__c='test';
            //objasset.City__c='test';
            //objasset.State__c='test';
            //objasset.Postcode__c=77;
            //objasset.Country__c='test';
            update objasset;   

            Financials_Source__c objfin=new Financials_Source__c();
            objfin.Asset_And_Liability__c=objasset.id;
            objfin.Source__c='RPData';
            objfin.Amount__c=1000;
            // insert objfin;
            List<Asset_And_Liability__c> lstAssetandLiability = new List<Asset_And_Liability__c>();
            lstAssetandLiability.add(objasset);
            test.starttest();
            clsCoreLogicServicesHelper.CreateRpdata(lstAssetandLiability);
            test.stoptest();
        }
        
        static testMethod void validate3b()
        {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorsVedas());
            LoadData();
            
            Avm_Property__c objavm=new Avm_Property__c();
            objavm.propertyId__c=99999;
            insert objavm;

            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            update objasset;   

            Financials_Source__c objfin=new Financials_Source__c();
            objfin.Asset_And_Liability__c=objasset.id;
            objfin.Source__c='RPData';
            objfin.Amount__c=1000;
            // insert objfin;
            List<Asset_And_Liability__c> lstAssetandLiability = new List<Asset_And_Liability__c>();
            lstAssetandLiability.add(objasset);
            test.starttest();
            clsCoreLogicServicesHelper.CreateRpdata(lstAssetandLiability);
            test.stoptest();
        }

        // addred bu prateek for status code 100 
        static testMethod void validate5()
        {
            Test.setMock(HttpCalloutMock.class, new MockHttpResponsForProIdforcode());
            LoadData();
            test.starttest();
            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            //objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            update objasset;
            test.stoptest();
        }

        static testMethod void validate6()
        {
           

            test.starttest();
             Test.setMock(HttpCalloutMock.class, new MockHttpResponsForProIdforcode());
            LoadData();
            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objAccount.acfPostal_Code__pc= null;
            update objAccount; 

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            update objasset;
            test.stoptest();
        }


        static testMethod void validate7()
        {
           
            test.starttest();
             Test.setMock(HttpCalloutMock.class, new MockHttpResponsForProIdnull());
            LoadData();
            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objAccount.acfPostal_Code__pc= null;
            update objAccount; 

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            update objasset;
            test.stoptest();
        }
        
        static testMethod void validate8()
        {
          
            
            test.starttest();
            
              Test.setMock(HttpCalloutMock.class, new MockHttpResponsForProIdnull());
            LoadData();
             Avm_Property__c objavm=new Avm_Property__c();
            // objavm.LastModifiedDate=date.valueof(System.today()-400);
            
            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;

            objAccount.acfPostal_Code__pc= null;
            update objAccount; 

            objasset.recordtypeid=SObjectType.Asset_And_Liability__c.getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();
            objasset.Street_Number__c='test';
            objasset.Street_Name__c='test';
            objasset.Street_Type__c='test';
            objasset.City__c='test';
            objasset.State__c='test';
            objasset.Postcode__c=77;
            objasset.Country__c='test';
            update objasset;
            test.stoptest();
        }
        
        private static void LoadData()
        {
            ACFSwitch__c acfswitch = new ACFSwitch__c();
            acfswitch.Asset_And_Liability_Switch__c= true;
            insert acfswitch;
            createLead();
            createAccount();
            createAssetandLiablility();
        }
        
        static void createLead()
        {
            objLead=new Lead();
            objLead=WLCommonTrackerClass.createLead(objLead);
        }
        
        static void createAccount()
        {
            objAccount = new Account();
            objAccount = WLCommonTrackerClass.CreatePersonAccount('test','test','123456','test@gmail.com',objLead.id);
            objAccount.acfPostal_Code__pc=null;
            update objAccount; 
        }
        static void createAssetandLiablility()
        {
            objasset=new Asset_And_Liability__c ();
            objasset=WLCommonTrackerClass.createAssetandLiablility(objasset,objAccount);
        }
        
        public class MockHttpResponseGeneratorsVedas implements HttpCalloutMock
        {
            public HTTPResponse respond(HTTPRequest req)
            {
                // Create a fake response
                HttpResponse res = new HttpResponse();
                // res.setHeader('Content-Type', 'text/x');
                //res.setBody('{"avmFaresDetail":{"faresCode":"0","faresCondition":"SUCCESS","faresDescription":"SUCCESS","faresFSDScore":"11","faresReferenceID":"VIC:1469096069036-1529423","faresRunDate":"2016-07-21T20:14:29.469+10:00","faresScore":"81","faresValuationDate":"2016-07-21T20:14:29.469+10:00","faresValueEstimate":"670937","faresValueHigh":"746893","faresValueLow":"594981","otmProperties":[9220514,9210721,9213533,9220100,9220914,9213758],"soldProperties":[9220514,9221337,9220386,9221887,9220527,9213765]},"propertyId":null,"systemInfo":{"instanceName":"71:8080","requestDate":"2016-07-21T20:14:29.017+10:00"}}');
                res.setBody('{}');
                res.setStatusCode(200);
                return res;
            }
        }
 }