src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Asset_And_Liability_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Asset_And_Liability_Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/Asset_And_Liability__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset And Liabilities</relationshipLabel>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clearing_From_This_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clearing From This Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Purpose__c</fullName>
        <label>Primary Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repayment_Frequency__c</fullName>
        <label>Repayment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anually</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repayments__c</fullName>
        <label>Repayments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Be_Purchased__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Be Purchased</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Asset</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Used_as_Security__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Used as Security</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acfWhat_is_your_postcode__c</fullName>
        <description>Click Loans</description>
        <label>What is the address?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CoreLogic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AvmEndpoint__c</fullName>
        <label>AvmEndpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientID__c</fullName>
        <label>ClientID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>ClientSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SearchApiEndPoint__c</fullName>
        <label>SearchApiEndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenEndPoint__c</fullName>
        <label>TokenEndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CoreLogic</label>
</CustomObject>

src/objects/Financials_Source__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financials Source</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Position__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Funding Positions</relationshipLabel>
        <relationshipName>Funding_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Funding Positions</relationshipLabel>
        <relationshipName>Funding_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Position</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Funding Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Position_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Funding Position Details</relationshipLabel>
        <relationshipName>Funding_Position_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Detail_Type__c</fullName>
        <label>Detail Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home Loan to Repay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Debts to Repay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Accrued Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Stamp Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge Costs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Price</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Funding_Position__c</fullName>
        <label>Funding Position</label>
        <referenceTo>Funding_Position__c</referenceTo>
        <relationshipLabel>Funding Position Details</relationshipLabel>
        <relationshipName>Funding_Position_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Position Detail</label>
    <nameField>
        <label>Funding Position Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Position Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfWhat_is_your_postcode__c</fullName>
        <description>Click Loans</description>
        <label>What is your postcode?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_partner_account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.BillingState</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfLegal_Fees__c</fullName>
        <description>Click Loans</description>
        <label>Legal Fees</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>acfLegal_Fees__c</fullName>
        <description>Click Loans</description>
        <label>Legal Fees</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

src/classes/AssetAndLiabilityTriggerHandlerTracker.cls
@isTest
private class AssetAndLiabilityTriggerHandlerTracker
{

                private static click_Bank_Statement_Data__c objBankStmtData;
                private static click_Bank_Statements_Sub_Category__c objBankStmtSubCat;
                private static Asset_And_Liability__c objAssetLiab;
                private static Asset_And_Liability__c objAssetLiabs;
                private static Account objAccount;
                private static Account objAccount1;
                private static Funding_Position__c objFundingpos;
                private static Opportunity objOpportunity;
                private static Funding_Position_Detail__c objFundingPosDetail;
                private static Financials_Source__c objFinanceSource;
                private static User objUser;
                private static State__c objState;
                private static Lead objLead;
                private static Product2 objPro;
                private static OpportunityLineItem oppLine;
                private static PricebookEntry pbEntry ;
                private static Pricebook2 objPricebook;
                private static acfTask_Master__c objTaskMaster;
                private static Opportunity objOpp;
                private static Id contactId;
                private static contact objContact;
                static List<Funding_Position__c> lstFpos=new List<Funding_Position__c>();
        
        static testMethod void validate()
        
        {
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                      
            
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Liabilities Mortgage Loan';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.Repayment_Frequency__c='Weekly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
                   Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
               fundingobj.name='test';
               fundingobj.Detail_Type__c='Potential Accrued Interest';
               fundingobj.Asset_And_Liability__c=objAssetLiab.id;
               fundingobj.Amount__c=67;
               fundingobj.Funding_Position__c=objFundingpos.id;
               insert fundingobj;
                
                
              Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
              mapobj.put(objAssetLiab.Account__c ,objFundingpos);
                
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
   // obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
    // obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
     
                
                  
                
                 
        }
           static testMethod void validate7()
        
        {
               
                
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                
               Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
               fundingobj.name='test';
               fundingobj.Detail_Type__c='Potential Accrued Interest';
               fundingobj.Funding_Position__c=objFundingpos.id;
               insert fundingobj;
                
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Asset Real Estate';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.State__c='NSW';
                objAssetLiab.To_Be_Purchased__c=false;
                objAssetLiab.Repayment_Frequency__c='Weekly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
              Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
              mapobj1.put(objAssetLiab.Account__c ,objFundingpos);
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
    // obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
    // obj.insertFPAssetEstateRecords(objAssetLiab,mapobj1);
     
                
                  
                
                 
        }
         static testMethod void validate9()
        
        {
                
                
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                
               Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
               fundingobj.name='test';
               fundingobj.Detail_Type__c='Potential Accrued Interest';
               fundingobj.Funding_Position__c=objFundingpos.id;
               fundingobj.Detail_Type__c='Transfer Fee';
               insert fundingobj;
                
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Asset Real Estate';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c =null;
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.State__c='NSW';
                objAssetLiab.To_Be_Purchased__c=false;
                objAssetLiab.Repayment_Frequency__c='Weekly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
              Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
              mapobj1.put(objAssetLiab.Account__c ,objFundingpos);
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
    // obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
    // obj.insertFPAssetEstateRecords(objAssetLiab,mapobj1);
     
                
                  
                
                 
        }
         static testMethod void validate88()
        
        {
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=false;
                objAssetLiab.name='Liability Mortgage Loan';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
               
                insert objAssetLiab;
       
     
     
                
                  
                
                 
        }
         
        static testMethod void validate1()
        
        {
               
                
                LoadData();
                
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Repayments__c=33;
                objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);
                objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.name='Liabilities Mortgage Loan';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.Repayments__c=37;
                objAssetLiab.Current_Balance__c=987;
                 
                  
               objFundingpos=new Funding_Position__c ();
               objFundingpos.Account__c=objAccount.id;
               objFundingPos.Opportunity__c = objOpportunity.id;
               insert objFundingpos; 
      
               Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
               fundingobj.name='test';
               fundingobj.Detail_Type__c='Potential Accrued Interest';
               fundingobj.Funding_Position__c=objFundingpos.id;
               insert fundingobj; 
               
            
              
               update objAssetLiab;
     
                
        }
        
         static testMethod void validate2()
        
        {
              
                LoadData();
                
                 objAssetLiab=new Asset_And_Liability__c();
                 objAssetLiab.Clearing_From_This_Loan__c=false;
                 objAssetLiab.name='Liability';
                 objAssetLiab.Opportunity__c=objOpportunity.id;
                 objAssetLiab.Repayment_Frequency__c='Weekly';
                 objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
                 objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);
       
     
     
      
      
                 objFundingpos=new Funding_Position__c ();
                 objFundingpos.Account__c=objAccount.id;
                 objFundingPos.Opportunity__c = objOpportunity.id;
                 insert objFundingpos; 
                 
        }
        
          static testMethod void validate21()
        
        {
               
                LoadData();
                
                 objAssetLiab=new Asset_And_Liability__c();
                 objAssetLiab.Clearing_From_This_Loan__c=false;
                 objAssetLiab.name='Liability';
                 objAssetLiab.Opportunity__c=objOpportunity.id;
                 objAssetLiab.Repayment_Frequency__c='Monthly';
                   objAssetLiab.Current_Balance__c=99;
                   objAssetLiab.Limit__c=88;
                 objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
                 objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);
       
     
     
      
      
                 objFundingpos=new Funding_Position__c ();
                 objFundingpos.Account__c=objAccount.id;
                 objFundingPos.Opportunity__c = objOpportunity.id;
                 insert objFundingpos; 
                 
        }
        
         static testMethod void validate25()
        
        {
                LoadData();
                
                 objAssetLiab=new Asset_And_Liability__c();
                 objAssetLiab.Clearing_From_This_Loan__c=false;
                 objAssetLiab.name='Liability';
                 objAssetLiab.Opportunity__c=objOpportunity.id;
                 objAssetLiab.Repayment_Frequency__c='Anually';
                 objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
                 objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);
       
     
     
      
      
                 objFundingpos=new Funding_Position__c ();
                 objFundingpos.Account__c=objAccount.id;
                 objFundingPos.Opportunity__c = objOpportunity.id;
                 insert objFundingpos; 
                 
        }
        
         static testMethod void validate22()
        
        {
              
                
                LoadData();
                
                 objAssetLiab=new Asset_And_Liability__c();
                 objAssetLiab.Clearing_From_This_Loan__c=false;
                 objAssetLiab.name='Liability';
                 objAssetLiab.Opportunity__c=objOpportunity.id;
                 objAssetLiab.Repayment_Frequency__c='Fortnightly';
                 objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
                 objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);
       
     
     
      
      
                 objFundingpos=new Funding_Position__c ();
                 objFundingpos.Account__c=objAccount.id;
                 objFundingPos.Opportunity__c = objOpportunity.id;
                 insert objFundingpos; 
                 
        }
        
         static testMethod void validate10()
        
        {
               
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                
               Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
               fundingobj.name='test';
               fundingobj.Detail_Type__c='Potential Accrued Interest';
               fundingobj.Funding_Position__c=objFundingpos.id;
               insert fundingobj;
                
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Asset Real Estate';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.State__c='NSW';
                objAssetLiab.To_Be_Purchased__c=false;
                objAssetLiab.Repayment_Frequency__c='Weekly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
              Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
              mapobj1.put(objAssetLiab.Account__c ,objFundingpos);
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
    // obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
    // obj.insertAssetEstateSingleRecords(objAssetLiab,mapobj1,66);
     
                
                  
                
                 
        }
        
           static testMethod void validate45()
        
        {
            
                
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Liabilities Mortgage Loan';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.Repayment_Frequency__c='Monthly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
              Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
              mapobj.put(objAssetLiab.Account__c ,objFundingpos);
                
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
   // obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
    // obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
     
                
                  
                
                 
        }
        
        static testMethod void validate46()
        
        {
                
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Liabilities Mortgage Loan';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.Repayment_Frequency__c='Anually';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
              Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
              mapobj.put(objAssetLiab.Account__c ,objFundingpos);
                
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
   //  obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
  //   obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
     
                
                  
                
                 
        }
        
        static testMethod void validate47()
        
        {
               
                LoadData();
              
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Liabilities Mortgage Loan';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.Repayment_Frequency__c='Fortnightly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
                
                  
                 
                
              Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
              mapobj.put(objAssetLiab.Account__c ,objFundingpos);
                
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
    // obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
   //  obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
     
                
                  
                
                 
        }
        
        static testMethod void validate90()
        
        {
             
                
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                      
            
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Liability';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                //objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.Repayment_Frequency__c='Weekly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
                   Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
               fundingobj.name='test';
               fundingobj.Detail_Type__c='Potential Accrued Interest';
               fundingobj.Asset_And_Liability__c=objAssetLiab.id;
               fundingobj.Amount__c=67;
               fundingobj.Funding_Position__c=objFundingpos.id;
               insert fundingobj;
                
                
              Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
              mapobj.put(objAssetLiab.Account__c ,objFundingpos);
                
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
   // obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
    // obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
     
                
                  
                
                 
        }
        
        static testMethod void validate91()
        
        {
              
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                      
            
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Liability';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
                objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.To_Be_Purchased__c=true; 
                //objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.Repayment_Frequency__c='Weekly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
                   Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
               fundingobj.name='test';
               fundingobj.Detail_Type__c='Potential Accrued Interest';
               fundingobj.Asset_And_Liability__c=objAssetLiab.id;
               fundingobj.Amount__c=67;
               fundingobj.Funding_Position__c=objFundingpos.id;
               insert fundingobj;
                
                
              Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
              mapobj.put(objAssetLiab.Account__c ,objFundingpos);
                
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
   // obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
    // obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
     
                
                  
                
                 
        }
        
          static testMethod void validate92()
        
        {
              
                LoadData();
                
                objFundingpos=new Funding_Position__c ();
                objFundingpos.Account__c=objAccount.id;
                objFundingPos.Opportunity__c = objOpportunity.id;
                insert objFundingpos; 
                
                      
            
                objAssetLiab=new Asset_And_Liability__c();
                objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.name='Liability';
                objAssetLiab.Opportunity__c=objOpportunity.id;
                objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
                objAssetLiab.Account__c = objAccount.Id;
                objAssetLiab.Account_Name__c = 'Bhasin Test';
                objAssetLiab.Account_Number__c ='ACN123456';
                objAssetLiab.Type__c ='Asset';
                objAssetLiab.Value__c = 100000;
                objAssetLiab.Primary_Purpose__c ='Owner Occupied';
                objAssetLiab.Repayments__c=09876;
               // objAssetLiab.Used_as_Security__c = true;
                objAssetLiab.Current_Balance__c=99;
                objAssetLiab.Limit__c=55;
                objAssetLiab.To_Be_Purchased__c=true; 
                //objAssetLiab.Clearing_From_This_Loan__c=true;
                objAssetLiab.Repayment_Frequency__c='Weekly';
               // objAssetLiab.Current_Balance__c=99;
                insert objAssetLiab;
                   Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
               fundingobj.name='test';
               fundingobj.Detail_Type__c='Potential Accrued Interest';
               fundingobj.Asset_And_Liability__c=objAssetLiab.id;
               fundingobj.Amount__c=67;
               fundingobj.Funding_Position__c=objFundingpos.id;
               insert fundingobj;
                
                
              Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
              mapobj.put(objAssetLiab.Account__c ,objFundingpos);
                
       
     AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
     //obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
    // obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
     
                
                  
                
                 
        }
      static void LoadData()
      {
      
      
                ACFSwitch__c acfswitch = new ACFSwitch__c();
                acfswitch.Asset_And_Liability_Switch__c= true;
                insert acfswitch;
                
      
      
            CoreLogic__c objcore=new CoreLogic__c();
            objcore.name='CoreLogic';
            objcore.UserName__c='test';
            objcore.password__c='AusCred4321';
            objcore.EndPoint__c='https://access-api.corelogic.asia';
            objcore.AvmEndpoint__c='test';
            objcore.ClientID__c='test';
            objcore.ClientSecret__c='test';
            objcore.TokenEndPoint__c='test';
            objcore.SearchApiEndPoint__c='test';
            insert objcore;
      
        objState=new State__c();
          objState.name='test';
          insert objState;
      
           objAccount1=new account();
           objAccount1=WLCommonTrackerClass.createAccount(objAccount1);
          
      
          objLead=new Lead();
          objLead=WLCommonTrackerClass.createLead(objLead);
          objLead.acf_partner_account__c=objAccount1.id;
          objLead.acfWhat_is_your_postcode__c='testinggg';
          update objLead;
          
          
              
        
      
          objAccount=new account();
          objAccount=WLCommonTrackerClass.createAccount(objAccount);
       
      
          objContact=new contact();
          objContact=WLCommonTrackerClass.createContact(objContact,objAccount);
      
          objUser = new User();
          objuser.ContactId = objContact.id;
          objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);
          
          objOpportunity = new Opportunity();
          objOpportunity = WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);
          objOpportunity.acfLegal_Fees__c=88;
          objOpportunity.clickEstablishment_Fee__c=99;
          objOpportunity.clickMortgage_Risk_Fee__c=888;
          update objOpportunity;
          
      
          objPro=new product2();
          objPro=WLCommonTrackerClass.createProduct(objPro);
          
          pbEntry = new PriceBookEntry();
          pbEntry.UnitPrice = 300;
          pbEntry.PriceBook2Id = Test.getStandardPricebookId();
          pbEntry.Product2Id = objPro.Id;
          pbEntry.IsActive = true;
          insert pbEntry ;
              
          oppLine = new OpportunityLineItem();
          oppLine.pricebookentryid=pbEntry.Id;
          oppLine.TotalPrice=2000;
          oppLine.Quantity = 2;
          oppLine.lender__c='test';
          oppLine.OpportunityID = objOpportunity.Id;
          insert oppLine;
      
      
      
     
     
      
      }
      
      }