src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Income_Trigger_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Income Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncomeExpenseTriggerHandlerTracker.cls
@isTest 
public class IncomeExpenseTriggerHandlerTracker{
    
    static testMethod void call() {
     ACFSwitch__c acfswitch = new ACFSwitch__c();
       acfswitch.Income_Trigger_Switch__c= true;    
       insert acfswitch;
     Income_And_Expense__c   obj = new Income_And_Expense__c  ();
     obj.Amount__c = 1000;
     
     Insert   obj ;
     //IncomeExpenseTriggerHandler ieObj = new IncomeExpenseTriggerHandler ();
     //ieObj.afterInsert();
     
     
     
       
    }
}