src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Asset_And_Liability_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Asset_And_Liability_Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/acfVedaApplicantLink__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>click_Applicant__c</referenceTo>
        <relationshipLabel>Veda Applicant Links</relationshipLabel>
        <relationshipName>Veda_Connector</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Veda_Summary__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Veda Summary</label>
        <referenceTo>Veda_Summary__c</referenceTo>
        <relationshipName>Veda_Connector</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Veda Applicant Link</label>
    <nameField>
        <label>Veda Applicant Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Veda Applicant Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset_And_Liability__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset And Liabilities</relationshipLabel>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Address__c</fullName>
        <formula>Account__r.PersonContact.acfWhat_is_your_postcode__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfEmployment_Type__c</fullName>
        <label>Employment Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfLast_2_years_Tax_Return_or_ATO_NOA__c</fullName>
        <label>Last 2 years Tax Return or ATO NOA</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Name__c</fullName>
        <label>Applicant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_How_Long_have_you_been_employed__c</fullName>
        <label>How Long have you been employe</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Dependants__c</fullName>
        <label>Dependants</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Marital_Status__c</fullName>
        <label>Marital Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>click_Applicant_Number__c</fullName>
        <label>Applicant Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>state__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Dependants__c</fullName>
        <description>Click Loans</description>
        <label>Dependants</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Name__c</fullName>
        <description>Click Loans</description>
        <label>Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_How_Long_have_you_been_employed__c</fullName>
        <description>Click Loans</description>
        <label>How Long have you been employed</label>
        <length>144</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Marital_Status__c</fullName>
        <description>Click Loans</description>
        <label>Marital Status</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/CoreLogic__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>AvmEndpoint__c</fullName>
        <label>AvmEndpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientID__c</fullName>
        <label>ClientID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ClientSecret__c</fullName>
        <label>ClientSecret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SearchApiEndPoint__c</fullName>
        <label>SearchApiEndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TokenEndPoint__c</fullName>
        <label>TokenEndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>password__c</fullName>
        <label>password</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>CoreLogic</label>
</CustomObject>

src/objects/Funding_Position_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Funding Position Details</relationshipLabel>
        <relationshipName>Funding_Position_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Funding_Position__c</fullName>
        <label>Funding Position</label>
        <referenceTo>Funding_Position__c</referenceTo>
        <relationshipLabel>Funding Position Details</relationshipLabel>
        <relationshipName>Funding_Position_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Position Detail</label>
    <nameField>
        <label>Funding Position Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Position Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>click_Applicant__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfEmployment_Type__c</fullName>
        <description>Click Loans</description>
        <label>Employment Type</label>
        <picklist>
            <picklistValues>
                <fullName>Full Time - PAYG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfLast_2_years_Tax_Return_or_ATO_NOA__c</fullName>
        <description>Click Loans</description>
        <label>Last 2 years Tax Return or ATO NOA</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_partner_account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <formula>TEXT (Account.PersonContact.Gender__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.BillingState</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Veda_Summary__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>click_Applicant__c</referenceTo>
        <relationshipLabel>Veda Summaries</relationshipLabel>
        <relationshipName>Veda_Summaries</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Veda Summary</label>
    <nameField>
        <displayFormat>N-{0000}</displayFormat>
        <label>Record Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Veda Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Generate_Di_XMLTracker.cls
@isTest
private class Generate_Di_XMLTracker
{
    private static Asset_And_Liability__c objAssetLiab;
    private static Account objAccount;
    private static Account objAccount1;
    private static Funding_Position__c objFundingpos;
    private static Opportunity objOpportunity;
    private static Funding_Position_Detail__c objFundingPosDetail;
    private static User objUser;
    private static State__c objState;
    private static Lead objLead;
    private static Product2 objPro;
    private static OpportunityLineItem oppLine;
    private static PricebookEntry pbEntry ;
    private static Opportunity objOpp;
    private static click_Applicant__c objApplicant;
    private static contact objContact;
    private static Income_And_Expense__c objIncomeandexpense;
    private static List<Funding_Position__c> lstFpos=new List<Funding_Position__c>();
    private static acfVedaApplicantLink__c objVedaApplicantLink;
    private static Veda_Summary__c objVedaSummary;
        
    static testMethod void validate()
    {
        LoadData(); 
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorForDiXML());
        test.starttest();
        Generate_Di_XML.Generate_Di_XML(objOpportunity.Id);
        test.stoptest(); 
    }
    
    static testMethod void validate1()
    {
        LoadData(); 
        objAccount.acfWhat_is_your_current_payment_type__pc = 'Interest Only';
        update objAccount;
        
        objApplicant.acfLast_2_years_Tax_Return_or_ATO_NOA__c = 'Yes, I\'ve got one of these';
        objApplicant.click_Applicant_Number__c = '2';
        objApplicant.ABN__C = 'test';
        objApplicant.Title__c = 'test';
        objApplicant.acf_Applicant_Name__c = 'test';
        objApplicant.gender__c = 'Male';
        objApplicant.acf_applicant_Marital_Status__c = 'Married';
        objApplicant.acf_applicant_Dependants__c= '1';
        objApplicant.Citizen_ship__c = 'Citizen';
        objApplicant.Address__c = '1 test test';
        objApplicant.acfEmployment_Type__c = 'test';
        objApplicant.acf_How_Long_have_you_been_employed__c = string.valueof(System.now());
        objApplicant.Gst_Registered__C = 'test';
        objApplicant.Gst_Months__C = 'May';
        update objApplicant;
        
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorForDiXML());
        test.starttest();
        Generate_Di_XML.Generate_Di_XML(objOpportunity.Id);
        test.stoptest(); 
    }

    static void LoadData()
    {
        ACFSwitch__c acfswitch = new ACFSwitch__c();
        acfswitch.Asset_And_Liability_Switch__c = true;
        insert acfswitch;
        
        CoreLogic__c objcore=new CoreLogic__c();
        objcore.name='CoreLogic';
        objcore.UserName__c='test';
        objcore.password__c='AusCred4321';
        objcore.EndPoint__c='https://access-api.corelogic.asia';
        objcore.AvmEndpoint__c='test';
        objcore.ClientID__c='test';
        objcore.ClientSecret__c='test';
        objcore.TokenEndPoint__c='test';
        objcore.SearchApiEndPoint__c='test';
        insert objcore;

        objState=new State__c();
        objState.name='test';
        insert objState;

        objAccount1=new account();
        objAccount1=WLCommonTrackerClass.createAccount(objAccount1);

        objLead=new Lead();
        objLead.acf_partner_account__c=objAccount1.id;
        objLead.acfWhat_is_your_postcode__c='testinggg';
        objLead=WLCommonTrackerClass.createLead(objLead);

        objAccount=new account();
        objAccount.acfCurrent_Loan_Amount__pc = 200000;
        objAccount.acfApproximately_how_much_is_your_house__pc = 4000000;
        objAccount.acfWhat_is_your_current_payment_type__pc = 'Principal and Interest';
        objAccount=WLCommonTrackerClass.createAccount(objAccount);

        objContact=new contact();
        objContact=WLCommonTrackerClass.createContact(objContact,objAccount);

        objUser = new User();
        objuser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);

        objOpportunity = new Opportunity();
        objOpportunity.acfLegal_Fees__c=88;
        objOpportunity.clickEstablishment_Fee__c=99;
        objOpportunity.clickMortgage_Risk_Fee__c=888;
        objOpportunity = WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);
        
        objApplicant = new click_Applicant__c();
        objApplicant = WLCommonTrackerClass.createApplicant(objApplicant,objAccount,objOpportunity);
        
        objVedaSummary = new Veda_Summary__c();
        objVedaSummary.Applicant__c = objApplicant.id;
        objVedaSummary.ApplicantRecId__c = string.valueof(objApplicant.id);
        objVedaSummary.Error__c = '';
        objVedaSummary.Opportunity__c = objOpportunity.id;
        insert objVedaSummary;
        
        objVedaApplicantLink = new acfVedaApplicantLink__c();
        objVedaApplicantLink.Applicant__c = objApplicant.id;
        objVedaApplicantLink.Record_Creation_date__c = System.now();
        objVedaApplicantLink.Veda_Status__c = 'Active';
        objVedaApplicantLink.Veda_Summary__c = objVedaSummary.Id;
        insert objVedaApplicantLink;
        
        Attachment objAttach = new Attachment();
        objAttach.Body = blob.valueof('test');
        objAttach.parentid = objVedaSummary.id;
        objAttach.Name = 'test';
        insert objAttach;
        
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        objPro=new product2();
        objPro=WLCommonTrackerClass.createProduct(objPro);

        pbEntry = new PriceBookEntry();
        pbEntry.UnitPrice = 300;
        pbEntry.PriceBook2Id = Test.getStandardPricebookId();
        pbEntry.Product2Id = objPro.Id;
        pbEntry.IsActive = true;
        insert pbEntry ;

        oppLine = new OpportunityLineItem();
        oppLine.pricebookentryid=pbEntry.Id;
        oppLine.TotalPrice=2000;
        oppLine.Quantity = 2;
        oppLine.lender__c='test';
        oppLine.OpportunityID = objOpportunity.Id;
        insert oppLine;

    }
}