src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>LeadTriggerSwitch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>On / Off the trigger switch on Lead</description>
        <label>[Trigger Switch] Lead</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AddToCallFileDate__c</fullName>
        <label>Add To Call File Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if the lead is being updated</description>
        <label>Is Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadToCallFileRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadToCallFileRule</label>
        <referenceTo>LeadToCallFileRule__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LeadToCallFileRule__c.object
<CustomObject>
    <description>Store the rules for distributing different call file to the lead</description>
    <fields>
        <fullName>Delay_To_Call_File_Days__c</fullName>
        <label>Delay To Call File Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exclude_Closed_And_Lost__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that status is closed or lost</description>
        <label>Exclude Closed And Lost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Converted_Lead__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that is already converted</description>
        <label>Exclude Converted Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Do_Not_Call__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude all the leads that tagged as do not call</description>
        <label>Exclude Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Do_Not_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that tagged as do not email</description>
        <label>Exclude Do Not Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the current rule is active or not</description>
        <label>Is Active Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Priority to check will rule should be fitted first when assign the call file to the lead</description>
        <label>Priority</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_Object__c</fullName>
        <label>Rule Object</label>
        <picklist>
            <picklistValues>
                <fullName>opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LeadToCallFileRule</label>
    <nameField>
        <label>LeadToCallFileRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LeadToCallFileRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/TestBatchAddCallFileToLead.cls
@isTest
public with sharing class TestBatchAddCallFileToLead {

	private static testMethod void testBatch() {
		LeadToCallFileRule__c rule = createRule();
		insert rule;

		Lead testLead = TestUtilities.createLead();
		testLead.is_Updated__c = false;
		testLead.addToCallFileDate__c = Date.today();
		testLead.LeadToCallFileRule__c = rule.id;
		List<Lead> testLeadRecords = TestUtilities.createLeads(10, testLead);
		System.debug(testLeadRecords);
		ACFSwitch__c swh = ACFSwitch__c.getOrgDefaults();
		swh.LeadTriggerSwitch__c = false;
		upsert swh;
		System.debug(swh);
		insert testLeadRecords;

		Test.startTest();
		BatchAddCallFileToLead b = new BatchAddCallFileToLead();
		Database.executebatch(b, 10);
		Test.stopTest();

		System.debug(testLeadRecords);
	}

	private static LeadToCallFileRule__c createRule() {
		LeadToCallFileRule__c rule = new LeadToCallFileRule__c(name = 'test');
		rule.Delay_To_Call_File_Days__c = 1;
		rule.Exclude_Closed_And_Lost__c = true;
		rule.Exclude_Converted_Lead__c = true;
		rule.Exclude_Do_Not_Call__c = true;
		rule.Exclude_Do_Not_Email__c = true;
		rule.Is_Active_Rule__c = true;
		rule.Priority__c = 0;
		rule.Rule_Object__c = 'Rule_Object__c';
		return rule;
	}

}