src/objects/acfSuggested_Product__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfFilter__c</fullName>
        <description>Click Loans</description>
        <label>Filter</label>
        <picklist>
            <picklistValues>
                <fullName>Include</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Exclude</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfLead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Suggested_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfProduct_Family__c</fullName>
        <description>Click Loans</description>
        <formula>Text(acfProduct__r.Family)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Product Family</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>Suggested_Products</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Suggested Product</label>
    <nameField>
        <displayFormat>Prod-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Suggested Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Click_IsActive__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Click_Network_ID__c</fullName>
        <label>Community Network ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Page_Prefix__c</fullName>
        <label>Page Prefix</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Support_Team_Name__c</fullName>
        <label>Support Team Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_URL__c</fullName>
        <label>Community URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Community_User_Name_Prefix__c</fullName>
        <label>Community User Name Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Loans_Bank__c.object
<CustomObject>
    <fields>
        <fullName>Click_Loans_Bank_Detail__c</fullName>
        <label>Click Loans Bank Detail</label>
        <referenceTo>acfBank_Detail__c</referenceTo>
        <relationshipName>Banks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Community_Setup__c</fullName>
        <label>Community Setup</label>
        <referenceTo>Click_Community_Setup__c</referenceTo>
        <relationshipName>Banks</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>CommunityBankAssociation</label>
    <nameField>
        <label>Bank Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunityBankAssociation</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfIs_Bank_Statement_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Bank Statement Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Identity_Document_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Post_Login_Ques_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Post Login Ques Attempted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfLoan_Amount__c</fullName>
        <description>Click Loans</description>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfWhat_is_your_current_payment_type__c</fullName>
        <description>Click Loans</description>
        <label>What is your current payment type</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LVR_Rate__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>ACF_Comparison_Rate__c</fullName>
        <description>Click Loans</description>
        <label>Comparison Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfApplication_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Application Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLVR__c</fullName>
        <description>Click Loans</description>
        <label>LVR To</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfLoan_Size__c</fullName>
        <description>Click Loans</description>
        <label>Loan Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>LVR_Rate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfRate__c</fullName>
        <description>Click Loans</description>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfTerm_in_Years__c</fullName>
        <description>Click Loans</description>
        <formula>If(acfProduct__r.RecordType.Name == &apos;Fixed&apos;,VALUE(Text(acfProduct__r.acfTenure_in_Years__c)),0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Term(in Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>clickFixed_Interest_Rate__c</fullName>
        <label>Fixed Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>clickLVR_From__c</fullName>
        <label>LVR From</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>clickLoan_Size_From__c</fullName>
        <label>Loan Size From</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Click Loans LVR &amp; Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LVR &amp; Rate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ACF_Comparison_Rate__c</fullName>
        <description>Click Loans</description>
        <label>Comparison_Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfApplication_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Application Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLoan_Size__c</fullName>
        <description>Click Loans</description>
        <label>Loan Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOffset_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Offset Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfTenure_in_Years__c</fullName>
        <description>Click Loans</description>
        <label>Term (in Years)</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfType__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Variable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfvarTenure_In_Years__c</fullName>
        <description>Click Loans</description>
        <label>Tenure (In Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Stage_Name__c</fullName>
        <description>Click Loans</description>
        <label>Stage Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question_Type__c</fullName>
        <description>Click Loans</description>
        <label>Question Type</label>
        <picklist>
            <controllingField>acf_Type__c</controllingField>
            <picklistValues>
                <fullName>Property Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Applicant Details</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assets and Liabilities</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Details</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_no__c</fullName>
        <description>Click Loans</description>
        <label>Sequence no</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Stage_Name__c</fullName>
        <description>Click Loans</description>
        <label>Stage Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WLQuoteDetail.cls
public class WLQuoteDetail 
{
    //------Public Properties--------//
    public string strLoanPurpose {get;set;}
    public decimal decCurrLoanAmt {get;set;}
    public decimal decEstPropVal{get;set;}
    public decimal decBestRate {get;set;}
    public decimal decComparison {get;set;}
    public integer decMonthlyPayment {get;set;}
    public string pge_name {set; get;}
    public static integer intWidth {get;set;}
    //------Constructor---------//
    public WLQuoteDetail()
    {
     string pge = Apexpages.currentPage().getUrl();
     List<String> parts = pge.split('/'); 
     List<String> parts1 = parts[2].split('\\?');
     pge_name = parts1[0].toLowerCase(); 
     strLoanPurpose = '';
     decMonthlyPayment = 0;
     decComparison = 0;
     decBestRate = 0;
     decEstPropVal = 0;
     decCurrLoanAmt = 0;
     map<string,LVR_Rate__c>mapProductIdToLVR = new map<string,LVR_Rate__c>();
     set<string>setProductIdToExclude = new set<string>();
     //Modified by karthik on 08-05-2015
     Id currentLeadId = ClickCommon.getCurrentLoggedInLeadId(userInfo.getuserid());
     system.debug('currentLeadId **********'+currentLeadId);
     if(currentLeadId != null)
     {
        list<lead> lstLead = [select id,acfLoan_Amount__c,RecordType.Name,acfApproximately_how_much_is_your_house__c,acfWhat_is_your_current_payment_type__c from lead where id=:currentLeadId];
       
        if(lstLead != null && lstLead .size()>0)
        { 
            Lead objLead = lstLead[0];
            if(objLead.RecordType.Name != null && objLead.RecordType.Name == 'Click Refi')
            {
                strLoanPurpose = 'Refinance';
            }else if(objLead.RecordType.Name != null && objLead.RecordType.Name == 'Click New Loans')
                  {
                    strLoanPurpose = 'New Loan';
                  }
            if(objLead.acfApproximately_how_much_is_your_house__c != null)
                decEstPropVal = objLead.acfApproximately_how_much_is_your_house__c;
            if(objLead.acfLoan_Amount__c != null)
                decCurrLoanAmt = objLead.acfLoan_Amount__c; 
            
            string paymentType = objLead.acfWhat_is_your_current_payment_type__c;
              
            
            double usrLVR = 0;

            if(objLead.acfLoan_Amount__c != null && objLead.acfApproximately_how_much_is_your_house__c != null)
                  usrLVR = (objLead.acfLoan_Amount__c/objLead.acfApproximately_how_much_is_your_house__c)*100;
            
            if(!Test.isRunningTest()){     
                for(acfSuggested_Product__c objSuggestedProduct:[select id,acfFilter__c,acfProduct__c,acfProduct_Family__c,acfLead__c from acfSuggested_Product__c where acfLead__c=:currentLeadId])
                {
                    if(objSuggestedProduct.acfFilter__c <> null && objSuggestedProduct.acfProduct__c <> null && objSuggestedProduct.acfFilter__c == 'Exclude')
                    {
                        setProductIdToExclude.add(objSuggestedProduct.acfProduct__c);
                    } 
                }
            }
            
            set<id> setOfBankDetailId = new set<id>();
            List<Click_Loans_Bank__c> lstbank = new List<Click_Loans_Bank__c>();
            string CommunityID =  Network.getNetworkId();
            if(CommunityID <> null)
            {
                Click_Community_Setup__c objCommunity = ClickCommon.getCommunitySetup(CommunityID);
                lstbank = [select id,Click_Loans_Bank_Detail__c,Community_Setup__c from Click_Loans_Bank__c where Community_Setup__c =:objCommunity.id];
            }
            if(lstbank.size() > 0 && lstbank != null)
            {
                for(Click_Loans_Bank__c objbank : lstbank)
                {
                        setOfBankDetailId.add(objbank.Click_Loans_Bank_Detail__c);
                }
            }
            list<LVR_Rate__c> lstRequiredLVRs = new list<LVR_Rate__c>();
            if(setOfBankDetailId != null && setOfBankDetailId.size()>0)
            {
                    list<LVR_Rate__c> lstLVRRate = [select id,acfLVR__c,acfRate__c,acfProduct__r.acfType__c,acfProduct__r.Recordtype.Name,acfProduct__c,acfLoan_Size__c,ACF_Comparison_Rate__c,
                                                clickFixed_Interest_Rate__c,clickLoan_Size_From__c,clickLVR_From__c,acfProduct__r.acfTenure_in_Years__c,acfApplication_Fee__c,
                                                acfProduct__r.acfvarTenure_In_Years__c,acfProduct__r.name,acfTerm_in_Years__c,acfProduct__r.acfOffset_Account__c 
                                                from LVR_Rate__c where clickLoan_Size_From__c <: objLead.acfLoan_Amount__c and acfLoan_Size__c >=:objLead.acfLoan_Amount__c and clickLVR_From__c <: usrLVR and 
                                                acfLVR__c>=:usrLVR and acfProduct__r.Recordtype.Name = 'Variable' and acfProduct__r.acfOffset_Account__c = false and acfProduct__c NoT IN:setProductIdToExclude and acfProduct__r.Click_Loans_Bank_Detail__c IN: setOfBankDetailId
                                                order by acfTerm_in_Years__c,acfRate__c,clickFixed_Interest_Rate__c asc];
                    for(LVR_Rate__c objLVR : lstLVRRate)
                    {
                        if(setProductIdToExclude <> null && setProductIdToExclude.size()>0 && setProductIdToExclude.contains(objLVR.acfProduct__c))
                        {
                            continue;
                        } 
                        lstRequiredLVRs.add(objLVR);
                    }
                                       
                    if(lstRequiredLVRs != null && lstRequiredLVRs.size()>0)
                    {
                        decBestRate = lstRequiredLVRs[0].acfRate__c;
                        decComparison = lstRequiredLVRs[0].ACF_Comparison_Rate__c;
                        If(lstRequiredLVRs[0].acfProduct__r.RecordType.Name == 'Variable' && decBestRate != null && lstRequiredLVRs[0].acfProduct__r.acfvarTenure_In_Years__c != null && decCurrLoanAmt!= null && paymentType != null)
                        {
                            decMonthlyPayment = integer.valueof(ClickCommon.calculateMonthlyPayment(decCurrLoanAmt,double.valueof(decBestRate),paymentType,double.valueof(lstRequiredLVRs[0].acfProduct__r.acfvarTenure_In_Years__c)));
                        }else if(lstRequiredLVRs[0].acfProduct__r.RecordType.Name == 'Fixed'  && lstRequiredLVRs[0].acfProduct__r.acfvarTenure_In_Years__c != null && decCurrLoanAmt != null && paymentType!= null)
                        {
                          decBestRate = lstRequiredLVRs[0].clickFixed_Interest_Rate__c;
                          if(decBestRate != null)
                            decMonthlyPayment = integer.valueof(ClickCommon.calculateMonthlyPayment(decCurrLoanAmt,double.valueof(decBestRate),paymentType,double.valueof(lstRequiredLVRs[0].acfProduct__r.acfvarTenure_In_Years__c)));
                        }
                     } 
               }
            }
        }
        
      } 
    
    
    public static void setProgressBarWidth(integer currentQues,integer totQues, string pagename,string strNetworkId)
    {
        system.debug('@@@@QuoteTest'+currentQues+'====='+totQues);
        //intWidth = ((currentQues+1) * 100)/totQues;
        List<Click_Community_Setup__c> lstCommunity = new List<Click_Community_Setup__c>();
        lstCommunity = [select id,name,Click_Page_Prefix__c,Click_Network_ID__c,Click_URL__c,Community_User_Name_Prefix__c,
                        Click_IsActive__c,Click_Support_Team_Name__c from Click_Community_Setup__c where Click_Network_ID__c = : strNetworkId AND Click_IsActive__c =: true limit 1];
        
        string LoggedInLead = ClickCommon.getCurrentLoggedInLeadId(userInfo.getuserId());
        List<Lead> lstLSteps = [select id,acfIs_Post_Login_Ques_Attempted__c, acfIs_Bank_Statement_Submitted__c, acfIs_Identity_Document_Submitted__c from lead where id =: LoggedInLead];
        set<id> setScript = new set<id>();
        for(Script__c objScript : [select id,acf_Sequence_no__c,acf_Type__c,acf_Stage_Name__c,acf_Question_Type__c  from Script__c where acf_Type__c=:'Post-Login' AND Click_Community_Setup__r.Click_Network_ID__c =: strNetworkId order by acf_Sequence_no__c asc])
        {
            setScript.add(objScript.id);
        }
        list<Question__c> lstQuestion = [select id from Question__c where acf_Script__c in: setScript and acf_Active__c = true];
        if(lstLSteps != null && lstLSteps.size()>0 && lstCommunity != null && lstCommunity.size()>0)
        {
            lead objLead = lstLSteps[0];
            if(pagename == lstCommunity[0].Click_Page_Prefix__c+'PostloginQuestionnaires')
            {
                integer totalQues = totQues + 5 + 5;
                
                if(objLead.acfIs_Bank_Statement_Submitted__c == true)
                    currentQues = currentQues + 5;
                    
                if(objLead.acfIs_Identity_Document_Submitted__c == true)
                    currentQues = currentQues + 5;
                    
                intWidth = ((currentQues+1) * 100)/totalQues;
                system.debug('@@@@test1212'+totalQues+'==='+intWidth);
            }
            else If(pagename == lstCommunity[0].Click_Page_Prefix__c+'BankInfoDetails')
            {
                integer totalQues = lstQuestion.size();
                
                currentQues = 5;
                
                if(objLead.acfIs_Post_Login_Ques_Attempted__c == true)
                    currentQues = currentQues + totalQues;
                    
                if(objLead.acfIs_Identity_Document_Submitted__c == true)
                    currentQues = currentQues + 5;
                    
                totalQues = lstQuestion.size() + 10;
                
                intWidth = ((currentQues+1) * 100)/totalQues;
            }
            else
            {            
                integer totalQues = lstQuestion.size();
                
                currentQues = 5;
                
                if(objLead.acfIs_Post_Login_Ques_Attempted__c == true)
                    currentQues = currentQues + totalQues;
                    
                if(objLead.acfIs_Bank_Statement_Submitted__c == true)
                    currentQues = currentQues + 5;
                    
                intWidth = ((currentQues+1) * 100)/totalQues;
            }
       }
    }
}