src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Applicant_Trigger_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applicant Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/Asset_And_Liability__c.object
<CustomObject>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>acfEmployment_Type__c</fullName>
        <label>Employment Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Annual_profit_income__c</fullName>
        <label>Annual profit / income</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_App_1_Monthly_Expenses__c</fullName>
        <label>App 1 Monthly Expenses</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clickApp_1_Monthly_Expenses__c</fullName>
        <label>Monthly Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>click_Applicant_Number__c</fullName>
        <label>Applicant Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials_Source__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Income_And_Expense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Income And Expense</label>
        <referenceTo>Income_And_Expense__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM User Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner User Input</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financials Source</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dividends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Allowance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overtime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basic Living Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Interest Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Time - PAYG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Govt Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability Expenses</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <recordTypes>
        <fullName>Expense</fullName>
        <active>true</active>
        <label>Expense</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApplicantTriggerHandlerTracker.cls
@isTest
private class ApplicantTriggerHandlerTracker{

private static Income_And_Expense__c objIncomeExpense;
private static Account objAccount;
private static Financials_Source__c objFinancialSource;
private static click_Applicant__c objApplicant;
private static Asset_And_Liability__c objAssetLiab;
private static Id recordtypeID;
 static testMethod void createApplicant(){
 
 string strExpenseAPI = system.label.acfExpense_API;
 
      ACFSwitch__c acfswitch = new ACFSwitch__c();
       acfswitch.Applicant_Trigger_Switch__c = true;
       insert acfswitch;
 
 /* Set<String> StrIncomeCategories = new set<string>();
     StrIncomeCategories.add('Full Time - PAYG');
     StrIncomeCategories.add('Basic Living Expense');
     StrIncomeCategories.add('Self Employed');
     */
 objAccount = new Account();
 objAccount = WLCommonTrackerClass.createAccount(objAccount);
 
 objApplicant = new click_Applicant__c();
 objApplicant = WLCommonTrackerClass.createApplicant(objApplicant,objAccount);
 
 objApplicant.click_Applicant_Number__c = 'APP5'; 
 objApplicant.acf_applicant_Annual_profit_income__c = '20000';
 objApplicant.acf_applicant_App_1_Monthly_Expenses__c = '3000';
 objApplicant.clickApp_1_Monthly_Expenses__c = 2400;
 objApplicant.acfEmployment_Type__c = 'Self Employed';
 // objApplicant.createdById = 'Customer Input';
 //objApplicant.lastmodifiedById = 'Customer Input';
 
 update objApplicant;
 
 objApplicant.acfEmployment_Type__c = 'Full Time - PAYG';
 update objApplicant;
 
 objApplicant.acf_applicant_App_1_Monthly_Expenses__c= '4003';
 update objApplicant;
 
 objApplicant.acfEmployment_Type__c = 'Full Time';
 update objApplicant;
 
 objIncomeExpense = new Income_And_Expense__c();
 objIncomeExpense = WLCommonTrackerClass.createIncomeExpense(objIncomeExpense,objApplicant);
 objIncomeExpense.Category__c = 'Full Time - PAYG';
 update objIncomeExpense;
 objIncomeExpense.Category__c = 'Self Employed';
 update objIncomeExpense;
 objIncomeExpense.Category__c = 'Basic Living Expense';
 update objIncomeExpense;
 
  ApplicantTriggerHandler objAppTrigHandler = new ApplicantTriggerHandler();
 // objAppTrigHandler.insertIncomeExpenses();
  
 update objIncomeExpense; 
 objAssetLiab = new Asset_And_Liability__c();
 objAssetLiab = WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);
 
     
 
    List<Financials_Source__c> lstfinancialsource = new List<Financials_Source__c>();
    objFinancialSource = new Financials_Source__c();
    objFinancialSource.Amount__c = 10000;
    objFinancialSource.Income_And_Expense__c = objIncomeExpense.Id;
    objFinancialSource.Source__c = 'Customer Input';
    objFinancialSource.Asset_And_Liability__c = objAssetLiab.Id;
    lstfinancialsource.add(objFinancialSource);
    
    insert lstfinancialsource;
    system.debug(objFinancialSource.id != null);
  
    update objFinancialSource;
    
   // objAppTrigHandler.insertIncomeExpenses();
  //  objAppTrigHandler.updateFinancialSources();
 
 }


}