src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Bank_Statement_SubCategory_TriggerSwitch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Bank Statement SubCategory TriggerSwitch</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>acfAnnual_profit_income__c</fullName>
        <label>Annual Profit Income</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Monthlly_Salary__c</fullName>
        <label>Annual Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>clickApp_1_Monthly_Expenses__c</fullName>
        <label>Monthly Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>click_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>click_Applicant_Number__c</fullName>
        <label>Applicant Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Bank_Statement_Data__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Statement_Account_Number__c</fullName>
        <label>Bank Statement Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Required_Document_Id__c</fullName>
        <label>Required Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Statement_No__c</fullName>
        <label>Category Index No.</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_TransactionCount__c</fullName>
        <label>Transaction Count</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_UniqueId__c</fullName>
        <formula>TRIM(Click_Required_Document_Id__c + Bank_Statement_Account_Number__c + Click_Statement_No__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UniqueId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>click_Bank_Statements_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statements Account</label>
        <referenceTo>click_Bank_Statements_Account__c</referenceTo>
        <relationshipName>Bank_Statement_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>click_monthAvg__c</fullName>
        <label>Month Avg</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>closingBalance__c</fullName>
        <label>Closing Balance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>openingBalance__c</fullName>
        <label>Opening Balance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bank Statement Category</label>
    <nameField>
        <label>Bank Statement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statement Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Bank_Statements_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Holder__c</fullName>
        <label>Account Holder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Loans_Required_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Required Document</label>
        <referenceTo>Required_Document__c</referenceTo>
        <relationshipLabel>Bank Statements Accounts</relationshipLabel>
        <relationshipName>Bank_Statements_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Statements Account</label>
    <nameField>
        <label>Bank Statements Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Bank_Statements_Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Statement_Account_Number__c</fullName>
        <label>Bank Statement Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Statement_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statement Category</label>
        <referenceTo>click_Bank_Statement_Data__c</referenceTo>
        <relationshipLabel>Bank Statement Sub Categories</relationshipLabel>
        <relationshipName>Bank_Statement_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Click_Bank_Statements_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statements Account</label>
        <referenceTo>click_Bank_Statements_Account__c</referenceTo>
        <relationshipLabel>Bank Statement Sub Categories</relationshipLabel>
        <relationshipName>Bank_Statement_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Click_Required_Document_Id__c</fullName>
        <label>Required Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Statement_No__c</fullName>
        <label>Category Index No.</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_TransactionCount__c</fullName>
        <label>TransactionCount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>click_monthAvg__c</fullName>
        <label>Month Avg</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bank Statements Sub Category</label>
    <nameField>
        <label>Bank Statements Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statement Sub Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials_Source__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank_Statements_Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statements Sub Category</label>
        <referenceTo>click_Bank_Statements_Sub_Category__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Click_Loans_Required_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Required Document</label>
        <referenceTo>Required_Document__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Income_And_Expense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Income And Expense</label>
        <referenceTo>Income_And_Expense__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM User Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner User Input</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financials Source</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>click_Applicant__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dividends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Allowance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overtime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basic Living Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Interest Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Time - PAYG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Govt Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability Expenses</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <recordTypes>
        <fullName>Income</fullName>
        <active>true</active>
        <label>Income</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BankStmtSubCategoryTriggerHandlerTracker.cls
@isTest
private class BankStmtSubCategoryTriggerHandlerTracker{

 private static click_Bank_Statement_Data__c objBankStmtData;
 private static click_Bank_Statements_Sub_Category__c objBankStmtSubCat;
 private static click_Bank_Statements_Sub_Category__c objBnkStatSubCategory2;
 private static list<click_Bank_Statement_Data__c> lstBnkStmtData;
 private static click_Bank_Statements_Account__c objBankStmtAcc;
 private static list<click_Bank_Statements_Account__c> lstBankStmtAcc;
 private static Income_And_Expense__c objIncome;
 private static Required_Document__c objRequiredDocument;
 private static Document_Master__c  objDocumentMaster;
 private static Opportunity objOpportunity;
 private static User objUser;
 private static Account objAccount;
 private static Lead objLead;
 private static click_Bank_Statement_Data__c objBankstmtcat;
 private static click_Applicant__c objApp;
 private static Financials_Source__c objFinancialSource;
 private Id clickReqDocId;
 

 static testMethod void createBankStatementAccount(){


 // objUser = WLCommonTrackerClass.createUser(objUser);
 // objOpportunity = WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);
 // objDocumentMaster = WLCommonTrackerClass.createDocumentMaster(objDocumentMaster);
 
          ACFSwitch__c acfswitch = new ACFSwitch__c();
           acfswitch.Bank_Statement_SubCategory_TriggerSwitch__c = true;
             insert acfswitch;
         
 
    objRequiredDocument = new Required_Document__c();
    objRequiredDocument.Name = 'Click Loan required doc';
    insert objRequiredDocument;
    
     objLead = new Lead();
        objLead.isconverted = false;
        objLead = WLCommonTrackerClass.createLead(objLead);
    
    
     objAccount = new Account();
        list<lead> lstLead = [select id,isConverted from lead where id =: objLead.id];
        if(lstLead != null && lstLead.size()>0)
        {
            if(lstLead[0].isConverted == false)
                objAccount.acf_Lead__pc = lstLead[0].id;
        }
        objAccount = WLCommonTrackerClass.createAccount(objAccount);
    
         objApp = new click_Applicant__c();
         objApp.acfAnnual_profit_income__c = '3234';
         objApp.acf_applicant_Monthlly_Salary__c = 45;
         objApp.clickApp_1_Monthly_Expenses__c  = 654.54;
         objApp.click_Applicant_Number__c = '1';
         objApp.click_Account__c = objAccount.id;
         insert objApp;
    

     Id IncomeRecordTypeId = Schema.SObjectType.Income_And_Expense__c.getRecordTypeInfosByName().get('Income').getRecordTypeId();
     objIncome = new Income_And_Expense__c();
     objIncome.recordTypeId = IncomeRecordTypeId;
     objIncome.Amount__c = 45;
     objIncome.Category__c = 'Full Time - PAYG';
     objIncome.Applicant__c = objApp.Id;
     insert objIncome;
    

    lstBankStmtAcc = new list<click_Bank_Statements_Account__c>();
    objBankStmtAcc = new click_Bank_Statements_Account__c();

    objBankStmtAcc.Name = 'Test BankStatement Account';
    objBankStmtAcc.Account_Holder__c = 'Manish Bhasin';
    objBankStmtAcc.Account_Number__c = 'ABC123';
    objBankStmtAcc.Click_Loans_Required_Document__c = objRequiredDocument.Id;
    lstBankStmtAcc.add(objBankStmtAcc);

    if(lstBankStmtAcc.size()>0 && lstBankStmtAcc!=null){
    insert lstBankStmtAcc;

//  objBankStmtAcc.Account_Holder__c = 'Mb';
//  update objBankStmtAcc;
   }
    system.debug('lstBankStmtAcc------------' +lstBankStmtAcc);
    system.assertEquals('Test BankStatement Account',objBankStmtAcc.Name);
    
     objBnkStatSubCategory2 = new click_Bank_Statements_Sub_Category__c();
    objBnkStatSubCategory2.Name = 'Wages';
    objBnkStatSubCategory2.Click_Required_Document_Id__c = string.valueof(objRequiredDocument.Id);
    objBnkStatSubCategory2.Bank_Statement_Account_Number__c = 'BNK1234';
    objBnkStatSubCategory2.Click_Statement_No__c = 'acsds1212';
    insert objBnkStatSubCategory2;
 
    String strUniqueID = '';
    strUniqueID = objBnkStatSubCategory2.Click_Required_Document_Id__c + objBnkStatSubCategory2.Bank_Statement_Account_Number__c + objBnkStatSubCategory2.Click_Statement_No__c;
   

    lstBnkStmtData = new List<click_Bank_Statement_Data__c>();
    objBankStmtData = new click_Bank_Statement_Data__c();
    objBankStmtData.Name = 'Income';
    objBankStmtData.click_Bank_Statements_Account__c = lstBankStmtAcc[0].Id;
    objBankStmtData.Click_Required_Document_Id__c = 'testId123';
   // objBankStmtData.Click_UniqueId__c = strUniqueID;
    objBankStmtData.closingBalance__c = '1200';
    objBankStmtData.openingBalance__c = '500';
    objBankStmtData.Bank_Statement_Account_Number__c = 'BNK112344';
    objBankStmtData.Click_Statement_No__c = 'BANK121343';
    lstBnkStmtData.add(objBankStmtData);
    
    if(lstBnkStmtData.size()>0 && lstBnkStmtData!=null){

    insert lstBnkStmtData; 
   
    system.debug('lstBnkStmtData++++++++++++++' +lstBnkStmtData);
    
     objBankstmtcat = new click_Bank_Statement_Data__c();      
        objBankstmtcat.Name = 'Income';   
        insert objBankstmtcat;
    
    
   
    
    objBankStmtSubCat = new click_Bank_Statements_Sub_Category__c();
    objBankStmtSubCat.Name = objBankstmtcat.Name;
    objBankStmtSubCat.Click_TransactionCount__c = '3';  
    objBankStmtSubCat.click_monthAvg__c = '432';
    objBankStmtSubCat.Bank_Statement_Category__c = objBankStmtData.Id;
    objBankStmtSubCat.Click_Required_Document_Id__c = string.valueof(objRequiredDocument.Id);
    if(objBankstmtcat.Name != null)
    {
    objBankStmtSubCat.Name = objBankstmtcat.Name;
    }
    objBankStmtSubCat.Click_Statement_No__c= 'abc12345';
    objBankStmtSubCat.Bank_Statement_Account_Number__c ='BNKAC123';
   
       
  //  insert objBankStmtSubCat;
    
    List<click_Bank_Statements_Sub_Category__c> lstbnkstmtsubcat = new List<click_Bank_Statements_Sub_Category__c>();
    lstbnkstmtsubcat.add(objBankStmtSubCat);
    insert lstbnkstmtsubcat;
    update lstbnkstmtsubcat;
    
    List<Financials_Source__c> lstFinancesource = new List<Financials_Source__c>(); 
    objFinancialSource = new Financials_Source__c();
    objFinancialSource.Source__c = 'Bank Stmt';
    objFinancialSource.Bank_Statements_Sub_Category__c = lstbnkstmtsubcat[0].id;
    objFinancialSource.Amount__c = decimal.valueof(lstbnkstmtsubcat[0].click_monthAvg__c)*12;
    objFinancialSource.Click_Loans_Required_Document__c = id.valueof(lstbnkstmtsubcat[0].Click_Required_Document_Id__c);
    lstFinancesource.add(objFinancialSource);
    insert lstFinancesource;
    
   // objFinancialSource = new Financials_Source__c();
    
    
    BankStatementSubCategoryTriggersHandler bnkstmtsubcat = new BankStatementSubCategoryTriggersHandler();
    map<id,click_Bank_Statements_Sub_Category__c> mapBankStmtSubCat = new map<id,click_Bank_Statements_Sub_Category__c>();
    bnkstmtsubcat.updateClickBankStatementSubCategory(lstbnkstmtsubcat);
    bnkstmtsubcat.createFinancialsSource(lstbnkstmtsubcat);
    
  //  bnkstmtsubcat.OnBeforeDelete(lstbnkstmtsubcat,mapBankStmtSubCat);
  //  bnkstmtsubcat.OnAfterDelete(lstbnkstmtsubcat,mapBankStmtSubCat);
  //  bnkstmtsubcat.OnAfterUnDelete(lstbnkstmtsubcat);
   // delete lstbnkstmtsubcat;
    
    
    List<click_Bank_Statement_Data__c> LstBnkStmtData2 = new List<click_Bank_Statement_Data__c>();
    click_Bank_Statement_Data__c objBankStmtData2 = new click_Bank_Statement_Data__c();
    objBankStmtData2.Click_Required_Document_Id__c = objBankStmtData.Bank_Statement_Account_Number__c;
    insert objBankStmtData2;

     }
    
    
    
   //  clickReqDocId = lstBnkStmtData[0].Click_Required_Document_Id__c;
   List<click_Bank_Statements_Account__c> list2 = new List<click_Bank_Statements_Account__c>();
     click_Bank_Statements_Account__c clkbnkstmtacc = new click_Bank_Statements_Account__c();

  }
}