src/objects/ACFSwitch__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Applicant_Trigger_Switch__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Applicant Trigger Switch</label>
        <type>Checkbox</type>
    </fields>
    <label>ACF Switchs</label>
</CustomObject>

src/objects/acfTask_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDescription__c</fullName>
        <description>Click Loans</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Click Loans Task Master</label>
    <nameField>
        <displayFormat>TM-{00000}</displayFormat>
        <label>Task Master Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset_And_Liability__c.object
<CustomObject>
    <fields>
        <fullName>acf_create_from_custom_clone_button__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create from custom clone button</label>
        <type>Checkbox</type>
    </fields>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>acfAnnual_profit_income__c</fullName>
        <label>Annual Profit Income</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfEconsent__c</fullName>
        <label>Econsent</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfRelationship_code__c</fullName>
        <label>Relation ship code</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Name__c</fullName>
        <label>Applicant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_DOB__c</fullName>
        <label>DOB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Employer_Name__c</fullName>
        <label>Employer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Monthlly_Salary__c</fullName>
        <label>Annual Salary</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_create_from_custom_clone_button__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create from custom clone button</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>clickApp_1_Monthly_Expenses__c</fullName>
        <label>Monthly Expenses</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>clickOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>click_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>click_Applicant_Number__c</fullName>
        <label>Applicant Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acfAnnual_profit_income__c</fullName>
        <description>Click Loans</description>
        <label>Annual profit / income</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfEconsent__c</fullName>
        <description>Click Loans</description>
        <label>acfEconsent</label>
        <length>55</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Name__c</fullName>
        <description>Click Loans</description>
        <label>Name</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_DOB__c</fullName>
        <description>Click Loans</description>
        <label>DOB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Employer_Name__c</fullName>
        <description>Click Loans</description>
        <label>Employer Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_Monthlly_Salary__c</fullName>
        <description>Click Loans</description>
        <label>Annual Salary</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>clickApp_1_Monthly_Expenses__c</fullName>
        <label>App 1 Monthly Expenses</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDescription__c</fullName>
        <description>Click Loans</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/E_Consent__c.object
<CustomObject>
    <label>E-Consent</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>E-Consent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>E-Consent</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials_Source__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Income_And_Expense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Income And Expense</label>
        <referenceTo>Income_And_Expense__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financials Source</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Jumio Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/ApplicantTriggerHandlerTracker.cls
@isTest
private class ApplicantTriggerHandlerTracker
    {
        private static Income_And_Expense__c objIncomeExpense;
        private static Account objAccount;
        private static Financials_Source__c objFinancialSource;
        private static click_Applicant__c objApplicant;
        private static Asset_And_Liability__c objAssetLiab;
        private static E_Consent__c objEconsent;
        private static Required_Document__c objrequiredDoc;
        private static Document_Master__c objDocumentMaster;
        private static Id recordtypeID;
        private static task objTask;
        private static user objUser;
        private static Lead objLead;
        private static Contact objContact;
        private static opportunity objOpportunity ;
        private static Document_Master__c docobj;
        private static Required_Document__c reqobj;
       // private static acfTask_Master__c objTask;
    
    static testMethod void validate()
    {
       
        ACFSwitch__c acfswitch = new ACFSwitch__c();
        acfswitch.Applicant_Trigger_Switch__c = true;    
        insert acfswitch;
        
        loadData();
        objTask=new Task();
        //objTask.Description = objTaskMaster.acfDescription__c;
        objTask.WhatId = reqobj.id;
        objTask.Status = 'Open';
        objTask.Priority = 'Normal';
        objTask.ActivityDate = system.today();
        objTask.IsVisibleInSelfService = true;
        //insert objTask;
        
        Financials_Source__c financeobj=new Financials_Source__c();
        financeobj.Income_And_Expense__c=objIncomeExpense.id;
        financeobj.Amount__c=888;
        insert financeobj;
        financeobj.Amount__c=880;
        update financeobj;
        
        objApplicant.acf_create_from_custom_clone_button__C=false;
        objApplicant.clickApp_1_Monthly_Expenses__c =56;
        objApplicant.acfEconsent__c='I Consent';
        update objApplicant; 
      }
      
      static testMethod void validate1()
    {
       
        ACFSwitch__c acfswitch = new ACFSwitch__c();
        acfswitch.Applicant_Trigger_Switch__c = true;    
        insert acfswitch;
        
        loadDataNew();
        //objTask=new Task();
        //objTask.WhatId = reqobj.id;
        //objTask.Status = 'Open';
        //objTask.Priority = 'Normal';
        //objTask.ActivityDate = system.today();
        //objTask.IsVisibleInSelfService = true;
        //insert objTask;
        
        Financials_Source__c financeobj=new Financials_Source__c();
        financeobj.Income_And_Expense__c=objIncomeExpense.id;
        financeobj.Amount__c=888;
        insert financeobj;
        financeobj.Amount__c=880;
        update financeobj;
        
        objApplicant.acf_create_from_custom_clone_button__C=false;
        objApplicant.clickApp_1_Monthly_Expenses__c =56;
        objApplicant.acfEconsent__c='I Consent';
        update objApplicant; 
      }
       
    static void loadData()
    {
        createLead();
        createAccount();
        createContact();
        createuser();
        createOpportunity();
        createApplicant();
        createEconsent();
        createIncomeAndExpenses(); 
    }
    
    static void loadDataNew()
    {
        createLead();
        createAccount();
        createContact();
        createuser();
        createOpportunity();
        createApplicantNew();
        createEconsent();
        createIncomeAndExpenses(); 
    }
    
    static void createLead()
    {
        objLead=new Lead();
        objLead=WLCommonTrackerClass.createLead(objLead);
    }
    
    static void createAccount()
    {
        objAccount = new Account();
        objAccount = WLCommonTrackerClass.CreatePersonAccount('test','test','88','test@gmail.com',objLead.id);
        objAccount.acfAsset_House_Worth__c=55;
        update objAccount; 
    }
    
      static void createuser()
    {
        objUser = new User();
        objuser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);
    }
      static void createContact()
    {
        objContact = new Contact();
        objContact = WLCommonTrackerClass.createContact(objContact,objAccount);
    }

    static void createOpportunity()
    {
        objOpportunity = new Opportunity();
        objOpportunity = WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);      
    }
    static void createApplicant()
    {
        objApplicant=new click_Applicant__c ();
        objApplicant.clickOpportunity__c = objOpportunity.id;
        //objApplicant.acfAnnual_profit_income__c = 3250;
        objApplicant.acf_applicant_Monthlly_Salary__c = 45;
        objApplicant.clickApp_1_Monthly_Expenses__c  = 654;
        objApplicant.click_Applicant_Number__c = '1';
        objApplicant.acf_applicant_DOB__c='10/06/2016';
        objApplicant.acfEconsent__c='test';
        objApplicant.acfRelationship_code__c='1';
        objApplicant.click_Account__c = objAccount.id;
        objApplicant.acf_Applicant_Name__c='Neha Gupta';
        objApplicant.acf_applicant_Employer_Name__c='test';
        insert objApplicant;
        
        docobj=new Document_Master__c ();
        docobj=WLCommonTrackerClass.createDocumentMaster(docobj);   
        reqobj=new Required_Document__c ();
        reqobj=WLCommonTrackerClass.createRequiredDocument(reqobj,docobj,objOpportunity);
        reqobj.Click_Applicant__c=objApplicant.id;
        reqobj.acfStatus__c='Verified';
        update reqobj;
    } 
    
    static void createApplicantNew()
    {
        objApplicant=new click_Applicant__c ();
        objApplicant.clickOpportunity__c = objOpportunity.id;
        objApplicant.acf_applicant_Monthlly_Salary__c = 45;
        objApplicant.acfAnnual_profit_income__c = '3250';
        objApplicant.clickApp_1_Monthly_Expenses__c  = 654;
        objApplicant.click_Applicant_Number__c = '1';
        objApplicant.acf_applicant_DOB__c='10/06/2016';
        objApplicant.acfEconsent__c='test';
        objApplicant.acfRelationship_code__c='1';
        objApplicant.click_Account__c = objAccount.id;
        objApplicant.acf_Applicant_Name__c='Neha Gupta';
        objApplicant.acf_applicant_Employer_Name__c='test';
        insert objApplicant;
    } 
    
    static void createEconsent()
    {
        objEconsent=new E_Consent__c();
        objEconsent=WLCommonTrackerClass.createEconsent(objApplicant);
    }
    
    static void createIncomeAndExpenses()
    {
        objIncomeExpense=new Income_And_Expense__c();
        objIncomeExpense=WLCommonTrackerClass.createIncomeExpense(objIncomeExpense,objApplicant);
    }
      
}