src/objects/acfVeda__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Veda</label>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>acfRelationship_code__c</fullName>
        <label>Relation ship code</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Name__c</fullName>
        <label>Applicant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_DOB__c</fullName>
        <label>DOB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <picklist>
            <picklistValues>
                <fullName>Female</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Male</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Gender__c</fullName>
        <formula>TEXT (Account.PersonContact.Gender__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/VedaRequest__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Permissiontypecode__c</fullName>
        <label>Permissiontypecode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_data_level_code__c</fullName>
        <label>Product data level code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>account_type_code__c</fullName>
        <label>account-type-code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>enquiry_client_reference__c</fullName>
        <label>enquiry-client-reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>operator_id__c</fullName>
        <label>operator-id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>operator_name__c</fullName>
        <label>operator-name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>scorecard_id__c</fullName>
        <label>scorecard-id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Veda Request Fields Values</label>
</CustomObject>

src/classes/UpdateVedasummaryTracker.cls
@isTest(seeAllData=false)

private class UpdateVedasummaryTracker {
    private static Lead objLead;
    private static User objUser;
    private static Account objAccount;
    private static Opportunity objOpportunity;
    private static click_Applicant__c objclickappl;
    private static List<id> lstclickappl;
   
    static testMethod void Validate1()
    {
        Loaddata(); 
        Test.startTest();
        lstclickappl = new List<id>();
        lstclickappl.add(objclickappl.id);
        UpdateVedasummary c = new UpdateVedasummary(lstclickappl);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorsVeda());
        Database.executeBatch(c);
        Test.stopTest();
    }
    
    static testMethod void Validate2()
    {
        Loaddata1(); 
        Test.startTest();
        lstclickappl = new List<id>();
        lstclickappl.add(objclickappl.id);
        UpdateVedasummary c = new UpdateVedasummary(lstclickappl);
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGeneratorsVeda());
        Database.executeBatch(c);
        Test.stopTest();
    }
 
 
    public static void Loaddata()
    {
        acfVeda__c objvedas = new acfVeda__c();
        objvedas.Name = 'Veda';
        objvedas.EndPoint__c = 'https://vedaxml.com/sys2/soap11/vedascore-apply-v2-0';
        objvedas.Password__c = 'U4YEb8cJXj';
        objvedas.UserName__c = 'AChrC1aMa4';
        insert objvedas;
        
        VedaRequest__c objVeda = new VedaRequest__c();
        objVeda.Name = 'Request';
        objVeda.account_type_code__c = 'RM'; 
        objVeda.enquiry_client_reference__c = 'Test1';
        objVeda.operator_id__c = 'I1N3';
        objVeda.operator_name__c = 'John Doe';
        objVeda.Permissiontypecode__c = 'XY';
        objVeda.Product_data_level_code__c = 'C';
        objVeda.scorecard_id__c = 'VSA_2.0_XY_CR,VSA_2.0_XY_NR'; 
        insert objVeda;
        
        createAccount();
        createuser();
        createOpportunity();
        createclickApplicant();       
    }
    
    public static void Loaddata1()
    {
        acfVeda__c objvedas = new acfVeda__c();
        objvedas.Name = 'Veda';
        objvedas.EndPoint__c = 'https://vedaxml.com/sys2/soap11/vedascore-apply-v2-0';
        objvedas.Password__c = 'U4YEb8cJXj';
        objvedas.UserName__c = 'AChrC1aMa4';
        insert objvedas;
        
        VedaRequest__c objVeda = new VedaRequest__c();
        objVeda.Name = 'Request';
        objVeda.account_type_code__c = 'RM'; 
        objVeda.enquiry_client_reference__c = 'Test1';
        objVeda.operator_id__c = 'I1N3';
        objVeda.operator_name__c = 'John Doe';
        objVeda.Permissiontypecode__c = 'XY';
        objVeda.Product_data_level_code__c = 'C';
        objVeda.scorecard_id__c = 'VSA_2.0_XY_CR,VSA_2.0_XY_NR'; 
        insert objVeda;
        
        createAccount1();
        createuser();
        createOpportunity();
        createclickApplicant1();       
    }
 
    static void createAccount()
    {
       objAccount = new Account();
       objAccount.Gender__pc = 'Male';  
       objAccount.acfWhat_is_your_postcode__pc = '12334';
       objAccount =  WLCommonTrackerClass.createAccount(objAccount);
    }
    
    static void createAccount1()
    {
       objAccount = new Account();
       objAccount.Gender__pc = 'Male';  
       objAccount =  WLCommonTrackerClass.createAccount(objAccount);
    }
 
     static void createuser()
    {
        objUser = new User();
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);
    }
 
    static void createOpportunity()
    {
        list<Account> lstAccount = [select id from Account where personContactId =: objUser.ContactId limit 1];
        objOpportunity = new Opportunity();
        objOpportunity.AccountId =lstAccount[0].id;
        objOpportunity.acfBankdetailStatus__c = 'Skipped';
        objOpportunity =  WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);
    }
    
    static void createclickApplicant()
    {
        objclickappl=new click_Applicant__c();       
        objclickappl= WLCommonTrackerClass.createApplicant(objclickappl,objaccount,objOpportunity);
        objclickappl.acf_applicant_DOB__c = string.valueof(System.now());
        objclickappl.acf_Applicant_Name__c = 'test';
        objclickappl.acfRelationship_code__c = '2'; 
        objclickappl.Gender__c = 'Male';
        update objclickappl;
    }
    
    static void createclickApplicant1()
    {
        objclickappl=new click_Applicant__c();       
        objclickappl= WLCommonTrackerClass.createApplicant(objclickappl,objaccount,objOpportunity);
    }
 }