src/objects/acfVedaApplicantLink__c.object
<CustomObject>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>click_Applicant__c</referenceTo>
        <relationshipLabel>Veda Applicant Links</relationshipLabel>
        <relationshipName>Veda_Connector</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Veda_Status__c</fullName>
        <label>Veda Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Veda Applicant Link</label>
    <nameField>
        <label>Veda Applicant Link Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Veda Applicant Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Asset_And_Liability__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset And Liabilities</relationshipLabel>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_applicant_DOB__c</fullName>
        <label>DOB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clickOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acf_applicant_DOB__c</fullName>
        <description>Click Loans</description>
        <label>DOB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IncomeAndExpenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>click_Applicant__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>IncomeAndExpenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <recordTypes>
        <fullName>Income</fullName>
        <active>true</active>
        <label>Income</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCreateVedaClass.cls
@isTest
public with sharing class TestCreateVedaClass {
    private static Opportunity oppo;
    private static Account acc;
    private static Contact cont;
    private static acfVedaApplicantLink__c vedaApp ;
    private static Income_And_Expense__c income;
    private static click_Applicant__c applicant;
    private static Asset_And_Liability__c asset;
    private static MercuryModel.URLParams urlParam;
    static {
        acc = TestUtilities.createAccount(true);
        insert acc;
        cont = TestUtilities.createContact();
        insert cont;
        oppo = TestUtilities.createOpportunity();
        oppo.accountId = acc.id;
        oppo.Sync_With_Mercury_Success__c =true;
        oppo.Sync_With_Mercury__c =true ;
        
        insert oppo;
        applicant = TestUtilities.createApplicant(acc);
        applicant.clickOpportunity__c =oppo.id;
        applicant.acf_applicant_DOB__c = '07/08/1982';
        applicant.Last_name__C = 'test';
        applicant.first_name__C = 'test';
        insert applicant;
        income = TestUtilities.createIncomeAndExpense();
        income.Applicant__c =applicant.id;
        income.Synk_with_Mercury__c=false;
        insert income;
       
        vedaApp = new acfVedaApplicantLink__c();
        vedaApp.Name = '07/08/1982test test';
        vedaApp.Veda_Status__c = 'Active';
        vedaApp.Applicant__c = applicant.id;
        insert vedaApp ;
        
        asset = TestUtilities.createAssetAndLiability();
        List<RecordType> recordTypeIdList = [SELECT id, name, sobjectType FROM RecordType WHERE sobjectType = 'Asset_And_Liability__c'];
        asset.opportunity__c = oppo.id;
        asset.recordTypeId = recordTypeIdList[0].id;
        asset.account__c = acc.id; 
        insert asset;
  
    }

     private static testMethod void ValidateData() {
         CreateVedaClass.createVedaApplicantLink(applicant.id);
         CreateVedaClass.callVedaApi(applicant);
     }
     
     private static testMethod void ValidateData1() {
        vedaApp.Veda_Status__c = 'InActive';
        update vedaApp;
         CreateVedaClass.createVedaApplicantLink(applicant.id);
         CreateVedaClass.callVedaApi(applicant);
     }
}