src/objects/Allocate_Appointment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Setting for Face to face And Phone broker</description>
    <fields>
        <fullName>Buffer__c</fullName>
        <description>The time difference between two appointment</description>
        <inlineHelpText>The time difference between two appointment</inlineHelpText>
        <label>Buffer</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DayEndTime__c</fullName>
        <label>DayEndTime</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DayStartTime__c</fullName>
        <label>DayStartTime</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DurationOfMeeting__c</fullName>
        <description>The length of meeting</description>
        <inlineHelpText>The length of meeting</inlineHelpText>
        <label>DurationOfMeeting</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntervalOfMeeting__c</fullName>
        <description>the slot difference, e.g. 15 min will make the appointment allocation page have available time as pick list with 15 min difference for consecutive available slot.</description>
        <inlineHelpText>the slot difference, e.g. 15 min will make the appointment allocation page have available time as pick list with 15 min difference for consecutive available slot.</inlineHelpText>
        <label>IntervalOfMeeting</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Allocate_Appointment</label>
</CustomObject>

src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Broker is Inactive.
Please check which Broker you&apos;re allocating to this Appointment</errorMessage>
            <filterItems>
                <field>Broker__c.Active_Broker__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Updates from Opportunity Page
Editable on the Appointment too</inlineHelpText>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <formula>TEXT(Opportunity__r.Current_Lender__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Lender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market_Region__c</fullName>
        <formula>Text (Market__r.Market_Region__c)</formula>
        <label>Market Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Australian Capital Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New South Wales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasmania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <formula>Text(Opportunity__r.Transaction_Type__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Transaction Type</label>
        <type>Text</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>Active_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Ticked if Active</inlineHelpText>
        <label>Active Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <label>MobilePhone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Next_Sync_Token__c</fullName>
        <label>Next Sync Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Market__c</fullName>
        <label>Primary Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Market_Region__c</fullName>
        <label>Market Region</label>
        <picklist>
            <picklistValues>
                <fullName>Adelaide</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brisbane</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central Coast / Newcastle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gold Coast / Tweed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Illawarra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Melbourne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Perth</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sunshine Coast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sydney</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canberra</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Region</label>
        <referenceTo>Region__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account.BillingCity</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.BillingState</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <formula>Account.BillingStreet</formula>
        <label>Street Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Refinance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Reigons</relationshipLabel>
        <relationshipName>Reigons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Saasfocus_HotTransfer_Controller_Tracker.cls
@isTest
public class Saasfocus_HotTransfer_Controller_Tracker
{
   static Broker__c objBrk;
   static Opportunity  o;
   static Market__c  m ;
   static State__c  s;
   static Region__c  r;
   static Appointment__c app;
   static Appointment__c app1;

   static testMethod void TestChangeAppointment()
   {
      loadData();
      //Allocate_Appointment__c custobj = new Allocate_Appointment__c(Name = 'Phone_Broker');
      ApexPages.currentPage().getParameters().put('id',app.id);
      Saasfocus_HotTransfer_Controller obj = new Saasfocus_HotTransfer_Controller();
      obj.ChangeBroker();
      obj.Back();
      obj.iscall=false;
      obj.InsertCalender();
      System.assertNotEquals(objBrk,null);

   }

   static testMethod void TestCallouts()
   {
      loadData();
      ApexPages.currentPage().getParameters().put('id',app1.id);
      Saasfocus_HotTransfer_Controller obj = new Saasfocus_HotTransfer_Controller();
      obj.ChangeBroker();
   }

   static void loadData()
   {
      insertBroker();
      insertAppointment();
      insertCustomSetting();

   }

   static void insertCustomSetting()
   {
      Allocate_Appointment__c custobj = new Allocate_Appointment__c();
      custobj.Name = 'Phone_Broker';
      custobj.Buffer__c = '15';
      custobj.DayEndTime__c = '20';
      custobj.DayStartTime__c = '8';
      custobj.DurationOfMeeting__c = '30';
      custobj.IntervalOfMeeting__c = '15';
      insert custobj;
   }

   static void insertBroker()
   {

      m = new Market__c();
      m.Name = 'Dash';
      m.Market_Region__c= 'North';
      insert m;


      objBrk = new Broker__c();
      objBrk.name = 'chen chen';
      objBrk.Active_Broker__c = true;
      objBrk.Email__c='chen@creditandfinance.com.au';
      objBrk.MobilePhone__c='9719764989';
      objBrk.Street_Address__c='ABC';
      objBrk.City__c='dehradun';
      objBrk.Primary_Market__c= m.id;
      objBrk.Next_Sync_Token__c='fhsdjf';
      insert objBrk;


   }

   static void insertAppointment()
   {
      o = new Opportunity();
      o.RecordTypeId= '01290000000thgD';
      o.Name = 'nee';
      o.StageName= 'Appointed';
      o.CloseDate = System.Today();
      o.Transaction_Type__c= 'Refinance';
      o.Current_Lender__c= 'AMP';
      o.Current_Loan_Value__c = 8888;
      o.Current_Loan_Type__c = 'Construction';
      o.Personal_Loan_Balance__c = 7879;
      o.Credit_Card_Balance__c = 8973;
      o.Car_Loan_Balance__c  = 8748;
      insert o;

      m = new Market__c();
      m.Name = 'Dash';
      m.Market_Region__c= 'North';
      insert m;

      s = new State__c();
      s.Name    = 'sim';
      insert s;

      r = new Region__c();
      r.State__c = s.Id ;
      r.Name  = 'North';
      r.Sydney_Timezone_Offset__c =10;
      insert r;

      app = new Appointment__c();
      app.RecordTypeId= '01290000000ttUO';
      app.Opportunity__c= o.Id;
      app.Broker__c = objBrk.Id;
      app.Market__c = m.Id;
      app.Region__c = r.Id ;
      app.Appointment_Date_and_Time__c = System.now();
      app.Appointment_Status__c   = 'New';
      app.Appointment_Type__c   = 'Phone Appointment';
      app.Speciality_Skills__c = 'Receive Phone Appointment; David Learn';
      app.Street_Address__c = 'abc';
      app.State__c = 'Victoria';
      app.City__c  = 'real street';
      app.Postal_Code__c = '6387';
      app.Pre_Sales_Notes__c='jlkasdhakj';
      app.Alternate_Phone__c = '78979878';
      insert app;

      app1 = new Appointment__c();
      app1.RecordTypeId= '01290000000ttUO';
      app1.Opportunity__c= o.Id;
      app1.Broker__c = objBrk.Id;
      app1.Market__c = m.Id;
      app1.Region__c = r.Id ;
      app1.Appointment_Date_and_Time__c = System.now();
      app1.Appointment_Status__c   = 'New';
      app1.Appointment_Type__c   = 'First Appointment';
      app1.Speciality_Skills__c = 'Receive Phone Appointment; Testuser2';
      app1.Street_Address__c = 'abc';
      app1.State__c = 'Victoria';
      app1.City__c  = 'real street';
      app1.Postal_Code__c = '6387';
      app1.Pre_Sales_Notes__c='jlkasdhakj';
      app1.Alternate_Phone__c = '78979878';
      app1.Pre_Sales_Notes__c = 'kjbfjkdshfkjds';
      insert app1;

   }
}