src/objects/Allocate_Appointment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Setting for Face to face And Phone broker</description>
    <fields>
        <fullName>DurationOfMeeting__c</fullName>
        <description>The length of meeting</description>
        <inlineHelpText>The length of meeting</inlineHelpText>
        <label>DurationOfMeeting</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Allocate_Appointment</label>
</CustomObject>

src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Email__c</fullName>
        <formula>Opportunity__r.Account.PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from the Account Page</inlineHelpText>
        <label>Account Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name_Text__c</fullName>
        <formula>Opportunity__r.Account.FirstName &amp; &quot; &quot; &amp; Opportunity__r.Account.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Opportunity__r.Account.Id, Opportunity__r.Account.FirstName &amp; &quot; &quot;  &amp;  Opportunity__r.Account.LastName)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Annual_Income__c</fullName>
        <formula>Opportunity__r.Annual_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Annual Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Appointment_Date_and_Time__c</fullName>
        <label>Appointment Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Appointment_Time_and_Date_Adj__c</fullName>
        <description>Adjusted time and date based on Time Zone</description>
        <label>Appointment Time and Date Adj</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Updates from Opportunity Page
Editable on the Appointment too</inlineHelpText>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Balance__c</fullName>
        <formula>Opportunity__r.Credit_Card_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Credit Card Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <formula>TEXT(Opportunity__r.Current_Lender__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Lender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <formula>Opportunity__r.Employment_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Employment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <formula>Opportunity__r.Industry__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Industry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>Text(+61)&amp;</description>
        <formula>Opportunity__r.Account.PersonMobilePhone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Account Page</inlineHelpText>
        <label>Mobile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Income__c</fullName>
        <formula>Opportunity__r.Partner_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Partner Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Loan_Balance__c</fullName>
        <formula>Opportunity__r.Personal_Loan_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Personal Loan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Opportunity__r.Account.Phone</formula>
        <inlineHelpText>Updates from Account Page</inlineHelpText>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Sales_Notes__c</fullName>
        <label>Pre Sales Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Australian Capital Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New South Wales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasmania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <formula>Text(Opportunity__r.Transaction_Type__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Transaction Type</label>
        <type>Text</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Markets</relationshipLabel>
        <relationshipName>Markets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Email__c</fullName>
        <formula>Account.PersonContact.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Annual_Income__c</fullName>
        <formula>Account.Annual_Income__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>To edit this field, please go to account page</inlineHelpText>
        <label>Annual Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account.BillingCity</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Balance__c</fullName>
        <label>Credit Card Balance</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <formula>TEXT(Account.Employment_Status__pc)</formula>
        <inlineHelpText>To edit this field, please go to account page</inlineHelpText>
        <label>Employment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <formula>TEXT(Account.Industry)</formula>
        <inlineHelpText>To edit this field, please go to account page</inlineHelpText>
        <label>Industry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Income__c</fullName>
        <formula>Account.Partner_Annual_Income__pc</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>To edit this field, please go to account page</inlineHelpText>
        <label>Partner Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Loan_Balance__c</fullName>
        <label>Personal Loan Balance</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pre_Sales_Notes__c</fullName>
        <label>Pre Sales Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.BillingState</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <formula>Account.BillingStreet</formula>
        <label>Street Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Refinance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Region__c.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Reigons</relationshipLabel>
        <relationshipName>Reigons</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Region</label>
    <nameField>
        <label>Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Regions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/EventUtilities.cls
public with sharing class EventUtilities {
	// Insert Event under new Broker
   public static Id InsertEvent(Id currentAppointmentId, String brokername, Appointment__c newAppointment) {
      Allocate_Appointment__c  objappAll =  Allocate_Appointment__c.getValues('Phone_Broker');
      Integer durationOfMeeting = Integer.valueOf(objappAll.durationOfMeeting__c);

      Appointment__c obj = new Appointment__c();
      obj =[SELECT Id,Name,Account_Name__c,Account_Email__c,Appointment_Date_and_Time__c, Account_Name_Text__c, Mobile__c,Phone__c,Employment_Status__c,Industry__c,Annual_Income__c,Partner_Income__c,Credit_Card_Balance__c,Personal_Loan_Balance__c,Appointment_Time_and_Date_Adj__c,Street_Address__c,City__c,State__c, Pre_Sales_Notes__c,Transaction_Type__c,Current_Lender__c,Current_Loan_Value__c,Current_Loan_Type__c,Current_Interest_Rate__c,Current_Interest_Rate_Type__c,Current_Financials_Up_to_Date__c,Last_Refinance__c,Fixed_Rate_Expiry__c,Age_of_Current_Loan__c,Postal_Code__c,Appointment_Type__c,Speciality_Skills__c,region__r.Sydney_Timezone_Offset__c,Market__r.Id,Market__r.Name,Region__r.Name,Region__c,Broker__r.Id FROM Appointment__c where id=:currentAppointmentId ];

      Time selectedT = Datetime.valueOf(obj.Appointment_Time_and_Date_Adj__c).time();
      //offset = (Integer) (obj.region__r.Sydney_Timezone_Offset__c *60);
      Broker__c Assignedbroker = [select id,Email__c,Primary_Market__r.Region__r.Sydney_Timezone_Offset__c from Broker__c where id =:brokername];

      List<User> brokeruser = [select id , Email from User where Email = :Assignedbroker.Email__c];
      Datetime DT = Datetime.newInstance(obj.Appointment_Time_and_Date_Adj__c.year(),obj.Appointment_Time_and_Date_Adj__c.month(),obj.Appointment_Time_and_Date_Adj__c.day(),selectedT.hour(),selectedT.minute(),0);

      Event e = new Event();

      if(brokeruser.size()>0)
      e.ownerid = brokeruser[0].id;

      e.Startdatetime= DT;
      e.Enddatetime= e.Startdatetime.addminutes(durationOfMeeting);

      //TODO: new offset
      // if(offset !=null) {
      //    e.startdatetime = e.startdatetime.addMinutes(offset);
      //    e.enddatetime = e.enddatetime.addMinutes(offset);
      // }

      String sfdcBaseURL = URL.getSalesforceBaseUrl().toExternalForm();

      e.whatid= newAppointment.Broker__c;
      if(Test.isRunningTest()) {
         e.IsAllDayEvent = true;
         e.ActivityDate = System.today();
      }

      e.Subject= obj.Name+ '-' +obj.Street_Address__c +' ' +obj.City__c +' ' +obj.State__c +' '  +obj.Postal_Code__c +'-' +obj.Phone__c +'-' +obj.Appointment_Type__c;
      e.Subject=e.Subject.replace('-null','');
      e.Subject=e.Subject.replace('null-','');
      e.Subject=e.Subject.replace('null','');
      e.Location = obj.Street_Address__c+','+obj.City__c+','+obj.State__c+','+obj.Postal_Code__c;
      e.Location =e.Location.replace(',null','');
      e.Location =e.Location.replace('null,','');
      e.Location =e.Location.replace('null','N/A');

      string s1 = '';
      if(obj.Pre_Sales_Notes__c != null){
         s1 = obj.Pre_Sales_Notes__c;
         s1=  s1.stripHtmlTags();
      }
      system.debug('neeeeeeee'+obj .Pre_Sales_Notes__c);
      system.debug('neeee2222'+obj .Street_Address__c);
      string nextline = '\n';
      e.Description = 'Appointment Reference: ' + obj .Name + nextline+ 'Date and Time Of Appointment:'+' '+obj .Appointment_Date_and_Time__c.format('dd/MM/yyyy hh:mm a')+nextline+
      'Customer Mobile:'+' '+obj .Mobile__c+nextline+
      'Customer Phone:'+' '+ obj .Phone__c +nextline+
      'Customer Location:'+' '+obj .Street_Address__c+','+obj .City__c+','+obj .State__c+','+obj .Postal_Code__c+nextline+
      'Customer Email:'+' '+obj .Account_Email__c+nextline+
      'Customer Name:'+' '+obj .Account_Name_Text__c+nextline+nextline+
      'Notes from Pre Sales' +nextline+
      +s1+nextline+nextline+
      'Opportunity Details:'+' '+nextline+
      'Transaction Type:'+' '+obj .Transaction_Type__c+nextline+
      'Current Lender:'+' ' +obj .Current_Lender__c+nextline+
      'Current Loan Value:'+' ' +obj .Current_Loan_Value__c+nextline+
      'Current Loan Type:' +' '+obj .Current_Loan_Type__c+nextline+
      'Current Interest Rate:'+' '+obj .Current_Interest_Rate__c+nextline+
      'Current Interest Rate Type:'+' '+obj .Current_Interest_Rate_Type__c+nextline+
      'Current Financials Up to Date:'+' '+obj .Current_Financials_Up_to_Date__c+nextline+
      'Last Refinanced: '+' '+obj .Last_Refinance__c+nextline+
      'Fixed Rate Expiry:'+' '+obj .Fixed_Rate_Expiry__c+nextline+
      'Age of Current Loan:'+' '+obj .Age_of_Current_Loan__c+nextline+nextline+nextline+
      'Income and Liability Details:'+' ' +nextline+
      'Employment Status:'+' '+ obj .Employment_Status__c +nextline+
      'Industry: '+' '+obj .Industry__c +nextline+
      'Annual Income:'+' '+obj .Annual_Income__c +nextline+
      'Partner Annual Income: '+' '+obj .Partner_Income__c +nextline+
      'Credit Card Balance: '+' '+obj .Credit_Card_Balance__c +nextline+
      'Personal Loan Balance:'+' '+obj .Personal_Loan_Balance__c;
      e.Description=e.Description.replace(',null','');
      e.Description=e.Description.replace('null,','');
      e.Description=e.Description.replace('null','N/A');

      System.debug('capacity' +e);
      insert e;

      return e.id;
   }
}