src/objects/Allocate_Appointment__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Setting for Face to face And Phone broker</description>
    <fields>
        <fullName>DurationOfMeeting__c</fullName>
        <description>The length of meeting</description>
        <inlineHelpText>The length of meeting</inlineHelpText>
        <label>DurationOfMeeting</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Allocate_Appointment</label>
</CustomObject>

src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Email__c</fullName>
        <formula>Opportunity__r.Account.PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from the Account Page</inlineHelpText>
        <label>Account Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name_Text__c</fullName>
        <formula>Opportunity__r.Account.FirstName &amp; &quot; &quot; &amp; Opportunity__r.Account.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Opportunity__r.Account.Id, Opportunity__r.Account.FirstName &amp; &quot; &quot;  &amp;  Opportunity__r.Account.LastName)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Age_of_Current_Loan__c</fullName>
        <formula>Text (Opportunity__r.Age_of_Current_Loan__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Age of Current Loan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternate_Phone__c</fullName>
        <label>Alternate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Annual_Income__c</fullName>
        <formula>Opportunity__r.Annual_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Annual Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Appointment_Date_and_Time__c</fullName>
        <label>Appointment Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>BrokerChannel__c</fullName>
        <description>this field is for separate phone and f2f broker in potential deal report</description>
        <formula>TEXT(Broker__r.Channel__c)</formula>
        <label>Broker Channel</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Broker is Inactive.
Please check which Broker you&apos;re allocating to this Appointment</errorMessage>
            <filterItems>
                <field>Broker__c.Active_Broker__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Updates from Opportunity Page
Editable on the Appointment too</inlineHelpText>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Balance__c</fullName>
        <formula>Opportunity__r.Credit_Card_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Credit Card Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Financials_Up_to_Date__c</fullName>
        <formula>text(Opportunity__r.Current_Financials_Up_to_Date__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Financials Up to Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Interest_Rate_Type__c</fullName>
        <formula>Text(Opportunity__r.Current_Interest_Rate_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Interest Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Interest_Rate__c</fullName>
        <formula>Opportunity__r.Current_Interest_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <formula>TEXT(Opportunity__r.Current_Lender__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Lender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Type__c</fullName>
        <formula>TEXT( Opportunity__r.Current_Loan_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Loan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Value__c</fullName>
        <formula>Opportunity__r.Current_Loan_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Loan Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <formula>Opportunity__r.Employment_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Employment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fixed_Rate_Expiry__c</fullName>
        <formula>Opportunity__r.Fixed_Rate_Expiry__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Fixed Rate Expiry</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <formula>Opportunity__r.Industry__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Industry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Refinance__c</fullName>
        <formula>Opportunity__r.Last_Refinance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Last Refinance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>Text(+61)&amp;</description>
        <formula>Opportunity__r.Account.PersonMobilePhone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Account Page</inlineHelpText>
        <label>Mobile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Income__c</fullName>
        <formula>Opportunity__r.Partner_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Partner Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Loan_Balance__c</fullName>
        <formula>Opportunity__r.Personal_Loan_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Personal Loan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Opportunity__r.Account.Phone</formula>
        <inlineHelpText>Updates from Account Page</inlineHelpText>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Sales_Notes__c</fullName>
        <label>Pre Sales Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Pre_Sales_User__c</fullName>
        <description>Shows Opportunity Owner on Appointment Pages</description>
        <formula>Opportunity__r.Owner.FirstName &amp; Opportunity__r.Owner.LastName</formula>
        <inlineHelpText>This is the Opportunity Owner</inlineHelpText>
        <label>Pre Sales User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Australian Capital Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New South Wales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasmania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <formula>Text(Opportunity__r.Transaction_Type__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Transaction Type</label>
        <type>Text</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compensatory_Appointment__c</fullName>
        <label>Compensatory Appointment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <inlineHelpText>Please enter 4 digit Post Code</inlineHelpText>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Counters</relationshipLabel>
        <relationshipName>Counters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Counter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppointmentUtil.cls
public class AppointmentUtil {

	public static List<SelectOption> getAvailabileOptions(List<Datetime> availableTimes, List<Broker__c> orderedBrokers, Map<String, GoogleCalendarModel.CalendarsItem> busyMap, String timezone, Integer coolDown, Integer duration) {
		List<SelectOption> ret = new List<SelectOption>();
		for(Datetime dt : availableTimes) {
			Broker__c broker = selectBroker(orderedBrokers, busyMap, dt.addMinutes(-coolDown), dt.addMinutes(duration + coolDown));
			ret.add(generateSelectOption(broker, dt, timezone));
		}
		return ret;
	}

	public static SelectOption generateSelectOption(Broker__c broker, Datetime dt, String timezone) {
		if(broker == null) {
			return new SelectOption('', '' + 'Not Availiable', true);
		} else {
			return new SelectOption(dt.format('yyyy-MM-dd HH:mm:ss'), '' + dt.format('HH:mm:ss', timezone), false);
		}
	}

	public static Broker__c selectBroker(List<Broker__c> orderedBrokers, Map<String, GoogleCalendarModel.CalendarsItem> busyMap, Datetime startDatetime, Datetime endDatetime) {
		for(Broker__c broker : orderedBrokers) {
			if(!isBusy(broker, busyMap, startDatetime, endDatetime)) return broker;
		}
		return null;
	}

	public static Boolean isClash(Datetime st1, Datetime ed1, Datetime st2, Datetime ed2) {
		if(st1 < ed2 && ed1 > st2) return true;
		return false;
	}

	public static Boolean isBusy(Broker__c broker, Map<String, GoogleCalendarModel.CalendarsItem> busyMap, Datetime eventStartTime, Datetime eventEndTime) {
		GoogleCalendarModel.CalendarsItem ci = busyMap.get(broker.email__c);
		List<GoogleCalendarModel.BusyItem> busyItems = ci.busy;
		Boolean ret = false;
		for(GoogleCalendarModel.BusyItem b : busyItems) {
			if(isClash(eventStartTime, eventEndTime, b.start, b.param_rr_end)) {
				return true;
			}
		}
		return false;
	}

	public static void increaseCount(Broker__c broker) {
		Counter__c c = [SELECT id, count__c FROM Counter__c WHERE broker__c = :broker.id LIMIT 1];
		c.count__c++;
		update c;
	}

	public static void decreaseCompensation(Broker__c broker) {
		broker.compensatory_Appointment__c--;
		update broker;
	}

	public static void adjustCounts(Broker__c broker) {
		if(broker.compensatory_Appointment__c > 0) {
			decreaseCompensation(broker);
		} else {
			increaseCount(broker);
		}
	}

	public static Datetime convertToLocalDatetime(Date gmtDate, String timezone) {
		Integer offset = getTimeZoneDiff('GMT', timezone);
		return ((Datetime) gmtDate).addSeconds(offset/1000);
	}

	public static Integer getTimeZoneDiff(String timezone1, String timezone2) {
		Datetime dt = Datetime.now();
		Datetime ldt1 = Datetime.valueOf(dt.format('yyyy-MM-dd HH:mm:ss', timezone1));
		Datetime ldt2 = Datetime.valueOf(dt.format('yyyy-MM-dd HH:mm:ss', timezone2));
		return (Integer) ((ldt1.getTime() - ldt2.getTime()));
	}

	public static List<Datetime> getAvailabileDatetime(Datetime displayStartTime, Datetime displayEndTime, Integer breakInMin) {
		List<Datetime> ret = new List<Datetime>();
		for(Datetime temp = displayStartTime; temp < displayEndTime; temp = temp.addMinutes(breakInMin)) {
			ret.add(temp);
		}
		return ret;
	}

	public static List<String> getGoogleCalendarIds(List<Broker__c> brokers) {
		Set<String> calendarIds = new Set<String>();
		for(Broker__c b : brokers) {
			calendarIds.add(b.email__c);
		}
		return new List<String>(calendarIds);
	}

	public static String constructAppointmentDescription(Appointment__c appt, String tempDocumentName) {
		String ret = DocumentService.getTemplate(tempDocumentName);
		ret = ret.replace('{!appointmentName}', appt.name == null ? '' : appt.name);
		ret = ret.replace('{!appointmentDatetime}', appt.appointment_Date_and_Time__c == null ? '' : appt.appointment_Date_and_Time__c.format('dd/MM/yyyy hh:mm a'));
		ret = ret.replace('{!contactMobile}', appt.mobile__c == null ? '' : appt.mobile__c);
		ret = ret.replace('{!contactPhone}', appt.phone__c == null ? '' : appt.phone__c);
		ret = ret.replace('{!contactAddress}', EventService.constructAppointmentEventLocation(appt, ','));
		ret = ret.replace('{!contactEmail}', appt.account_Email__c == null ? '' : appt.account_Email__c);
		ret = ret.replace('{!contactName}', appt.account_Name_Text__c == null ? '' : appt.account_Name_Text__c);
		ret = ret.replace('{!appointmentNotes}', appt.pre_Sales_Notes__c == null ? '' : appt.pre_Sales_Notes__c.stripHtmlTags());
		ret = ret.replace('{!transactionType}', appt.transaction_Type__c == null ? '' : appt.transaction_Type__c);
		ret = ret.replace('{!currentLender}', appt.current_Lender__c == null ? '' : appt.current_Lender__c);
		ret = ret.replace('{!currentLoanType}', appt.current_Loan_Type__c == null ? '' : appt.current_Loan_Type__c);
		ret = ret.replace('{!currentInterestRateType}', appt.current_Interest_Rate_Type__c == null ? '' : appt.current_Interest_Rate_Type__c);
		ret = ret.replace('{!currentFinancials}', appt.current_Financials_Up_to_Date__c == null ? '' : appt.current_Financials_Up_to_Date__c);
		ret = ret.replace('{!lastRefinance}', appt.last_Refinance__c == null ? '' : appt.last_Refinance__c.format());
		ret = ret.replace('{!fixedRateExpiry}', appt.fixed_Rate_Expiry__c == null ? '' : appt.fixed_Rate_Expiry__c.format());
		ret = ret.replace('{!currentLoanAge}', appt.age_of_Current_Loan__c == null ? '' : appt.age_of_Current_Loan__c);
		ret = ret.replace('{!incomeLiabilityDetails}', ' ');
		ret = ret.replace('{!employmentStatus}', appt.employment_Status__c == null ? '' : appt.employment_Status__c);
		ret = ret.replace('{!industry}', appt.industry__c == null ? '' : appt.industry__c);

		ret = ret.replace('{!currentLoanValue}', appt.current_Loan_Value__c == null ? '' : '' + appt.current_Loan_Value__c);
		ret = ret.replace('{!currentInterestRate}', '' + appt.current_Interest_Rate__c);
		ret = ret.replace('{!annualIncome}', appt.annual_Income__c == null ? '' : '' + appt.annual_Income__c);
		ret = ret.replace('{!partnerAnualIncome}', appt.partner_Income__c == null ? '' : '' + appt.partner_Income__c);
		ret = ret.replace('{!creditCardBalance}', appt.credit_Card_Balance__c == null ? '' : '' + appt.credit_Card_Balance__c);
		ret = ret.replace('{!personalLoanBalance}', appt.personal_Loan_Balance__c == null ? '' : '' + appt.personal_Loan_Balance__c);

		return ret;
	}

	public static Event constructEvent(Appointment__c appt, Datetime startTime, Id ownerId, Broker__c broker, String tempDocumentName) {
		Integer durationOfMeeting = Integer.valueOf(Allocate_Appointment__c.getValues(AppointmentService.CHANNEL_TO_CONFIG_NAME.get(appt.brokerChannel__c)).durationOfMeeting__c);

		Event e = new Event();
		e.ownerid = ownerId;
		e.startdatetime = startTime;
		e.enddatetime = startTime.addminutes(durationOfMeeting);
		e.whatid = broker.id;
		e.description = constructAppointmentDescription(appt, tempDocumentName);
		e.location = EventService.constructAppointmentEventLocation(appt, ',');
		e.subject = EventService.constructAppointmentEventSubject(appt);
		return e;
	}

	public static String constructEmailBodyToNewBroker(Appointment__c appt, EmailTemplate emailTemplate) {
		string ret = '';
		ret = emailTemplate.htmlValue;
		ret = ret.replace('{!Broker.Name}', appt.broker__r.name == null ? '' : appt.broker__r.name);
		ret = ret.replace('[[AppRef]]', appt.name == null ? '' : appt.name);
		ret = ret.replace('[[Presales]]', appt.pre_Sales_User__c == null ? '' : appt.pre_Sales_User__c);
		ret = ret.replace('[[CustName]]', appt.account_Name__c == null ? '' : appt.account_Name__c);
		ret = ret.replace('[[CustEmail]]', appt.account_Email__c == null ? '' : appt.account_Email__c);
		ret = ret.replace('[[Mobile]]', appt.mobile__c == null ? '' : appt.mobile__c);
		ret = ret.replace('[[Phone]]', appt.phone__c == null ? '' : appt.phone__c);
		ret = ret.replace('[[AlternatePhone]]', appt.alternate_Phone__c == null ? '' : appt.alternate_Phone__c);
		ret = ret.replace('[[AppDateTime]]', appt.appointment_Date_and_Time__c == null ? '' : String.valueOf(appt.appointment_Date_and_Time__c.format('dd/MM/yyyy hh:mm a')));
		ret = ret.replace('[[StreetAddress]]', appt.street_Address__c == null ? '' : appt.street_Address__c);
		ret = ret.replace('[[City]]', appt.city__c == null ? '' : appt.city__c);
		ret = ret.replace('[[PostalCode]]', appt.postal_Code__c == null ? '' : appt.postal_Code__c);
		ret = ret.replace('[[State]]', appt.state__c == null ? '' : appt.state__c);
		ret = ret.replace('[[AppType]]', appt.appointment_Type__c == null ? '' : appt.appointment_Type__c);
		ret = ret.replace('[[preNote]]', appt.pre_Sales_Notes__c == null ? '' : appt.pre_Sales_Notes__c);
		ret = ret.replace('[[TransactionType]]', appt.transaction_Type__c == null ? '' : appt.transaction_Type__c);
		ret = ret.replace('[[CurrentLender]]', appt.current_Lender__c == null ? '' : appt.current_Lender__c);
		ret = ret.replace('[[CurrentLoanValue]]', appt.current_Loan_Value__c == null ? '' : String.valueOf(appt.current_Loan_Value__c));
		ret = ret.replace('[[CurrentLoanType]]', appt.current_Loan_Type__c == null ? '' : appt.current_Loan_Type__c);
		ret = ret.replace('[[CurrentInterestRate]]', appt.current_Interest_Rate__c == null ? '' : String.valueOf(appt.current_Interest_Rate__c));
		ret = ret.replace('[[CurrentInterestRateType]]', appt.current_Interest_Rate_Type__c == null ? '' : appt.current_Interest_Rate_Type__c);
		ret = ret.replace('[[CurrentFinancials]]', appt.current_Financials_Up_to_Date__c == null ? '' : appt.current_Financials_Up_to_Date__c);
		ret = ret.replace('[[FixedRate]]', appt.fixed_Rate_Expiry__c == null ? '' : String.valueOf(appt.fixed_Rate_Expiry__c));
		ret = ret.replace('[[lastRefinance]]', appt.last_Refinance__c == null ? '' : String.valueOf(appt.last_Refinance__c));
		ret = ret.replace('[[AgeCurrent]]', appt.age_of_Current_Loan__c == null ? '' : appt.age_of_Current_Loan__c);
		ret = ret.replace('[[EmploymentStatus]]', appt.employment_Status__c == null ? '' : appt.employment_Status__c);
		ret = ret.replace('[[Industry]]', appt.industry__c == null ? '' : appt.industry__c);
		ret = ret.replace('[[AnnualIncome]]', appt.annual_Income__c == null ? '' : String.valueOf(appt.annual_Income__c));
		ret = ret.replace('[[CreditCardBalance]]', appt.credit_Card_Balance__c == null ? '' : String.valueOf(appt.credit_Card_Balance__c));
		ret = ret.replace('[[PartnerIncome]]', appt.partner_Income__c == null ? '' : String.valueOf(appt.partner_Income__c));
		ret = ret.replace('[[CarLoanBalance]]', appt.car_Loan_Balance__c == null ? '' : String.valueOf(appt.car_Loan_Balance__c));
		ret = ret.replace('[[PersonalLoanBalance]]', appt.personal_Loan_Balance__c == null ? '' : String.valueOf(appt.personal_Loan_Balance__c));
		return ret;
	}

	public static String constructEmailBodyToOldBroker(Appointment__c appt, EmailTemplate emailTemplate) {
		String ret = emailTemplate.htmlValue;
		ret = ret.replace('{!Broker.Name}', appt.Broker__r.name == null ? '' : appt.Broker__r.name);
		ret = ret.replace('[[apptref]]', appt.name == null ? '' : appt.Name);
		ret = ret.replace('[[customer name and address]]', appt.Street_Address__c != null || appt.City__c!= null || appt.Postal_Code__c != null || appt.State__c!= null ? '' : EventService.constructAppointmentEventLocation(appt, ' '));
		ret = ret.replace('[[appointment date and time]]', String.valueOf(appt.Appointment_Date_and_Time__c == null ? '' : appt.Appointment_Date_and_Time__c.format('dd/MM/yyyy hh:mm a')));
		return ret;
	}

}