src/objects/Answer__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Click_Community_Setup__c</fullName>
        <formula>acf_Question__r.Click_Community_Setup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Community Setup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Click Loans Answer</label>
    <nameField>
        <displayFormat>Ans-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Click_Network_ID__c</fullName>
        <label>Community Network ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Page_Prefix__c</fullName>
        <label>Page Prefix</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acfType__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <label>Current Lender</label>
        <picklist>
            <picklistValues>
                <fullName>Current Lender - TBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advantedge Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anchorage Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia First Mortgage Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian First Mortgage Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Defence Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Unity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Melbourne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banksia Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bendigo Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluebay Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Mortgage Corporation Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circle Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citibank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastline Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collins Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commonwealth Bank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LVR_Rate__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>ACF_Comparison_Rate__c</fullName>
        <description>Click Loans</description>
        <label>Comparison Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfApplication_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Application Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLVR__c</fullName>
        <description>Click Loans</description>
        <label>LVR To</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfLoan_Size__c</fullName>
        <description>Click Loans</description>
        <label>Loan Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>LVR_Rate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfRate__c</fullName>
        <description>Click Loans</description>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>clickFixed_Interest_Rate__c</fullName>
        <label>Fixed Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>clickLVR_From__c</fullName>
        <label>LVR From</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>clickLoan_Size_From__c</fullName>
        <label>Loan Size From</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Click Loans LVR &amp; Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LVR &amp; Rate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfOffset_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Offset Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ACF_Comparison_Rate__c</fullName>
        <description>Click Loans</description>
        <label>Comparison_Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfApplication_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Application Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLoan_Size__c</fullName>
        <description>Click Loans</description>
        <label>Loan Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOffset_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Offset Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfTenure_in_Years__c</fullName>
        <description>Click Loans</description>
        <label>Term (in Years)</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfType__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Variable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfvarTenure_In_Years__c</fullName>
        <description>Click Loans</description>
        <label>Tenure (In Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfIs_refinance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is refinance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfRefinance_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Refinance Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Script</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_no__c</fullName>
        <description>Click Loans</description>
        <label>Sequence no</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClickQuoteDetailPartnerTracker.cls
@isTest(SeeAllData = false)
private class ClickQuoteDetailPartnerTracker 
{   
    private static Lead objLead ;
    private static User objUser;
    private static Contact objContact;
    private static Account objAccount;
    private static Opportunity objOpportunity;
    
    
    
    
    static testMethod void validate() 
    {
        LoadData();
        Click_Community_Setup__c objccs=new Click_Community_Setup__c();
        objccs.Name='ClickLoans';
        objccs.Click_Page_Prefix__c = 'Click';
        objccs.Click_Network_ID__c='0DB900000008Ptg';
        insert objccs;
        
        //    RecordType objRT=[select id, name, SObjectType From RecordType Where SObjectType= 'product2' AND name= 'Variable'];
        product2 objPro = new product2();
        objPro.ACF_Comparison_Rate__c = 10;
        objPro.IsActive = true;
        objPro.acfType__c = 'Variable';
        //     objPro.Recordtype.Name = 'Variable';
        objPro.acfTenure_in_Years__c = '2'; 
        objPro.acfvarTenure_In_Years__c = 10;
        //objPro.clickLoan_Type__c =  'Basic';
        objPro.acfOffset_Account__c = false;
        objPro.Name = 'test';
        //   objPro.acfRating__c = '1';
        insert objPro;
        
        LVR_Rate__c objLVR = new LVR_Rate__c();
        objLVR.acfLVR__c = 120000.25;
        objLVR.acfRate__c = 10.25;
        objLVR.acfProduct__c = objPro.id;
        objLVR.acfLoan_Size__c = 10000.20;
        objLVR.ACF_Comparison_Rate__c = 10.00; 
        objLVR.clickFixed_Interest_Rate__c = 9.00;
        objLVR.clickLoan_Size_From__c = 50.50;
        objLVR.clickLVR_From__c = 1.2;
        objLVR.acfApplication_Fee__c = 5000; 
        insert objLVR; 
        
        
        Script__c objScript = new Script__c();
        objScript.acf_Type__c = 'Post-Login';
        objScript.acf_Sequence_no__c = 1;
        insert objScript; 
        
        Question__c objQuestion = new Question__c ();
        objQuestion.acf_Question__c = 'Who is your current lender?';
        objQuestion.acf_Active__c = true;
        objQuestion.acf_Sequence_No__c = 2.0;
        objQuestion.acf_Type__c = 'Button';
        objQuestion.acfRefinance_Sequence_No__c = 1;
        objQuestion.acfIs_refinance__c = true;
        objQuestion.acf_Script__c = objScript.id;
        insert objQuestion;
        
            
            PageReference pageRef = new PageReference('http://www.google.com');
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('cid',objAccount.id);
            ClickQuoteDetail_partner.intWidth = 10;
            ClickQuoteDetail_partner.setProgressBarWidth(10,10,'BrokerClickPostloginQuestionnaires');
            ClickQuoteDetail_partner objclick = new ClickQuoteDetail_partner ();
            
            objclick.strLoanPurpose = 'test';
            objclick.decCurrLoanAmt = 10.01;
            objclick.decEstPropVal = 10.01;
            objclick.decBestRate = 10.01;
            objclick.decComparison = 10.01;
            objclick.decMonthlyPayment = 10;
            objclick.pge_name = 'test';
        
    }
    
    
    static testMethod void validate1() 
    {
        LoadData();
         Click_Community_Setup__c objccs=new Click_Community_Setup__c();
        objccs.Name='ClickLoans';
        objccs.Click_Page_Prefix__c = 'Click';
        objccs.Click_Network_ID__c='0DB900000008Ptg';
        insert objccs;
        //      RecordType objRT=[select id, name, SObjectType From RecordType Where SObjectType= 'product2' AND name= 'Variable'];
        product2 objPro = new product2();
        objPro.ACF_Comparison_Rate__c = 10;
        objPro.IsActive = true;
        objPro.acfType__c = 'Variable';
        //       objPro.Recordtype.Name = 'Variable';
        objPro.acfTenure_in_Years__c = '2'; 
        objPro.acfvarTenure_In_Years__c = 10;
        //  objPro.clickLoan_Type__c =  'Basic';
        objPro.acfOffset_Account__c = false;
        objPro.Name = 'test';
        //    objPro.acfRating__c = '1';
        insert objPro;
        
        LVR_Rate__c objLVR = new LVR_Rate__c();
        objLVR.acfLVR__c = 120000.25;
        objLVR.acfRate__c = 10.25;
        objLVR.acfProduct__c = objPro.id;
        objLVR.acfLoan_Size__c = 10000.20;
        objLVR.ACF_Comparison_Rate__c = 10.00; 
        objLVR.clickFixed_Interest_Rate__c = 9.00;
        objLVR.clickLoan_Size_From__c = 50.50;
        objLVR.clickLVR_From__c = 1.2;
        objLVR.acfApplication_Fee__c = 5000; 
        insert objLVR; 
        
        
        Script__c objScript = new Script__c();
        objScript.acf_Type__c = 'Post-Login';
        objScript.acf_Sequence_no__c = 1;
        insert objScript; 
        
        Question__c objQuestion = new Question__c ();
        objQuestion.acf_Question__c = 'Who is your current lender?';
        objQuestion.acf_Active__c = true;
        objQuestion.acf_Sequence_No__c = 2.0;
        objQuestion.acf_Type__c = 'Button';
        objQuestion.acfRefinance_Sequence_No__c = 1;
        objQuestion.acfIs_refinance__c = true;
        objQuestion.acf_Script__c = objScript.id;
        insert objQuestion;
        
            Id recorsTypeId  = acfCommon.GetRecordTypeId('Lead','Click New Loans');
            objLead.RecordTypeId = recorsTypeId;
            update objLead;
            
            PageReference pageRef = new PageReference('http://www.google.com');
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('cid',objAccount.id);
            ClickQuoteDetail_partner.intWidth = 10;
            ClickQuoteDetail_partner.setProgressBarWidth(10,10,'BrokerClickBankInfoDetails');
            ClickQuoteDetail_partner objclick = new ClickQuoteDetail_partner ();
            
            objclick.strLoanPurpose = 'test';
            objclick.decCurrLoanAmt = 10.01;
            objclick.decEstPropVal = 10.01;
            objclick.decBestRate = 10.01;
            objclick.decComparison = 10.01;
            objclick.decMonthlyPayment = 10;
            objclick.pge_name = 'test';
        
    }
    
    
    /*static testMethod void validate2() 
    {
        LoadData();
        
        //      RecordType objRT=[select id, name, SObjectType From RecordType Where SObjectType= 'product2' AND name= 'Variable'];
        product2 objPro = new product2();
        objPro.ACF_Comparison_Rate__c = 10;
        objPro.IsActive = true;
        objPro.acfType__c = 'Variable';
        //       objPro.Recordtype.Name = 'Variable';
        objPro.acfTenure_in_Years__c = '2'; 
        objPro.acfvarTenure_In_Years__c = 10;
        //   objPro.clickLoan_Type__c =  'Basic';
        objPro.acfOffset_Account__c = false;
        objPro.Name = 'test';
        //    objPro.acfRating__c = '1';
        insert objPro;
        
        LVR_Rate__c objLVR = new LVR_Rate__c();
        objLVR.acfLVR__c = 120000.25;
        objLVR.acfRate__c = 10.25;
        objLVR.acfProduct__c = objPro.id;
        objLVR.acfLoan_Size__c = 10000.20;
        objLVR.ACF_Comparison_Rate__c = 10.00; 
        objLVR.clickFixed_Interest_Rate__c = 9.00;
        objLVR.clickLoan_Size_From__c = 50.50;
        objLVR.clickLVR_From__c = 1.2;
        objLVR.acfApplication_Fee__c = 5000; 
        insert objLVR; 
        
        Script__c objScript= acfCommonTrackerClass.createScriptnew('Post-Login');        
        objScript.acf_Sequence_no__c = 1;
        
        Question__c objQuestion = new Question__c ();
        objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Button',true,false,objScript.id,'Current_Lender__c');
        objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Button',true,false,objScript.id,'Current_Lender__c');
        objQuestion   = acfCommonTrackerClass.CreatePrePostLoginQuestionsnew('Who is your current lender?',1,'Text',true,false,objScript.id,'Current_Lender__c');
        
        answer__c objAnswer=new answer__c();
        objAnswer     = acfCommonTrackerClass.createAnswer(objQuestion.id, null,'Westpac Bank');
        
        
        
       
        
        
        
            PageReference pageRef = new PageReference('http://www.google.com');
            Test.setCurrentPage(pageRef);
            ApexPages.currentPage().getParameters().put('cid',objAccount.id);
            ClickQuoteDetail_partner.intWidth = 10;
            ClickQuoteDetail_partner.currentLeadId=objLead.id;
        
        
        
        
            ClickQuoteDetail_partner.setProgressBarWidth(10,10,'BrokerClickid_verification');
            ClickQuoteDetail_partner.setProgressBarWidth(10,10,'BrokerClickBankInfoDetails');
        
        
            ClickQuoteDetail_partner objclick = new ClickQuoteDetail_partner ();
            objclick.strLoanPurpose = 'test';
            objclick.decCurrLoanAmt = 10.01;
            objclick.decEstPropVal = 10.01;
            objclick.decBestRate = 10.01;
            objclick.decComparison = 10.01;
            objclick.decMonthlyPayment = 10;
            objclick.pge_name = 'test';
        
    }*/
    static testMethod void validatefinal() {
        LoadData();
        PageReference pageRef = new PageReference('http://www.BrokerClickPostloginQuestionnaires.com');
        Test.setCurrentPage(pageRef);
        ApexPages.currentPage().getParameters().put('cid',objAccount.id);        
        ClickQuoteDetail_partner.setProgressBarWidth(10,12, 'BrokerClickPostloginQuestionnaires');
        
    }
    private static void LoadData()
    {
        createLead();
        createAccount();
        //createContact();
        //createUser();
        createOpportunity();
        
    }
    
    static void createLead()
    {
        objLead = new Lead();
        Id recorsTypeId  = acfCommon.GetRecordTypeId('Lead','Click Refi');
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.Status = 'Open';
        objLead.RecordTypeId = recorsTypeId;
        objLead.acfOneTimePassword__c = '724715';
        objLead.acfApproximately_how_much_is_your_house__c = 100.01;
        objLead.acfLoan_Amount__c = 100.20;
        objLead.acfIs_Bank_Statement_Submitted__c = true;
        objLead.acfIs_Identity_Document_Submitted__c = true;
        objLead.acfIs_Post_Login_Ques_Attempted__c =true;
        objLead.acfIs_Identity_Document_Submitted__c =true;
        
        insert objLead;
        //   objLead = acfCommonTrackerClass.createLeadForPortal();
    }
    static void createAccount()
    { 
        objAccount = new Account();
        recordType   recType = [select id,name,sobjectType,ispersontype from recordType where ispersontype=true and sobjectType='account' limit 1];
        objAccount.recordtypeId=recType.id;
        objAccount.firstname='testname';
        objAccount.lastname='testname';
        objAccount.acf_Lead__pc=objLead.Id;
        
        insert objAccount;
    }
    static void createContact()
    {
        objContact = new Contact();
        objContact.acf_lead__c = objLead.id;
        objContact = acfCommontrackerClass.createPartnerContact(objContact,objAccount);
    }
    
    static void createuser()
    {
        objUser = new User();
        objUser.MobilePhone='+611234567890';
        
        objUser.contactId=objContact.Id;
        List<Profile> lstCommUserProfile = [select id,name from profile where name='Customize Partner User' limit 1];
        //List<Account>lstPersonContact = [select id,PersonContactId from Account where id=:ContactId];
        //User objUser = new User();
        objUser.FirstName = 'test';
        objUser.LastName = 'test';
        objUser.Alias  = ('test'+String.valueof(Math.random())).substring(0,5);
        objUser.LocaleSidKey = 'en_AU';
        objUser.LanguageLocaleKey = 'en_US';
        objUser.MobilePhone = '+6145678904';
        objUser.Username = 'test@fakeEmail.com';
        objUser.Email = 'test@fakeEmail.com';
        objUser.ProfileId = lstCommUserProfile[0].id;
        //objUser.ContactId = lstPersonContact[0].PersonContactId;
        objuser.EmailEncodingKey = 'UTF-8';
        objUser.CommunityNickname = String.valueof(Math.random()+DateTime.now().year()+DateTime.now().month()+DateTime.now().day()+DateTime.now().hour()+DateTime.now().minute()+DateTime.now().second());
        objUser.TimeZoneSidKey = 'Australia/Brisbane';
        objUser.acfIs_Password_Reset__c = true;
        Database.DMLOptions dlo = new Database.DMLOptions();
        dlo.EmailHeader.triggerUserEmail = false;
        objUser.setOptions(dlo);
        insert(objUser);
        objLead = new Lead();
        Id recorsTypeId  = acfCommon.GetRecordTypeId('Lead','Click Refi');
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.Status = 'Open';
        objLead.RecordTypeId = recorsTypeId;
        objLead.acfOneTimePassword__c = '724715';
        objLead.acfIs_Post_Login_Ques_Attempted__c=false;
        objLead.acfIs_Bank_Statement_Submitted__c=false;
        objLead.acfIs_Identity_Document_Submitted__c=false;
        
        insert objLead;
    }
    
    static void createOpportunity()
    {
        objOpportunity = new Opportunity();
        objOpportunity.acfBankdetailStatus__c = 'Skipped';        
        objOpportunity.AccountId = objAccount.id;
        objOpportunity.recordtypeid = acfCommon.GetRecordTypeId('Opportunity','Click Refi');
        objOpportunity.name = 'test';
        objOpportunity.Stagename = 'Application Taken';
        objOpportunity.CloseDate = System.today();
        insert objOpportunity;
    }
    
    
    
}