src/objects/Answer__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Click_Community_Setup__c</fullName>
        <formula>acf_Question__r.Click_Community_Setup__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Community Setup</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Answer__c</fullName>
        <description>Click Loans</description>
        <label>Answer</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Answer</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Click Loans Answer</label>
    <nameField>
        <displayFormat>Ans-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Answer</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Click_Page_Prefix__c</fullName>
        <label>Page Prefix</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Community_User_Name_Prefix__c</fullName>
        <label>Community User Name Prefix</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acf_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_partner_account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfBubble_Text__c</fullName>
        <description>Click Loans</description>
        <label>Bubble Text</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfIs_New_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is New Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfNew_Loan_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>New Loan Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acfWatermark_Text__c</fullName>
        <description>Click Loans</description>
        <label>Watermark Text</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_ApiName__c</fullName>
        <description>Click Loans</description>
        <label>ApiName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Current_lender__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Current lender</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Description__c</fullName>
        <description>Click Loans</description>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Master_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Master Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Postal_Code__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Postal Code</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Stage_Name__c</fullName>
        <description>Click Loans</description>
        <label>Stage Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Script</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_no__c</fullName>
        <description>Click Loans</description>
        <label>Sequence no</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Stage_Name__c</fullName>
        <description>Click Loans</description>
        <label>Stage Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>acfIs_Password_Reset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Password Reset</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ClickEnablePortalUserFromCRM.cls
global class ClickEnablePortalUserFromCRM 
{ 
   webservice static string createPortalUserFromCRM(string strLeadFName,string strLeadLName,string strLeadEmail,string strPhone,string strLeadId)
   {
      if(IsValidUserName(strLeadEmail))
      {
       //Creating Person Account
        Id currentAccountRecordTypeId = acfcommon.GetRecordTypeId('Account','Click Refi');
        Account objPersonAccount      = new Account();
        objPersonAccount.FirstName    = strLeadFName; 
        objPersonAccount.LastName     = strLeadLName;
        objPersonAccount.PersonMobilePhone        = strPhone;
        objPersonAccount.PersonEmail  = strLeadEmail;
        objPersonAccount.acf_Lead__pc = strLeadId;
        objPersonAccount.RecordTypeId = currentAccountRecordTypeId;  
        objPersonAccount.Lead_Type__pc = 'Click Refi';  
        insert objPersonAccount;
        //List To get Person Account Contact.
        List<Account>lstPersonContact = [select id,PersonContactId from Account where id=:objPersonAccount.Id];
        if(lstPersonContact <> null && lstPersonContact.size()>0)
        {
            List<Profile> lstCommUserProfile = [select id,name from profile where name='Community User' limit 1];
            User objUser = new User();
            objUser.FirstName = strLeadFName;
            objUser.LastName = strLeadLName;
            objUser.Alias  = (strLeadLName+String.valueof(Math.random())).substring(0,5);
            objUser.LocaleSidKey = 'en_AU';
            objUser.LanguageLocaleKey = 'en_US';
            objUser.MobilePhone = strPhone;
            objUser.Username = strLeadEmail;
            objUser.Email = strLeadEmail;
            objUser.ProfileId = lstCommUserProfile[0].id;
            objUser.ContactId = lstPersonContact[0].PersonContactId;
            objuser.EmailEncodingKey = 'UTF-8';
            objUser.CommunityNickname = String.valueof(Math.random()+DateTime.now().year()+DateTime.now().month()+DateTime.now().day()+DateTime.now().hour()+DateTime.now().minute()+DateTime.now().second());
            objUser.TimeZoneSidKey = 'Australia/Brisbane';
            objUser.acfIs_Password_Reset__c = true;
            Database.DMLOptions dlo = new Database.DMLOptions();
            dlo.EmailHeader.triggerUserEmail = false;
            objUser.setOptions(dlo);
            insert(objUser);
            //system.setPassword(objUser.id, 'testpassword1');
            //Updating Account and Contact in Lead.
            Lead objLead = new Lead(id=strLeadId);
            objLead.acf_Contact__c = lstPersonContact[0].PersonContactId;
            objLead.acf_partner_account__c = objPersonAccount.id;
            update objLead;
            acfCustomerRegisterController.generateReqDocs(strLeadId);
            return 'Portal user created.';
        }
      }
      else
      {
         return 'Email already Exist, Please use different one.';   
      }  
      return '';   
   }
   public static boolean IsValidUserName(string struseEmail)
   {
        List<User>lstUser = [select id,Name from user where UserName=:struseEmail];
        if(lstUser <> null && lstUser.size()>0)
        {
            return false;
        }
        return true;
   }
   
   webservice static string createPortalUserFromCRMWithAccounts(id AccId,string strLeadFName,string strLeadLName,string strLeadEmail,string strPhone,string strLeadId,Id CommunityId)
    {
 //       if(IsValidUserName(strLeadEmail))
 //       {
            Click_Community_Setup__c community = new Click_Community_Setup__c();
            if(CommunityId <> null)
            community = [select id,Click_Page_Prefix__c,Community_User_Name_Prefix__c from Click_Community_Setup__c where id=:CommunityId];
            string CommunityProfileName = '';
            if(community != null)
            {
                if(community.Community_User_Name_Prefix__c <> null && community.Community_User_Name_Prefix__c <> '')
                {
                    CommunityProfileName = 'Community User '+community.Click_Page_Prefix__c;
                }
                else if(community.Community_User_Name_Prefix__c == null )
                {
                    CommunityProfileName = 'Community User';
                }
            }
            //List To get Person Account Contact.
            List<Account>lstPersonContact = [select id,PersonContactId from Account where id=:AccId];
            if(lstPersonContact <> null && lstPersonContact.size()>0)
            {
                List<Profile> lstCommUserProfile = [select id,name from profile where name =: CommunityProfileName limit 1];
                User objUser = new User();
                objUser.FirstName = strLeadFName;
                objUser.LastName = strLeadLName;
                //objuser.username='testuser';
                //objuser.email='testmail@gmail.com';
                objUser.Alias  = (strLeadLName+String.valueof(Math.random())).substring(0,5);
                objUser.LocaleSidKey = 'en_AU';
                objUser.LanguageLocaleKey = 'en_US';
                objUser.MobilePhone = strPhone;
                if(community != null && community.Community_User_Name_Prefix__c <> null && community.Community_User_Name_Prefix__c <> '')
                {
                    objUser.Username= community.Community_User_Name_Prefix__c+strLeadEmail;
                }
                else if(community != null && community.Community_User_Name_Prefix__c == null)
                {
                    objUser.Username = strLeadEmail;
                }
                objUser.Email = strLeadEmail;
                objUser.ProfileId = lstCommUserProfile[0].id;
                objUser.ContactId = lstPersonContact[0].PersonContactId;
                objuser.EmailEncodingKey = 'UTF-8';
                objUser.CommunityNickname = String.valueof(Math.random()+DateTime.now().year()+DateTime.now().month()+DateTime.now().day()+DateTime.now().hour()+DateTime.now().minute()+DateTime.now().second());
                objUser.TimeZoneSidKey = 'Australia/Brisbane';
                objUser.acfIs_Password_Reset__c = true;
                Database.DMLOptions dlo = new Database.DMLOptions();
                dlo.EmailHeader.triggerUserEmail = false;
                objUser.setOptions(dlo);
       //       system.debug('###objUser'+objUser); 
                insert(objUser);
                //system.setPassword(objUser.id, 'testpassword1');
                //Updating Account and Contact in Lead.
                Lead objLead = new Lead(id=strLeadId);
                objLead.acf_Contact__c = lstPersonContact[0].PersonContactId;
                objLead.acf_partner_account__c = AccId;
                update objLead;
                Click_Community_Setup__c ObjComm = [select id,Click_Page_Prefix__c from Click_Community_Setup__c
                                                          where id =:CommunityId limit 1];
                if(ObjComm != null)
                WLCustomerRegisterController.generateReqDocs(strLeadId,ObjComm);
                
                //Code to display suggested products.
                List<Question__c> lstQuestions = [select id,acf_ApiName__c,acf_Description__c,acf_Current_lender__c,acf_Master_Question__c,acf_Question__c,acf_Script__c,acf_Type__c,acf_Stage_Name__c,acf_Sequence_No__c, acf_Postal_Code__c,
                                                acfBubble_Text__c,(select id,acf_Answer__c from Answer__r),acfWatermark_Text__c,acfIs_New_Loan__c,acfNew_Loan_Sequence_No__c                                                            
                                                from Question__c where (acf_Script__r.acf_Type__c='Pre-Login' and acf_Active__c = true and (acf_Type__c ='picklist' or acf_Type__c ='Checkbox' or acf_Type__c ='button' or acf_Type__c ='Radiobutton'))];

                Set<String> setOfQuesApiNames = new Set<String>();
                List<Answer__c> lstAnswer = new List<Answer__c>();
                if(lstQuestions != null && lstQuestions.size()>0)
                {
                    for(Question__c objQues :lstQuestions)
                    {
                        setOfQuesApiNames.add(objQues.acf_ApiName__c);
                        
                        for(Answer__c objAns:objQues.Answer__r)
                        {
                            lstAnswer.add(objAns);
                        }
                    }
                }
                String strleadQues='';
                if(setOfQuesApiNames != null && setOfQuesApiNames.size()>0)
                {
                    for(String strApiname : setOfQuesApiNames)
                    {
                        strleadQues = strleadQues+strApiname+',';
                    }
                }
                if(strleadQues != null && strleadQues <> '')
                {
                    String strQueryOnObj = 'select '+strleadQues+'id from Lead where id = \'' + strLeadId + '\'';
                    SObject[] lstDependentObj = Database.query(strQueryOnObj);
                    Set<String> setOfAnswers = new Set<String>(); 
                    if(lstDependentObj != null && lstDependentObj.size()>0)
                    {
                        for(SObject objDependentObj : lstDependentObj)
                        {
                            for(String strApiName : setOfQuesApiNames)
                            {
                                If(strApiName <> '' && objDependentObj.get(strApiName) <> null)
                                {  
                                    setOfAnswers.add(string.valueof(objDependentObj.get(strApiName))); 
                                }
                            }   
                        }
                    }
                    Set<String> setSelectedAnsIds = new Set<String>();
                    if(lstAnswer != null && lstAnswer.size()>0)
                    {
                        for(Answer__c objAns : lstAnswer)
                        {
                            if(setOfAnswers.contains(objAns.acf_Answer__c))
                            {
                                setSelectedAnsIds.add(objAns.id);
                            }
                        }
                    } 
                    if(CommunityId <> null)  
                    {                
                        ClickCommon.getSuggestedProductsFromAnswers(strLeadId,setSelectedAnsIds,string.valueof(CommunityId));
                        ClickCommon.getRequiredDocumentsFromAnswersFromCRM(strLeadId,setSelectedAnsIds,CommunityId);
                    }
                    
                      
                 }                                                            
                    return 'Portal user created.';
               }
    //        }
    //        else
   //         {
   //             return 'Email already Exist, Please use different one.';   
  //          }  
            return '';   
        }
        //To deploy community lookup functionality and needs to remove this method after brokers changes deployed on production 
        webservice static string createPortalUserFromCRMWithAccount(string AccId,string strLeadFName,string strLeadLName,string strLeadEmail,string strPhone,string strLeadId)
        {
         if(IsValidUserName(strLeadEmail))
        {
           
            //List To get Person Account Contact.
            List<Account>lstPersonContact = [select id,PersonContactId from Account where id=:AccId];
            if(lstPersonContact <> null && lstPersonContact.size()>0)
            {
                List<Profile> lstCommUserProfile = [select id,name from profile where name='Community User' limit 1];
                User objUser = new User();
                objUser.FirstName = strLeadFName;
                objUser.LastName = strLeadLName;
                //objuser.username='testuser';
                //objuser.email='testmail@gmail.com';
                objUser.Alias  = (strLeadLName+String.valueof(Math.random())).substring(0,5);
                objUser.LocaleSidKey = 'en_AU';
                objUser.LanguageLocaleKey = 'en_US';
                objUser.MobilePhone = strPhone;
                objUser.Username = strLeadEmail;
                objUser.Email = strLeadEmail;
                objUser.ProfileId = lstCommUserProfile[0].id;
                objUser.ContactId = lstPersonContact[0].PersonContactId;
                objuser.EmailEncodingKey = 'UTF-8';
                objUser.CommunityNickname = String.valueof(Math.random()+DateTime.now().year()+DateTime.now().month()+DateTime.now().day()+DateTime.now().hour()+DateTime.now().minute()+DateTime.now().second());
                objUser.TimeZoneSidKey = 'Australia/Brisbane';
                objUser.acfIs_Password_Reset__c = true;
                Database.DMLOptions dlo = new Database.DMLOptions();
                dlo.EmailHeader.triggerUserEmail = false;
                objUser.setOptions(dlo);
                insert(objUser);
                //system.setPassword(objUser.id, 'testpassword1');
                //Updating Account and Contact in Lead.
                Lead objLead = new Lead(id=strLeadId);
                objLead.acf_Contact__c = lstPersonContact[0].PersonContactId;
                objLead.acf_partner_account__c = AccId;
                update objLead;
                acfCustomerRegisterController.generateReqDocs(strLeadId);
                
                //Code to display suggested products.
                List<Question__c> lstQuestions = [select id,acf_ApiName__c,acf_Description__c,acf_Current_lender__c,acf_Master_Question__c,acf_Question__c,acf_Script__c,acf_Type__c,acf_Stage_Name__c,acf_Sequence_No__c, acf_Postal_Code__c,
                                                acfBubble_Text__c,(select id,acf_Answer__c from Answer__r),acfWatermark_Text__c,acfIs_New_Loan__c,acfNew_Loan_Sequence_No__c                                                            
                                                from Question__c where (acf_Script__r.acf_Type__c='Pre-Login' and acf_Active__c = true AND (acf_Type__c ='picklist' or acf_Type__c ='Checkbox' or acf_Type__c ='button' or acf_Type__c ='Radiobutton'))];

                Set<String> setOfQuesApiNames = new Set<String>();
                List<Answer__c> lstAnswer = new List<Answer__c>();
                if(lstQuestions != null && lstQuestions.size()>0)
                {
                    for(Question__c objQues :lstQuestions)
                    {
                        setOfQuesApiNames.add(objQues.acf_ApiName__c);
                        
                        for(Answer__c objAns:objQues.Answer__r)
                        {
                            lstAnswer.add(objAns);
                        }
                    }
                }
                String strleadQues='';
                if(setOfQuesApiNames != null && setOfQuesApiNames.size()>0)
                {
                    for(String strApiname : setOfQuesApiNames)
                    {
                        strleadQues = strleadQues+strApiname+',';
                    }
                }
                if(strleadQues != null && strleadQues <> '')
                {
                    String strQueryOnObj = 'select '+strleadQues+'id from Lead where id = \'' + strLeadId + '\'';
                    SObject[] lstDependentObj = Database.query(strQueryOnObj);
                    Set<String> setOfAnswers = new Set<String>(); 
                    if(lstDependentObj != null && lstDependentObj.size()>0)
                    {
                        for(SObject objDependentObj : lstDependentObj)
                        {
                            for(String strApiName : setOfQuesApiNames)
                            {
                                If(strApiName <> '' && objDependentObj.get(strApiName) <> null)
                                {  
                                    setOfAnswers.add(string.valueof(objDependentObj.get(strApiName))); 
                                }
                            }   
                        }
                    }
                    Set<String> setSelectedAnsIds = new Set<String>();
                    if(lstAnswer != null && lstAnswer.size()>0)
                    {
                        for(Answer__c objAns : lstAnswer)
                        {
                            if(setOfAnswers.contains(objAns.acf_Answer__c))
                            {
                                setSelectedAnsIds.add(objAns.id);
                            }
                        }
                    }
                    system.debug('@@karthik'+setSelectedAnsIds);                   
                    acfCommon.getSuggestedProductsFromAnswers(strLeadId,setSelectedAnsIds);
                    
                    acfCommon.getRequiredDocumentsFromAnswers(strLeadId,setSelectedAnsIds);  
                 }                                                            
                    return 'Portal user created.';
               }
            }
            else
            {
                return 'Email already Exist, Please use different one.';   
            }  
            return '';   
        }
   // to convert Lead from CRM manually.     
   webservice static string createPortalUserFromCRMOnLead(string strLeadFName,string strLeadLName,string strLeadEmail,string strPhone,string strLeadId,string strRecordTypeId)
   {
   //   if(IsValidUserName(strLeadEmail))
   //   {
        string strrecordTypeName = '';
        RecordType objRecTypeName = [SELECT id,Name from RecordType where id=:strRecordTypeId Limit 1];
        if(objRecTypeName.Name <> null && objRecTypeName.Name <> '')
        strrecordTypeName = objRecTypeName.Name;
        string[] strrec = strrecordTypeName.split(' ');
        string StrRecordTypeFirstName = strrec[0];
        
       //Creating Person Account
        Id currentAccountRecordTypeId = acfcommon.GetRecordTypeId('Account',objRecTypeName.Name);
        Account objPersonAccount      = new Account();
        objPersonAccount.FirstName    = strLeadFName; 
        objPersonAccount.LastName     = strLeadLName;
        objPersonAccount.PersonMobilePhone        = strPhone;
        objPersonAccount.PersonEmail  = strLeadEmail;
        objPersonAccount.acf_Lead__pc = strLeadId;
        if(currentAccountRecordTypeId <> null)
        objPersonAccount.RecordTypeId = currentAccountRecordTypeId;  
        objPersonAccount.Lead_Type__pc = objRecTypeName.Name;  
        insert objPersonAccount;
        //List To get Person Account Contact.
        List<Account>lstPersonContact = [select id,PersonContactId from Account where id=:objPersonAccount.Id];
        if(lstPersonContact <> null && lstPersonContact.size()>0)
        {
            List<Profile> lstCommUserProfile = new List<Profile>();
            if(StrRecordTypeFirstName == 'Click')
            {
                lstCommUserProfile = [select id,name from profile where name='Community User' limit 1];
            }
            else if(StrRecordTypeFirstName == 'ACF')
            {
                lstCommUserProfile = [select id,name from profile where name='Community User ACF' limit 1];
            }
            User objUser = new User();
            objUser.FirstName = strLeadFName;
            objUser.LastName = strLeadLName;
            objUser.Alias  = (strLeadLName+String.valueof(Math.random())).substring(0,5);
            objUser.LocaleSidKey = 'en_AU';
            objUser.LanguageLocaleKey = 'en_US';
            objUser.MobilePhone = strPhone;
             if(StrRecordTypeFirstName == 'Click')
            {
                objUser.Username = strLeadEmail;
            }
            else if(StrRecordTypeFirstName == 'ACF')
            {
                objUser.Username = 'ACF_'+strLeadEmail;
            }
            objUser.Email = strLeadEmail;
            objUser.ProfileId = lstCommUserProfile[0].id;
            objUser.ContactId = lstPersonContact[0].PersonContactId;
            objuser.EmailEncodingKey = 'UTF-8';
            objUser.CommunityNickname = String.valueof(Math.random()+DateTime.now().year()+DateTime.now().month()+DateTime.now().day()+DateTime.now().hour()+DateTime.now().minute()+DateTime.now().second());
            objUser.TimeZoneSidKey = 'Australia/Brisbane';
            objUser.acfIs_Password_Reset__c = true;
            Database.DMLOptions dlo = new Database.DMLOptions();
            dlo.EmailHeader.triggerUserEmail = false;
            objUser.setOptions(dlo);
            insert(objUser);
            //system.setPassword(objUser.id, 'testpassword1');
            //Updating Account and Contact in Lead.
            Lead objLead = new Lead(id=strLeadId);
            objLead.acf_Contact__c = lstPersonContact[0].PersonContactId;
            objLead.acf_partner_account__c = objPersonAccount.id;
            update objLead;
            acfCustomerRegisterController.generateReqDocs(strLeadId);
            return 'Portal user created.';
        }
  //    }
  //    else
  //    {
 //        return 'Email already Exist, Please use different one.';   
 //     }  
      return '';   
   }
}