src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Appointment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Doc Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Appointment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Updates from Opportunity Page
Editable on the Appointment too</inlineHelpText>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Australian Capital Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New South Wales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasmania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EventServiceTest.cls
@isTest
public class EventServiceTest {

    private static testMethod void testConstructAppointmentEventSubject() {
        Appointment__c appt = new Appointment__c();
        appt.appointment_Type__c = 'First Appointment';

        appt.street_Address__c = 'a';
        appt.city__c = 'b';
        appt.state__c = 'New South Wales';
        appt.postal_Code__c = '2000';
        String res = EventService.constructAppointmentEventSubject(appt);
        System.assertEquals('-a b New South Wales 2000--First Appointment', res);
    }

}