src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Appointment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Doc Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Appointment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Broker is Inactive.
Please check which Broker you&apos;re allocating to this Appointment</errorMessage>
            <filterItems>
                <field>Broker__c.Active_Broker__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Counters</relationshipLabel>
        <relationshipName>Counters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Counter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppointmentServiceTest.cls
@isTest
public class AppointmentServiceTest {
	public static Broker__c broker1;
	public static Broker__c broker2;
	public static Broker__c broker3;

	private static List<Appointment__c> initAppointment() {
		Opportunity oppo = TestUtilities.createOpportunity();
		broker1 = TestUtilities.createBroker();
		broker1.channel__c = 'Phone broker';
		broker1.email__c = 'email1';
		broker2 = TestUtilities.createBroker();
		broker2.channel__c = 'Partner';
		broker2.email__c = 'email1';
		broker3 = TestUtilities.createBroker();
		broker3.channel__c = 'Partner';
		broker3.email__c = 'email2';
		Market__c market1 = TestUtilities.createMarket();
		Market__c market2 = TestUtilities.createMarket();

		insert oppo;
		insert broker1;
		insert broker2;
		insert broker3;
		insert market1;
		insert market2;

		Counter__c c = [SELECT id, count__c FROM Counter__c WHERE broker__c = :broker2.id LIMIT 1];
		c.count__c += 1;
		update c;

		insert TestUtilities.createMarketAssociation(broker1, market1);
		insert TestUtilities.createMarketAssociation(broker1, market2);
		insert TestUtilities.createMarketAssociation(broker2, market2);
		insert TestUtilities.createMarketAssociation(broker2, market1);
		insert TestUtilities.createMarketAssociation(broker3, market2);

		Appointment__c appt1 = TestUtilities.createAppointment(oppo, broker1, market1);
		appt1.appointment_Type__c = 'Phone Appointment';
		Appointment__c appt2 = TestUtilities.createAppointment(oppo, broker2, market2);
		appt2.appointment_Type__c = 'First Appointment';
		return new List<Appointment__c>{appt1, appt2};
	}

}