src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Appointment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Doc Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Appointment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Broker is Inactive.
Please check which Broker you&apos;re allocating to this Appointment</errorMessage>
            <filterItems>
                <field>Broker__c.Active_Broker__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Speciality_Skills__c</fullName>
        <label>Speciality Skills</label>
        <picklist>
            <picklistValues>
                <fullName>Complex Investments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK-Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SK-Specialty Lending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Receive Phone Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pod 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pod 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pod 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pod 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pod 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pod 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pod 7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pod 8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alex Papadimitriou</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrew Jackson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andy Rajpurohit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anthony Arida</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ben Murray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brent Wedesweiler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Chris Rayner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Damien Mckay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorian Loupis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henry Giguere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Jacqui Gray</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>James Blanche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Joseph Eichenblatt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tim McKenzie</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aaron Plumridge</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andre Spaapen</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>Active_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Ticked if Active</inlineHelpText>
        <label>Active Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Compensatory_Appointment__c</fullName>
        <label>Compensatory Appointment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Speciality_Skills__c</fullName>
        <label>Speciality Skills</label>
        <picklist>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complex Investments</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High Value</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Specialty Lending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Receive Phone Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pot 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pot 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pot 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pot 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pot 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pot 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pot 7</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pot 8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sasha Anitei</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alex Nassar</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrew Jackson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andrew Perry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andy Rajpurohit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Brent Wedesweiler</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cameron Langton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Craig Thompson</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>David Learn</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dorian Loupis</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gerry Bruno</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Graeme Chapman</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Henry Giguere</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>James Blanche</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>James Wu</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Munther El-Alami</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Counters</relationshipLabel>
        <relationshipName>Counters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Counter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Market_Broker_Association__c.object
<CustomObject>
    <fields>
        <fullName>Active_Broker__c</fullName>
        <formula>Broker__r.Active_Broker__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Active Broker?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Market - New</relationshipLabel>
        <relationshipName>Market_Broker_Associations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Brokers - New</relationshipLabel>
        <relationshipName>Market_Broker_Associations</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Market Broker Association</label>
    <nameField>
        <label>Market Broker Association Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Market Broker Associations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Lendi/src/classes/BrokerService.cls
public class BrokerService {
	List<Broker__c> brokers;
	Map<Id, Broker__c> brokerMap;

	public BrokerService(Appointment__c appt) {
		brokers = getBrokers(appt);
		brokerMap = new Map<Id, Broker__c>(brokers);
	}

	public List<String> getGoogleCalendarIds() {
		List<String> calendarIds = new List<String>();
		for(Broker__c b : brokers) {
			calendarIds.add(b.email__c);
		}
		return calendarIds;
	}

	public List<Broker__c> getBrokers() {
		return this.brokers;
	}

	public Map<Id, Broker__c> getBrokerMap() {
		return this.brokerMap;
	}

	public Map<Id, Broker__c> getBrokers(List<Market_Broker_Association__c> associations, String speciality) {
		Set<Id> brokerIds = new Set<Id>();
		for(Market_Broker_Association__c association : associations) {
			brokerIds.add(association.broker__c);
		}
		List<Broker__c> brokersWithCompensation;
		List<Broker__c> brokersWithoutCompensation;
		if(speciality == null) {
			brokersWithCompensation = [SELECT id, compensatory_Appointment__c, email__c FROM Broker__c WHERE id IN :brokerIds AND active_Broker__c = true AND compensatory_Appointment__c > 0];
		} else {
			brokersWithCompensation = [SELECT id, compensatory_Appointment__c, email__c FROM Broker__c WHERE id IN :brokerIds AND active_Broker__c = true AND compensatory_Appointment__c > 0 AND speciality_Skills__c INCLUDES (:speciality)];
		}
		Set<Id> brokerIdsWithoutCompensation = new Set<Id>(brokerIds);
		brokerIdsWithoutCompensation.removeAll((new Map<Id, Broker__c>(brokersWithCompensation)).keySet());

		if(speciality == null) {
			brokersWithoutCompensation = [SELECT id, compensatory_Appointment__c, email__c FROM Broker__c WHERE id IN :brokerIdsWithoutCompensation AND active_Broker__c = true];
		} else {
			brokersWithoutCompensation = [SELECT id, compensatory_Appointment__c, email__c FROM Broker__c WHERE id IN :brokerIdsWithoutCompensation AND active_Broker__c = true AND speciality_Skills__c INCLUDES (:speciality)];
		}
		brokersWithCompensation.addAll(brokersWithoutCompensation);
		return new Map<Id, Broker__c>(brokersWithCompensation);
	}

	// get all brokers for this appointment
	public List<Broker__c> getBrokers(Appointment__c appt) {
		//check self appointment
		User curUser = [SELECT email FROM User WHERE id = :UserInfo.getUserId()];
		List<Broker__c> ret = [SELECT id, compensatory_Appointment__c, email__c FROM broker__c WHERE email__c = :curUser.email];
		if(ret.size() > 0) return ret;

		List<Market_Broker_Association__c> marketAssociations = getMarketAssociation(appt);
		Map<Id, Broker__c> marketBrokers = getBrokers(marketAssociations, appt.speciality_Skills__c);
		List<Counter__c> counter = [SELECT id, count__c, broker__c FROM Counter__c where broker__c IN :marketBrokers.keySet() ORDER BY count__c ASC];
		for(Counter__c c : counter) {
			ret.add(marketBrokers.get(c.broker__c));
		}
		return ret;
	}

	public List<Market_Broker_Association__c> getMarketAssociation(Appointment__c appt) {
		String apptType = appt.appointment_Type__c == 'Phone Appointment' ? 'Phone Broker' : 'Face to Face';
		return [SELECT id, broker__c, broker__r.type__c FROM Market_Broker_Association__c WHERE market__c = :appt.market__c AND broker__r.type__c = :apptType];
	}

}