src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Opportunity__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestUpdateBrokerTrigger.cls
@isTest
private class TestUpdateBrokerTrigger {

	private static testMethod void testQueue() {
		MercuryTestUtilities.setCustomSettings(true);
		Appointment__c app = TestUtilities.createAppointment();
		insert app;
		app.RecordTypeId = [SELECT Name, id FROM RecordType WHERE sObjectType='Appointment__c' and isActive=true and Name='Confirmed Appointment'][0].id;
		Test.startTest();
		update app;
		Test.stopTest();
	}
	
	private static testMethod void testNotQueue() {
		MercuryTestUtilities.setCustomSettings(false);
		Appointment__c app = TestUtilities.createAppointment();
		insert app;
		MercuryTestUtilities.setMock(app.Opportunity__c, app.Account_Id__c);
		app.RecordTypeId = [SELECT Name, id FROM RecordType WHERE sObjectType='Appointment__c' and isActive=true and Name='Confirmed Appointment'][0].id;
		Test.startTest();
		update app;
		Test.stopTest();
	}
}