src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Appointment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Doc Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Appointment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Broker is Inactive.
Please check which Broker you&apos;re allocating to this Appointment</errorMessage>
            <filterItems>
                <field>Broker__c.Active_Broker__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>Active_Broker__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Ticked if Active</inlineHelpText>
        <label>Active Broker</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/AppointmentChangeBrokerController.cls
public class AppointmentChangeBrokerController {
	public String selection {get; set;}
	public Appointment__c appt;
	public List<SelectOption> options {
		get {
			List<SelectOption> ret = new List<SelectOption>();
			List<Broker__c> brokers;
			if(appt.appointment_Type__c == 'Phone Appointment') brokers = [SELECT id, name FROM Broker__c WHERE active_Broker__c = true AND name != 'Unallocated Broker' AND channel__c = 'Phone Broker' AND id != :appt.broker__c];
			else brokers = [SELECT id, name FROM Broker__c WHERE active_Broker__c = true AND name != 'Unallocated Broker' AND (channel__c = 'Partner' OR channel__c = 'Employee') AND id != :appt.broker__c];
			for(Broker__c broker : brokers) {
				ret.add(new SelectOption(broker.id, broker.name));
			}
			return ret;
		}
		set;
	}

	public AppointmentChangeBrokerController() {
		String apptId = ApexPages.currentPage().getParameters().get('id');
		init(apptId);
	}

	public AppointmentChangeBrokerController(String apptId) {
		init(apptId);
	}

	public void init(String apptId) {
		appt = [SELECT id, appointment_Type__c, broker__c FROM Appointment__c WHERE id = :apptId];
	}

	public PageReference confirm() {
		return new pagereference('/' + appt.id);
	}

	public PageReference cancel() {
		return new pagereference('/' + appt.id);
	}
}