src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Email__c</fullName>
        <formula>Opportunity__r.Account.PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from the Account Page</inlineHelpText>
        <label>Account Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <formula>HYPERLINK(&quot;/&quot; &amp; Opportunity__r.Account.Id, Opportunity__r.Account.FirstName &amp; &quot; &quot;  &amp;  Opportunity__r.Account.LastName)</formula>
        <label>Account Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Age_of_Current_Loan__c</fullName>
        <formula>Text (Opportunity__r.Age_of_Current_Loan__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Age of Current Loan</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Alternate_Phone__c</fullName>
        <label>Alternate Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Annual_Income__c</fullName>
        <formula>Opportunity__r.Annual_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Annual Income</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Appointment_Date_and_Time__c</fullName>
        <label>Appointment Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Appointment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Doc Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Appointment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Broker_Email__c</fullName>
        <formula>Broker__r.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker_Mobile__c</fullName>
        <formula>Broker__r.MobilePhone__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Mobile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Broker__c</fullName>
        <label>Broker</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Broker is Inactive.
Please check which Broker you&apos;re allocating to this Appointment</errorMessage>
            <filterItems>
                <field>Broker__c.Active_Broker__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Car_Loan_Balance__c</fullName>
        <formula>Opportunity__r.Car_Loan_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Car Loan Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Updates from Opportunity Page
Editable on the Appointment too</inlineHelpText>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Balance__c</fullName>
        <formula>Opportunity__r.Credit_Card_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Credit Card Balance</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Financials_Up_to_Date__c</fullName>
        <formula>text(Opportunity__r.Current_Financials_Up_to_Date__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Financials Up to Date</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Interest_Rate_Type__c</fullName>
        <formula>Text(Opportunity__r.Current_Interest_Rate_Type__c )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Interest Rate Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Interest_Rate__c</fullName>
        <formula>Opportunity__r.Current_Interest_Rate__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <formula>TEXT(Opportunity__r.Current_Lender__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Lender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Type__c</fullName>
        <formula>TEXT( Opportunity__r.Current_Loan_Type__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Loan Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Value__c</fullName>
        <formula>Opportunity__r.Current_Loan_Value__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Current Loan Value</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <formula>Opportunity__r.Employment_Status__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Employment Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Fixed_Rate_Expiry__c</fullName>
        <formula>Opportunity__r.Fixed_Rate_Expiry__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Fixed Rate Expiry</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Industry__c</fullName>
        <formula>Opportunity__r.Industry__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Industry</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Refinance__c</fullName>
        <formula>Opportunity__r.Last_Refinance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Last Refinance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>Text(+61)&amp;</description>
        <formula>Opportunity__r.Account.PersonMobilePhone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Account Page</inlineHelpText>
        <label>Mobile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Income__c</fullName>
        <formula>Opportunity__r.Partner_Income__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Partner Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Loan_Balance__c</fullName>
        <formula>Opportunity__r.Personal_Loan_Balance__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Personal Loan Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Opportunity__r.Account.Phone</formula>
        <inlineHelpText>Updates from Account Page</inlineHelpText>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Sales_Notes__c</fullName>
        <label>Pre Sales Notes</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Pre_Sales_User__c</fullName>
        <description>Shows Opportunity Owner on Appointment Pages</description>
        <formula>Opportunity__r.Owner.FirstName &amp; Opportunity__r.Owner.LastName</formula>
        <inlineHelpText>This is the Opportunity Owner</inlineHelpText>
        <label>Pre Sales User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Australian Capital Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New South Wales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasmania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <formula>Text(Opportunity__r.Transaction_Type__c)</formula>
        <inlineHelpText>Updates from Opportunity Page</inlineHelpText>
        <label>Transaction Type</label>
        <type>Text</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <inlineHelpText>Please enter 4 digit Post Code</inlineHelpText>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>State</label>
        <referenceTo>State__c</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AppointmentUtilities.cls
public with sharing class AppointmentUtilities {
	// Email Notification to old broker
   public static void sendEmailToOldBroker(Appointment__c currentAppointment) {
      EmailTemplate templateId = [select id,subject,body, name,HtmlValue from EmailTemplate where DeveloperName = 'Old_BrokerTemplate' AND isActive=true];
      string body1='';
      body1=templateId.HtmlValue;
      if(currentAppointment.Broker__r.name != null) {
         body1=body1.replace('{!Broker.Name}',currentAppointment.Broker__r.name);
      } else {
         body1=body1.replace('{!Broker.Name}','');
      }

      if(currentAppointment.Name != null) {
         body1=body1.replace('[[apptref]]',currentAppointment.Name);
      } else {
         body1=body1.replace('[[apptref]]','');
      }

      if(currentAppointment.Street_Address__c != null || currentAppointment.City__c!= null || currentAppointment.Postal_Code__c != null || currentAppointment.State__c!= null) {
         body1=body1.replace('[[customer name and address]]',currentAppointment.Account_Name__c+' '+currentAppointment.Street_Address__c+' '+currentAppointment.City__c+' '+currentAppointment.Postal_Code__c+' '+currentAppointment.State__c);
      } else {
         body1=body1.replace('[[customer name and address]]','');
      }

      if(currentAppointment.Appointment_Date_and_Time__c != null) {
         body1=body1.replace('[[appointment date and time]]',String.valueOf(currentAppointment.Appointment_Date_and_Time__c.format('dd/MM/yyyy hh:mm a')));
      } else {
         body1=body1.replace('[[apptref]]','');
      }

      Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

      email.setSubject(templateId.subject);
      email.setToAddresses( new string [] {currentAppointment.Broker_Email__c});
      email.setHtmlBody(body1);
      email.setBccSender(true);

      Messaging.sendEmail(new Messaging.SingleEmailMessage[]{email});
   }

   // Email Notification to New broker
   public static void sendEmailToNewBroker(Appointment__c currentAppointment) {
      Appointment__c newAppointment = [Select name,Car_Loan_Balance__c,Personal_Loan_Balance__c,Credit_Card_Balance__c,Partner_Income__c,Annual_Income__c,Industry__c,Employment_Status__c,Age_of_Current_Loan__c,Last_Refinance__c,Fixed_Rate_Expiry__c,Current_Financials_Up_to_Date__c,Current_Interest_Rate_Type__c,Current_Interest_Rate__c,Current_Loan_Type__c,Current_Loan_Value__c,Current_Lender__c,Transaction_Type__c,Pre_Sales_Notes__c,Appointment_Type__c,Street_Address__c,City__c,Postal_Code__c,State__c,Alternate_Phone__c,Phone__c,Mobile__c,Account_Name__c,Account_Email__c,Pre_Sales_User__c,Broker__r.name,Appointment_Date_and_Time__c,Broker_Email__c,Broker_Mobile__c from Appointment__c where id=:currentAppointment.id ];

      EmailTemplate templateIdnew = [select id,subject,body, name,HtmlValue from EmailTemplate where DeveloperName = 'New_BrokerTemplate' AND isActive=true];
      string body2='';
      body2=templateIdnew.HtmlValue;

      if(newAppointment.Broker__r.name!= null) {
         body2=body2.replace('{!Broker.Name}',newAppointment.Broker__r.name);
      } else {
         body2=body2.replace('{!Broker.Name}','');
      }

      if(newAppointment.name != null) {
         body2=body2.replace('[[AppRef]]',newAppointment.name);
      } else {
         body2=body2.replace('[[AppRef]]','');
      }

      if(newAppointment.Pre_Sales_User__c != null) {
         body2=body2.replace('[[Presales]]',newAppointment.Pre_Sales_User__c);
      } else {
         body2=body2.replace('[[Presales]]','');
      }

      if(newAppointment.Account_Name__c != null) {
         body2=body2.replace('[[CustName]]',newAppointment.Account_Name__c);
      } else {
         body2=body2.replace('[[CustName]]','');
      }

      if(newAppointment.Account_Email__c != null) {
         body2=body2.replace('[[CustEmail]]',newAppointment.Account_Email__c);
      } else {
         body2=body2.replace('[[CustEmail]]','');
      }

      if(newAppointment.Mobile__c != null) {
         body2=body2.replace('[[Mobile]]',newAppointment.Mobile__c);
      } else {
         body2=body2.replace('[[Mobile]]','');
      }

      if(newAppointment.Phone__c != null) {
         body2=body2.replace('[[Phone]]',newAppointment.Phone__c);
      } else {
         body2=body2.replace('[[Phone]]','');
      }

      if(newAppointment.Alternate_Phone__c != null) {
         body2=body2.replace('[[AlternatePhone]]',newAppointment.Alternate_Phone__c);
      } else {
         body2=body2.replace('[[AlternatePhone]]','');
      }

      if(newAppointment.Appointment_Date_and_Time__c != null) {
         body2=body2.replace('[[AppDateTime]]',String.valueOf(newAppointment.Appointment_Date_and_Time__c.format('dd/MM/yyyy hh:mm a')));
      } else {
         body2=body2.replace('[[AppDateTime]]','');
      }

      if(newAppointment.Street_Address__c != null) {
         body2=body2.replace('[[StreetAddress]]',newAppointment.Street_Address__c);
      } else {
         body2=body2.replace('[[StreetAddress]]','');
      }

      if(newAppointment.City__c!= null) {
         body2=body2.replace('[[City]]',newAppointment.City__c);
      } else {
         body2=body2.replace('[[City]]','');
      }

      if(newAppointment.Postal_Code__c != null) {
         body2=body2.replace('[[PostalCode]]',newAppointment.Postal_Code__c);
      } else {
         body2=body2.replace('[[PostalCode]]','');
      }

      if(newAppointment.State__c!= null) {
         body2=body2.replace('[[State]]',newAppointment.State__c);
      } else {
         body2=body2.replace('[[State]]','');
      }

      if(newAppointment.Appointment_Type__c != null) {
         body2=body2.replace('[[AppType]]',newAppointment.Appointment_Type__c);
      } else {
         body2=body2.replace('[[AppType]]','');
      }

      if(newAppointment.Pre_Sales_Notes__c != null) {
         body2=body2.replace('[[preNote]]',newAppointment.Pre_Sales_Notes__c);
      } else {
         body2=body2.replace('[[preNote]]','');
      }

      if(newAppointment.Transaction_Type__c != null) {
         body2=body2.replace('[[TransactionType]]',newAppointment.Transaction_Type__c);
      } else {
         body2=body2.replace('[[TransactionType]]','');
      }

      if(newAppointment.Current_Lender__c != null) {
         body2=body2.replace('[[CurrentLender]]',newAppointment.Current_Lender__c);
      } else {
         body2=body2.replace('[[CurrentLender]]','');
      }

      if(newAppointment.Current_Loan_Value__c != null) {
         body2=body2.replace('[[CurrentLoanValue]]',String.valueOf(newAppointment.Current_Loan_Value__c));
      } else {
         body2=body2.replace('[[CurrentLoanValue]]','');
      }

      if(newAppointment.Current_Loan_Type__c != null) {
         body2=body2.replace('[[CurrentLoanType]]',newAppointment.Current_Loan_Type__c);
      } else {
         body2=body2.replace('[[CurrentLoanType]]','');
      }

      if(newAppointment.Current_Interest_Rate__c != null) {
         body2=body2.replace('[[CurrentInterestRate]]',String.valueOf(newAppointment.Current_Interest_Rate__c));
      } else {
         body2=body2.replace('[[CurrentInterestRate]]','');
      }

      if(newAppointment.Current_Interest_Rate_Type__c != null) {
         body2=body2.replace('[[CurrentInterestRateType]]',newAppointment.Current_Interest_Rate_Type__c);
      } else {
         body2=body2.replace('[[CurrentInterestRateType]]','');
      }

      if(newAppointment.Current_Financials_Up_to_Date__c != null) {
         body2=body2.replace('[[CurrentFinancials]]',newAppointment.Current_Financials_Up_to_Date__c);
      } else {
         body2=body2.replace('[[CurrentFinancials]]','');
      }

      if(newAppointment.Fixed_Rate_Expiry__c != null) {
         body2=body2.replace('[[FixedRate]]',String.valueOf(newAppointment.Fixed_Rate_Expiry__c));
      } else {
         body2=body2.replace('[[FixedRate]]','');
      }

      if(newAppointment.Last_Refinance__c != null) {
         body2=body2.replace('[[lastRefinance]]',String.valueOf(newAppointment.Last_Refinance__c));
      } else {
         body2=body2.replace('[[lastRefinance]]','');
      }

      if(newAppointment.Age_of_Current_Loan__c != null) {
         body2=body2.replace('[[AgeCurrent]]',newAppointment.Age_of_Current_Loan__c);
      } else {
         body2=body2.replace('[[AgeCurrent]]','');
      }

      if(newAppointment.Employment_Status__c!= null) {
         body2=body2.replace('[[EmploymentStatus]]',newAppointment.Employment_Status__c);
      } else {
         body2=body2.replace('[[EmploymentStatus]]','');
      }

      if(newAppointment.Industry__c != null) {
         body2=body2.replace('[[Industry]]',newAppointment.Industry__c);
      } else {
         body2=body2.replace('[[Industry]]','');
      }

      if(newAppointment.Annual_Income__c != null) {
         body2=body2.replace('[[AnnualIncome]]',String.valueOf(newAppointment.Annual_Income__c));
      } else {
         body2=body2.replace('[[AnnualIncome]]','');
      }

      if(newAppointment.Partner_Income__c != null) {
         body2=body2.replace('[[PartnerIncome]]',String.valueOf(newAppointment.Partner_Income__c));
      } else {
         body2=body2.replace('[[PartnerIncome]]','');
      }

      if(newAppointment.Credit_Card_Balance__c != null) {
         body2=body2.replace('[[CreditCardBalance]]',String.valueOf(newAppointment.Credit_Card_Balance__c));
      } else {
         body2=body2.replace('[[CreditCardBalance]]','');
      }

      if(newAppointment.Personal_Loan_Balance__c != null) {
         body2=body2.replace('[[PersonalLoanBalance]]',String.valueOf(newAppointment.Personal_Loan_Balance__c));
      } else {
         body2=body2.replace('[[PersonalLoanBalance]]','');
      }

      if(newAppointment.Car_Loan_Balance__c != null) {
         body2=body2.replace('[[CarLoanBalance]]',String.valueOf(newAppointment.Car_Loan_Balance__c));
      } else {
         body2=body2.replace('[[CarLoanBalance]]','');
      }

      Messaging.SingleEmailMessage emailnew = new Messaging.SingleEmailMessage();

      emailnew.setSubject(templateIdnew.subject);
      emailnew.setToAddresses( new string [] {newAppointment.Broker_Email__c});
      emailnew.setHtmlBody(body2);
      emailnew.setBccSender(true);

      Messaging.sendEmail(new Messaging.SingleEmailMessage[]{emailnew});
   }
}