src/objects/Appointment__c.object
<CustomObject>
    <fields>
        <fullName>Account_Email__c</fullName>
        <formula>Opportunity__r.Account.PersonEmail</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from the Account Page</inlineHelpText>
        <label>Account Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Id__c</fullName>
        <formula>Opportunity__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Id</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name_Text__c</fullName>
        <formula>Opportunity__r.Account.FirstName &amp; &quot; &quot; &amp; Opportunity__r.Account.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Name Text</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Appointment_Date_and_Time__c</fullName>
        <label>Appointment Date and Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Appointment_Status__c</fullName>
        <label>Appointment Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Allocated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rescheduled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Show</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Appointment Held</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Appointment_Type__c</fullName>
        <label>Appointment Type</label>
        <picklist>
            <picklistValues>
                <fullName>First Appointment</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Follow Up Appointment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage Doc Signing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Appointment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Broker_Email__c</fullName>
        <formula>Broker__r.Email__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Broker Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <inlineHelpText>Updates from Opportunity Page
Editable on the Appointment too</inlineHelpText>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Future_Followed_Date__c</fullName>
        <description>Used for reschedule or cancellation</description>
        <label>Future Followed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Mobile__c</fullName>
        <description>Text(+61)&amp;</description>
        <formula>Opportunity__r.Account.PersonMobilePhone</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Updates from Account Page</inlineHelpText>
        <label>Mobile</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opp_Owner_Email__c</fullName>
        <formula>Opportunity__r.Owner.Email</formula>
        <label>Opp Owner Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Appointments</relationshipLabel>
        <relationshipName>Appointments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <formula>Opportunity__r.Account.Phone</formula>
        <inlineHelpText>Updates from Account Page</inlineHelpText>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Potential_Deal__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Potential Deal</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pre_Sales_User__c</fullName>
        <description>Shows Opportunity Owner on Appointment Pages</description>
        <formula>Opportunity__r.Owner.FirstName &amp; Opportunity__r.Owner.LastName</formula>
        <inlineHelpText>This is the Opportunity Owner</inlineHelpText>
        <label>Pre Sales User</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>STP_Forecast_Date__c</fullName>
        <label>STP Forecast Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>Australian Capital Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New South Wales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northern Territory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>South Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tasmania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Western Australia</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Appointment</label>
    <nameField>
        <displayFormat>APPT-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>Appointment Ref</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Appointments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Appointment__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The appointment this case relates to</description>
        <label>Appointment</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Appointment__c.Opportunity__r.AccountId</field>
                <operation>equals</operation>
                <valueField>$Source.AccountId</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Appointment__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Account_Email__c</fullName>
        <formula>Account.PersonContact.Email</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <formula>Account.BillingCity</formula>
        <label>City</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Closed_Lost_Reason__c</fullName>
        <label>Closed Lost Reason</label>
        <picklist>
            <controllingField>StageName</controllingField>
            <picklistValues>
                <fullName>Not Enough Deposit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Enough Equity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currently Unemployed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too Old</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Language Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bad Credit History</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Couldn&apos;t Show Enough Savings</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recently Refinanced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed Rate Break Fee Too High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Doesn&apos;t Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed &lt;1yr</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tax Returns/BAS Incomplete</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Law Issue Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Legal Issues Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Didn&apos;t Want to Leave Current Lender</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Proceeding Despite Best Efforts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitive Pricing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Future_Followed_Date__c</fullName>
        <label>Future Followed Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <formula>Account.BillingPostalCode</formula>
        <label>Postal Code</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Second_Appointment_Date__c</fullName>
        <label>Second Appointment Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.BillingState</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <formula>Account.BillingStreet</formula>
        <label>Street Address</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/State__c.object
<CustomObject>
    <label>State</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>States</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BrokerAppointmentReportBrokerController.cls
public class BrokerAppointmentReportBrokerController {
    public List<Appointment__c> appointments { get; set; }
    public Id currentAppointmentId { get; set; }
    public Map<Id, Appointment__c> appointmentMap { get; set; }
    public String[] closeLostReason { get; set; } 
    public String feedback { get; set; }
    public String oppoDescription { get; set; }
    public String actionContent { get; set; }
    public Boolean presalesAction { get; set; }
    public Id currentUserManager { get; set; }
    public Boolean needHelp { get; set; }
    public Boolean haveUnreportedInterview { get; set; } 
    public List<String> ruleObjectList { get; set; }
    
    public BrokerAppointmentReportBrokerController () {
        appointments = new List <Appointment__c>();
        appointmentMap = new Map<Id, Appointment__c>();
        appointments = getAllAppointmentFromCurrentUser();
        if (appointments != null && appointments.size() > 0) {
            haveUnreportedInterview = true;
            for (Appointment__c appointment : appointments) {
                appointmentMap.put(appointment.Id, appointment);
            }
        }
        feedback = '';
    }
    
    public List<Appointment__c> getAllAppointmentFromCurrentUser() {
        Id currentUserId = UserInfo.getUserId();
        if (currentUserId != null) {
            User user = [Select Id, Email, ManagerId From User where Id =:currentUserId and IsActive = true];
            if (user != null) {
                currentUserManager = user.ManagerId;
                Datetime currentTime = System.now();
                List<Appointment__c> appointments = [Select Id, Name, Opp_Owner_Email__c, Account_Id__c, Appointment_Status__c, Broker_Email__c, Appointment_Type__c, Appointment_Date_and_Time__c, Account_Name_Text__c, Account_Email__c, Phone__c, Mobile__c, Postal_Code__c, Street_Address__c, State__c, City__c, Pre_Sales_User__c, Opportunity__c, Opportunity__r.Future_Followed_Date__c, Opportunity__r.Second_Appointment_Date__c, Opportunity__r.Description, Opportunity__r.StageName, Opportunity__r.Closed_Lost_Reason__c, Potential_Deal__c, STP_Forecast_Date__c From Appointment__c where Broker_Email__c = :user.Email and Appointment_Status__c = 'Allocated' and Appointment_Date_and_Time__c < :currentTime order by Appointment_Date_and_Time__c DESC];
                return appointments;
            }
        } 
        return null;
    }
    
    public List<SelectOption> getAppStatusItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Appointment Held','Appointment Held'));
        options.add(new SelectOption('No Show','No Show'));
        return options;
    }
    
    public List<SelectOption> getOppoStatusItems() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Work In Progress', 'Work In Progress'));
        options.add(new SelectOption('2nd Appt Booked', '2nd Appt Booked'));
        options.add(new SelectOption('Future Opportunity', 'Future Opportunity'));
        options.add(new SelectOption('Closed Won - Signed','Closed Won - Signed'));
        options.add(new SelectOption('Closed Lost','Closed Lost'));
        return options;
    }
    
    public List<SelectOption> getClosedLostReasons() {
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('Not Enough Deposit', 'Not Enough Deposit'));
        options.add(new SelectOption('Not Enough Equity', 'Not Enough Equity'));
        options.add(new SelectOption('Currently Unemployed', 'Currently Unemployed'));
        options.add(new SelectOption('Too Old','Too Old'));
        options.add(new SelectOption('Language Issues','Language Issues'));
        
        options.add(new SelectOption('Bad Credit History','Bad Credit History'));
        options.add(new SelectOption('Couldn\'t Show Enough Savings','Couldn\'t Show Enough Savings'));
        options.add(new SelectOption('Recently Refinanced','Recently Refinanced'));
        options.add(new SelectOption('Fixed Rate Break Fee Too High','Fixed Rate Break Fee Too High'));
        options.add(new SelectOption('Doesn\'t Service','Doesn\'t Service'));
        options.add(new SelectOption('Self Employed <1yr','Self Employed <1yr'));
        
        options.add(new SelectOption('Tax Returns/BAS Incomplete','Tax Returns/BAS Incomplete'));
        options.add(new SelectOption('Family Law Issue Pending','Family Law Issue Pending'));
        options.add(new SelectOption('Legal Issues Pending','Legal Issues Pending'));
        options.add(new SelectOption('Didn\'t Want to Leave Current Lender','Didn\'t Want to Leave Current Lender'));
        options.add(new SelectOption('Not Proceeding Despite Best Efforts','Not Proceeding Despite Best Efforts'));
        return options;
    }
    
    public void saveAndProcess() {
        //System.debug('appt stat : ' + currentSelectedAppointmentStatus);
        //System.debug('appt Id ' + currentAppointmentId);
        Appointment__c appointment = appointmentMap.get(currentAppointmentId);
        //System.debug('appt status ' + appointment.Appointment_Status__c);
        //System.debug('oppo stat : ' + appointment.Opportunity__r.StageName);
        //String result = String.join(closeLostReason, ';');
        /*System.debug('close and lost reason : ' + appointment.Opportunity__r.Closed_Lost_Reason__c);
        System.debug('f o date : ' + appointment.Opportunity__r.Future_Followed_Date__c);
        System.debug('s a date : ' + appointment.Opportunity__r.Second_Appointment_Date__c);
        System.debug('oppo comment : ' + appointment.Opportunity__r.Description);
        System.debug('action requirement : ' + presalesAction);
        System.debug('action content : ' + actionContent);*/
        System.debug('appointment ' + appointment);
        update appointment;
        Opportunity oppo = [Select Id, Name, StageName, Description, Closed_Lost_Reason__c, Second_Appointment_Date__c, Future_Followed_Date__c From Opportunity Where Id = : appointment.Opportunity__c];
        if (appointment.Appointment_Status__c != 'No Show') {
            //logic for saving on the opportunity
            if (oppo != null) {
                if (appointment.Opportunity__r.StageName == 'Work In Progress') {
                    oppo.StageName = 'Appointed';
                } else if (appointment.Opportunity__r.StageName == '2nd Appt Booked') {
                    oppo.StageName = 'Appointed';
                    oppo.Second_Appointment_Date__c = appointment.Opportunity__r.Second_Appointment_Date__c;
                } else if (appointment.Opportunity__r.StageName == 'Future Opportunity') {
                    oppo.StageName = 'Appointed';
                    oppo.Future_Followed_Date__c = appointment.Opportunity__r.Future_Followed_Date__c;
                } else if (appointment.Opportunity__r.StageName == 'Closed Won - Signed') {
                    oppo.StageName = 'Closed Won - Signed';
                } else if (appointment.Opportunity__r.StageName == 'Closed Lost') {
                    oppo.StageName = 'Closed Lost';
                    if (appointment.Opportunity__r.Closed_Lost_Reason__c != null) {
                        String[] picklistlines = new String[]{};
                        picklistlines = appointment.Opportunity__r.Closed_Lost_Reason__c.replace('[', '').replace(']', '').split(',');
                        String result = String.join(picklistlines, ';');
                        oppo.Closed_Lost_Reason__c = result;
                    }
                }
            }
        }
        if (oppo != null) {
            oppo.Description = appointment.Opportunity__r.Description;
            update oppo;
        }
        //create case put on the queue
        if (presalesAction) {
            Group presalesGroup = [Select Id, Name from Group where Name = 'Presales Action Req - Appts'];
            if (presalesGroup != null) {
                Case presalesCase = new Case();
                presalesCase.OwnerId = presalesGroup.Id;
                presalesCase.Appointment__c = appointment.Id;
                presalesCase.AccountId = appointment.Account_Id__c;
                presalesCase.Status = 'New';
                presalesCase.Priority = 'High';
                presalesCase.Subject = 'Presales action required';
                presalesCase.Description = actionContent;
                insert presalesCase;
            }
        } 
        //send email
        String emailContent = 'We have received your appointment eod details.<br/>';
        emailContent += 'Thanks!<br/>';
        emailContent += 'Timestamp :: ' + System.now() + '<br/>';
        emailContent += 'Username :: ' + appointment.Broker_Email__c + '<br/>';
        emailContent += 'Customer Name :: ' + appointment.Account_Name_Text__c + '<br/>';
        emailContent += 'Appointment Reference :: ' + appointment.Name + '<br/>';
        emailContent += 'Opportunity Status ' + appointment.Appointment_Status__c + ' - ' + oppo.StageName + '<br/>';
        emailContent += 'Opportunity Comments :: ' + oppo.Description + '<br/>';
        if (appointment.Opportunity__r.Closed_Lost_Reason__c != null) {
            emailContent += 'Closed Lost Reasons :: ' + appointment.Opportunity__r.Closed_Lost_Reason__c.replace('[', '').replace(']', '') + '<br/>';
        }
        emailContent += '2nd Appt Date :: ' + oppo.Second_Appointment_Date__c + '<br/>';
        emailContent += 'future followed date :: ' + oppo.Future_Followed_Date__c + '<br/>';
        emailContent += 'Presales Action Required? :: ' + presalesAction + '<br/>';
        emailContent += 'Presales Actions :: ' + actionContent + '<br/>';
        emailContent += 'Presales Rep :: ' + appointment.Pre_Sales_User__c + '<br/>';
        emailContent += 'Timestamp :: ' + System.now() + '<br/>';
        String emailSubject = '[brokerdailyreport] ACF Broker EOD - Successfully Submitted';
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<String> sendTo = new List<String>();
        sendTo.add(appointment.Broker_Email__c);
        sendTo.add('brokerdailyreport@creditandfinance.com.au');
        sendTo.add(appointment.Opp_Owner_Email__c);
        //sendTo.add('cche5425@uni.sydney.edu.au');
        mail.setToAddresses(sendTo);
        mail.setSubject(emailSubject);
        mail.setHtmlBody(emailContent);
        List<Messaging.SingleEmailMessage> mails = new List<Messaging.SingleEmailMessage>();
        mails.add(mail);
        Messaging.sendEmail(mails);
        
        System.debug('needHelp ' + needHelp);
        if (needHelp && currentUserManager != null) {
            //send message to chatter
            ConnectApi.FeedItemInput feedItemInput = new ConnectApi.FeedItemInput();
            ConnectApi.MentionSegmentInput mentionSegmentInput = new ConnectApi.MentionSegmentInput();
            ConnectApi.MessageBodyInput messageBodyInput = new ConnectApi.MessageBodyInput();
            ConnectApi.TextSegmentInput textSegmentInput = new ConnectApi.TextSegmentInput();
            textSegmentInput.text = ' I need help with this scenario ';
            messageBodyInput.messageSegments = new List<ConnectApi.MessageSegmentInput>();
            
            mentionSegmentInput.id = currentUserManager;
            messageBodyInput.messageSegments.add(mentionSegmentInput);
            messageBodyInput.messageSegments.add(textSegmentInput);
            
            feedItemInput.body = messageBodyInput;
            feedItemInput.feedElementType = ConnectApi.FeedElementType.FeedItem;
            feedItemInput.subjectId = oppo.Id;
            
            ConnectApi.FeedElement feedElement = ConnectApi.ChatterFeeds.postFeedElement(Network.getNetworkId(), feedItemInput, null);
        	
        	//Send email to josef
        	List<Messaging.SingleEmailMessage> mailsS = new List<Messaging.SingleEmailMessage>();
        	Messaging.SingleEmailMessage mailsSc = new Messaging.SingleEmailMessage();
        	List<String> sendToEmails = new List<String>();
      		sendToEmails.add('scenarios@creditandfinance.com.au');
      		mailsSc.setToAddresses(sendToEmails);
      		
      		mailsSc.setReplyTo(appointment.Broker_Email__c);
      		mailsSc.setSenderDisplayName('Scenario Help');
      		mailsSc.setSubject('Broker Needs Help');
      		
      		String body = 'Need help with appointment ' + appointment.Name + ', broker email is ' + appointment.Broker_Email__c;
      		mailsSc.setHtmlBody(body);
      		mailsS.add(mailsSc);
      		Messaging.sendEmail(mailsS);
        }
    }
    
}