src/objects/Asset_And_Liability__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Asset And Liabilities</relationshipLabel>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Clearing_From_This_Loan__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Clearing From This Loan</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Current_Balance__c</fullName>
        <label>Current Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Limit__c</fullName>
        <label>Limit</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Purpose__c</fullName>
        <label>Primary Purpose</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repayment_Frequency__c</fullName>
        <label>Repayment Frequency</label>
        <picklist>
            <picklistValues>
                <fullName>Weekly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fortnightly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Monthly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anually</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Repayments__c</fullName>
        <label>Repayments</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>OTHER</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>To_Be_Purchased__c</fullName>
        <defaultValue>false</defaultValue>
        <label>To Be Purchased</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Used_as_Security__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Used as Security</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>state__c</fullName>
        <label>State</label>
        <picklist>
            <picklistValues>
                <fullName>ACT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NSW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>QLD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TAS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>WA</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <recordTypes>
        <fullName>Lendi</fullName>
        <active>true</active>
        <label>Lendi</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Position__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Funding Positions</relationshipLabel>
        <relationshipName>Funding_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Funding Positions</relationshipLabel>
        <relationshipName>Funding_Positions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Funding Position</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Funding Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Position_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Funding Position Details</relationshipLabel>
        <relationshipName>Funding_Position_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Detail_Type__c</fullName>
        <label>Detail Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home Loan to Repay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Debts to Repay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Accrued Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Stamp Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge Costs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Price</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Funding_Position__c</fullName>
        <label>Funding Position</label>
        <referenceTo>Funding_Position__c</referenceTo>
        <relationshipLabel>Funding Position Details</relationshipLabel>
        <relationshipName>Funding_Position_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Position Detail</label>
    <nameField>
        <label>Funding Position Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Position Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>IncomeAndExpenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>click_Applicant__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>IncomeAndExpenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <recordTypes>
        <fullName>Expense</fullName>
        <active>true</active>
        <label>Expense</label>
    </recordTypes>
    <recordTypes>
        <fullName>Income</fullName>
        <active>true</active>
        <label>Income</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>State__c</fullName>
        <formula>Account.BillingState</formula>
        <label>State</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

Lendi/src/classes/AssetAndLiabilityTriggerHandlerTracker.cls
@isTest
private class AssetAndLiabilityTriggerHandlerTracker
{
    private static Asset_And_Liability__c objAssetLiab;
    private static Account objAccount;
    private static Account objAccount1;
    private static Funding_Position__c objFundingpos;
    private static Opportunity objOpportunity;
    private static Funding_Position_Detail__c objFundingPosDetail;
    private static User objUser;
    private static State__c objState;
    private static Lead objLead;
    private static Product2 objPro;
    private static OpportunityLineItem oppLine;
    private static PricebookEntry pbEntry ;
    private static Opportunity objOpp;
    private static click_Applicant__c objApplicant;
    private static contact objContact;
    private static Income_And_Expense__c objIncomeandexpense;
    static List<Funding_Position__c> lstFpos=new List<Funding_Position__c>();
        
    static testMethod void validate()
    {
        LoadData();
        
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 
        
        Test.startTest();
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj = new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
    
    static testMethod void validate1()
    {
        LoadData();
        
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Asset Real Estate';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.State__c='NSW';
        objAssetLiab.To_Be_Purchased__c=false;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
        mapobj1.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj1);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj1);
        Test.stopTest();
    }
    static testMethod void validate2()
    {
        LoadData();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Funding_Position__c=objFundingpos.id;
        fundingobj.Detail_Type__c='Transfer Fee';
        insert fundingobj;

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Asset Real Estate';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c =null;
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.State__c='NSW';
        objAssetLiab.To_Be_Purchased__c=false;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
        mapobj1.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj1);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj1);
        Test.stopTest();
    }
    
    static testMethod void validate3()
    {
        LoadData();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=false;
        objAssetLiab.name='Liability Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        insert objAssetLiab;
        Test.stopTest();
    }
         
    static testMethod void validate4()
    {
        LoadData();
        Test.startTest();
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Repayments__c=33;
        objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);
        objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.Repayments__c=37;
        objAssetLiab.Current_Balance__c=987;

        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj; 
        update objAssetLiab;
        Test.stopTest();
    }
        
     static testMethod void validate5()
    {
        LoadData();
        Test.startTest();
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=false;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
        objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);

        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos;   
        Test.stopTest();           
    }
        
    static testMethod void validate5a()
    {      
        LoadData();
        Test.startTest();
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=false;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.Repayment_Frequency__c='Monthly';
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=88;
        objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
        objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);

        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos;   
        Test.stopTest();     
    }
        
     static testMethod void validate5b()
    {
        LoadData();
        Test.startTest();
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=false;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.Repayment_Frequency__c='Anually';
        objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
        objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);

        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos;    
        Test.stopTest();  
    }
        
     static testMethod void validate5c()
    {
        LoadData();
        Test.startTest();
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=false;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.Repayment_Frequency__c='Fortnightly';
        objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
        objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);

        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 
        Test.stopTest();            
    }
        
    static testMethod void validate6()
    {
        LoadData();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Asset Real Estate';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.State__c='NSW';
        objAssetLiab.To_Be_Purchased__c=false;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
        mapobj1.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj1);
        obj.insertAssetEstateSingleRecords(objAssetLiab,mapobj1,66);
        Test.stopTest();  
    }
        
    static testMethod void validate7()
    {
        LoadData();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Monthly';
        insert objAssetLiab;
        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
        
    static testMethod void validate7a()
    {
        LoadData();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Anually';
        insert objAssetLiab;
        
        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
        
    static testMethod void validate7b()
    {
        LoadData();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Fortnightly';
        insert objAssetLiab;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
            
    static testMethod void validate8()
    {
        LoadData();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
        
    static testMethod void validate8a()
    {
        LoadData();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.To_Be_Purchased__c=true; 
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
        
    static testMethod void validate8b()
    {
        LoadData();
        Test.startTest();
        Opportunity objOppo = new opportunity();
        objOppo.AccountId =objUser.AccountId ;
        objOppo.recordtypeid= Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Lendi').getRecordTypeId();
        objOppo.name = 'test';
        objOppo.Stagename = 'Application Taken';
        objOppo.CloseDate = System.today();
        objOppo.acfAsset_House_Worth__c = 200000;
        insert objOppo;
        
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 
        
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOppo.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.To_Be_Purchased__c=true; 
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Id IncomeRecordTypeId = Schema.SObjectType.Income_And_Expense__c.getRecordTypeInfosByName().get('Expense').getRecordTypeId();
        objIncomeandexpense = new Income_And_Expense__c();
        objIncomeandexpense.recordTypeId = IncomeRecordTypeId;
        objIncomeandexpense.Amount__c = 45;
        objIncomeandexpense.Category__c = 'Full Time - PAYG';
        objIncomeandexpense.Applicant__c = objApplicant.Id;
        objIncomeandexpense.Asset_And_Liability__c = objAssetLiab.Id;
        insert objIncomeandexpense;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
    
    static testMethod void validate9a()
    {
        
      /*  Test.startTest(); 
        LoadData();   
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 
        
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity .id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.To_Be_Purchased__c=true; 
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Id IncomeRecordTypeId = Schema.SObjectType.Income_And_Expense__c.getRecordTypeInfosByName().get('Income').getRecordTypeId();
        objIncomeandexpense = new Income_And_Expense__c();
        objIncomeandexpense.recordTypeId = IncomeRecordTypeId;
        objIncomeandexpense.Amount__c = 45;
        objIncomeandexpense.Category__c = 'Full Time - PAYG';
        //objIncomeandexpense.Applicant__c = objApplicant.Id;
        objIncomeandexpense.Asset_And_Liability__c = objAssetLiab.Id;
        insert objIncomeandexpense;
        
        Asset_And_Liability__c objAssetLiabs=new Asset_And_Liability__c();
        objAssetLiabs.Clearing_From_This_Loan__c=true;
        objAssetLiabs.name='Liability';
        objAssetLiabs.Opportunity__c=objOpportunity .id;
        objAssetLiabs.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
        objAssetLiabs.Account__c = objAccount.Id;
        objAssetLiabs.Repayments__c=09876;
        objAssetLiabs.Current_Balance__c=99;
        objAssetLiabs.Limit__c=55;
        objAssetLiabs.Repayment_Frequency__c='Weekly';
        insert objAssetLiabs;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
        */
    }
    
    static testMethod void validateLenditest()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        objAssetLiab.Limit__c=59;
        update objAssetLiab;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj = new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
    
    static testMethod void validateLenditest1()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Asset Real Estate';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.State__c='NSW';
        objAssetLiab.To_Be_Purchased__c=false;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
        mapobj1.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj1);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj1);
        Test.stopTest();
    }
    
    static testMethod void validateLenditest2()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Funding_Position__c=objFundingpos.id;
        fundingobj.Detail_Type__c='Transfer Fee';
        insert fundingobj;

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Asset Real Estate';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c =null;
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.State__c='NSW';
        objAssetLiab.To_Be_Purchased__c=false;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
        mapobj1.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj1);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj1);
        Test.stopTest();
    }
    
    static testMethod void validateLenditest3()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=false;
        objAssetLiab.name='Liability Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        insert objAssetLiab;
        Test.stopTest();
    }
         
    static testMethod void validateLenditest4()
    {
        LoadDatatest();
        Test.startTest();
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Repayments__c=33;
        objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);
        objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.Repayments__c=37;
        objAssetLiab.Current_Balance__c=987;

        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj; 
        update objAssetLiab;
        Test.stopTest();
    }
        
     static testMethod void validateLenditest5()
    {
        LoadDatatest();
        Test.startTest();
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=false;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        objAssetLiab.recordtypeid = Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();  
        objAssetLiab=WLCommonTrackerClass.createAssetandLiablility(objAssetLiab,objAccount);

        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos;   
        Test.stopTest();           
    }
    
    static testMethod void validateLenditest6()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Asset Real Estate';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.State__c='NSW';
        objAssetLiab.To_Be_Purchased__c=false;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        Map<Id,Funding_Position__c> mapobj1=new Map<Id,Funding_Position__c> ();
        mapobj1.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj1);
        obj.insertAssetEstateSingleRecords(objAssetLiab,mapobj1,66);
        Test.stopTest();
    }
        
    static testMethod void validateLenditest7()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Monthly';
        insert objAssetLiab;
        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
        
    static testMethod void validateLenditest7a()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Anually';
        insert objAssetLiab;
        
        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
        
    static testMethod void validateLenditest7b()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liabilities Mortgage Loan';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Liability Mortgage Loan').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Fortnightly';
        insert objAssetLiab;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
            
    static testMethod void validateLenditest8()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
        
    static testMethod void validateLenditest8a()
    {
        LoadDatatest();
        Test.startTest();
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 

        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOpportunity.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Used_as_Security__c = true;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.To_Be_Purchased__c=true; 
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
        
    static testMethod void validateLenditest8b()
    {
        LoadDatatest();
        Test.startTest();
        Opportunity objOppo = new opportunity();
        objOppo.AccountId =objUser.AccountId ;
        objOppo.recordtypeid= Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Lendi').getRecordTypeId();
        objOppo.name = 'test';
        objOppo.Stagename = 'Application Taken';
        objOppo.CloseDate = System.today();
        objOppo.acfAsset_House_Worth__c = 200000;
        insert objOppo;
        
        objFundingpos=new Funding_Position__c ();
        objFundingpos.Account__c=objAccount.id;
        objFundingPos.Opportunity__c = objOpportunity.id;
        insert objFundingpos; 
        
        objAssetLiab=new Asset_And_Liability__c();
        objAssetLiab.Clearing_From_This_Loan__c=true;
        objAssetLiab.name='Liability';
        objAssetLiab.Opportunity__c=objOppo.id;
        objAssetLiab.recordtypeid= Schema.SObjectType.Asset_And_Liability__c .getRecordTypeInfosByName().get('Asset Real Estate').getRecordTypeId();    
        objAssetLiab.Account__c = objAccount.Id;
        objAssetLiab.Value__c = 100000;
        objAssetLiab.Primary_Purpose__c ='Owner Occupied';
        objAssetLiab.Repayments__c=09876;
        objAssetLiab.Current_Balance__c=99;
        objAssetLiab.Limit__c=55;
        objAssetLiab.To_Be_Purchased__c=true; 
        objAssetLiab.Repayment_Frequency__c='Weekly';
        insert objAssetLiab;
        
        Id IncomeRecordTypeId = Schema.SObjectType.Income_And_Expense__c.getRecordTypeInfosByName().get('Expense').getRecordTypeId();
        objIncomeandexpense = new Income_And_Expense__c();
        objIncomeandexpense.recordTypeId = IncomeRecordTypeId;
        objIncomeandexpense.Amount__c = 45;
        objIncomeandexpense.Category__c = 'Full Time - PAYG';
        objIncomeandexpense.Applicant__c = objApplicant.Id;
        objIncomeandexpense.Asset_And_Liability__c = objAssetLiab.Id;
        insert objIncomeandexpense;
        
        Funding_Position_Detail__c fundingobj=new Funding_Position_Detail__c();
        fundingobj.name='test';
        fundingobj.Detail_Type__c='Potential Accrued Interest';
        fundingobj.Asset_And_Liability__c=objAssetLiab.id;
        fundingobj.Amount__c=67;
        fundingobj.Funding_Position__c=objFundingpos.id;
        insert fundingobj;

        Map<Id,Funding_Position__c> mapobj=new Map<Id,Funding_Position__c> ();
        mapobj.put(objAssetLiab.Account__c ,objFundingpos);

        AssetAndLiabilityTriggerHandler obj=new AssetAndLiabilityTriggerHandler();
        obj.insertFPLiabilityOtherRecords(objAssetLiab,mapobj);
        obj.insertFPAssetEstateRecords(objAssetLiab,mapobj);
        Test.stopTest();
    }
    
    static void LoadData()
    {
        ACFSwitch__c acfswitch = new ACFSwitch__c();
        acfswitch.Asset_And_Liability_Switch__c = true;
        insert acfswitch;
        
        CoreLogic__c objcore=new CoreLogic__c();
        objcore.name='CoreLogic';
        objcore.UserName__c='test';
        objcore.password__c='AusCred4321';
        objcore.EndPoint__c='https://access-api.corelogic.asia';
        objcore.AvmEndpoint__c='test';
        objcore.ClientID__c='test';
        objcore.ClientSecret__c='test';
        objcore.TokenEndPoint__c='test';
        objcore.SearchApiEndPoint__c='test';
        insert objcore;

        objState=new State__c();
        objState.name='test';
        insert objState;

        objAccount1=new account();
        objAccount1=WLCommonTrackerClass.createAccount(objAccount1);

        objLead=new Lead();
        objLead.acf_partner_account__c=objAccount1.id;
        objLead.acfWhat_is_your_postcode__c='testinggg';
        objLead=WLCommonTrackerClass.createLead(objLead);

        objAccount=new account();
        objAccount=WLCommonTrackerClass.createAccount(objAccount);

        objContact=new contact();
        objContact=WLCommonTrackerClass.createContact(objContact,objAccount);

        objUser = new User();
        objuser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);

        objOpportunity = new Opportunity();
        objOpportunity.acfLegal_Fees__c=88;
        objOpportunity.clickEstablishment_Fee__c=99;
        objOpportunity.clickMortgage_Risk_Fee__c=888;
        objOpportunity = WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);
        
        objApplicant = new click_Applicant__c();
        objApplicant = WLCommonTrackerClass.createApplicant(objApplicant,objAccount,objOpportunity);
        
        objPro=new product2();
        objPro=WLCommonTrackerClass.createProduct(objPro);

        pbEntry = new PriceBookEntry();
        pbEntry.UnitPrice = 300;
        pbEntry.PriceBook2Id = Test.getStandardPricebookId();
        pbEntry.Product2Id = objPro.Id;
        pbEntry.IsActive = true;
        insert pbEntry ;

        oppLine = new OpportunityLineItem();
        oppLine.pricebookentryid=pbEntry.Id;
        oppLine.TotalPrice=2000;
        oppLine.Quantity = 2;
        oppLine.lender__c='test';
        oppLine.OpportunityID = objOpportunity.Id;
        insert oppLine;

    }
    
    static void LoadDatatest()
    {
        ACFSwitch__c acfswitch = new ACFSwitch__c();
        acfswitch.Asset_And_Liability_Switch__c = true;
        insert acfswitch;
        
        CoreLogic__c objcore=new CoreLogic__c();
        objcore.name='CoreLogic';
        objcore.UserName__c='test';
        objcore.password__c='AusCred4321';
        objcore.EndPoint__c='https://access-api.corelogic.asia';
        objcore.AvmEndpoint__c='test';
        objcore.ClientID__c='test';
        objcore.ClientSecret__c='test';
        objcore.TokenEndPoint__c='test';
        objcore.SearchApiEndPoint__c='test';
        insert objcore;

        objState=new State__c();
        objState.name='test';
        insert objState;

        objAccount1=new account();
        objAccount1=WLCommonTrackerClass.createAccount(objAccount1);

        objLead=new Lead();
        objLead.acf_partner_account__c=objAccount1.id;
        objLead.acfWhat_is_your_postcode__c='testinggg';
        objLead=WLCommonTrackerClass.createLead(objLead);

        objAccount=new account();
        objAccount.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Lendi').getRecordTypeId();
        objAccount=WLCommonTrackerClass.createAccount(objAccount);

        objContact=new contact();
        objContact=WLCommonTrackerClass.createContact(objContact,objAccount);

        objUser = new User();
        objuser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objAccount.id);

        objOpportunity = new Opportunity();
        objOpportunity.acfLegal_Fees__c=88;
        objOpportunity.clickEstablishment_Fee__c=99;
        objOpportunity.clickMortgage_Risk_Fee__c=888;
        objOpportunity = WLCommonTrackerClass.createOpportunity1(objOpportunity,objAccount);
        objOpportunity.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Lendi').getRecordTypeId();
        update objOpportunity;
        objApplicant = new click_Applicant__c();
        objApplicant = WLCommonTrackerClass.createApplicant(objApplicant,objAccount,objOpportunity);
        
        objPro=new product2();
        objPro=WLCommonTrackerClass.createProduct(objPro);

        pbEntry = new PriceBookEntry();
        pbEntry.UnitPrice = 300;
        pbEntry.PriceBook2Id = Test.getStandardPricebookId();
        pbEntry.Product2Id = objPro.Id;
        pbEntry.IsActive = true;
        insert pbEntry ;

        oppLine = new OpportunityLineItem();
        oppLine.pricebookentryid=pbEntry.Id;
        oppLine.TotalPrice=2000;
        oppLine.Quantity = 2;
        oppLine.lender__c='test';
        oppLine.OpportunityID = objOpportunity.Id;
        insert oppLine;
    }
}