src/objects/Asset_And_Liability__c.object
<CustomObject>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Position__c.object
<CustomObject>
    <label>Funding Position</label>
    <nameField>
        <displayFormat>A-{000}</displayFormat>
        <label>Funding Position Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Positions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Funding_Position_Detail__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Asset_And_Liability__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset And Liability</label>
        <referenceTo>Asset_And_Liability__c</referenceTo>
        <relationshipLabel>Funding Position Details</relationshipLabel>
        <relationshipName>Funding_Position_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Debt</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fee</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Detail_Type__c</fullName>
        <label>Detail Type</label>
        <picklist>
            <picklistValues>
                <fullName>Home Loan to Repay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Debts to Repay</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Potential Accrued Interest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Stamp Duty</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transfer Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Registration Fee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharge Costs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchase Price</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Funding_Position__c</fullName>
        <label>Funding Position</label>
        <referenceTo>Funding_Position__c</referenceTo>
        <relationshipLabel>Funding Position Details</relationshipLabel>
        <relationshipName>Funding_Position_Details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Funding Position Detail</label>
    <nameField>
        <label>Funding Position Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Funding Position Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ProfilesToOverwrite__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <label>ProfilesToOverwrite</label>
</CustomObject>

src/classes/FundingPositionDeatilTriggerHandler.cls
public with sharing class FundingPositionDeatilTriggerHandler extends TriggerHandler{
    public override void beforeUpdate() { 
        allowListedUsers('Update');
    }
    
    public override void beforeInsert() { 
        allowListedUsers('Insert');
    }
    
    public void allowListedUsers(String Event){
        Set<String> profileSet = new Set<String>();
        string NAME = 'Name';
        string AMOUNT = 'Amount__c';
        string ASSETLIABILITY = 'Asset_And_Liability__c';
        string CATEGORY = 'Category__c';
        string DETAILTYPE = 'Detail_Type__c';
        string FUNDINGPOSITION = 'Funding_Position__c';
        
        List<ProfilesToOverwrite__c> profilesList = ProfilesToOverwrite__c.getall().values(); 
        List<Profile> PROFILE = [SELECT Id, Name FROM Profile WHERE Id=:userinfo.getProfileId() LIMIT 1];
        String currUserProfile = PROFILE[0].Name;
        system.debug('##curr'+profilesList );
        system.debug('##currUser'+currUserProfile);
       
        if(profilesList.size() > 0){
            for(ProfilesToOverwrite__c pList:profilesList){
                system.debug('###pList'+pList);
                profileSet.add(pList.Name);
            }
            Map<String, Schema.SObjectField> schemaFieldMap = Schema.SObjectType.Funding_Position_Detail__c .fields.getMap();
            if(!profileSet.contains(currUserProfile)){
                 for(Funding_Position_Detail__c fDetTrig:(List<Funding_Position_Detail__c >)trigger.new){ 
                      if(Event == 'Update'){
                          fDetTrig.Name = (String)trigger.oldMap.get(fDetTrig.id).get(Name);
                          fDetTrig.Amount__c = (Decimal)trigger.oldMap.get(fDetTrig.id).get(AMOUNT);
                          fDetTrig.Asset_And_Liability__c = (Id)trigger.oldMap.get(fDetTrig.id).get(ASSETLIABILITY);
                          fDetTrig.Category__c = (String)trigger.oldMap.get(fDetTrig.id).get(CATEGORY);
                          fDetTrig.Detail_Type__c = (String)trigger.oldMap.get(fDetTrig.id).get(DETAILTYPE);
                          //fDetTrig.Funding_Position__c = (Id)trigger.oldMap.get(fDetTrig.id).get(FUNDINGPOSITION);
                      }
                 }
            }
        }
    }
}