src/objects/Asset_And_Liability__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Asset_And_Liabilities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Asset And Liability</label>
    <nameField>
        <label>Asset And Liabilities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Asset And Liabilities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AssetAndLiabilitySelector.cls
public with sharing class AssetAndLiabilitySelector extends SObjectSelector{
	public AssetAndLiabilitySelector() {
		super('Asset_And_Liability__c', null, null);
	}

	public AssetAndLiabilitySelector(Set<String> specFields, Set<String> excludeFields) {
		super('Asset_And_Liability__c', specFields, excludeFields);
	}

	public List<Asset_And_Liability__c> getById(List<Id> ids) {
		return (List<Asset_And_Liability__c>) super.selectByIds(ids);
	}

	public Asset_And_Liability__c getById(Id rid) {
		return (Asset_And_Liability__c) super.selectByIds(new List<Id>{rid})[0];
	}

	public List<Asset_And_Liability__c> getByOpportunit(Opportunity oppo) {
		return (List<Asset_And_Liability__c>) super.selectByOpenCondition('WHERE Opportunity__c = \'' + oppo.id + '\'');
	}
}