src/objects/AsyncRequest__c.object
<CustomObject>
    <description>This object is for recording Asynchronous calls, which can use with batch to serialise process.</description>
    <fields>
        <fullName>Failed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Error Recovery</description>
        <label>Failed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Define the type of Async Job</description>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNREQ{YYYY}-{MM}-{DD}--{0}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AsyncRequestSelector.cls
public with sharing class AsyncRequestSelector extends SObjectSelector{
	public AsyncRequestSelector() {
		super('AsyncRequest__c', null, null);
	}

	public List<AsyncRequest__c> getById(List<Id> ids) {
		return (List<AsyncRequest__c>) super.selectByIds(ids);
	}

	public List<AsyncRequest__c> getFailedRequests(String type) {
		return (List<AsyncRequest__c>) super.selectByOpenCondition('WHERE failed__c = true AND type__c = \'' + type + '\'');
	}

	public List<AsyncRequest__c> getSyncBackRequests() {
		return (List<AsyncRequest__c>) super.selectByOpenCondition('WHERE type__c = \'' + AsyncRequestType.MERCURY_TO_SF + '\' AND failed__c = false');
	}

	public List<AsyncRequest__c> getPendingRequests(AsyncRequestType type) {
		return (List<AsyncRequest__c>) super.selectByOpenCondition('WHERE failed__c = false AND type__c = \'' + type + '\'');
	}
}