src/objects/AsyncRequest__c.object
<CustomObject>
    <description>This object is for recording Asynchronous calls, which can use with batch to serialise process.</description>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNREQ{YYYY}-{MM}-{DD}--{0}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/MercurySettings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>RecoverSyncFailure__c</fullName>
        <defaultValue>false</defaultValue>
        <description>this switch will enable MercurySyncRecoveryScheduler to run hourly, every time restart MercurySyncRecoveryScheduler should run: System.schedule(&apos;Mercury Recovery&apos;, &apos;0 0 * * * ?&apos;, new MercurySyncRecoveryScheduler() );</description>
        <inlineHelpText>enable MercurySyncRecoveryScheduler to run hourly</inlineHelpText>
        <label>Recover Sync Failure</label>
        <type>Checkbox</type>
    </fields>
    <label>Mercury Settings</label>
</CustomObject>

src/classes/MercurySyncRecoveryScheduler.cls
public with sharing class MercurySyncRecoveryScheduler implements Schedulable {

	public void execute(SchedulableContext ctx) {
		if(!MercurySettings__c.getOrgDefaults().RecoverSyncFailure__c) return;
		AsyncRequestSelector ars = new AsyncRequestSelector();
		List<AsyncRequest__c> reqs = ars.getFailedRequests('sync to mercury');
		if(reqs.size() > 0) MercuryService.futureSyncWithMercury(reqs[0].id);
	}

}