src/objects/AsyncRequest__c.object
<CustomObject>
    <description>This object is for recording Asynchronous calls, which can use with batch to serialise process.</description>
    <fields>
        <fullName>Params__c</fullName>
        <description>Define the parameters need to run the Async Request</description>
        <label>Params</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Define the type of Async Job</description>
        <label>Type</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AsyncRequest</label>
    <nameField>
        <displayFormat>ASYNREQ{YYYY}-{MM}-{DD}--{0}</displayFormat>
        <label>AsyncRequest Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AsyncRequests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestAsyncRequestService.cls
@isTest
public with sharing class TestAsyncRequestService {

	private static testMethod void testAddSyncBackRequest() {
		MercuryModel.LoanResponse lr = new MercuryModel.LoanResponse();
		lr.loans = new List<MercuryModel.loan>();
		for(Integer i = 0; i < 10; i++) {
			MercuryModel.Loan l = new MercuryModel.Loan();
			l.uniqueId = '' + i;
			lr.loans.add(l);
		}

		System.debug(lr.idList);
		AsyncRequestService.addSyncBackRequest('Opportunity', new set<String>(lr.idList));
		AsyncRequestSelector ars = new AsyncRequestSelector();
		List<AsyncRequest__c> res = ars.getSyncBackRequests();
		System.assertEquals(10, res.size());
		Integer i = 0;
		for(AsyncRequest__c ar : res) {
			System.debug(ar);

			System.assertEquals('' + AsyncRequestType.MERCURY_TO_SF, ar.type__c);
			System.assertEquals('' + i, ((Map<String, Object>) JSON.deserializeUntyped(ar.params__c)).get('uniqueId'));
			i++;
		}
	}

}