src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Counter__c.object
<CustomObject>
    <fields>
        <fullName>Broker__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Broker</label>
        <referenceTo>Broker__c</referenceTo>
        <relationshipLabel>Counters</relationshipLabel>
        <relationshipName>Counters</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Counter</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Counter Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Counters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/SaasFocus_CounterACFFaceBroker.cls
// ----------------------------------------------------------------------------------
// This class tests business logic for CounterACFFaceBroker
// Version#        Date             Author              Description
// ----------------------------------------------------------------------------------
//   1.0       15-April-2015      Amit Kumar Sharma         Initial Version
// ----------------------------------------------------------------------------------
// ----------------------------------------------------------------------------------
// Notes: 
// ----------------------------------------------------------------------------------
// Test coverage for CounterACFFaceBroker:  100%

public class SaasFocus_CounterACFFaceBroker
{
//picks type of channel from picklist and makes the counter zero monthly
public void count()
{
    
    list<Counter__c> lstCounter=[select Count__c, Broker__r.Channel__c from Counter__c where Broker__r.Channel__c = 'Employee' or Broker__r.Channel__c = 'Partner'];
   
    for(Counter__c cc: lstCounter)
    {
         cc.Count__c =0;
    }
 update lstCounter;
}
}