src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>Channel__c</fullName>
        <label>Channel</label>
        <picklist>
            <picklistValues>
                <fullName>Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Phone Broker</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Compensatory_Appointment__c</fullName>
        <label>Compensatory Appointment</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <label>MobilePhone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Market__c</fullName>
        <label>Primary Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <fields>
        <fullName>Sydney_Timezone_Offset__c</fullName>
        <description>Adjustment of timezone from Sydney</description>
        <label>Sydney Timezone Offset</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SaasFocusCounterACFPhoneBroker_Tracker.cls
@istest
public class SaasFocusCounterACFPhoneBroker_Tracker {
  Public Static testmethod void testmymethod()
    {
        Market__c market_obj=new Market__c ();
        market_obj.Name='australia';
        market_obj.Sydney_Timezone_Offset__c=10;
        insert market_obj;
        
    Broker__c broker_obj=new Broker__c ();
        broker_obj.Compensatory_Appointment__c =null;
        broker_obj.Name='VT';
        broker_obj.Email__c='vinod.tiw@fb.com';
        broker_obj.MobilePhone__c='9719764989';//
        broker_obj.Street_Address__c='ABC';
        broker_obj.City__c='dehradun';
        broker_obj.Channel__c='Phone Broker';
        broker_obj.Primary_Market__c=market_obj.id;
        insert broker_obj;
        
        SaasFocus_CounterACFPhoneBroker obj= new SaasFocus_CounterACFPhoneBroker();
        obj.count();
    }
}