src/objects/Broker__c.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <required>true</required>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MobilePhone__c</fullName>
        <label>MobilePhone</label>
        <required>true</required>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Primary_Market__c</fullName>
        <label>Primary Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Brokers</relationshipLabel>
        <relationshipName>Brokers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Street_Address__c</fullName>
        <label>Street Address</label>
        <length>128</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Broker</label>
    <nameField>
        <label>Broker Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Brokers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Google_API_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Access_Token_Time_Stamp__c</fullName>
        <label>Access Token Time Stamp</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Client_Email_ID__c</fullName>
        <label>Client Email ID</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Client_ID__c</fullName>
        <label>Client ID</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Google_Calender_ID__c</fullName>
        <label>Google Calender ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Google API Setting</label>
</CustomObject>

src/objects/Market__c.object
<CustomObject>
    <label>Market</label>
    <nameField>
        <label>Market Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Markets</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Saasfocus_GoogleCalenderHelper_Tracker.cls
@isTest(SeeAllData=true)
public class Saasfocus_GoogleCalenderHelper_Tracker {

  static testmethod void TestSaasfocus_GoogleSyncEvent() {
    Saasfocus_GoogleCalenderHelper obj = new Saasfocus_GoogleCalenderHelper();

    Market__c ok= new Market__c();
    ok.Name='Amit';
    insert ok;
    Broker__c broker_obj= new Broker__c();
    broker_obj.Name='kripa';
    broker_obj.Email__c='testuser1@tpoint.com.au';
    broker_obj.MobilePhone__c='9719764989';
    broker_obj.Street_Address__c='ABC';
    broker_obj.City__c='dehradun';
    broker_obj.Primary_Market__c=ok.id;
    insert broker_obj;
    Event ev=new Event();
    ev.StartDateTime=Datetime.now();
    ev.EndDateTime=Datetime.now().addhours(2);
    ev.Subject='asadg';
    ev.Location='fhgj';
    ev.Description='gfhf';
    ev.Whatid = broker_obj.id;
    ev.Google_Event_ID__c='rsen87vvo231f9b04592bsl9ic~testuser1@tpoint.com.au';

    insert ev;
    List<String> lstApp = new List<String>();
    lstApp.add((String)ev.id);
    Google_API_Setting__c  obj1 =  new Google_API_Setting__c();
    obj1.Name='Google_Setting';
    obj1.Access_Token_Time_Stamp__c= DateTime.now().addDays(-2);
    obj1.Google_Calender_ID__c='kripa@getmaxx.in';
    obj1.Client_Email_ID__c='762657576047-4gg9618bagvckjbrk4t0ju5lej191ai1@developer.gserviceaccount.com';
    obj1.Client_ID__c='762657576047-4gg9618bagvckjbrk4t0ju5lej191ai1@developer.gserviceaccount.com';

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());
    GoogleCalendarService.insertGoogleEvent(lstApp);
    Test.stopTest();

    Datetime dt= Datetime.now();
  }

  static testmethod void TestSaasfocus_GoogleSyncEvent1() {
    Saasfocus_Global.GoogleSyncProces=True;
    Saasfocus_GoogleCalenderHelper obj = new Saasfocus_GoogleCalenderHelper();
    Market__c ok= new Market__c();
    ok.Name='Amit';
    insert ok;
    Broker__c broker_obj= new Broker__c();
    broker_obj.Name='kripa';
    broker_obj.Email__c='testuser1@tpoint.com.au';
    broker_obj.MobilePhone__c='9719764989';
    broker_obj.Street_Address__c='ABC';
    broker_obj.City__c='dehradun';
    broker_obj.Primary_Market__c=ok.id;
    insert broker_obj;
    Event ev=new Event();
    ev.StartDateTime=Datetime.now();
    ev.EndDateTime=Datetime.now().addhours(2);
    ev.Subject='asadg';
    ev.Location='fhgj';
    ev.Description='gfhf';
    ev.whatid=broker_obj.id;

    insert ev;

    List<String> lstApp = new List<String>();
    lstApp.add((String)ev.id);
    Google_API_Setting__c  obj1 =  new Google_API_Setting__c();
    obj1.Name='Google_Setting';
    obj1.Access_Token_Time_Stamp__c= DateTime.now().addDays(-2);
    obj1.Google_Calender_ID__c='kripa@getmaxx.in';
    obj1.Client_Email_ID__c='762657576047-4gg9618bagvckjbrk4t0ju5lej191ai1@developer.gserviceaccount.com';
    obj1.Client_ID__c='762657576047-4gg9618bagvckjbrk4t0ju5lej191ai1@developer.gserviceaccount.com';

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

    GoogleCalendarService.insertGoogleEvent(lstApp);
    Test.stopTest();
  }

  static testmethod void TestSaasfocus_GoogleSyncEvent2() {
    Saasfocus_Global.GoogleSyncProces=True;
    Saasfocus_GoogleCalenderHelper obj = new Saasfocus_GoogleCalenderHelper();
    Market__c ok= new Market__c();
    ok.Name='Amit';
    insert ok;
    Broker__c broker_obj= new Broker__c();
    broker_obj.Name='kripa';
    broker_obj.Email__c='testuser1@tpoint.com.au';
    broker_obj.MobilePhone__c='9719764989';
    broker_obj.Street_Address__c='ABC';
    broker_obj.City__c='dehradun';
    broker_obj.Primary_Market__c=ok.id;
    insert broker_obj;
    Event ev=new Event();
    ev.StartDateTime=Datetime.now();
    ev.EndDateTime=Datetime.now().addhours(2);
    ev.Subject='asadg';
    ev.Location='fhgj';
    ev.Description='gfhf';
    ev.whatid=broker_obj.id;
    ev.Google_Event_ID__c='rsen87vvo231f9b04592bsl9ic~testuser1@tpoint.com.au';

    insert ev;

    List<String> lstApp = new List<String>();
    lstApp.add((String)ev.id);
    Google_API_Setting__c  obj1 =  new Google_API_Setting__c();
    obj1.Name='Google_Setting';
    obj1.Access_Token_Time_Stamp__c= DateTime.now().addDays(-2);
    obj1.Google_Calender_ID__c='kripa@getmaxx.in';
    obj1.Client_Email_ID__c='762657576047-4gg9618bagvckjbrk4t0ju5lej191ai1@developer.gserviceaccount.com';
    obj1.Client_ID__c='762657576047-4gg9618bagvckjbrk4t0ju5lej191ai1@developer.gserviceaccount.com';

    Test.startTest();
    Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator());

    GoogleCalendarService.insertGoogleEvent(lstApp);
    Test.stopTest();
  }

}