src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Applicant_Email__c</fullName>
        <label>Applicant Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Applicant_Phone__c</fullName>
        <label>Applicant Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Community_Setup__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Community Setup</label>
        <referenceTo>Click_Community_Setup__c</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Applicant_Name__c</fullName>
        <label>Applicant Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clickOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>click_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>click_Applicant_Number__c</fullName>
        <label>Applicant Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Click_Community_Setup__c.object
<CustomObject>
    <fields>
        <fullName>Click_Page_Prefix__c</fullName>
        <label>Page Prefix</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_URL__c</fullName>
        <label>Community URL</label>
        <type>Url</type>
    </fields>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Jumio Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/clsSendEConsent.cls
global class clsSendEConsent
 {
 
   webservice static void SendEonsent(String EconsentID)
   {

            if(EconsentID != null && EconsentID != '')
            {
                List<Required_Document__c> lstReqDoc = [Select EconsentID__C , Type__c ,Bankid__c ,Id,Click_Applicant__c,
                Click_Applicant__r.clickOpportunity__r.Community_Setup__c,
                acfStatus__c From Required_Document__c where EconsentID__C =:EconsentID];
                
                if(!lstReqDoc.isEmpty() && lstReqDoc[0].Click_Applicant__r.clickOpportunity__r.Community_Setup__c  != null)
                {

                    if(lstReqDoc[0].Bankid__C != null   &&   lstReqDoc[0].Type__c != 'General'   ){

                        List<acf_Bank_Template__c>  lstBank = [Select Id ,Body__c ,Click_Loans_Bank_Detail__c from acf_Bank_Template__c

                        where Click_Loans_Bank_Detail__c = :   lstReqDoc[0].Bankid__C  ] ;

                        if(  lstReqDoc != null  && lstBank.size() > 0  && lstReqDoc[0].EconsentID__C != null  )
                        SendEmail(lstBank[0].ID ,lstReqDoc[0].Click_Applicant__c  , lstReqDoc[0].Id  ,lstReqDoc[0].EconsentID__C   , lstReqDoc[0].Click_Applicant__r.clickOpportunity__r.Community_Setup__c  ); 

                    }
                    else{
                        If(lstReqDoc[0].Type__c == 'General'   && lstReqDoc[0].Click_Applicant__c  != null  
                        && lstReqDoc[0].Click_Applicant__r.clickOpportunity__r.Community_Setup__c != null ){
                        sendEconsentEmailSMS(lstReqDoc[0].Click_Applicant__c  ,  lstReqDoc[0].Click_Applicant__r.clickOpportunity__r.Community_Setup__c);
                        }
                    }
                }
            } 
     }   
        
   
   
    global static  void SendEmail(ID BankId  , Id applicantId   , ID reqDocID , ID econID  ,ID  objCommunityID)
   {
    
                List<Click_Community_Setup__c> objCommunity = [Select  Name ,Click_URL__c , Click_Page_Prefix__c  from   Click_Community_Setup__c where id = : objCommunityID ];
                list<click_Applicant__c> lstApplicants = [select id,acf_Applicant_Name__c,click_Account__c,
                click_Applicant_Number__c,Applicant_Phone__c,Applicant_Email__c from click_Applicant__c where id=:applicantId];
                try
                {
                    if(lstApplicants != null && !lstApplicants.isEmpty()  && objCommunity.size() > 0 )
                    {
                        List<EmailTemplate> templateId =new List<EmailTemplate>();  
                        templateId = [select id,subject,body, name,HtmlValue from EmailTemplate where DeveloperName = 'ProductEConsent' AND isActive=true];
                        for(click_Applicant__c app:lstApplicants ){
                             system.debug('### Entered Mail Method1');
                              system.debug('### Entered Mail Method1'+app.Applicant_Email__c);
                            string econsentId='';
                            string encodedDate=string.valueOf(System.currentTimeMillis());
                            econsentId=encodedDate+'-'+applicantId+'-'+BankId+'-'+reqDocID+'-'+econID;
                                         
                            
                            Blob cryptoKey = Blob.valueOf('380db410e8b11fa9');                    
                            Blob data1 = Blob.valueOf(econsentId);
                            Blob encryptedValue  =Crypto.encryptWithManagedIV('AES128', cryptoKey, data1);
                            string Encryptdata=EncodingUtil.base64encode(encryptedValue);
                            string finalData= EncodingUtil.urlEncode(Encryptdata, 'UTF-8');
                            string body='';                            
                            body=templateId[0].HtmlValue;
                            body=body.replace('{!econsentid}',finalData);  
                            body = body.replace('{!Site.Label}',objCommunity[0].Name); 
                            body = body.replace('baseurl',objCommunity[0].Click_URL__c);
                            body=body.replace('{!Account.Name}',app.acf_Applicant_Name__c);
                            system.debug('###body'+body);
                            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                            String[] toaddress=new List<String>();
                            toaddress.add(app.Applicant_Email__c); 
                            system.debug('###'+toaddress);                   
                            mail.setToAddresses(toaddress);
                            mail.setSubject(templateId[0].Subject);
                            mail.setHtmlBody(body);
                            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
                            string mobileMessage = '';
                           if(objCommunity[0].Click_Page_Prefix__c == 'ACF'){
                             mobileMessage=Label.Applicant_Econsent_Message_Acf_for_product; 
                            }
                            else 
                            {
                                mobileMessage=Label.Applicant_E_consent_message_for_product;
                            } 
                            mobileMessage=mobileMessage.replace('{!econsentid}',finalData);             
                            mobileMessage=mobileMessage.replace('{!Account.Name}',app.acf_Applicant_Name__c);  
                           
                            System.debug('___________mobileMessage_____________'+mobileMessage);                            
                          acfCommon.SendSMSUsingFutureEconsent(app.acf_Applicant_Name__c,app.Applicant_Phone__c,mobileMessage ,true,objCommunity[0].Click_Page_Prefix__c);
                        }
                       
                    }
                   
                }
                catch(Exception Ex)
                      {
                          
                      } 
                
              
                     
       
   }
   
    global   Static  void sendEconsentEmailSMS(Id applicantId , ID  objCommunityID)
   {
    
            List<Click_Community_Setup__c> objCommunity = [Select  Name ,Click_URL__c , Click_Page_Prefix__c  from   
            Click_Community_Setup__c where id = : objCommunityID ];
            
               
           list<click_Applicant__c> lstApplicants = [select id,acf_Applicant_Name__c,click_Account__c,click_Applicant_Number__c,Applicant_Phone__c,Applicant_Email__c from 
            click_Applicant__c where id=:applicantId];
                try
                {
                    if(lstApplicants != null && !lstApplicants.isEmpty() &&  objCommunity != null  && objCommunity.size() > 0 )
                    {
                        List<EmailTemplate> templateId =new List<EmailTemplate>();  
                        templateId = [select id,subject,body, name,HtmlValue from EmailTemplate where DeveloperName = 'GenericEConsent' AND isActive=true];
                        for(click_Applicant__c app:lstApplicants ){
                             system.debug('### Entered Mail Method1');
                              system.debug('### Entered Mail Method1'+app.Applicant_Email__c);
                            string econsentId='';
                            string encodedDate=string.valueOf(System.currentTimeMillis());
                            econsentId=encodedDate+'-'+app.click_Account__c+'-'+app.click_Applicant_Number__c;
                                         
                            
                            Blob cryptoKey = Blob.valueOf('380db410e8b11fa9');                    
                            Blob data1 = Blob.valueOf(econsentId);
                            Blob encryptedValue  =Crypto.encryptWithManagedIV('AES128', cryptoKey, data1);
                            string Encryptdata=EncodingUtil.base64encode(encryptedValue);
                            string finalData= EncodingUtil.urlEncode(Encryptdata, 'UTF-8');
                            string body='';                            
                            body=templateId[0].HtmlValue;
                            body=body.replace('{!econsentid}',finalData);  
                            body = body.replace('{!Site.Label}',objCommunity[0].Name); 
                            body = body.replace('baseurl',objCommunity[0].Click_URL__c);
                            body=body.replace('{!Account.Name}',app.acf_Applicant_Name__c);
                            system.debug('###body'+body);
                            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                            String[] toaddress=new List<String>();
                            toaddress.add(app.Applicant_Email__c); 
                            system.debug('###'+toaddress);                   
                            mail.setToAddresses(toaddress);
                            mail.setSubject(templateId[0].Subject);
                            mail.setHtmlBody(body);
                            Messaging.sendEmail(new Messaging.SingleEmailMessage[]{mail});
                            string mobileMessage = '';
                           if(objCommunity[0].Click_Page_Prefix__c == 'ACF'){
                             mobileMessage=Label.Applicant_Econsent_Message_ACF; 
                            }
                            else 
                            {
                                mobileMessage=Label.Applicant_E_consent_message;
                            } 
                            mobileMessage=mobileMessage.replace('{!econsentid}',finalData);             
                            mobileMessage=mobileMessage.replace('{!Account.Name}',app.acf_Applicant_Name__c);              
                            acfCommon.SendSMSUsingFutureEconsent(app.acf_Applicant_Name__c,app.Applicant_Phone__c,mobileMessage,true,objCommunity[0].Click_Page_Prefix__c);
                        }
                       
                    }
                    
                }catch(Exception Ex)
                      {
                          
                      }       
            }  
   }