src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>click_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applicants</relationshipLabel>
        <relationshipName>Applicants</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>click_Applicant_Number__c</fullName>
        <label>Applicant Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Bank_Statement_Data__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Statement_Account_Number__c</fullName>
        <label>Bank Statement Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Required_Document_Id__c</fullName>
        <label>Required Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Statement_No__c</fullName>
        <label>Category Index No.</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_TransactionCount__c</fullName>
        <label>Transaction Count</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_UniqueId__c</fullName>
        <formula>TRIM(Click_Required_Document_Id__c + Bank_Statement_Account_Number__c + Click_Statement_No__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>UniqueId</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>click_monthAvg__c</fullName>
        <label>Month Avg</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bank Statement Category</label>
    <nameField>
        <label>Bank Statement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statement Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Bank_Statements_Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Statement_Account_Number__c</fullName>
        <label>Bank Statement Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Statement_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statement Category</label>
        <referenceTo>click_Bank_Statement_Data__c</referenceTo>
        <relationshipLabel>Bank Statement Sub Categories</relationshipLabel>
        <relationshipName>Bank_Statement_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Click_Required_Document_Id__c</fullName>
        <label>Required Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Statement_No__c</fullName>
        <label>Category Index No.</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_TransactionCount__c</fullName>
        <label>TransactionCount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>click_monthAvg__c</fullName>
        <label>Month Avg</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bank Statements Sub Category</label>
    <nameField>
        <label>Bank Statements Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statement Sub Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financials_Source__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Bank_Statements_Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statements Sub Category</label>
        <referenceTo>click_Bank_Statements_Sub_Category__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Click_Loans_Required_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Required Document</label>
        <referenceTo>Required_Document__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Income_And_Expense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Income And Expense</label>
        <referenceTo>Income_And_Expense__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM User Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner User Input</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financials Source</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant</label>
        <referenceTo>click_Applicant__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Bonus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Business Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dividends</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Family Allowance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Overtime</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rental</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Salary</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Credit Card</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Home Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Car Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personal Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rent Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Basic Living Expense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Education</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Insurance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Existing Interest Expenses</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Time - PAYG</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other Income</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Govt Benefits</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Liability Expenses</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Copy_From__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Master Record</label>
        <referenceTo>Income_And_Expense__c</referenceTo>
        <relationshipLabel>Income And Expenses</relationshipLabel>
        <relationshipName>Income_And_Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <recordTypes>
        <fullName>Expense</fullName>
        <active>true</active>
        <label>Expense</label>
    </recordTypes>
    <recordTypes>
        <fullName>Income</fullName>
        <active>true</active>
        <label>Income</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_partner_account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BankStatementSubCategoryTriggersHandler.cls
//-------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------
// Version#      Date                    Author                Description
// ------------------------------------- ------------------------------------------------------
// 1.0         25-03-2016              Ankit Singh          Initial Version
// -------------------------------------------------------------------------------------------
public class BankStatementSubCategoryTriggersHandler extends TriggerHandler
 {  
    public override void BeforeInsert() {
     //  updateClickBankStatementSubCategory(trigger.New);
     }
     
      public override void AfterInsert() {
        system.debug('test'+trigger.New); 
        createFinancialsSource(trigger.New);
     }
     
   /*------------------------------------------------------------------------------------------------------
     This Method is used to Link BankStatementCategory with BankStatementAccount Object.
     ------------------------------------------------------------------------------------------------------*/
     public void updateClickBankStatementSubCategory(list<click_Bank_Statements_Sub_Category__c> triggerNew)
    {
        Map<string,String> mapBnkStatementDataCategoryUniqueIdToId = new Map<string,string>();
        set<string> setOfUniqueId = new set<string>();
        if(triggerNew.size() >0)  
        {        
            for(click_Bank_Statements_Sub_Category__c objbankStatementSubCategory : triggerNew)
            {
                string strUniqueId = '';
                if(string.isNotEmpty(objbankStatementSubCategory.Click_Required_Document_Id__c)  
                    && string.isNotEmpty(objbankStatementSubCategory.Click_Statement_No__c)
                   && string.isNotEmpty(objbankStatementSubCategory.Bank_Statement_Account_Number__c))
                {
                    strUniqueId = objbankStatementSubCategory.Click_Required_Document_Id__c+objbankStatementSubCategory.Bank_Statement_Account_Number__c+objbankStatementSubCategory.Click_Statement_No__c;
                    strUniqueId = strUniqueId.trim();
                    setOfUniqueId.add(strUniqueId);    
                }
            } 
            system.debug('setOfUniqueId8************'+setOfUniqueId);   
        }
        list<click_Bank_Statement_Data__c> lstBankStatementData = new list<click_Bank_Statement_Data__c>();
        if(setOfUniqueId <> null && setOfUniqueId.size() > 0)
        {
                      
            lstBankStatementData = [select id,Bank_Statement_Account_Number__c,Click_Required_Document_Id__c,Click_Statement_No__c,
                                    Click_UniqueId__c from click_Bank_Statement_Data__c where Click_UniqueId__c IN:setOfUniqueId];
            system.debug('lstBankStatementData ************'+lstBankStatementData);
                                                                                      
        }
        
        if(lstBankStatementData <> null && lstBankStatementData .size() > 0)
        {
            for(click_Bank_Statement_Data__c objBankStateData : lstBankStatementData)
            {
                mapBnkStatementDataCategoryUniqueIdToId.put(objBankStateData.Click_UniqueId__c,objBankStateData.Id);
                system.debug('mapBnkStatementDataCategoryUniqueIdToId************'+mapBnkStatementDataCategoryUniqueIdToId);
            }
        }
        
        for(click_Bank_Statements_Sub_Category__c objbnkStateSubCategory : triggerNew)
        {
            if(string.isNotEmpty(objbnkStateSubCategory.Click_Required_Document_Id__c) && string.isNotEmpty(objbnkStateSubCategory.Click_Statement_No__c)
               && string.isNotEmpty(objbnkStateSubCategory.Bank_Statement_Account_Number__c)
               && mapBnkStatementDataCategoryUniqueIdToId.get(objbnkStateSubCategory.Click_Required_Document_Id__c+objbnkStateSubCategory.Bank_Statement_Account_Number__c+objbnkStateSubCategory.Click_Statement_No__c) != null)
            {
                objbnkStateSubCategory.Bank_Statement_Category__c = mapBnkStatementDataCategoryUniqueIdToId.get(objbnkStateSubCategory.Click_Required_Document_Id__c+objbnkStateSubCategory.Bank_Statement_Account_Number__c+objbnkStateSubCategory.Click_Statement_No__c);
                 system.debug('!@#$%^&************'+mapBnkStatementDataCategoryUniqueIdToId.get(objbnkStateSubCategory.Click_Required_Document_Id__c+objbnkStateSubCategory.Bank_Statement_Account_Number__c+objbnkStateSubCategory.Click_Statement_No__c));
            }
        }
    }
    
    
  /* -------------------------------------------------------------------------------
     This method is used to create Financial Source tagged with Income and Expense. 
     when Bank Statement subcategory object under Income Type Bank Statement category 
     is created.
     --------------------------------------------------------------------------------*/  
    public void createFinancialsSource(list<click_Bank_Statements_Sub_Category__c> lstTriggerNew)
    {
        if(lstTriggerNew.size() >0)  
        {   
            List<click_Bank_Statements_Sub_Category__c> lstBankStatesubCategory = [select id,Bank_Statement_Category__c,
                                                                                   Bank_Statement_Category__r.Name,Click_TransactionCount__c,
                                                                                   click_monthAvg__c,Click_Required_Document_Id__c from 
                                                                                   click_Bank_Statements_Sub_Category__c where id=:lstTriggerNew];
            system.debug('test'+lstTriggerNew);  
            map<id,id> mapBankstatementSubCategoryIdToReqDocId = new map<id,id>();   
            for(click_Bank_Statements_Sub_Category__c objbankStatementsubcategory : lstBankStatesubCategory)
            {
                if(objbankStatementsubcategory.Bank_Statement_Category__c != null && string.isNotEmpty(objbankStatementsubcategory.Bank_Statement_Category__r.Name) && objbankStatementsubcategory.Bank_Statement_Category__r.Name == 'Income'
                   && integer.valueof(objbankStatementsubcategory.Click_TransactionCount__c) > 0)
                {
                   
                    if(string.isNotEmpty(objbankStatementsubcategory.Click_Required_Document_Id__c))
                    {
                        mapBankstatementSubCategoryIdToReqDocId.put(objbankStatementsubcategory.id,Id.valueof(objbankStatementsubcategory.Click_Required_Document_Id__c));
                        system.debug('mapBankstatementSubCategoryIdToReqDocId********'+mapBankstatementSubCategoryIdToReqDocId);
                    }
                }
            } 
            
            map<id,id> mapReqDocIdToAccountId = new map<id,id>(); 
            if(mapBankstatementSubCategoryIdToReqDocId != null && mapBankstatementSubCategoryIdToReqDocId.size() > 0
               && mapBankstatementSubCategoryIdToReqDocId.keyset() != null && mapBankstatementSubCategoryIdToReqDocId.keyset().size() > 0
               && mapBankstatementSubCategoryIdToReqDocId.values() != null
               && mapBankstatementSubCategoryIdToReqDocId.values().size() > 0)  
            {
                 List<Required_Document__c> lstReqDoc = [select id,Lead__c,Lead__r.isconverted,Lead__r.acf_partner_account__c,acfOpportunity__c,
                                                         acfOpportunity__r.AccountId from Required_Document__c
                                                         where id=:mapBankstatementSubCategoryIdToReqDocId.values()];
                 system.debug('lstReqDoc ********'+lstReqDoc);                                        
                                                     
                 if(lstReqDoc != null && lstReqDoc.size() > 0)
                 {
                     for(Required_Document__c objReqDoc : lstReqDoc)
                     {
                         if(objReqDoc.Lead__r.isconverted == false)
                         {
                             system.debug('test111********'+objReqDoc.Lead__r.acf_partner_account__c); 
                             if(objReqDoc.Lead__r.acf_partner_account__c != null)
                                 mapReqDocIdToAccountId.put(objReqDoc.id,objReqDoc.Lead__r.acf_partner_account__c); 
                             system.debug('mapReqDocIdToAccountId********'+mapReqDocIdToAccountId); 
                         }
                         else
                         {
                             if(objReqDoc.acfOpportunity__r.AccountId != null)
                                 mapReqDocIdToAccountId.put(objReqDoc.id,objReqDoc.acfOpportunity__r.AccountId);
                             system.debug('mapReqDocIdToAccountId111111********'+mapReqDocIdToAccountId);     
                         }
                     }
                 }                                            
            }
            
            map<id,id> mapAccIdToApplicantId = new map<id,id>();
            map<id,id> mapApplicantIdToIncomeAndExpId = new map<id,id>();
            if(mapReqDocIdToAccountId != null && mapReqDocIdToAccountId.size() > 0 && mapReqDocIdToAccountId.keyset() != null 
               && mapReqDocIdToAccountId.keyset().size() > 0 && mapReqDocIdToAccountId.values() != null && mapReqDocIdToAccountId.values().size() > 0)
            {
                 List<click_Applicant__c> lstApplicant = [select id,click_Account__c,(select id,Category__c,CreatedDate,Recordtype.Name from Income_And_Expenses__r where
                                                          (Category__c = 'Full Time - PAYG'  OR Category__c = 'Self Employed')and Recordtype.Name IN ('Income') ORDER BY CreatedDate ASC Limit 1),
                                                          click_Applicant_Number__c from click_Applicant__c
                                                          where click_Account__c=:mapReqDocIdToAccountId.values() and click_Applicant_Number__c = '1'];
                 system.debug('lstApplicant ********'+lstApplicant);                                      
                 if(lstApplicant != null && lstApplicant.size() > 0)
                 {
                     for(click_Applicant__c objApplicant : lstApplicant)
                     {
                         if(objApplicant.click_Account__c != null)
                             mapAccIdToApplicantId.put(objApplicant.click_Account__c,objApplicant.id);
                         system.debug('mapAccIdToApplicantId********'+mapAccIdToApplicantId);    
                         if(objApplicant.Income_And_Expenses__r != null && objApplicant.Income_And_Expenses__r.size() > 0)
                             mapApplicantIdToIncomeAndExpId.put(objApplicant.id,objApplicant.Income_And_Expenses__r[0].id); 
                         system.debug('mapApplicantIdToIncomeAndExpId********'+mapApplicantIdToIncomeAndExpId);                 
                     }
                 } 
            } 
            List<Financials_Source__c> lstFinancialSource = new List<Financials_Source__c>();
            for(click_Bank_Statements_Sub_Category__c objbnkStatementSubCategory : lstBankStatesubCategory)
            {
                if(objbnkStatementSubCategory.Bank_Statement_Category__c != null && string.isNotEmpty(objbnkStatementSubCategory.Bank_Statement_Category__r.Name) && objbnkStatementSubCategory.Bank_Statement_Category__r.Name == 'Income'
                   && integer.valueof(objbnkStatementSubCategory.Click_TransactionCount__c) > 0)
                {
                    Financials_Source__c objFinancialSource = new Financials_Source__c();
                    objFinancialSource.Source__c = 'Bank Statements';
                    objFinancialSource.Bank_Statements_Sub_Category__c = objbnkStatementSubCategory.id;
                    if(string.isNotEmpty(objbnkStatementSubCategory.click_monthAvg__c))
                    {
                        Decimal decAmt = decimal.valueof(objbnkStatementSubCategory.click_monthAvg__c)*12;
                        objFinancialSource.Amount__c = decAmt;
                    }
                    if(string.isNotEmpty(objbnkStatementSubCategory.Click_Required_Document_Id__c))
                       objFinancialSource.Click_Loans_Required_Document__c = id.valueof(objbnkStatementSubCategory.Click_Required_Document_Id__c);
                    if(mapBankstatementSubCategoryIdToReqDocId != null && mapBankstatementSubCategoryIdToReqDocId.size() > 0
                       && mapBankstatementSubCategoryIdToReqDocId.get(objbnkStatementSubCategory.id) != null && mapReqDocIdToAccountId != null 
                       && mapReqDocIdToAccountId.size() > 0 && mapReqDocIdToAccountId.get(mapBankstatementSubCategoryIdToReqDocId.get(objbnkStatementSubCategory.id)) != null && mapAccIdToApplicantId != null && mapAccIdToApplicantId.size() > 0 && mapAccIdToApplicantId.get(mapReqDocIdToAccountId.get(mapBankstatementSubCategoryIdToReqDocId.get(objbnkStatementSubCategory.id))) != null
                       && mapApplicantIdToIncomeAndExpId != null && mapApplicantIdToIncomeAndExpId.size() > 0 && mapApplicantIdToIncomeAndExpId.get(mapAccIdToApplicantId.get(mapReqDocIdToAccountId.get(mapBankstatementSubCategoryIdToReqDocId.get(objbnkStatementSubCategory.id)))) != null)
                    {
                        objFinancialSource.Income_And_Expense__c =  mapApplicantIdToIncomeAndExpId.get(mapAccIdToApplicantId.get(mapReqDocIdToAccountId.get(mapBankstatementSubCategoryIdToReqDocId.get(objbnkStatementSubCategory.id))));
                    }
                    lstFinancialSource.add(objFinancialSource);
                }
            }  
            
            if(lstFinancialSource != null && lstFinancialSource.size() > 0)
            {
                insert lstFinancialSource;
            }
        }
    }
}