src/objects/Click_Community_Setup__c.object
<CustomObject>
    <label>Community Setup</label>
    <nameField>
        <label>Click Community Setup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Community Setup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Jumio_Credentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active_API_secret__c</fullName>
        <label>Active API secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_API_token__c</fullName>
        <label>Merchant API token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Jumio Credentials</label>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/acfJumioIntegration_brokerTracker.cls
@isTest
public class acfJumioIntegration_brokerTracker
{

        private static User objUser;
        private static Contact objContact;
        private static Account objAccount;
        private static Account objpersonAccount;
        private static Opportunity objOpp;
        private static Lead objLead;
        private static Id objid;
        private static Jumio_Credentials__c objJum;
        private static Required_Document__c objre;
        private static Document_Master__c objmas;
        private static Click_Community_Setup__c objclcmm;
        
        
        static testMethod void validate1()
       {
    
        LoadData();
         Apexpages.currentpage().getparameters().put('cid',objpersonAccount.Id);
         acfJumioIntegration_broker clsObj = new acfJumioIntegration_broker();
         
         acfJumioIntegration_broker.RootObject objWrapCls = new  acfJumioIntegration_broker.RootObject();
       objWrapCls .timestamp = 'test';
       objWrapCls .authorizationToken = 'test';
       objWrapCls .clientRedirectUrl = 'test';
       objWrapCls .jumioIdScanReference = 'test';
         
         Test.startTest();
       Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerators12());
     //  try
     //  {
       clsObj.CallToJumio();
    //   }
     //  catch(Exception e)
     //  {
       
      // }
       Test.stopTest();
         }
         
          static testMethod void validate2()
       {
    
        LoadData();
         Apexpages.currentpage().getparameters().put('cid',objpersonAccount.Id);
         acfJumioIntegration_broker clsObj = new acfJumioIntegration_broker();
          clsObj.redirectToNextPage();
        
         }
         
    private static void LoadData()
      {
        createLead();
        createAccount();
        createContact();
        createmasterdoc();
        createPersonAccount();
        createJumiocred();
        createclickCommunitySetup();
        createPortalUser();
        createCurrentLoggedInLeadId();
        createOpportunity();
        createrequireddoc();
      }
    
    static void createAccount()
    {
        objAccount = new Account();
        objAccount = WLCommonTrackerClass.createAccount(objAccount);
    }
    
    static void createLead()
    {
        objLead = new Lead();
        objLead = WLCommonTrackerClass.createLead(objLead);
    }
    
    static void createJumiocred()
    {
     objJum=new Jumio_Credentials__c();
     objJum.name='Credential';
     objJum.Merchant_API_token__c='test';
     objJum.Active_API_secret__c='test';
     objJum.EndPoint__c='test';
     insert objJum;
    
    }
    
    static void createclickCommunitySetup() 
    {
        objclcmm= new Click_Community_Setup__c();
        objclcmm= ClickCommon.getCommunitySetup('');
    }
    
     static void createCurrentLoggedInLeadId()
     {
     objid=ClickCommon.getCurrentLoggedInLeadId(objUser.Id);
     }
      
    static void createContact()
    {
        objContact = new Contact();
        objContact = WLCommonTrackerClass.createContact(objContact,objAccount);
    }
    
    static void createPersonAccount()
    {
        objpersonAccount= new Account();
        objpersonAccount=WLCommonTrackerClass.CreatePersonAccount('Fname','LName','strPhone','strLead12Email@gmail.com',objLead.Id);
    }
    static void createPortalUser()
    {
        objUser = new User();
        objUser.ContactId = objContact.id;
        objUser = WLCommonTrackerClass.CreatePortalUser(objpersonAccount.id);
    
    }
    
    static void createOpportunity()
    {
        objOpp= new Opportunity();
        objOpp.AccountId =objuser.AccountId;
        String recordtypeid =Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Click Refi').getRecordTypeId();
        objOpp.recordtypeid =recordtypeid;
        objOpp.name = 'test';
        objOpp.Stagename = 'Settlement';
        objOpp.CloseDate = System.today();
        objOpp=WLCommonTrackerClass.createOpportunity(objOpp,objUser);
    }
     static void createmasterdoc()
    {
        objmas= new Document_Master__c(); 
        objmas= WLCommonTrackerClass.createDocumentMaster(objmas);
    }
    
    static void createrequireddoc()
    {
        objre= new Required_Document__c();
        objre= WLCommonTrackerClass.createRequiredDocument(objre,objmas,objOpp);
    }

 }