src/objects/click_Bank_Statement_Data__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Statement_Account_Number__c</fullName>
        <label>Bank Statement Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Required_Document_Id__c</fullName>
        <label>Required Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Statement_No__c</fullName>
        <label>Category Index No.</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>click_Bank_Statements_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statements Account</label>
        <referenceTo>click_Bank_Statements_Account__c</referenceTo>
        <relationshipName>Bank_Statement_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>closingBalance__c</fullName>
        <label>Closing Balance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>openingBalance__c</fullName>
        <label>Opening Balance</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Bank Statement Category</label>
    <nameField>
        <label>Bank Statement Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statement Category</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Bank_Statements_Account__c.object
<CustomObject>
    <fields>
        <fullName>Account_Holder__c</fullName>
        <label>Account Holder</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Number__c</fullName>
        <label>Account Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Loans_Required_Document__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Click Loans Required Document</label>
        <referenceTo>Required_Document__c</referenceTo>
        <relationshipLabel>Bank Statements Accounts</relationshipLabel>
        <relationshipName>Bank_Statements_Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Statements Account</label>
    <nameField>
        <label>Bank Statements Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statements Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Bank_Statements_Sub_Category__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Statement_Account_Number__c</fullName>
        <label>Bank Statement Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Statement_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statement Category</label>
        <referenceTo>click_Bank_Statement_Data__c</referenceTo>
        <relationshipLabel>Bank Statement Sub Categories</relationshipLabel>
        <relationshipName>Bank_Statement_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Click_Bank_Statements_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statements Account</label>
        <referenceTo>click_Bank_Statements_Account__c</referenceTo>
        <relationshipLabel>Bank Statement Sub Categories</relationshipLabel>
        <relationshipName>Bank_Statement_Sub_Categories</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Click_Required_Document_Id__c</fullName>
        <label>Required Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Statement_No__c</fullName>
        <label>Category Index No.</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Subcategory_Index__c</fullName>
        <label>Subcategory Index</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Unique_Id__c</fullName>
        <formula>Click_Required_Document_Id__c &amp; &apos;-:-&apos;&amp;  Bank_Statement_Account_Number__c &amp; &apos;-:-&apos;&amp;  Click_Statement_No__c &amp; &apos;-:-&apos;&amp;  Click_Subcategory_Index__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unique Id</label>
        <type>Text</type>
    </fields>
    <label>Bank Statements Sub Category</label>
    <nameField>
        <label>Bank Statements Sub Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statement Sub Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/click_Bank_Statements_Transactions__c.object
<CustomObject>
    <fields>
        <fullName>Bank_Statement_Account_Number__c</fullName>
        <label>Bank Statement Account Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Bank_Statements_Sub_Category__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statements Sub Category</label>
        <referenceTo>click_Bank_Statements_Sub_Category__c</referenceTo>
        <relationshipLabel>Bank Statement Transactions</relationshipLabel>
        <relationshipName>Bank_Statement_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Click_Required_Document_Id__c</fullName>
        <label>Required Document Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Statement_No__c</fullName>
        <label>Category Index No.</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Click_Subcategory_Index__c</fullName>
        <label>Subcategory Index</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>click_Bank_Statements_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Bank Statements Account</label>
        <referenceTo>click_Bank_Statements_Account__c</referenceTo>
        <relationshipLabel>Bank Statement Transactions</relationshipLabel>
        <relationshipName>Bank_Statement_Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Bank Statements Transactions</label>
    <nameField>
        <label>Bank Statements Transactions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bank Statement Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransactionHandlerTracker.cls
@isTest
private class TransactionHandlerTracker{

 private static click_Bank_Statement_Data__c objBankStmtData;
 private static click_Bank_Statements_Sub_Category__c objBankStmtSubCat;
 private static click_Bank_Statements_Transactions__c objBankStatementTransaction;
 private static List<click_Bank_Statements_Transactions__c> listbanktrans;
 
 private static list<click_Bank_Statement_Data__c> lstBnkStmtData;
 private static click_Bank_Statements_Account__c objBankStmtAcc;
 private static list<click_Bank_Statements_Account__c> lstBankStmtAcc;

 private static Required_Document__c objRequiredDocument;
 private static Document_Master__c  objDocumentMaster;
 private static Opportunity objOpportunity;
 private static User objUser;
 private Id clickReqDocId;
 


 static testMethod void validate(){


 // objUser = WLCommonTrackerClass.createUser(objUser);
 // objOpportunity = WLCommonTrackerClass.createOpportunity(objOpportunity,objUser);
 // objDocumentMaster = WLCommonTrackerClass.createDocumentMaster(objDocumentMaster);
    objRequiredDocument = new Required_Document__c();
    objRequiredDocument.Name = 'Click Loan required doc';
    insert objRequiredDocument;


    lstBankStmtAcc = new list<click_Bank_Statements_Account__c>();
    objBankStmtAcc = new click_Bank_Statements_Account__c();

    objBankStmtAcc.Name = 'Test BankStatement Account';
    objBankStmtAcc.Account_Holder__c = 'Manish Bhasin';
    objBankStmtAcc.Account_Number__c = 'ABC123';
    objBankStmtAcc.Click_Loans_Required_Document__c = objRequiredDocument.Id;
    lstBankStmtAcc.add(objBankStmtAcc);

    if(lstBankStmtAcc.size()>0 && lstBankStmtAcc!=null){
    insert lstBankStmtAcc;

//  objBankStmtAcc.Account_Holder__c = 'Mb';
//  update objBankStmtAcc;
   }
    system.debug('lstBankStmtAcc------------' +lstBankStmtAcc);
    system.assertEquals('Test BankStatement Account',objBankStmtAcc.Name);
    
     

    lstBnkStmtData = new List<click_Bank_Statement_Data__c>();
    objBankStmtData = new click_Bank_Statement_Data__c();
    objBankStmtData.Name = 'test bank data';
    objBankStmtData.click_Bank_Statements_Account__c = lstBankStmtAcc[0].Id;
    objBankStmtData.Click_Required_Document_Id__c = 'testId123';
    objBankStmtData.closingBalance__c = '1200';
    objBankStmtData.openingBalance__c = '500';
    objBankStmtData.Bank_Statement_Account_Number__c = 'BNK112344';
    lstBnkStmtData.add(objBankStmtData);

    if(lstBnkStmtData.size()>0 && lstBnkStmtData!=null){

    insert lstBnkStmtData; 
   
    system.debug('lstBnkStmtData++++++++++++++' +lstBnkStmtData);
    
   
    objBankStmtSubCat = new click_Bank_Statements_Sub_Category__c ();
    objBankStmtSubCat.Name = 'demo bank sub category';
    objBankStmtSubCat.Bank_Statement_Category__c = objBankStmtData.Id;
    objBankStmtSubCat.Click_Required_Document_Id__c = 'abc123';
    objBankStmtSubCat.Click_Statement_No__c= 'abc12345';
    objBankStmtSubCat.Bank_Statement_Account_Number__c ='BNKAC123';
    insert objBankStmtSubCat;
    
    
    listbanktrans = new list<click_Bank_Statements_Transactions__c>();
    objBankStatementTransaction = new click_Bank_Statements_Transactions__c();
    objBankStatementTransaction.Name = 'My first test transaction';
    objBankStatementTransaction.Bank_Statements_Sub_Category__c = objBankStmtSubCat.Id;
    objBankStatementTransaction.Click_Required_Document_Id__c = 'ID1010';
    objBankStatementTransaction.Click_Statement_No__c = 'STMT123';
    objBankStatementTransaction.Bank_Statement_Account_Number__c = 'BNKAC123';
    objBankStatementTransaction.Click_Subcategory_Index__c = 'Index-123';
    listbanktrans.add(objBankStatementTransaction);
    insert listbanktrans;
    
    TransactionHandler objtranshandler = new TransactionHandler(); 
    map<id,click_Bank_Statements_Transactions__c> triggerOldMap = new map<id,click_Bank_Statements_Transactions__c>();
    objtranshandler.OnAfterUpdate(listbanktrans, triggerOldMap, listbanktrans);
    
    List<click_Bank_Statements_Sub_Category__c> lstBankStatementSubCategory = new list<click_Bank_Statements_Sub_Category__c>();
    lstBankStatementSubCategory = [select id,Bank_Statement_Account_Number__c,Click_Required_Document_Id__c,
                                            Click_Statement_No__c,Click_Subcategory_Index__c,Click_Unique_Id__c
                                            from click_Bank_Statements_Sub_Category__c];
                                            

    List<click_Bank_Statement_Data__c> LstBnkStmtData2 = new List<click_Bank_Statement_Data__c>();
    click_Bank_Statement_Data__c objBankStmtData2 = new click_Bank_Statement_Data__c();
    objBankStmtData2.Click_Required_Document_Id__c = objBankStmtData.Bank_Statement_Account_Number__c;
    insert objBankStmtData2;

     }

   //  clickReqDocId = lstBnkStmtData[0].Click_Required_Document_Id__c;
   List<click_Bank_Statements_Account__c> list2 = new List<click_Bank_Statements_Account__c>();
     click_Bank_Statements_Account__c clkbnkstmtacc = new click_Bank_Statements_Account__c();

  }
}