src/objects/click_Applicant__c.object
<CustomObject>
    <fields>
        <fullName>Address__c</fullName>
        <label>Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfRelationship_code__c</fullName>
        <label>Relation ship code</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_applicant_DOB__c</fullName>
        <label>DOB</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Applicant</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Applicant</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/ApplicantButtonTestClass.cls
@isTest 
private class ApplicantButtonTestClass {
    static testMethod void validateBatchclasss1()
    {
      
                click_Applicant__c  obj = new click_Applicant__c();
                    obj.address__C = 'ssaasa';
                    obj.Gender__c = 'Male';
                    obj.acf_applicant_DOB__c = '10/10/2016';
                    obj.acfRelationship_code__c = '2';
                    obj.First_Name__c = 'ssaasa';
                    obj.Last_Name__c = 'ssaasa';                
                 insert obj ;
                 CreateVedaClass.createVedaApplicantLink(obj.ID);
                 CreateVedaClass.callVedaApi(obj);
    }
    
    
     static testMethod void validateBatchclasss2()
    {
      
                click_Applicant__c  obj = new click_Applicant__c();
                    obj.address__C = null;
                    obj.Gender__c = Null;
                    obj.acf_applicant_DOB__c = null;
                    obj.acfRelationship_code__c =  null;
                    obj.First_Name__c =  null;
                    obj.Last_Name__c =  null;               
                 insert obj ;
                 CreateVedaClass.createVedaApplicantLink(obj.ID);
    }
     
}