src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLoan_Amount__c</fullName>
        <description>Click Loans</description>
        <label>Outstanding Loan Amount</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acfType__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfApproximately_how_much_is_your_house__c</fullName>
        <description>Click Loans</description>
        <label>Approx House Worth</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfIs_Bank_Statement_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Bank Statement Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Identity_Document_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Post_Login_Ques_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Post Login Ques Attempted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfLoan_Amount__c</fullName>
        <description>Click Loans</description>
        <label>Loan Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOneTimePassword__c</fullName>
        <description>Click Loans</description>
        <label>One Time Password</label>
        <length>225</length>
        <type>Text</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LVR_Rate__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>ACF_Comparison_Rate__c</fullName>
        <description>Click Loans</description>
        <label>Comparison Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfApplication_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Application Fee</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLVR__c</fullName>
        <description>Click Loans</description>
        <label>LVR To</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfLoan_Size__c</fullName>
        <description>Click Loans</description>
        <label>Loan Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfProduct__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipName>LVR_Rate</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfRate__c</fullName>
        <description>Click Loans</description>
        <label>Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>clickFixed_Interest_Rate__c</fullName>
        <label>Fixed Interest Rate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>clickLVR_From__c</fullName>
        <label>LVR From</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>clickLoan_Size_From__c</fullName>
        <label>Loan Size From</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Click Loans LVR &amp; Rate</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LVR &amp; Rate</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfBankdetailStatus__c</fullName>
        <description>Click Loans</description>
        <label>BankdetailStatus</label>
        <picklist>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfIs_Identity_Document_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfOffset_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Offset Account</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>ACF_Comparison_Rate__c</fullName>
        <description>Click Loans</description>
        <label>Comparison_Rate</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>acfApplication_Fee__c</fullName>
        <description>Click Loans</description>
        <label>Application Fee</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfLoan_Size__c</fullName>
        <description>Click Loans</description>
        <label>Loan Size</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>acfOffset_Account__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Offset Account</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfTenure_in_Years__c</fullName>
        <description>Click Loans</description>
        <label>Term (in Years)</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfType__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Variable</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acfvarTenure_In_Years__c</fullName>
        <description>Click Loans</description>
        <label>Tenure (In Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
</CustomObject>

src/objects/Question__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfIs_refinance__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is refinance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfRefinance_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Refinance Sequence No</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Question__c</fullName>
        <description>Click Loans</description>
        <label>Question</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>acf_Script__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Script</label>
        <referenceTo>Script__c</referenceTo>
        <relationshipName>Questions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_No__c</fullName>
        <description>Click Loans</description>
        <label>Sequence No</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Picklist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Checkbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Button</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RadioButton</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Component</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Currency</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Percent</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Question</label>
    <nameField>
        <displayFormat>Question-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Questions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Script__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Question__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Question</label>
        <referenceTo>Question__c</referenceTo>
        <relationshipName>Script</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acf_Sequence_no__c</fullName>
        <description>Click Loans</description>
        <label>Sequence no</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>acf_Type__c</fullName>
        <description>Click Loans</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pre-Login</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Post-Login</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Script</label>
    <nameField>
        <displayFormat>Script-{0000}</displayFormat>
        <label>Script Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Script</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ClickQuoteDetailTracker.cls
@isTest(SeeAllData = false)
private class ClickQuoteDetailTracker 
{   
    private static Lead objLead ;
    private static User objUser;
    private static Contact objContact;
    private static Account objAccount;
    private static Opportunity objOpportunity;

    
    static testMethod void validate() 
    {
      LoadData();
      
  //      RecordType objRT=[select id, name, SObjectType From RecordType Where SObjectType= 'product2' AND name= 'Variable'];
        product2 objPro = new product2();
        objPro.ACF_Comparison_Rate__c = 10;
        objPro.IsActive = true;
        objPro.acfType__c = 'Variable';
 //       objPro.Recordtype.Name = 'Variable';
        objPro.acfTenure_in_Years__c = '2'; 
        objPro.acfvarTenure_In_Years__c = 10;
        //objPro.clickLoan_Type__c =  'Basic';
        objPro.acfOffset_Account__c = false;
        objPro.Name = 'test';
     //   objPro.acfRating__c = '1';
        insert objPro;
      
        LVR_Rate__c objLVR = new LVR_Rate__c();
        objLVR.acfLVR__c = 120000.25;
        objLVR.acfRate__c = 10.25;
        objLVR.acfProduct__c = objPro.id;
        objLVR.acfLoan_Size__c = 10000.20;
        objLVR.ACF_Comparison_Rate__c = 10.00; 
        objLVR.clickFixed_Interest_Rate__c = 9.00;
        objLVR.clickLoan_Size_From__c = 50.50;
        objLVR.clickLVR_From__c = 1.2;
        objLVR.acfApplication_Fee__c = 5000; 
        insert objLVR; 
      
      
       Script__c objScript = new Script__c();
       objScript.acf_Type__c = 'Pre-Login';
       objScript.acf_Sequence_no__c = 1;
       insert objScript; 
      
        Question__c objQuestion = new Question__c ();
        objQuestion.acf_Question__c = 'Who is your current lender?';
        objQuestion.acf_Active__c = true;
        objQuestion.acf_Sequence_No__c = 2.0;
        objQuestion.acf_Type__c = 'Button';
        objQuestion.acfRefinance_Sequence_No__c = 1;
        objQuestion.acfIs_refinance__c = true;
        objQuestion.acf_Script__c = objScript.id;
        insert objQuestion;
        
      System.runAs(objuser) 
        {
            
      PageReference pageRef = new PageReference('http://www.google.com');
      Test.setCurrentPage(pageRef);
      ClickQuoteDetail.intWidth = 10;
      ClickQuoteDetail.setProgressBarWidth(10,10,'ClickPostloginQuestionnaires');
      ClickQuoteDetail objclick = new ClickQuoteDetail ();
      objclick.strLoanPurpose = 'test';
      objclick.decCurrLoanAmt = 10.01;
      objclick.decEstPropVal = 10.01;
      objclick.decBestRate = 10.01;
      objclick.decComparison = 10.01;
      objclick.decMonthlyPayment = 10;
      objclick.pge_name = 'test';
     }
    }
    
        
    static testMethod void validate1() 
    {
      LoadData();
      
  //      RecordType objRT=[select id, name, SObjectType From RecordType Where SObjectType= 'product2' AND name= 'Variable'];
        product2 objPro = new product2();
        objPro.ACF_Comparison_Rate__c = 10;
        objPro.IsActive = true;
        objPro.acfType__c = 'Variable';
 //       objPro.Recordtype.Name = 'Variable';
        objPro.acfTenure_in_Years__c = '2'; 
        objPro.acfvarTenure_In_Years__c = 10;
      //  objPro.clickLoan_Type__c =  'Basic';
        objPro.acfOffset_Account__c = false;
        objPro.Name = 'test';
    //    objPro.acfRating__c = '1';
        insert objPro;
      
        LVR_Rate__c objLVR = new LVR_Rate__c();
        objLVR.acfLVR__c = 120000.25;
        objLVR.acfRate__c = 10.25;
        objLVR.acfProduct__c = objPro.id;
        objLVR.acfLoan_Size__c = 10000.20;
        objLVR.ACF_Comparison_Rate__c = 10.00; 
        objLVR.clickFixed_Interest_Rate__c = 9.00;
        objLVR.clickLoan_Size_From__c = 50.50;
        objLVR.clickLVR_From__c = 1.2;
        objLVR.acfApplication_Fee__c = 5000; 
        insert objLVR; 
      
      
       Script__c objScript = new Script__c();
       objScript.acf_Type__c = 'Pre-Login';
       objScript.acf_Sequence_no__c = 1;
       insert objScript; 
      
        Question__c objQuestion = new Question__c ();
        objQuestion.acf_Question__c = 'Who is your current lender?';
        objQuestion.acf_Active__c = true;
        objQuestion.acf_Sequence_No__c = 2.0;
        objQuestion.acf_Type__c = 'Button';
        objQuestion.acfRefinance_Sequence_No__c = 1;
        objQuestion.acfIs_refinance__c = true;
        objQuestion.acf_Script__c = objScript.id;
        insert objQuestion;
        
      System.runAs(objuser) 
        {
            
      PageReference pageRef = new PageReference('http://www.google.com');
      Test.setCurrentPage(pageRef);
      ClickQuoteDetail.intWidth = 10;
      ClickQuoteDetail.setProgressBarWidth(10,10,'ClickBankInfoDetails');
      ClickQuoteDetail objclick = new ClickQuoteDetail ();
      objclick.strLoanPurpose = 'test';
      objclick.decCurrLoanAmt = 10.01;
      objclick.decEstPropVal = 10.01;
      objclick.decBestRate = 10.01;
      objclick.decComparison = 10.01;
      objclick.decMonthlyPayment = 10;
      objclick.pge_name = 'test';
     }
    }
    
    
      static testMethod void validate2() 
    {
      LoadData();
      
  //      RecordType objRT=[select id, name, SObjectType From RecordType Where SObjectType= 'product2' AND name= 'Variable'];
        product2 objPro = new product2();
        objPro.ACF_Comparison_Rate__c = 10;
        objPro.IsActive = true;
        objPro.acfType__c = 'Variable';
 //       objPro.Recordtype.Name = 'Variable';
        objPro.acfTenure_in_Years__c = '2'; 
        objPro.acfvarTenure_In_Years__c = 10;
     //   objPro.clickLoan_Type__c =  'Basic';
        objPro.acfOffset_Account__c = false;
        objPro.Name = 'test';
    //    objPro.acfRating__c = '1';
        insert objPro;
      
        LVR_Rate__c objLVR = new LVR_Rate__c();
        objLVR.acfLVR__c = 120000.25;
        objLVR.acfRate__c = 10.25;
        objLVR.acfProduct__c = objPro.id;
        objLVR.acfLoan_Size__c = 10000.20;
        objLVR.ACF_Comparison_Rate__c = 10.00; 
        objLVR.clickFixed_Interest_Rate__c = 9.00;
        objLVR.clickLoan_Size_From__c = 50.50;
        objLVR.clickLVR_From__c = 1.2;
        objLVR.acfApplication_Fee__c = 5000; 
        insert objLVR; 
      
      
       Script__c objScript = new Script__c();
       objScript.acf_Type__c = 'Pre-Login';
       objScript.acf_Sequence_no__c = 1;
       insert objScript; 
      
        Question__c objQuestion = new Question__c ();
        objQuestion.acf_Question__c = 'Who is your current lender?';
        objQuestion.acf_Active__c = true;
        objQuestion.acf_Sequence_No__c = 2.0;
        objQuestion.acf_Type__c = 'Button';
        objQuestion.acfRefinance_Sequence_No__c = 1;
        objQuestion.acfIs_refinance__c = true;
        objQuestion.acf_Script__c = objScript.id;
        insert objQuestion;
        
      System.runAs(objuser) 
        {
            
      PageReference pageRef = new PageReference('http://www.google.com');
      Test.setCurrentPage(pageRef);
      ClickQuoteDetail.intWidth = 10;
     // ClickQuoteDetail.setProgressBarWidth(10,10,'Clickid_verification');
      ClickQuoteDetail objclick = new ClickQuoteDetail ();
      objclick.strLoanPurpose = 'test';
      objclick.decCurrLoanAmt = 10.01;
      objclick.decEstPropVal = 10.01;
      objclick.decBestRate = 10.01;
      objclick.decComparison = 10.01;
      objclick.decMonthlyPayment = 10;
      objclick.pge_name = 'test';
     }
    }
    
    private static void LoadData()
    {
        createLead();
        createAccount();
 //     createContact();
        createUser();
        createOpportunity();

    }
    
    static void createLead()
    {
        objLead = new Lead();
        Id recorsTypeId  = acfCommon.GetRecordTypeId('Lead','Click Refi');
        objLead.FirstName = '+619654922845';
        objLead.LastName = '+619654922845';
        objLead.Email = 'swati.sharma@saasfocus.com';
        objLead.MobilePhone = '+619654922845';
        objLead.Status = 'Open';
        objLead.RecordTypeId = recorsTypeId;
        objLead.acfOneTimePassword__c = '724715';
        objLead.acfApproximately_how_much_is_your_house__c = 100.01;
        objLead.acfLoan_Amount__c = 100.20;
        objLead.acfIs_Bank_Statement_Submitted__c = true;
        //objLead.acfIs_Identity_Document_Submitted__c = true;
        //objLead.acfIs_Post_Login_Ques_Attempted__c =true;
        //objLead.acfIs_Identity_Document_Submitted__c =true;
        insert objLead;
 //   objLead = acfCommonTrackerClass.createLeadForPortal();
    }
    static void createAccount()
    {
        objAccount = new Account();
        objAccount = acfCommonTrackerClass.CreatePersonAccount('test','test','+619540505050','test@fakeemail.com',objLead.id);
    }
    
    static void createContact()
    {

      
        objContact = new Contact();
        objContact.acf_lead__c = objLead.id;
        objContact = acfCommontrackerClass.createContact(objContact,objAccount);
    }
    
    static void createuser()
    {
        objUser = new User();
        objUser = acfCommonTrackerClass.CreatePortalUser(objAccount.id);
    }
    
    static void createOpportunity()
    {
      objOpportunity = new Opportunity();
      objOpportunity.acfBankdetailStatus__c = 'Skipped';
      objOpportunity = acfCommontrackerClass.createOpportunity(objOpportunity,objUser);
    }
    

    
}