src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acf_Source__c</fullName>
        <description>Click Loans</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Jumio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Jumio_Credentials__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <fields>
        <fullName>Active_API_secret__c</fullName>
        <label>Active API secret</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>EndPoint__c</fullName>
        <label>EndPoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Merchant_API_token__c</fullName>
        <label>Merchant API token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Jumio Credentials</label>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>acfIs_Bank_Statement_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Bank Statement Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Identity_Document_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfIs_Post_Login_Ques_Attempted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Post Login Ques Attempted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfScanReference__c</fullName>
        <description>Click Loans</description>
        <label>Scan Reference</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>acf_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>clickJumio_Status__c</fullName>
        <label>Jumio Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfIs_Identity_Document_Submitted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Is Identity Document Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Jumio Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>clickJumio_Status__c</fullName>
        <label>Jumio Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Skipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempted</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfDocument_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Reference_No__c</fullName>
        <description>Click Loans</description>
        <label>Reference No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/acfJumioIntegration.cls
/*
   						Click Loans
    This class is used to integrate user data with jumio for identity verfication
    =============================================================================
    Name                             Date                                version
    =============================================================================
    Prashant Kumar                11/18/2014                                1.0
    =============================================================================
*/
public class acfJumioIntegration 
{
    //variables declarations
    public string strIframeURL {get; set;}
    public string strLeadId {get; set;}
    public ID LoggedInLeadId;
    Public Boolean isSkipvisible {get;set;}
    //Constructor
    public  acfJumioIntegration()
    {
        LoggedInLeadId  = acfCommon.getCurrentLoggedInLeadId(UserInfo.getUserId()); 
        isSkipvisible = true;
        If(LoggedInLeadId != null)
        {
            System.debug('@@@leadid'+LoggedInLeadId);
            List<Lead> lstLead = [select id,acfIs_Bank_Statement_Submitted__c,acfIs_Post_Login_Ques_Attempted__c from lead where id=:LoggedInLeadId];
            If(lstLead != null && lstLead.size()>0){
                   System.debug('@@@leadid'+lstLead);
                   If(lstLead[0].acfIs_Bank_Statement_Submitted__c && lstLead[0].acfIs_Post_Login_Ques_Attempted__c){
                        isSkipvisible = false;
                   }
            }
         }
          ClickQuoteDetail.setProgressBarWidth(0,0,'Clickjumiointegration');
       /* string strUserId = UserInfo.getUserId();
        list<User> lstUser = [select id, ContactId from User where Id =: strUserId and IsActive = true];
        if(lstUser != null && lstUser.size() > 0 && lstUser[0].ContactId != null){
            list<Lead> lstLead = [select id , acf_Contact__c from Lead where acf_Contact__c =: lstUser[0].ContactId];
            if(lstlead != null && lstLead.size() > 0){
                strLeadId = lstLead[0].id;
            }
        }*/
                    
    }
    
    /*
        This method is used to get the iframe url of jumio
        ===================================================
        Name                 Date                   version
        ===================================================
        Prashant Kumar      11/18/2014                1.0
        ===================================================   
    */
    public void CallToJumio() 
    {
        JSONGenerator objJsonGen = JSON.createGenerator(true);
        objJsonGen.writeStartObject();
        
        if(LoggedInLeadId != null)
        {
            objJsonGen.writeStringField('merchantIdScanReference', LoggedInLeadId);
        }
        else
            objJsonGen.writeStringField('merchantIdScanReference', 'TestScanReference');
        String strRetUrl = System.label.acfSite_Url+'/acfJumioSuccess';  
        objJsonGen.writeStringField('successUrl',strRetUrl);
        objJsonGen.writeStringField('errorUrl',strRetUrl);
        objJsonGen.writeEndObject();
        String jsonRequest = objJsonGen.getAsString();                
        
        //Get Merchant Api and Secret from Custom setting
        Jumio_Credentials__c objJumioCredential = Jumio_Credentials__c.getValues('Credential');       
        
        String strUserName = objJumioCredential.Merchant_API_token__c;
        String strPassword = objJumioCredential.Active_API_secret__c;    
        String strEndPoint = objJumioCredential.EndPoint__c;
        
        String strAuthorizationHeader = 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(strUserName + ':' + strPassword));
        
        //Create Http request
        HttpRequest req = new HttpRequest();
        req.setMethod('POST');
        req.setEndpoint(strEndPoint);
        System.debug('!!!! strAuthorizationHeader -'+ strAuthorizationHeader);
        req.setHeader('Authorization', strAuthorizationHeader);
        req.setHeader('Accept', 'application/json');             
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('User-Agent', 'SaasFocus Saas/1.9.0');
        req.setBody(jsonRequest);
                
        //send request        
        Http http = new Http();
        HTTPResponse jsonResponse = http.send(req);
        String jsonResponseBody = jsonResponse.getBody(); 
        system.debug('@@@json'+jsonResponseBody);  
                    
        RootObject objRootObject = parse(jsonResponseBody);
        strIframeURL = objRootObject.clientRedirectUrl;
        
        /*List<lead> lstLead = [select id, IsConverted from Lead where id =: strLeadId];
        if(lstLead != null && lstLead.size() > 0)
        {
            if(!lstLead[0].IsConverted)
            {
                lead lead_obj = new lead(id = strLeadId, acfScanReference__c = objRootObject.jumioIdScanReference);
                update lead_obj;
            }
            else
            {
                //TODO: Update contact code here                
            }
        }*/
        //Update Document Object and Lead.
        List<lead> lstLead = [select id, IsConverted from Lead where id =: LoggedInLeadId];
        if(lstLead != null && lstLead.size() > 0)
        {
            if(!lstLead[0].IsConverted && objRootObject.jumioIdScanReference <> null)
            {
                   List<Required_Document__c>lstRequiredDoc = [select id,acfStatus__c,acf_Reference_No__c,acfDocument_Master__c from Required_Document__c where acfDocument_Master__c <> null and Lead__c=:LoggedInLeadId and acfDocument_Master__r.acf_Source__c = 'Jumio' limit 1];
                   if(lstRequiredDoc <> null && lstRequiredDoc.size()>0)
                   {
                       lstRequiredDoc[0].acfStatus__c = 'Awaited';
                       lstRequiredDoc[0].acf_Reference_No__c = objRootObject.jumioIdScanReference;
                       update lstRequiredDoc;
                   }
            }
        }
    }
    
    public class RootObject
    {
        public string timestamp { get; set; }
        public string authorizationToken { get; set; }
        public string clientRedirectUrl { get; set; }
        public string jumioIdScanReference { get; set; }
    }
    
    public static RootObject parse(String json) 
    {
        return (RootObject) System.JSON.deserialize(json, RootObject.class);
    } 
    
    /***added by karthik 02-01-2015******/
    Public pagereference redirectToNextPage()
    {
        string loggedInOppId = acfCommon.getCurrentLoggedInOpportunityId(UserInfo.getuserId());
        if(loggedInOppId == null)
        {
                string strLoggedInleadid = acfcommon.getCurrentLoggedInLeadId(userInfo.getuserId());
                    lead leadObj = new lead(acfIs_Identity_Document_Submitted__c =true,clickJumio_Status__c = 'Skipped', id= strLoggedInleadid);
                    update leadObj;
        }else{
                opportunity objOpp = new opportunity(acfIs_Identity_Document_Submitted__c =true,clickJumio_Status__c = 'Skipped',id= loggedInOppId);
                update objOpp;
        }
        String retPgname = acfCommon.sendReturnUrl(userInfo.getUserId(),false,'clickid_verification');
        Pagereference pageref = new Pagereference('/'+retPgname);
        
        
       /* String retPgname = acfCommon.sendReturnUrl(userInfo.getUserId(),true,'clickid_verification');
        Pagereference pageref = new Pagereference('/partners/'+retPgname);
        Pagereference pageref = page.acfBankDetails;
        pageref.setredirect(true);*/
        return pageref;
    }
       
}