src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>acfConditions_of_Approval__c</fullName>
        <description>Click Loans</description>
        <label>Conditions of Approval</label>
        <picklist>
            <picklistValues>
                <fullName>Text</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Text and Document</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDocument_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/acfApprovalConditionTracker.cls
@isTest(SeeAllData=false)
private class acfApprovalConditionTracker 
{
	private static User objuser;
    private static Opportunity objOpportunity;
    private static Account objAccount;
    private static Lead objLead;
    static testMethod void myUnitTest() 
    {
    	objLead = acfCommonTrackerClass.createLeadForPortal();
        objAccount = acfCommonTrackerClass.CreatePersonAccount('test','test','+619540505050','test@fakeemail.com',objLead.id);
        objuser    =  acfCommonTrackerClass.CreatePortalUser(objAccount.id);
        objOpportunity  =  new Opportunity();
        objOpportunity.AccountId =  objAccount.id;
        objOpportunity.recordtypeid = acfCommon.GetRecordTypeId('Opportunity','Click Refi');
        objOpportunity.Name = 'test';
        objOpportunity.StageName = 'Application Taken';
        objOpportunity.acfConditions_of_Approval__c = 'Text and Document';
        objOpportunity.CloseDate = system.today();
        insert objOpportunity;
        Document_Master__c objDoc = new Document_Master__c();
        objDoc.acfActive__c = true;
        objDoc.Name = 'testDoc';
        insert objDoc;
        Required_Document__c objReqDoc = new Required_Document__c();
        objReqDoc.acfDocument_Master__c = objDoc.id;
        objReqDoc.acfOpportunity__c = objOpportunity.id;
        insert objReqDoc;
        ApexPages.StandardController sc = new ApexPages.standardController(objOpportunity);
        acfApprovalCondition objApp = new acfApprovalCondition(sc);
        objApp.ShowEditable();
        objApp.MakeUnEditable();
        objApp.ShowDocumentSection();
        objApp.lstRequiredDocList = new List<string>(); 
        objApp.lstRequiredDocList.add(objDoc.id);
        objApp.UpdateCondition();
    }
    static testMethod void myUnitTest1() 
    {
    	objLead = acfCommonTrackerClass.createLeadForPortal();
        objAccount = acfCommonTrackerClass.CreatePersonAccount('test','test','+619540505050','test@fakeemail.com',objLead.id);
        objuser    =  acfCommonTrackerClass.CreatePortalUser(objAccount.id);
        objOpportunity  =  new Opportunity();
        objOpportunity.AccountId =  objAccount.id;
        objOpportunity.recordtypeid = acfCommon.GetRecordTypeId('Opportunity','Click Refi');
        objOpportunity.Name = 'test';
        objOpportunity.StageName = 'Application Taken';
        objOpportunity.acfConditions_of_Approval__c = 'Text';
        objOpportunity.CloseDate = system.today();
        insert objOpportunity;
        Document_Master__c objDoc = new Document_Master__c();
        objDoc.acfActive__c = true;
        objDoc.Name = 'testDoc';
        insert objDoc;
        Required_Document__c objReqDoc = new Required_Document__c();
        objReqDoc.acfDocument_Master__c = objDoc.id;
        objReqDoc.acfOpportunity__c = objOpportunity.id;
        insert objReqDoc;
        ApexPages.StandardController sc = new ApexPages.standardController(objOpportunity);
        acfApprovalCondition objApp = new acfApprovalCondition(sc);
        objApp.ShowEditable();
        objApp.MakeUnEditable();
        objApp.ShowDocumentSection();
        objApp.lstRequiredDocList = new List<string>(); 
        objApp.lstRequiredDocList.add(objDoc.id);
        objApp.UpdateCondition();
    }
}