src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfDocument_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Brokers_AddReqDocumentsController.cls
public class Brokers_AddReqDocumentsController
{
    public string MyAccountId{get; set;}
    public  string strReqDocName {get;set;}
    public Account objAccount;
    public string strerrMsg{get;set;}
    public boolean isDocAdded {get;set;}
    public string docMasterId {get;set;}
    public Brokers_AddReqDocumentsController()
    {
        strerrMsg = ''; 
        isDocAdded = false;
        docMasterId = '';   
        strReqDocName = '';
    }
    
    public Account getObjAccount()
    {
       Account objAcc = new Account();
        if(MyAccountId != null && MyAccountId <> '')
        {
            list<Account> lstAccount = [select id,acf_Lead__pc,acf_Lead__pr.isConverted,acf_Lead__pr.ConvertedOpportunityId from account where id =: MyAccountId];           
            
            if(lstAccount != null && lstAccount.size()>0)
            {
                objAcc = lstAccount[0];
            }
        }
        return objAcc;
    }
    public void insertReqDocument()
    {
       try
       {
        objAccount = getObjAccount();
        if(objAccount != null && objAccount.acf_Lead__pr.ConvertedOpportunityId != null)
        {
           if(strReqDocName != null && strReqDocName <> '' && docMasterId != null && docMasterId <> '')
           { 
                Required_Document__c ObjReqDocument = new Required_Document__c();
                ObjReqDocument.Name = strReqDocName;
                ObjReqDocument.acfStatus__c = 'Pending';
                ObjReqDocument.acfDocument_Master__c = docMasterId;
               /* if(objAccount.acf_Lead__pc != null && objAccount.acf_Lead__pr.isConverted == false)
                {
                    ObjReqDocument.Lead__c = objAccount.acf_Lead__pc;
                }else*/
                    if(objAccount.acf_Lead__pc != null && objAccount.acf_Lead__pr.isConverted == true)
                    {
                       ObjReqDocument.acfOpportunity__c = objAccount.acf_Lead__pr.ConvertedOpportunityId;
                    }
                insert ObjReqDocument;
                strerrMsg = 'Required document added successfully.';
                isDocAdded = true;
           }else{
               strerrMsg = 'Please fill all required fields';
           }
        }else{
             strerrMsg = 'Required document not added,Please try again!';
        }
       }catch(Exception ex)
           {
             //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'Please fill all values'));
             strerrMsg = 'Required document not added,Please try again!';
           }
    }
       
   public pagereference reqDocCancel()
   {   
        Pagereference pageref = new Pagereference('/apex/BrokerClickDashboard?cid='+MyAccountId);
        pageref.setRedirect(true);
        Cookie cookieActiveTab = new Cookie('cookieActiveTab', 'Document', null, -1, true);           
        ApexPages.currentPage().setCookies( new Cookie[]{ cookieActiveTab });
        //PageReference pageref = Page.BrokerClickDashboard;
        //pageref.getParameters().put('cid',MyAccountId);
        return pageref;
    }
    
    public void resetReqDocPopup()
    {
        strerrMsg = '';
        docMasterId = '';
        strReqDocName = '';
        isDocAdded = false;
    }
    
    public List<SelectOption> getDocumentMasterNames()
    {  
        List<Document_Master__c> lstDocMaster = [select id,Name,acfActive__c from Document_Master__c where acfActive__c = true];
        List<SelectOption> options = new List<SelectOption>();
        if(lstDocMaster != null && lstDocMaster.size()>0)
        {
           options.add(new SelectOption('','--NONE--'));
           for(Document_Master__c objDocMaster : lstDocMaster)
           { 
             options.add(new SelectOption(objDocMaster.id,objDocMaster.Name));
           }
        }
        return options;
    }
}