src/objects/Document_Master__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfActive__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Click Loans</description>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Source__c</fullName>
        <description>Click Loans</description>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Jumio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Others</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Click Loans Document Master</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Document Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfDocument_Master__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Document Master</label>
        <referenceTo>Document_Master__c</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>acfStatus__c</fullName>
        <description>Click Loans</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not Verified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Uploaded</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaited</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>acf_Bank_Statement_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Bank Statement Doc</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>acf_Is_Identity_Verification_Doc__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Identity Verification Doc</label>
        <type>Checkbox</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>acfIs_Password_Reset__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Password Reset</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

Lendi/src/classes/ClickAddDocumentController.cls
public class ClickAddDocumentController
{
    public string MyAccountId{get; set;}
    public  string strReqDocName {get;set;}
    public Account objAccount;
    public string strerrMsg{get;set;}
    public boolean isDocAdded {get;set;}
    public string docMasterId {get;set;}
    public string strCommunityName {get;set;}
    public boolean strCommName {get;set;}
    public String MyOpportunityIds;
    public string setMyOpportunityIds(String testId)
    {
        MyOpportunityIds = testId; 
     // AddDocument();
        return null; 
    } 
    
    public String getMyOpportunityIds()
    {
       return MyOpportunityIds; 
    }
    
    public void AddDocument()
    {
        
    }
    public ClickAddDocumentController()
    {   
        strerrMsg = ''; 
        isDocAdded = false;
        docMasterId = '';   
        strReqDocName = '';
        
        strCommunityName = ClickCommon.getCommunitySetup(Network.getNetworkId()).Click_Page_Prefix__c;
        if(strCommunityName == 'ACF')
        {
        strCommName = false;
        }
        else if(strCommunityName == 'Click')
        {
        strCommName  = true;
        }     
    }
    
 /*   public Account getObjAccount()
    {
       Account objAcc = new Account();
       List<User> lstUser = [select id,AccountId,acfIs_Password_Reset__c from User where id =: UserInfo.getuserId() AND IsActive =: true];
        if(lstUser != null && lstUser.size()>0)
        {
            MyAccountId = lstUser[0].AccountId;
        }
        if(MyAccountId != null)
        {
            list<Account> lstAccount = [select id,acf_Lead__pc,acf_Lead__pr.isConverted,acf_Lead__pr.ConvertedOpportunityId from account where id =: MyAccountId];           
            
            if(lstAccount != null && lstAccount.size()>0)
            {
                objAcc = lstAccount[0];
            }
        }
        return objAcc;
    }     */
    public void insertReqDocument()
    {
       try
       {
     /* objAccount = getObjAccount();
        system.debug('objAccount!@#$%'+objAccount+'!@#$%^&*ANKIT'+objAccount.acf_Lead__pr+'*******'+objAccount.acf_Lead__pr.ConvertedOpportunityId);  */
        if(MyOpportunityIds != null && MyOpportunityIds <> '')   
        {
           system.debug('MyOpportunityIds___________AddDoc'+MyOpportunityIds);
           system.debug('strReqDocName ###########'+strReqDocName );
           system.debug('docMasterId ###########'+docMasterId );
                
           if(strReqDocName != null && strReqDocName <> '' && docMasterId != null && docMasterId <> '')
           { 
                List<Document_Master__c> lstDocMaster = [select id,acf_Source__c from Document_Master__c where id=:docMasterId and
                                                            (acf_Source__c = 'Jumio' OR acf_Source__c = 'Bank Statement' OR acf_Source__c = 'Note')];
                system.debug('lstDocMaster ###########'+lstDocMaster);                                            
                Required_Document__c ObjReqDocument = new Required_Document__c();
                ObjReqDocument.Name = strReqDocName;
                ObjReqDocument.acfStatus__c = 'Pending';
                ObjReqDocument.acfDocument_Master__c = docMasterId;
                if(lstDocMaster <> null && lstDocMaster.size() > 0)
                {
                    if(lstDocMaster[0].acf_Source__c == 'Jumio')
                    {
                        ObjReqDocument.acf_Is_Identity_Verification_Doc__c = true;
                    }
                    if(lstDocMaster[0].acf_Source__c == 'Bank Statement')
                    {
                        ObjReqDocument.acf_Bank_Statement_Doc__c = true;
                    }
                    if(lstDocMaster[0].acf_Source__c == 'Note')
                    {
                        ObjReqDocument.Click_Is_Note_Type__c = true;
                    }
                }
                if(MyOpportunityIds != null && MyOpportunityIds <> '') // objAccount.acf_Lead__pc != null && objAccount.acf_Lead__pr.isConverted == true
                {
                   ObjReqDocument.acfOpportunity__c = Id.valueof(MyOpportunityIds); //objAccount.acf_Lead__pr.ConvertedOpportunityId;
                }
                insert ObjReqDocument;
                system.debug('ObjReqDocument___________'+ObjReqDocument);
                strerrMsg = 'Required document added successfully.';
                isDocAdded = true;
           }else{
               strerrMsg = 'Please fill all required fields';
           }
        }else{
             strerrMsg = 'Required document not added,Please try again!';
        }
       }catch(Exception ex)
           {
             //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.error,'Please fill all values'));
             strerrMsg = 'Required document not added,Please try again!';
           }
    }
       
   public pagereference reqDocCancel()
   {   
 //   string strNetworkId =  Network.getNetworkId();
      if(ClickCommon.getCommunitySetup(Network.getNetworkId()).Click_Page_Prefix__c != null)
      {
        Pagereference pageref = new Pagereference('/apex/'+ClickCommon.getCommunitySetup(Network.getNetworkId()).Click_Page_Prefix__c+'Dashboard?id='+MyOpportunityIds);
        pageref.setRedirect(true);
        Cookie cookieActiveTab = new Cookie('cookieActiveTab', 'Document', null, -1, true);           
        ApexPages.currentPage().setCookies( new Cookie[]{ cookieActiveTab });
        return pageref;
       }
       return null;
    }
    
    public void resetReqDocPopup()
    {
        strerrMsg = '';
        docMasterId = '';
        strReqDocName = '';
        isDocAdded = false;
    }
    
    public List<SelectOption> getDocumentMasterNames()
    {         
        List<Document_Master__c> lstDocMaster = [select id,Name,acfActive__c from Document_Master__c where acfActive__c = true AND Click_Community_Setup__r.Click_Network_ID__c=: Network.getNetworkId() order by Name ASC];
        List<SelectOption> options = new List<SelectOption>();
        if(lstDocMaster != null && lstDocMaster.size()>0)
        {
           options.add(new SelectOption('','--NONE--'));
           for(Document_Master__c objDocMaster : lstDocMaster)
           { 
             options.add(new SelectOption(objDocMaster.id,objDocMaster.Name));
           }
        }
        return options;
    }
}