src/objects/Financials_Source__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Income_And_Expense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Income And Expense</label>
        <referenceTo>Income_And_Expense__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM User Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner User Input</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financials Source</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/createFinancialSourceForExistingRecord.cls
//-------------------------------------------------------------------------------------------
// -------------------------------------------------------------------------------------------
// Version#      Date                    Author                Description
// ------------------------------------- ------------------------------------------------------
// 1.0         25-03-2016              Ankit Singh          Initial Version
// -------------------------------------------------------------------------------------------
// This Batch Class is used to create Financial Source for Existing Record
// --------------------------------------------------------------------------------------------
global class createFinancialSourceForExistingRecord implements Database.Batchable<sObject>{

 global Database.QueryLocator start(Database.BatchableContext BC) {
        String query = 'Select id,Amount__c from Income_And_Expense__c';
        return Database.getQueryLocator(query);
       }  
       
 global void execute(Database.BatchableContext BC, List<Income_And_Expense__c> lstIncome) {
        List<Financials_Source__c> lstFinancial = new List<Financials_Source__c>();
        if(lstIncome != null && lstIncome.size() > 0)
        {
            for(Income_And_Expense__c objIncome : lstIncome)
            {
                Financials_Source__c obj = new Financials_Source__c();
                obj.Amount__c = objIncome.Amount__c;
                obj.Source__c = 'Customer Input';
                obj.Income_And_Expense__c = objIncome.id;
                lstFinancial.add(obj);
            }
        }
        if(lstFinancial != null && lstFinancial.size() > 0)
        {
           insert lstFinancial;   
        }
 
     }     
     
      global void finish(Database.BatchableContext BC) {
    }
 }