src/objects/Financials_Source__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Income_And_Expense__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Income And Expense</label>
        <referenceTo>Income_And_Expense__c</referenceTo>
        <relationshipLabel>Financials Sources</relationshipLabel>
        <relationshipName>Financials_Sources</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank Statements</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Document</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RPData</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CRM User Input</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Partner User Input</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Financials Source</label>
    <nameField>
        <displayFormat>FS-{0000}</displayFormat>
        <label>Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financials Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Income_And_Expense__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lendi_Income_And_Expense_uuid__c</fullName>
        <label>Lendi Income And Expense uuid</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Income And Expense</label>
    <nameField>
        <displayFormat>INC-{0000}</displayFormat>
        <label>IncomeAndExpense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Income And Expenses</pluralLabel>
    <recordTypes>
        <fullName>Expense</fullName>
        <active>true</active>
        <label>Expense</label>
    </recordTypes>
    <recordTypes>
        <fullName>Income</fullName>
        <active>true</active>
        <label>Income</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/IncomeExpenseTriggerHandler.cls
/*
    This class is used handle Income&Expense Trigger logic
    =============================================================================
    Name                             Date                                version
    =============================================================================
    Karthik Chekkilla               05/05/2016                               1.0
    =============================================================================
*/
public class IncomeExpenseTriggerHandler extends TriggerHandler
{
    // changes done by Ankit 
    // added GUID functionality.
    public override void BeforeInsert() 
    {
        for(Income_And_Expense__c  objIncome : (List<Income_And_Expense__c>) Trigger.new) 
        {
            if(string.isEmpty(objIncome.Lendi_Income_And_Expense_uuid__c))
            {
                List<string> lstGuid = new List<string>();
                lstGuid = Utilities.NewGuid();
                if(lstGuid != null && !lstGuid.isEmpty())
                    objIncome.Lendi_Income_And_Expense_uuid__c = lstGuid[0];
            }
        }
    }
    
    public override void afterInsert() 
    {
        list<Financials_Source__c> lstFinancialSource = new list<Financials_Source__c>();
        list<id> tempUserId = new list<id>();
        for(Income_And_Expense__c  objIncome : (list<Income_And_Expense__c>)trigger.new)
        {
            tempUserId.add(objIncome.CreatedById);
        }
        map<String,String> mapUser  =ClickCommon.mapUserInputType(tempUserId);
        string strUserType = '';
        //create financial records
        for(Income_And_Expense__c objIncome : (List<Income_And_Expense__c>) trigger.new)
        {
            Financials_Source__c objFinance = new Financials_Source__c();
            objFinance.Amount__c = objIncome.Amount__c;
            objFinance.Income_And_Expense__c = objIncome.id;
            if(mapUser != null && mapUser.size()>0)
            {
                strUserType = mapUser.get(objIncome.createdById);
                if(strUserType <> null && strUserType <> '')
                {
                    objFinance.Source__c = strUserType;
                }
            }
            lstFinancialSource.add(objFinance);
        }
        if(lstFinancialSource != null && lstFinancialSource.size()>0)
        {
            insert lstFinancialSource;
        }
    }
}