src/objects/LeadToCallFileRule__c.object
<CustomObject>
    <description>Store the rules for distributing different call file to the lead</description>
    <fields>
        <fullName>Call_File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Call file that the rule is corresponding to</description>
        <label>Call File</label>
        <referenceTo>vhc__Campaign__c</referenceTo>
        <relationshipLabel>LeadToCallFileRules</relationshipLabel>
        <relationshipName>LeadToCallFileRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Exclude_Closed_And_Lost__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that status is closed or lost</description>
        <label>Exclude Closed And Lost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Converted_Lead__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that is already converted</description>
        <label>Exclude Converted Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Do_Not_Call__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude all the leads that tagged as do not call</description>
        <label>Exclude Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Do_Not_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that tagged as do not email</description>
        <label>Exclude Do Not Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the current rule is active or not</description>
        <label>Is Active Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Priority to check will rule should be fitted first when assign the call file to the lead</description>
        <label>Priority</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_Description__c</fullName>
        <description>Rule Description</description>
        <label>Rule Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rule_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Rule Name</description>
        <externalId>true</externalId>
        <label>Rule Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>LeadToCallFileRule</label>
    <nameField>
        <label>LeadToCallFileRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LeadToCallFileRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ListAllRuleTest.cls
@isTest(SeeAllData=true)
private class ListAllRuleTest {
	
    static testMethod void listAllRuleControllerTest() {
        Account account = new Account(Name='Account Name'); 
        List<LeadToCallFileRule__c> rulesBefore = LeadToCallFileDAO.getAllLeadToCallFileRules();
        LeadToCallFileRule__c rule1 = new LeadToCallFileRule__c();
    	rule1.Rule_Name__c = 'test rule 1';
    	rule1.Is_Active_Rule__c = true;
    	rule1.Exclude_Do_Not_Call__c = true;
    	rule1.Exclude_Do_Not_Email__c = true;
    	rule1.Exclude_Closed_And_Lost__c = true;
    	rule1.Exclude_Converted_Lead__c = true;
    	rule1.Rule_Description__c = 'test description 1';
    	//rule1.Call_File__c = 'aaa';
    	rule1.Priority__c = 1;
    	insert rule1;
    	
    	ApexPages.StandardController controller = new ApexPages.StandardController(account);
    	ListAllRule stdController = new ListAllRule(controller);
    	system.assert(stdController != null);
    	system.assert(stdController.rulesList != null && stdController.rulesList.size() !=0);
    	stdController.addNewRule();
    	List<LeadToCallFileRule__c> rulesAfter = LeadToCallFileDAO.getAllLeadToCallFileRules();
    	System.assertEquals(rulesBefore.size() + 2, rulesAfter.size());
    }
}