src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LeadToCallFileRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadToCallFileRule</label>
        <referenceTo>LeadToCallFileRule__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LeadToCallFileRule__c.object
<CustomObject>
    <description>Store the rules for distributing different call file to the lead</description>
    <fields>
        <fullName>Rule_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Rule Name</description>
        <externalId>true</externalId>
        <label>Rule Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rule_Object__c</fullName>
        <label>Rule Object</label>
        <picklist>
            <picklistValues>
                <fullName>opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LeadToCallFileRule</label>
    <nameField>
        <label>LeadToCallFileRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LeadToCallFileRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LeadToCallFileRuleSet__c.object
<CustomObject>
    <description>Contain all the lead to call file rule conditions</description>
    <fields>
        <fullName>LeadToCallFileRule__c</fullName>
        <description>A leadToCallFileRule can have multi leadToCallFileRuleSets</description>
        <label>LeadToCallFileRule</label>
        <referenceTo>LeadToCallFileRule__c</referenceTo>
        <relationshipLabel>LeadToCallFileRuleSets</relationshipLabel>
        <relationshipName>LeadToCallFileRuleSets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>Operator is used to compare the values</description>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>is equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>is not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>is greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>is less than</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LeadToCallFileRuleSet</label>
    <nameField>
        <label>LeadToCallFileRuleSet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LeadToCallFileRuleSets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LeadToCallFileRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadToCallFileRule</label>
        <referenceTo>LeadToCallFileRule__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ListAllRuleSet.cls
public without sharing class ListAllRuleSet {
    
    public LeadToCallFileRule__c rule {get; set;}
    public List<LeadToCallFileRuleSet__c> ruleSets {get; set;}
    public Boolean isActive {get; set;}
    public Boolean excludeDoNotCall {get; set;}
    public Boolean excludeDoNotEmail {get; set;}
    public Boolean excludeConverted {get; set;}
    public Boolean excludeClosedAndLost {get; set;}
    public list<SelectOption> fieldOptions {get; set;}
    public list<SelectOption> operators {get; set;}
    public String ruleName {get; set;}
    public String ruleDescription {get; set;}
    public String selectedRuleSetId {get; set;}
    public String selectedRuleObject {get; set;}
    public Boolean renderErrorMessage {get; set;}
    public String errorMessage {get; set;}
    public List<SelectOption> callFilesOptions {get; set;}
    public List<SelectOption> ruleObjectOptions { get; set; }
    
    public ListAllRuleSet() {
    	renderErrorMessage = false;
    	selectedRuleObject = '';
        rule = new LeadToCallFileRule__c();
        Id ruleId =  ApexPages.currentPage().getParameters().get('Id');
        fieldOptions = new list<SelectOption>();
        //fieldOptions = Utilities.getPicklistValues(new LeadToCallFileRuleSet__c() , 'Field_Name__c');
        operators = new list<SelectOption>();
        operators = Utilities.getPicklistValues(new LeadToCallFileRuleSet__c(), 'Operator__c');
        callFilesOptions = new list<SelectOption>();
        callFilesOptions = QuickSort.sortOptionList(Utilities.getCallFileSelectOptions());
        ruleObjectOptions = new list<SelectOption>();
        ruleObjectOptions = getRuleObjectsOptions();
        if (ruleId != null) {
        	rule = LeadToCallFileDAO.getLeadToCallFileRuleById(ruleId);
            if (rule != null) {
                ruleSets = new List<LeadToCallFileRuleSet__c>();
                ruleSets = rule.LeadToCallFileRuleSets__r;
                if (rule.Rule_Object__c == null) {
                	selectedRuleObject = 'lead';
                } else {
                	selectedRuleObject = rule.Rule_Object__c;
                }            
            } else {
            	selectedRuleObject = 'lead';
            }
        } else {
        	selectedRuleObject = 'lead';
        }
        fieldOptions = QuickSort.sortOptionList(Utilities.getSObjectFieldAsSelectOptions(selectedRuleObject));
    }
   
   	public void changeRuleObject() {
   		fieldOptions = QuickSort.sortOptionList(Utilities.getSObjectFieldAsSelectOptions(this.selectedRuleObject));
   	}
   
    public PageReference save() {
    	//ruleSets Debugging
    	Boolean isValidRuleSet = true;
    	for (LeadToCallFileRuleSet__c ruleSet : ruleSets) {
    		if (!LeadToCallFileUtilities.ruleSetErrorCheck(ruleSet)) {
    			isValidRuleSet = false;
    			break;
    		}
    	}
    	if (isValidRuleSet) {
    		renderErrorMessage = true;
    		errorMessage = 'Success Saved';
    		update ruleSets;
	        if (rule != null && rule.Rule_Name__c != null && rule.Rule_Name__c != '') {
	            rule.Name = rule.Rule_Name__c;
	        }
	        upsert rule;
    	} else {
    		errorMessage = 'There is something wrong in the filter';
    		renderErrorMessage = true;
    	}
        return null;
    }
    
    public void moreRule() {
        LeadToCallFileRuleSet__c newRule = new LeadToCallFileRuleSet__c();
        newRule.LeadToCallFileRule__c = rule.Id;
        insert newRule;
        ruleSets.add(newRule);
        //update ruleSets;
    }
    
    public static list<SelectOption> getRuleObjectsOptions() {
   		list<SelectOption> options = new list<SelectOption>();
   		options.add(new SelectOption('lead', 'lead'));
   		options.add(new SelectOption('opportunity', 'opportunity'));
   		//options.add(new SelectOption('Account', 'Account'));
   		return options;
   }
    
    public void deleteRule() {
        // if for any reason we are missing the reference 
        if (selectedRuleSetId == null) {
            return;
        }
        // find the ruleSet in the list
        LeadToCallFileRuleSet__c tobeDeleted = null;
        for(Integer i=0; i < ruleSets.size(); i ++) {
            if (ruleSets.get(i).Id == selectedRuleSetId) {
                tobeDeleted = ruleSets.get(i);
                ruleSets.remove(i);
                break;
            }
        }
        
       //if ruleSet record found delete it
       if (tobeDeleted != null) {
           Delete tobeDeleted;
       }
       
    }
}