src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AddToCallFileDateCheck__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Add To Call File Date Check</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AddToCallFileDate__c</fullName>
        <label>Add To Call File Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Is_Updated__c</fullName>
        <defaultValue>false</defaultValue>
        <description>if the lead is being updated</description>
        <label>Is Updated</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LeadToCallFileRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadToCallFileRule</label>
        <referenceTo>LeadToCallFileRule__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>vhc__CallFile__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call File</label>
        <referenceTo>vhc__Campaign__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LeadToCallFileRule__c.object
<CustomObject>
    <description>Store the rules for distributing different call file to the lead</description>
    <fields>
        <fullName>Call_File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Call file that the rule is corresponding to</description>
        <label>Call File</label>
        <referenceTo>vhc__Campaign__c</referenceTo>
        <relationshipLabel>LeadToCallFileRules</relationshipLabel>
        <relationshipName>LeadToCallFileRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>LeadToCallFileRule</label>
    <nameField>
        <label>LeadToCallFileRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LeadToCallFileRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BatchAddCallFileToLead.cls
global without sharing class BatchAddCallFileToLead implements Database.Batchable<sObject> {

	global BatchAddCallFileToLead() {
	}

	global Database.QueryLocator start(Database.BatchableContext BC) {
		LeadSelector selector = new LeadSelector();
		String query = selector.getQueryPartOne() + 'WHERE Is_Updated__c = false AND AddToCallFileDate__c = today LIMIT 10000';
		return Database.getQueryLocator(query);
	}

	global void execute(Database.BatchableContext BC, List<Lead> scope) {
		List<LeadToCallFileRule__c> rules = LeadToCallFileDAO.getAllActiveLeadToCallFileRules();

		List<Lead> updateList = new List<Lead>();
		for(Lead l : scope) {
			if(l.LeadToCallFileRule__c != null) {
				LeadToCallFileRule__c rule = LeadToCallFileDAO.getLeadToCallFileRuleById(l.LeadToCallFileRule__c);
				boolean isFittedRule = LeadToCallFileUtilities.checkIfLeadFitTheRule(l, rule);
				System.debug('isFittedRule ' + isFittedRule);
				if (isFittedRule) {
					l.vhc__CallFile__c = rule.Call_File__c;
					l.Is_Updated__c = true;
					l.AddToCallFileDateCheck__c = true;
					updateList.add(l);
				}
			}
		}

		update updateList;
	}

	global void finish(Database.BatchableContext BC) {

	}

}