src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Credit_History__c</fullName>
        <label>Credit History</label>
        <picklist>
            <picklistValues>
                <fullName>Paid or Unpaid Defaults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged from Part 9 or Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too Many Credit Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Credit History</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excellent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excellent - No Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average - Paid telco/utility default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fair - Multiple Defaults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor - Prior Bankruptcy or Part 9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Interest_Rate_Type__c</fullName>
        <label>Current Interest Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Variable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Variable / Fixed Split</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line of Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Interest_Rate__c</fullName>
        <label>Current Interest Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <label>Current Lender</label>
        <picklist>
            <picklistValues>
                <fullName>Current Lender - TBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advantedge Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anchorage Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia First Mortgage Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian First Mortgage Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Defence Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Unity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Melbourne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banksia Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bendigo Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluebay Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Mortgage Corporation Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circle Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citibank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastline Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collins Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commonwealth Bank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Type__c</fullName>
        <label>Current Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Value__c</fullName>
        <label>Current Loan Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <inlineHelpText>You can select more than one value for the Employment Status</inlineHelpText>
        <label>Employment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Casual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centrelink or Pension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unemployed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fixed_Rate_Expiry__c</fullName>
        <inlineHelpText>If the date not available in popup window (+5 Years)
Just type the date in the box using this format 
DD/MM/YYYY
17/12/1969</inlineHelpText>
        <label>Fixed Rate Expiry</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Housing_Status__c</fullName>
        <label>Housing Status</label>
        <picklist>
            <picklistValues>
                <fullName>Boarding/Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Own Outright</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Looking to Buy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saving Deposit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Refinance__c</fullName>
        <inlineHelpText>Just type the date in the box using this format 
DD/MM/YYYY
17/12/1969</inlineHelpText>
        <label>Last Refinance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Looking_To_Buy__c</fullName>
        <label>Looking To Buy</label>
        <picklist>
            <picklistValues>
                <fullName>Within a year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In 2 years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than 2 years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

Lendi/src/classes/LeadWithCustomButtonControllerExtension.cls
public class LeadWithCustomButtonControllerExtension {
	public Lead lead;
	public String currectCreditHistory {get; set;}
	public String employmentStatus {get; set;}
	public String housingStatus {get; set;}
	public String mortgageStatus {get; set;}
	public String interestType {get; set;}
	public String lastRefinance {get; set;}
	public String fixedExpiry {get; set;}
	public String lookingToBuy {get; set;}
	public Integer loadAmount {get; set;} 
	public Double interestRate {get; set;}
	public String currentLender {get; set;}
	
	public LeadWithCustomButtonControllerExtension(ApexPages.StandardController stdController) {
		this.lead = (Lead)stdController.getRecord();
		this.lead = LeadDAO.getLeadById(lead.Id);
		Date lateRefinanceDate = lead.Last_Refinance__c;
		if (lateRefinanceDate != null) {
			DateTime dtValue = DateTime.newInstance(lateRefinanceDate.year(), lateRefinanceDate.month(), lateRefinanceDate.day());
			this.lastRefinance = dtValue.format('yyyy-MM-dd');
		}
		Date fixedExpiryDate = lead.Fixed_Rate_Expiry__c;
		if (fixedExpiryDate != null) {
			DateTime dtValue = DateTime.newInstance(fixedExpiryDate.year(), fixedExpiryDate.month(), fixedExpiryDate.day());
			this.fixedExpiry = dtValue.format('yyyy-MM-dd');
		}
	}
	
	public void saveCurrentLender() {
		if (currentLender == null) {
			return;
		}
		lead.Current_Lender__c = currentLender;
		update lead;
	}
	
	public void saveLoadAmount() {
		if (loadAmount == null) {
			return;
		}
		lead.Current_Loan_Value__c = loadAmount;
		update lead;
	}
	
	public void saveInterestRate() {
		if (interestRate == null) {
			return;
		}
		lead.Current_Interest_Rate__c = interestRate;
		update lead;
	}
	
	public void saveCreditHistory() {
		if (currectCreditHistory == null) {
			return;
		}
		lead.Credit_History__c = currectCreditHistory;
		update lead;
	}
	
	public void saveEmploymentStatus() {
		if (employmentStatus == null) {
			return;
		}
		lead.Employment_Status__c = employmentStatus;
		update lead;
	}
	
	public void saveHousingStatus() {
		if (housingStatus == null) {
			return;
		}
		lead.Housing_Status__c = housingStatus;
		update lead;
	}
	
	public void saveMortgageStatus() {
		if (mortgageStatus == null) {
			return;
		}
		lead.Current_Loan_Type__c = mortgageStatus;
		update lead;
	}
	
	public void saveInterestType() {
		if (interestType == null) {
			return;
		}
		lead.Current_Interest_Rate_Type__c = interestType;
		update lead;
	}
	
	public void saveLookingToBuy() {
		if (lookingToBuy == null) {
			return;
		}
		lead.Looking_To_Buy__c = lookingToBuy;
		update lead;
	}
	
	public void saveLastRefinanceDate() {
		if (lastRefinance == null) {
			return;
		}
		String[] dateComponent = lastRefinance.split('-');
		Date lfDate = Date.newInstance(Integer.valueOf(dateComponent[0]), Integer.valueOf(dateComponent[1]), Integer.valueOf(dateComponent[2]));
		lead.Last_Refinance__c = lfDate;
		update lead;
	}
	
	public void saveFixedExpiryDate() {
		if (fixedExpiry == null) {
			return;
		}
		String[] dateComponent = fixedExpiry.split('-');
		Date feDate = Date.newInstance(Integer.valueOf(dateComponent[0]), Integer.valueOf(dateComponent[1]), Integer.valueOf(dateComponent[2]));
 		lead.Fixed_Rate_Expiry__c = feDate;
 		update lead;
 	}
 	 	
}