src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Credit_History__c</fullName>
        <label>Credit History</label>
        <picklist>
            <picklistValues>
                <fullName>Paid or Unpaid Defaults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Discharged from Part 9 or Bankruptcy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Too Many Credit Enquiries</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Credit History</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excellent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Excellent - No Issues</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Average - Paid telco/utility default</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fair - Multiple Defaults</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Poor - Prior Bankruptcy or Part 9</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Interest_Rate_Type__c</fullName>
        <label>Current Interest Rate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Variable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Variable / Fixed Split</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fixed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Line of Credit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Interest_Rate__c</fullName>
        <label>Current Interest Rate</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <label>Current Lender</label>
        <picklist>
            <picklistValues>
                <fullName>Current Lender - TBA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advantedge Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anchorage Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia First Mortgage Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian First Mortgage Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Defence Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Unity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Melbourne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banksia Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bendigo Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluebay Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Mortgage Corporation Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circle Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citibank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Coastline Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Collins Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commonwealth Bank</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Type__c</fullName>
        <label>Current Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Value__c</fullName>
        <label>Current Loan Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Employment_Status__c</fullName>
        <inlineHelpText>You can select more than one value for the Employment Status</inlineHelpText>
        <label>Employment Status</label>
        <picklist>
            <picklistValues>
                <fullName>Casual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Centrelink or Pension</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Full Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Part Time</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Self Employed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unemployed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Fixed_Rate_Expiry__c</fullName>
        <inlineHelpText>If the date not available in popup window (+5 Years)
Just type the date in the box using this format 
DD/MM/YYYY
17/12/1969</inlineHelpText>
        <label>Fixed Rate Expiry</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Housing_Status__c</fullName>
        <label>Housing Status</label>
        <picklist>
            <picklistValues>
                <fullName>Boarding/Family</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mortgage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Own Outright</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Looking to Buy</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saving Deposit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Last_Refinance__c</fullName>
        <inlineHelpText>Just type the date in the box using this format 
DD/MM/YYYY
17/12/1969</inlineHelpText>
        <label>Last Refinance</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Loan_Value__c</fullName>
        <label>Loan Value</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Looking_To_Buy__c</fullName>
        <label>Looking To Buy</label>
        <picklist>
            <picklistValues>
                <fullName>Within a year</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In 2 years</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>More than 2 years</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_Calls__c</fullName>
        <label>Total Calls</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/classes/LeadWithCustomBControllerExtensionTest.cls
@isTest(SeeAllData=true)
private class LeadWithCustomBControllerExtensionTest {
	public static Lead testLead1;
	static {
		testLead1 = new Lead();
    	testLead1.Source__c = 'test 1';
    	testLead1.LastName = 'lI';
    	testLead1.Total_Calls__c = 3;
    	testLead1.Status = 'New';
    	testLead1.Last_Refinance__c = Date.today();
    	testLead1.Fixed_Rate_Expiry__c = Date.today();
    	insert testLead1;
	}
    static testMethod void customButtonControllerTest() {
        Test.startTest();
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(testLead1);
        LeadWithCustomButtonControllerExtension stdController = new LeadWithCustomButtonControllerExtension(controller);
        System.assert(stdController != null);
        stdController.currectCreditHistory = 'Excellent - No Issues';
        stdController.currentLender = 'BankWest';
        stdController.employmentStatus = 'Full Time';
        stdController.fixedExpiry = '2015-05-06';
        stdController.housingStatus = 'Boarding/Family';
        stdController.interestRate = 4.29;
        stdController.interestType = 'Variable';
        stdController.lastRefinance = '2015-03-08';
        stdController.loadAmount = 440000;
        stdController.lookingToBuy = 'More than 2 years';
        stdController.mortgageStatus = 'Owner Occupied';
        stdController.saveCreditHistory();
        stdController.saveCurrentLender();
        stdController.saveEmploymentStatus();
        stdController.saveFixedExpiryDate();
        stdController.saveHousingStatus();
        stdController.saveInterestRate();
        stdController.saveInterestType();
        stdController.saveLastRefinanceDate();
        stdController.saveLoadAmount();
        stdController.saveLookingToBuy();
        stdController.saveMortgageStatus();
        Test.stopTest();
        Lead newLead = [Select Id, Name, Current_Loan_Value__c, Current_Lender__c, Credit_History__c, Employment_Status__c, Fixed_Rate_Expiry__c, Housing_Status__c, Current_Interest_Rate__c, Current_Interest_Rate_Type__c, Last_Refinance__c, Loan_Value__c, Looking_To_Buy__c, Current_Loan_Type__c From Lead where Id = : testLead1.Id];
    	System.assertEquals(newLead.Current_Lender__c, 'BankWest');
    	System.assertEquals(newLead.Credit_History__c, 'Excellent - No Issues');
    	System.assertEquals(newLead.Employment_Status__c, 'Full Time');
    	System.assertEquals(newLead.Housing_Status__c, 'Boarding/Family');
    	System.assertEquals(newLead.Current_Interest_Rate__c, 4.29);
    	System.assertEquals(newLead.Current_Interest_Rate_Type__c, 'Variable');
    	System.assertEquals(newLead.Current_Loan_Value__c, 440000);
    	System.assertEquals(newLead.Looking_To_Buy__c, 'More than 2 years');
    	System.assertEquals(newLead.Current_Loan_Type__c, 'Owner Occupied');
    	stdController.currectCreditHistory = null;
        stdController.currentLender = null;
        stdController.employmentStatus = null;
        stdController.fixedExpiry = null;
        stdController.housingStatus = null;
        stdController.interestRate = null;
        stdController.interestType = null;
        stdController.lastRefinance = null;
        stdController.loadAmount = null;
        stdController.lookingToBuy = null;
        stdController.mortgageStatus = null;
        stdController.saveCreditHistory();
        stdController.saveCurrentLender();
        stdController.saveEmploymentStatus();
        stdController.saveFixedExpiryDate();
        stdController.saveHousingStatus();
        stdController.saveInterestRate();
        stdController.saveInterestType();
        stdController.saveLastRefinanceDate();
        stdController.saveLoadAmount();
        stdController.saveLookingToBuy();
        stdController.saveMortgageStatus();
    }
}