src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LeadToCallFileRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadToCallFileRule</label>
        <referenceTo>LeadToCallFileRule__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ReadWriteTransfer</sharingModel>
</CustomObject>

src/objects/LeadToCallFileRule__c.object
<CustomObject>
    <description>Store the rules for distributing different call file to the lead</description>
    <fields>
        <fullName>Call_File__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Call file that the rule is corresponding to</description>
        <label>Call File</label>
        <referenceTo>vhc__Campaign__c</referenceTo>
        <relationshipLabel>LeadToCallFileRules</relationshipLabel>
        <relationshipName>LeadToCallFileRules</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Delay_To_Call_File_Days__c</fullName>
        <label>Delay To Call File Days</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Exclude_Closed_And_Lost__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that status is closed or lost</description>
        <label>Exclude Closed And Lost</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Converted_Lead__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that is already converted</description>
        <label>Exclude Converted Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Do_Not_Call__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude all the leads that tagged as do not call</description>
        <label>Exclude Do Not Call</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Exclude_Do_Not_Email__c</fullName>
        <defaultValue>true</defaultValue>
        <description>Exclude the leads that tagged as do not email</description>
        <label>Exclude Do Not Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Is_Active_Rule__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check if the current rule is active or not</description>
        <label>Is Active Rule</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Priority to check will rule should be fitted first when assign the call file to the lead</description>
        <label>Priority</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_Description__c</fullName>
        <description>Rule Description</description>
        <label>Rule Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Rule_Name__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>Rule Name</description>
        <externalId>true</externalId>
        <label>Rule Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Rule_Object__c</fullName>
        <label>Rule Object</label>
        <picklist>
            <picklistValues>
                <fullName>opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>account</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LeadToCallFileRule</label>
    <nameField>
        <label>LeadToCallFileRule Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LeadToCallFileRules</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LeadToCallFileRuleSet__c.object
<CustomObject>
    <description>Contain all the lead to call file rule conditions</description>
    <fields>
        <fullName>Field_Name_Dyna__c</fullName>
        <description>Dynamic field name field</description>
        <label>Field Name Dyna</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Field_Value__c</fullName>
        <description>Field value on the right of the condition</description>
        <label>Field Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>LeadToCallFileRule__c</fullName>
        <description>A leadToCallFileRule can have multi leadToCallFileRuleSets</description>
        <label>LeadToCallFileRule</label>
        <referenceTo>LeadToCallFileRule__c</referenceTo>
        <relationshipLabel>LeadToCallFileRuleSets</relationshipLabel>
        <relationshipName>LeadToCallFileRuleSets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <description>Operator is used to compare the values</description>
        <label>Operator</label>
        <picklist>
            <picklistValues>
                <fullName>is equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>is not equal to</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>is greater than</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>is less than</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>LeadToCallFileRuleSet</label>
    <nameField>
        <label>LeadToCallFileRuleSet Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LeadToCallFileRuleSets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>LeadToCallFileRule__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>LeadToCallFileRule</label>
        <referenceTo>LeadToCallFileRule__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadToCallFileDAO.cls
public class LeadToCallFileDAO {
	public static LeadToCallFileRule__c getLeadToCallFileRuleById(Id ruleId) {
		List<LeadToCallFileRule__c> rules = [Select Id, Name, Delay_To_Call_File_Days__c, Rule_Object__c, Rule_Name__c, Rule_Description__c, Is_Active_Rule__c, 
                    Exclude_Closed_And_Lost__c, Priority__c, Exclude_Converted_Lead__c, Exclude_Do_Not_Call__c, 
                    Exclude_Do_Not_Email__c ,Call_File__c, (select Id, Name, Field_Name_Dyna__c,
                    Field_Value__c, Operator__c From LeadToCallFileRuleSets__r)
                    From LeadToCallFileRule__c where id =: ruleId];
        if (rules.size() > 0) {
        	return rules.get(0);
        }
        return null;            
	}
	
	public static List<LeadToCallFileRule__c> getAllActiveLeadToCallFileRules() {
		List<LeadToCallFileRule__c> rules = [Select Id, Name, Delay_To_Call_File_Days__c, Rule_Object__c, Rule_Name__c, Rule_Description__c, Is_Active_Rule__c, 
                    Exclude_Closed_And_Lost__c, Priority__c, Exclude_Converted_Lead__c, Exclude_Do_Not_Call__c, 
                    Exclude_Do_Not_Email__c ,Call_File__c, (select Id, Name, Field_Name_Dyna__c,
                    Field_Value__c, Operator__c From LeadToCallFileRuleSets__r)
                    From LeadToCallFileRule__c where Is_Active_Rule__c = true and Rule_Object__c = 'Lead'];
        return rules;
	}
	
	public static List<LeadToCallFileRule__c> getAllActiveOpportunityToCallFileRules() {
		List<LeadToCallFileRule__c> rules = [Select Id, Name, Delay_To_Call_File_Days__c, Rule_Object__c, Rule_Name__c, Rule_Description__c, Is_Active_Rule__c, 
                    Exclude_Closed_And_Lost__c, Priority__c, Exclude_Converted_Lead__c, Exclude_Do_Not_Call__c, 
                    Exclude_Do_Not_Email__c ,Call_File__c, (select Id, Name, Field_Name_Dyna__c,
                    Field_Value__c, Operator__c From LeadToCallFileRuleSets__r)
                    From LeadToCallFileRule__c where Is_Active_Rule__c = true and Rule_Object__c = 'Opportunity'];
        return rules;
	}
	
	public static List<LeadToCallFileRule__c> getAllLeadToCallFileRules() {
		List<LeadToCallFileRule__c> rules = [Select Id, Name, Delay_To_Call_File_Days__c, Rule_Object__c, Rule_Name__c, Rule_Description__c, Priority__c, Is_Active_Rule__c, Call_File__c From LeadToCallFileRule__c];
		return rules;
	}
}