src/objects/Mercury_Opportunity__c.object
<CustomObject>
    <description>to hold the opportunity cant be synced back to salesforce</description>
    <fields>
        <fullName>merc_current_status__c</fullName>
        <label>merc current status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>merc_last_sync_time__c</fullName>
        <label>merc last sync time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>merc_transaction_name__c</fullName>
        <label>merc transaction name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mercury Mismatch Queue</label>
    <nameField>
        <label>Mercury Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercury Mismatch Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/TestMercuryOpportunityService.cls
@isTest
public with sharing class TestMercuryOpportunityService {

	private static testMethod void testCastLoanWithSFId() {
		Opportunity oppo = testUtilities.createOpportunity();
		insert oppo;

		MercuryModel.loan l = new MercuryModel.loan();
		l.uniqueId = oppo.id;
		l.loanName = 'test loan';

		Mercury_Opportunity__c mo = MercuryOpportunityService.castMercuryOpportunity(l);
		Opportunity newOppo = MercuryOpportunityService.castOpportunity(mo);
		System.assertEquals(oppo.id, newOppo.id);
		System.assertEquals(l.loanName, mo.merc_transaction_name__c);
		System.assertEquals(mo.merc_transaction_name__c, newOppo.merc_transaction_name__c);
	}

	private static testMethod void testCastLoanWithoutSFId() {
		MercuryModel.loan l = new MercuryModel.loan();
		l.uniqueId = 'abc';
		l.loanName = 'test loan';

		Mercury_Opportunity__c o = MercuryOpportunityService.castMercuryOpportunity(l);
		System.assertEquals(null, o.id);
		System.assertEquals('abc', o.get(MercuryUtility.loanOpportunityMap.get('uniqueId')));
		System.assertEquals(l.loanName, o.merc_transaction_name__c);
	}

	public static testMethod void testCastMercuryOpportunity() {
		Mercury_Opportunity__c mo = new Mercury_Opportunity__c();
		mo.merc_current_status__c = 'test';
		Opportunity o = MercuryOpportunityService.castOpportunity(mo);
		System.assertEquals(o.merc_current_status__c, mo.merc_current_status__c);
		System.assertEquals(o.merc_last_sync_time__c, mo.merc_last_sync_time__c);
	}

}