src/objects/Mercury_Opportunity__c.object
<CustomObject>
    <description>to hold the opportunity cant be synced back to salesforce</description>
    <fields>
        <fullName>merc_current_status__c</fullName>
        <label>merc current status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>merc_transaction_name__c</fullName>
        <label>merc transaction name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Mercury Mismatch Queue</label>
    <nameField>
        <label>Mercury Opportunity Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Mercury Mismatch Queue</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestOpportunityService.cls
@isTest
public with sharing class TestOpportunityService {

	private static testMethod void testCastLoanWithSFId() {
		Opportunity oppo = testUtilities.createOpportunity();
		insert oppo;

		MercuryModel.loan l = new MercuryModel.loan();
		l.uniqueId = oppo.id;
		l.loanName = 'test loan';

		Opportunity o = OpportunityService.castLoan(l);
		System.assertEquals(oppo.id, o.id);
		System.assertEquals(l.loanName, o.merc_transaction_name__c);
	}

	private static testMethod void testCastLoanWithoutSFId() {
		MercuryModel.loan l = new MercuryModel.loan();
		l.uniqueId = 'abc';
		l.loanName = 'test loan';

		Opportunity o = OpportunityService.castLoan(l);
		System.assertEquals(null, o.id);
		System.assertEquals('abc', o.get(MercuryModel.loanOpportunityMap.get('uniqueId')));
		System.assertEquals(l.loanName, o.merc_transaction_name__c);
	}

	public static testMethod void testCastMercuryOpportunity() {
		Opportunity o = TestUtilities.createOpportunity();
		o.merc_current_status__c = 'test';
		Mercury_Opportunity__c mo = OpportunityService.castMercuryOpportunity(o);
		System.assertEquals(o.merc_current_status__c, mo.merc_current_status__c);
	}

}