src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Car_Loan_Balance__c</fullName>
        <label>Car Loan Balance</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Balance__c</fullName>
        <label>Credit Card Balance</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <label>Current Lender</label>
        <picklist>
            <controllingField>Transaction_Type__c</controllingField>
            <picklistValues>
                <fullName>Adelaide Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advantedge Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anchorage Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assured Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aussie Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia First Mortgage Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Defence Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian First Mortgage Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Unity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank MECU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Melbourne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banksia Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankstown City Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bendigo Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluebay Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Mortgage Corporation Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circle Credit Union</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Type__c</fullName>
        <label>Current Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Value__c</fullName>
        <label>Current Loan Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Loan_Balance__c</fullName>
        <label>Personal Loan Balance</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Refinance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityRestTest.cls
@isTest(SeeAllData=true)
private class OpportunityRestTest {
	public static Account acc {get; set;}
	public static Opportunity opp {get; set;}
	
	
    static testMethod void doPostTest() {
        acc = new Account();
		//acc.Name = 'Test Account';
		acc.FirstName = 'Test';
		acc.LastName = 'Account';
		acc.PersonEmail = 'test@mailinator.com';
		acc.Phone = '+61423292909';
		acc.Employment_Status__pc = 'Full Time';
		acc.Marital_Status__pc = 'Single';
		acc.Housing_Status__pc = 'Renting';
		acc.Annual_Income__pc = 100000;
		acc.Super_Balance__pc = 100000;
		acc.Number_of_Children__pc = '2';
		acc.Partner_Annual_Income__pc = 100000;
		acc.Partner_Super_Balance__pc = 10000;
		insert acc;
		
		opp = new Opportunity();
		opp.Name = 'TEST';
		opp.AccountId = acc.Id;
		opp.CloseDate = Date.today();
		opp.StageName = 'Appointed';
		opp.Transaction_Type__c = 'Refinance';
		opp.Current_Lender__c = 'ANZ';
		opp.Current_Loan_Value__c = 45666;
		opp.Current_Loan_Type__c = 'Commercial';
		opp.Personal_Loan_Balance__c = 100;
		opp.Credit_Card_Balance__c = 120;
		opp.Car_Loan_Balance__c = 2000;
		insert opp;
		
        RestRequest req = new RestRequest(); 
    	RestResponse res = new RestResponse();
    	req.params.put('oppoId', String.valueOf(opp.Id));
    	req.params.put('status', 'test chen');
    	req.requestURI = 'https://cs5.salesforce.com/services/apexrest/v1/Opportunity/';
    	req.httpMethod = 'POST';
    	RestContext.request = req;
    	RestContext.response = res;
    	ResponseHandler results = OpportunityRest.doPost();
    	System.assertEquals('Failed', results.status);
    }
}