src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Car_Loan_Balance__c</fullName>
        <label>Car Loan Balance</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Credit_Card_Balance__c</fullName>
        <label>Credit Card Balance</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Current_Lender__c</fullName>
        <label>Current Lender</label>
        <picklist>
            <controllingField>Transaction_Type__c</controllingField>
            <picklistValues>
                <fullName>Adelaide Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Adelaide Bank Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advantedge Finance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AMP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anchorage Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Assured Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aussie Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia First Mortgage Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Defence Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian First Mortgage Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australian Unity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>B&amp;E</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank MECU</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Melbourne</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Queensland</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank of Victoria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bank SA Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Banksia Group</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bankstown City Credit Union</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BankWest Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bendigo Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Beyond Bank</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluebay Home Loans</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bluestone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Mortgage Corporation Pty Ltd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Circle Credit Union</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Type__c</fullName>
        <label>Current Loan Type</label>
        <picklist>
            <picklistValues>
                <fullName>Owner Occupied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment Property</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Commercial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Construction</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Current_Loan_Value__c</fullName>
        <label>Current Loan Value</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Personal_Loan_Balance__c</fullName>
        <label>Personal Loan Balance</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <picklist>
            <picklistValues>
                <fullName>Refinance</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>New Purchase</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Required_Document__c.object
<CustomObject>
    <description>Click Loans</description>
    <fields>
        <fullName>acfOpportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Click Loans</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Required_Documents</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Click Loans Required Document</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Required Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Lendi/src/classes/TestPreviewFileController.cls
@isTest
private class TestPreviewFileController {
	public static Opportunity testOppo1;
	public static Required_Document__c reqDocs;
	public static Attachment attachment1;
	public static Attachment attachment2;

	static {
		Account account = new Account();
		account.LastName = 'testLastName';
		account.PersonEmail = 'test@mailinator.com';
		account.PersonMobilePhone = '+61428938900';
		account.Employment_Status__pc = 'Full Time';
		account.Marital_Status__pc = 'Single';
		account.Housing_Status__pc = 'Mortgage';
		account.Number_of_Children__pc = '2';
		account.Annual_Income__pc = 100000;
		account.Super_Balance__pc = 1;
		account.Partner_Annual_Income__pc = 0;
		account.Partner_Super_Balance__pc = 0;
		insert account;
		
	 	testOppo1 = new Opportunity();
	 	testOppo1.Name = 'test 1';
	 	testOppo1.AccountId = account.Id;
	 	testOppo1.CloseDate = Date.today().addDays(1);
	 	testOppo1.StageName = 'Appointed';
	 	testOppo1.Transaction_Type__c = 'Refinance';
	 	testOppo1.Current_Lender__c = 'AMP';
	 	testOppo1.Current_Loan_Value__c = 40000;
	 	testOppo1.Current_Loan_Type__c = 'Commercial';
	 	testOppo1.Personal_Loan_Balance__c = 300;
	 	testOppo1.Credit_Card_Balance__c = 3;
	 	testOppo1.Car_Loan_Balance__c = 400;
	 	RecordType recType = [Select Id, Name From RecordType  Where SobjectType = 'Opportunity' and Name = 'Home Opportunity'];
	 	testOppo1.RecordTypeId = recType.Id;
	 	insert testOppo1;

	 	//create require doc
	 	reqDocs = new Required_Document__c();
	 	reqDocs.Name = 'test doc';
	 	reqDocs.acfOpportunity__c = testOppo1.Id;
	 	insert reqDocs;
	 	//create attachment linked with require doc and oppo
	 	String encodedContentsString = 'get test done';
	 	attachment1 = new Attachment();
		attachment1.Body = Blob.valueOf(encodedContentsString);
		attachment1.Name = String.valueOf('test1.txt');
		attachment1.ParentId = reqDocs.Id; 
		insert attachment1;

		attachment2 = new Attachment();
		attachment2.Body = Blob.valueOf(encodedContentsString);
		attachment2.Name = String.valueOf('test2.txt');
		attachment2.ParentId = testOppo1.Id; 
		insert attachment2;
	}

	@isTest static void getAllAttachmentFromOpportunityTest() {
		Test.startTest();
		System.debug('testOppoId' + testOppo1.Id);
		System.debug('reqDocs ' + reqDocs.Id + reqDocs.acfOpportunity__c);
		System.currentPageReference().getParameters().put('id', testOppo1.Id);
        ApexPages.Standardcontroller controller = new ApexPages.Standardcontroller(testOppo1);
        PreviewFileController stdController = new PreviewFileController(controller);
        System.assert(stdController != null);
        PreviewFileController.getAllAttachmentFromOpportunity();
        System.debug(PreviewFileController.attachInfos.size());
        Test.stopTest();
	}
	
}