src/objects/Pardot_Visitor_Activity__c.object
<CustomObject>
    <label>Pardot Visitor Activity</label>
    <nameField>
        <label>Pardot Visitor Activities Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pardot Visitor Activities</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Visitor_Page_View__c.object
<CustomObject>
    <fields>
        <fullName>Pardot_Visitor_Activity__c</fullName>
        <label>Pardot Visitor Activity</label>
        <referenceTo>Pardot_Visitor_Activity__c</referenceTo>
        <relationshipLabel>Visitor Page Views</relationshipLabel>
        <relationshipName>Visitor_Page_Views</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Visitor Page View</label>
    <nameField>
        <label>Visitor Page View Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Visitor Page Views</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PardotActivitiesUtilitiesTest.cls
@isTest(SeeAllData=true)
private class PardotActivitiesUtilitiesTest {

    static testMethod void getPardoctVisitorActivitiesTest() {
    	//List<Pardot_Visitor_Activity__c> activitiesBefore = [Select Id, Name From Pardot_Visitor_Activity__c];
    	//List<Visitor_Page_View__c> pageViewsBefore = [Select Id, Name From Visitor_Page_View__c];
        Lead lead = new Lead();
        lead.LastName = 'test';
        lead.Email = 'testy@yahoo.com';
        insert lead;
        Test.startTest();
        String testEmail = 'test@yahoo.com';
        PardotActivitiesUtilities.getPardoctVisitorActivities(testEmail, lead);
    	Test.stopTest();
    	//Compare activity size
    	//List<Pardot_Visitor_Activity__c> activitiesAfter = [Select Id, Name From Pardot_Visitor_Activity__c];
    	//List<Visitor_Page_View__c> pageViewsAfter = [Select Id, Name From Visitor_Page_View__c];
    	//Compare activity page view size
    	//System.assert(activitiesAfter.size() > 0);
    	//System.assert(pageViewsAfter.size() > 0);
    	//System.assert(activitiesAfter.size() > activitiesBefore.size());
    	//System.assert(pageViewsAfter.size() > pageViewsBefore.size());
    }
}