src/objects/S3DocumentSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>apiVersion__c</fullName>
        <label>API version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>domain__c</fullName>
        <label>Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>entrence__c</fullName>
        <label>Entrence</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>resources__c</fullName>
        <label>Resources</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>S3Document Setting</label>
</CustomObject>

src/classes/S3StaticValue.cls
public with sharing class S3StaticValue {
	public static final String S3_SERVICE_DOMAIN   = S3DocumentSetting__c.getOrgDefaults().domain__c;
	public static final String TOKEN               = S3DocumentSetting__c.getOrgDefaults().token__c;
	public static final String API_VERSION         = S3DocumentSetting__c.getOrgDefaults().apiVersion__c;
	public static final String ENTRENCE            = S3DocumentSetting__c.getOrgDefaults().entrence__c;
	public static final String RESOURCE            = S3DocumentSetting__c.getOrgDefaults().resources__c;
	public static final String S3_SERVICE_ENDPOINT = S3_SERVICE_DOMAIN + '/' + ENTRENCE + '/' + API_VERSION + '/' + RESOURCE;

	public static final String MULTIPART_BOUNDARY  = '----S3ServiceMULTIPART_BOUNDARY' + Utilities.generateRandomString(10);
	public static final Integer TIME_OUT_MILLISEC  = 80000;
	public static final String PDF_MINE_TYPE       = 'application/pdf';
	public static final String TEXT_MINE_TYPE      = 'text/plain';
}