src/objects/S3Document__c.object
<CustomObject>
    <fields>
        <fullName>isSuccess__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Success</label>
        <type>Checkbox</type>
    </fields>
    <label>S3Document</label>
    <nameField>
        <label>S3Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>S3Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/S3DocumentSetting__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>apiVersion__c</fullName>
        <label>API version</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>domain__c</fullName>
        <label>Domain</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>entrence__c</fullName>
        <label>Entrence</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>resources__c</fullName>
        <label>Resources</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>token__c</fullName>
        <label>Token</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>S3Document Setting</label>
</CustomObject>

src/classes/TestS3DocumentRecoveryScheduler.cls
@isTest
public with sharing class TestDocumentRecoveryScheduler {
	public static MultiStaticResourceCalloutMock multimock;
	static {
		insert new S3DocumentSetting__c (
		domain__c     = 'www.lendi.com.au',
		token__c      = '47847d52-8842-4055-b6e1-9cb71fe42f28',
		apiVersion__c = 'v1',
		entrence__c   = 'api',
		resources__c  = 'docs'
		);
		multimock = new MultiStaticResourceCalloutMock();
		multimock.setStaticResource(LendiApiStaticValue.DOC_SERVICE_ENDPOINT, 's3UploadSuccess');
		multimock.setHeader('Content-Type', 'application/json');
	}

	private static testMethod void testS3DocumentRecoveryScheduler() {
		multimock.setStatusCode(200);
		Test.setMock(HttpCalloutMock.class, multimock);

		List<S3Document__c> testS3Docs = TestUtilities.createS3Documents(10);
		insert testS3Docs;

		List<Attachment> testAtt = new List<Attachment>();
		for(S3Document__c doc : testS3Docs) {
			doc.isSuccess__c = false;
			Attachment att = new Attachment();
			att.name = doc.name;
			att.body = Blob.valueOf(doc.name);
			att.parentId = doc.id;
			testAtt.add(att);
		}
		update testS3Docs;
		insert testAtt;

		Test.startTest();
		S3DocumentRecoveryScheduler s = new S3DocumentRecoveryScheduler();
		s.execute(null);
		Test.stopTest();
	}

}